<?php

$vars = array(
	'token' => '',
	'strClass' => 'Plugin',
	'idModule' => 'Accounting',

	/*20190401 start*/
    'strTitle' => ' - <%idEntityCurrent%> 第<%numFiscalPeriodCurrent%>期<%strStatus%> 自<%strStartYear%>年(平成<%strStartHeisei%>年)<%strStartMonth%>月1日 至<%strEndYear%>年(平成<%strEndHeisei%>年)<%strEndMonth%>月末日',
    'strTitle20190401' => ' - <%idEntityCurrent%> 第<%numFiscalPeriodCurrent%>期<%strStatus%> 自<%strStartYear%>年(<%strStartNengoYear%>年)<%strStartMonth%>月1日 至<%strEndYear%>年(<%strEndNengoYear%>年)<%strEndMonth%>月末日',
    /*20190401 end*/

    'strTitleConfigAdmin' => ' - <%idEntityCurrent%> 第<%numFiscalPeriodCurrent%>期<%strStatus%> 要初期設定',
	'strTitleConfig' => ' - <%idEntityCurrent%> 第<%numFiscalPeriodCurrent%>期<%strStatus%>',
	'varsItem'  => array(
		'strLock' => '(確定済)',
		'strTempLock' => '(仮繰越処理中)',
	),
	'pathCss' => 'front/else/plugin/accounting/css/style.css?v=13650',
	'portal' => array(
		'varsNavi' => array(
			'varsStatus' => array(
				'flagNow' => 'tree',
				'flagCakeUse' => 1,
				'flagTreeUse' => 1,
				'flagSearchUse' => 0,
				'flagFolderUse' => 0,
				'switchList' => array('tree'),
			),
			'varsDetail' => array(),
			'tree' => array(
				'varsFormat' => array(
					'id' => '',
					'flagType' => 'normalFormat',
					'numHeight' => 0,
					'numWidth' => 0,
					'flagHeaderLeftUse' => 1,
					'strTitleHeaderLeft' => 'メニュー',
					'strClassHeaderLeft' => 'codeLibBaseImgDb',
					'flagHeaderRightUse' => 1,
					'strTitleHeaderRight' => '',
					'strClassHeaderRight' => 'codeLibBaseImgUnloading',
					'flagBodyAutoUse' => 0,
					'strBody' => '',
					'strClassBody' => '',
					'flagFooderUse' => 1,
					'flagFooderLeftUse' => 1,
					'strTitleFooderLeft' => '',
					'strClassFooderLeft' => '',
					'flagFooderRightUse' => 1,
					'strTitleFooderRight' => '',
					'strClassFooderRight' => '',
					'flagHeaderLeftWidth' => 1,
					'numWidthHeaderLeft' => 0,
					'flagHeaderRightWidth' => 0,
					'numWidthHeaderRight' => 0,
					'flagFooderLeftWidth' => 0,
					'numWidthFooderLeft' => 0,
					'flagFooderRightWidth' => 0,
					'numWidthFooderRight' => 0,
				),
				'varsEdit' => array(
					'flagReloadUse' => 1,
				),
				'varsDetail' => array(
					'varsStatus' => array(
						'flagUse' => 1,
						'flagMoveUse' => 0,
						'flagInsertUse' => 0,
						'flagFoldNow' => 0,
						'flagFoldUse' => 1,
						'flagCakeUse' => 1,
						'flagRemoveUse' => 0,
						'flagCheckUse' => 0,
						'flagCheckNow' => 1,
						'flagBarUse' => 1,
						'flagBtnBottomUse' => 0,
						'flagBtnUse' => 1,
						'flagLockUse' => 0,
						'flagLockNow' => 0,
						'flagPageUse' => 0,
						'flagInnerPageUse' => 0,
						'flagFindUse' => 1,
						'id' => 'tree',
					),
					'varsFormat' => array(
						'id' => '',
						'flagType' => 'singleFormat',
						'numHeight' => 0,
						'numWidth' => 0,
						'flagHeaderUse' => 1,
						'flagHeaderLeftUse' => 1,
						'strTitleHeaderLeft' => '',
						'strClassHeaderLeft' => '',
						'flagHeaderRightUse' => 1,
						'strTitleHeaderRight' => '',
						'strClassHeaderRight' => '',
						'flagBodyAutoUse' => 1,
						'strBody' => '',
						'strClassBody' => '',
						'flagFooderUse' => 0,
						'flagFooderLeftUse' => 0,

						'strTitleFooderLeft' => '',
						'strClassFooderLeft' => '',
						'flagFooderRightUse' => 0,

						'strTitleFooderRight' => '',
						'strClassFooderRight' => '',

						'flagHeaderLeftWidth' => 0,
						'numWidthHeaderLeft' => 0,
						'flagHeaderRightWidth' => 0,
						'numWidthHeaderRight' => 0,
						'flagFooderLeftWidth' => 0,
						'numWidthFooderLeft' => 0,
						'flagFooderRightWidth' => 0,
						'numWidthFooderRight' => 0,
					),
					'varsFind' => array(
						'value' => '',
						'flag' => 0,
						'num' => 0,
						'numWidth' => 70,
						'unitWidth' => '%',
						'strTitle' => '絞込検索',
					),
					'varsBtn' => array(),
					'varsDetail' => array(
						array(
							'id' => 'Admin', 'flagUse' => 1, 'flagMoveUse' => 1, 'flagInsertUse' => 1, 'flagBtnUse' => 0, 'flagFoldUse' => 1, 'flagFoldNow' => 1, 'flagChildrenUse' => 1, 'flagCheckUse' => 0, 'flagCheckNow' => 0, 'flagRemoveUse' => 1, 'flagEditUse' => 1,
							'strTitle' => '管理者項目',
							'strClass' => 'codeLibBaseImgFolder',
							'vars' => array(),
							'child' => array(
								array(
									'id' => '', 'flagUse' => 1, 'flagMoveUse' => 1, 'flagInsertUse' => 1, 'flagBtnUse' => 1, 'flagFoldUse' => 0, 'flagFoldNow' => 0, 'flagChildrenUse' => 0, 'flagCheckUse' => 0, 'flagCheckNow' => 0, 'flagRemoveUse' => 1, 'flagEditUse' => 1,
									'strTitle' => '事業体',
									'strClass' => 'codeLibBaseImgDetail',
									'vars' => array(
										'idTarget' => 'entityWindow',
									),
									'child' => array(),
								),
								array(
									'id' => '', 'flagUse' => 1, 'flagMoveUse' => 1, 'flagInsertUse' => 1, 'flagBtnUse' => 1, 'flagFoldUse' => 0, 'flagFoldNow' => 0, 'flagChildrenUse' => 0, 'flagCheckUse' => 0, 'flagCheckNow' => 0, 'flagRemoveUse' => 1, 'flagEditUse' => 1,
									'strTitle' => 'アクセス可能事業体',
									'strClass' => 'codeLibBaseImgDetail',
									'vars' => array(
										'idTarget' => 'accountWindow',
									),
									'child' => array(),
								),
								array(
									'id' => '', 'flagUse' => 1, 'flagMoveUse' => 1, 'flagInsertUse' => 1, 'flagBtnUse' => 1, 'flagFoldUse' => 0, 'flagFoldNow' => 0, 'flagChildrenUse' => 0, 'flagCheckUse' => 0, 'flagCheckNow' => 0, 'flagRemoveUse' => 1, 'flagEditUse' => 1,
									'strTitle' => 'アクセス権限パターン',
									'strClass' => 'codeLibBaseImgDetail',
									'vars' => array(
										'idTarget' => 'authorityWindow',
									),
									'child' => array(),
								),
							),
						),
						array(
							'id' => 'IdEntityCurrent', 'flagUse' => 1, 'flagMoveUse' => 1, 'flagInsertUse' => 1, 'flagBtnUse' => 1, 'flagFoldUse' => 0, 'flagFoldNow' => 0, 'flagChildrenUse' => 0, 'flagCheckUse' => 0, 'flagCheckNow' => 0, 'flagRemoveUse' => 1, 'flagEditUse' => 1,
							'strTitle' => '作業事業体選択',
							'strClass' => 'codeLibBaseImgSheet',
							'vars' => array(
								'idTarget' => 'idEntityCurrent',
								'varsEdit' => array( 'flagReloadUse' => 0, ),
								'varsBtn' => array(
									array(
										'flagUse' => 1, 'flagLeftUse' => 0, 'flagRightUse' => 1, 'flagTextUse' => 0, 'flagBtnUse' => 1,
										'id' => 'IdEntityCurrent',
										'vars' => array( 'idTarget' => 'idEntityCurrent',  ),
										'strTitle' => '保存',
									),
								),
								'varsDetail' => array(
									array(
										'flagMustUse' => 1,
										'id' => 'IdEntityCurrent',
										'strTitle' => '事業体', 'strExplain' => '作業する任意の事業体を一つ選択してください。<br>　※ 保存後、ページを<span class="codeLibBaseFontTypeCheck" style="float:none;">自動更新</span>します。', 'value' => '',
										'flagErrorNow' => 0,
										'arrayError' => array(
											array( 'flagCheck' => 'blank', 'flagUse' => 1, 'flagNow' => 0, 'flagType' => 'empty', 'strComment' => array('common' => '選択漏れがあるようです。', ), ),
											array( 'flagCheck' => 'word', 'flagUse' => 1, 'flagNow' => 0, 'flagArr' => 0, 'flagType' => 'num', 'strComment' => array('common' => '半角数字で記入されていないようです。', ), ),
											array( 'flagCheck' => 'attest', 'flagUse' => 1, 'strComment' => array('idEntityCurrent' => '選択された事業体は、既に存在しないようです。',),),
										),
										'flagContentUse' => 1,
										'flagCommentUse' => 0, 'strCommentTitle' => '', 'strComment' => '',
										'flagTag' => 'input', 'flagInputType' => 'text', 'numMaxlength' => 200,
										'numWidth' => 80, 'unitWidth' => '%', 'numHeight' => 0, 'unitHeight' => '',
										'arrayOption' => array(),
										'varsFormList' => array(
											'varsStatus' => array( 'flagSortUse' => 0, 'flagCopyUse' => 0, 'flagRemoveUse' => 0, 'flagAddUse' => 1, 'strAddNow' => 'addSelect', 'flagEditUse' => 0, 'flagFormUse' => 0, 'flagBtnUse' => 0, ),
											'templateDetail' => array( 'id' => 'Dummy', 'flagSortUse' => 0, 'flagCopyUse' => 0, 'flagRemoveUse' => 1, 'flagEditUse' => 0, 'flagFormUse' => 0, 'flagBtnUse' => 0, 'numSort' => 0, 'value' => '', ),
											'varsDetail' => array(),
										),
										'varsTmplItem' => '　　【 <%strTitle%> 】　<%strValue%><br>',

										/*20190401 start*/
									    'varsTmplTerm' => '(自)平成<%strStartHeisei%>年<%strStartMonth%>月1日 ～ (至)平成<%strEndHeisei%>年<%strEndMonth%>月末日',
									    'varsTmplTerm20190401' => '(自)<%strStartNengoYear%>年<%strStartMonth%>月1日 ～ (至)<%strEndNengoYear%>年<%strEndMonth%>月末日)',
									    /*20190401 end*/


										'varsTmpl' => '作業する任意の事業体を選択してください。<br>　※ 保存後、ページを<span class="codeLibBaseFontTypeCheck" style="float:none;">自動更新</span>します。<br>　※ 現在、作業中の事業体は、<span class="codeLibBaseFontTypeCheck" style="float:none;">『 <%idEntityCurrent%>　-　第<%numFiscalPeriodCurrent%>期 』</span> です。<br><%item%>',
										'varsTmplDetail' => array(
											'numFiscalPeriodCurrent' => array(
												'flagMustUse' => 1,
												'id' => 'NumFiscalPeriodCurrent',
												'strTitle' => '会計年度', 'strExplain' => '作業する任意の会計年度を一つ選択してください。', 'value' => '',
												'flagErrorNow' => 0,
												'arrayError' => array(
													array( 'flagCheck' => 'blank', 'flagUse' => 1, 'flagNow' => 0, 'flagType' => 'empty', 'strComment' => array( 'common' => '選択漏れがあるようです。', ),),
													array( 'flagCheck' => 'word', 'flagUse' => 1, 'flagNow' => 0, 'flagArr' => 0, 'flagType' => 'num', 'strComment' => array( 'common' => '半角数字以外の文字が混入したようです。', ), ),
													array( 'flagCheck' => 'attest', 'flagUse' => 1, 'strComment' => array('notMove' => '現在作業中のため移動する必要がないようです。',),),
												),
												'flagContentUse' => 0,
												'flagCommentUse' => 0, 'strCommentTitle' => '', 'strComment' => '',
												'flagTag' => 'select', 'flagInputType' => '', 'numMaxlength' => 0,
												'numWidth' => 40, 'unitWidth' => '%', 'numHeight' => 0, 'unitHeight' => '',
												'arrayOption' => array(),
												'numSize' => 3,
												'varsTmpl' => '第<%strTitle%>期',
												'varsStr' => array(
													'strLock' => '確定済',
													'strUnLock' => '未確定',
													'strTempLock' => '仮繰越処理中',
													'strCurrent' => '(作業中)',
												),
											),
										),
									),
								),
							),
							'child' => array(),
						),
						array(
							'id' => 'EntityCurrent', 'flagUse' => 1, 'flagMoveUse' => 1, 'flagInsertUse' => 1, 'flagBtnUse' => 0, 'flagFoldUse' => 1, 'flagFoldNow' => 1, 'flagChildrenUse' => 1, 'flagCheckUse' => 0, 'flagCheckNow' => 0, 'flagRemoveUse' => 1, 'flagEditUse' => 1,
							'strTitle' => '作業事業体',
							'strClass' => 'codeLibBaseImgFolder',
							'vars' => array(),
							'child' => array(),
						),
						array(
							'id' => '', 'flagUse' => 1, 'flagMoveUse' => 1, 'flagInsertUse' => 1, 'flagBtnUse' => 0, 'flagFoldUse' => 1, 'flagFoldNow' => 1, 'flagChildrenUse' => 1, 'flagCheckUse' => 0, 'flagCheckNow' => 0, 'flagRemoveUse' => 1, 'flagEditUse' => 1,
							'strTitle' => 'ヘルプ',
							'strClass' => 'codeLibBaseImgFolder',
							'vars' => array(),
							'child' => array(
								array(
									'id' => '', 'flagUse' => 1, 'flagMoveUse' => 1, 'flagInsertUse' => 1, 'flagBtnUse' => 1, 'flagFoldUse' => 0, 'flagFoldNow' => 0, 'flagChildrenUse' => 0, 'flagCheckUse' => 0, 'flagCheckNow' => 0, 'flagRemoveUse' => 1, 'flagEditUse' => 1,
									'strTitle' => 'オンラインマニュアル',
									'strClass' => 'codeLibBaseImgSheet',
									'vars' => array(
										'idTarget' => 'release',
										'varsEdit' => array( 'flagReloadUse' => 0, ),
										'varsBtn' => array(
											array(
												'flagUse' => 1, 'flagLeftUse' => 0, 'flagRightUse' => 1, 'flagTextUse' => 0, 'flagBtnUse' => 1, 'flagATag' => 1, 'path' => '',
												'id' => 'Release',
												'vars' => array( 'idTarget' => 'release', ),
												'strTitle' => 'オンラインマニュアルサイト',
											),
										),
										'varsDetail' => array(
											array(
												'flagMustUse' => 0,
												'id' => 'Release',
												'strTitle' => '', 'strExplain' => '', 'value' => 0,
												'flagErrorNow' => 0,
												'arrayError' => array(),
												'flagContentUse' => 0,
												'flagCommentUse' => 1, 'strComment' => 'オンラインマニュアルは下記ボタンのリンク先を参照してください。',
												'flagTag' => '', 'flagInputType' => '', 'numMaxlength' => 0,
												'unitWidth' => '', 'numWidth' => 0, 'unitHeight' => '', 'numHeight' => 0,
												'arrayOption' => array(),
											),
										),
									),
									'child' => array(),
								),
							),
						),
					),
				),
			),
			'item' => array(),
			'folder' => array(),
		),
		'varsDetail' => array(
			'varsStart' => array(
				'strTitle'   => '',
				'strClass'   => '',
				'varsDetail' => array(),
			),
			'varsStartTmpl' => array(
				'InfoEntityNone' => array(
					'strTitle' => '設定不足詳細',
					'strClass' => 'codeLibBaseImgInfo',
					'varsDetail' => array(
						array(
							'flagMustUse' => 1,
							'id' => 'InfoEntityNone',
							'strTitle' => '', 'strExplain' => '', 'value' => '',
							'flagErrorNow' => 0,
							'arrayError' => array(),
							'flagContentUse' => 0,
							'flagCommentUse' => 1, 'strCommentTitle' => 'まだ事業体が登録されていないようです。',
							'strComment' => '
								1、当ウィンドウにあるナビボックスのメニューから 『事業体』 を選んで『事業体』 ウィンドウを開いてください。
							<br>2、『事業体』 ウィンドウを開いたら詳細ボックスのツールエリアにある 『新規』 ボタンを押して新しく事業体を登録してください。
							<br>3、事業体を登録したら、当ウィンドウにあるナビボックスのツールエリアにある 『更新』 ボタンを押してメニューを更新してください。
							<br>4、メニューが更新され、『作業事業体選択』 を選択し案内に従ってください。
							',
							'flagTag' => 'input', 'flagInputType' => 'text', 'numMaxlength' => 1000,
							'numWidth' => 80, 'unitWidth' => '%', 'numHeight' => 0, 'unitHeight' => '',
							'arrayOption' => array(),
							'flagFoldUse' => 1, 'flagFoldNow' => 0,
						),
					),
				),
				'InfoEntityCurrent' => array(
					'strTitle' => '設定不足詳細',
					'strClass' => 'codeLibBaseImgInfo',
					'varsDetail' => array(
						array(
							'flagMustUse' => 1,
							'id' => 'InfoEntityCurrent',
							'strTitle' => '', 'strExplain' => '', 'value' => '',
							'flagErrorNow' => 0,
							'arrayError' => array(),
							'flagContentUse' => 0,
							'flagCommentUse' => 1, 'strCommentTitle' => 'まだ作業事業体が選択されていないようです。',
							'strComment' => '
								1、当ウィンドウにあるナビボックスのメニューから 『作業事業体選択』 を選んで案内に従ってください。
							',
							'flagTag' => 'input', 'flagInputType' => 'text', 'numMaxlength' => 1000,
							'numWidth' => 80, 'unitWidth' => '%', 'numHeight' => 0, 'unitHeight' => '',
							'arrayOption' => array(),
							'flagFoldUse' => 1, 'flagFoldNow' => 0,
						),
					),
				),
				'InfoEntityCurrentConfig' => array(
					'strTitle' => '設定不足詳細',
					'strClass' => 'codeLibBaseImgInfo',
					'varsDetail' => array(
						array(
							'flagMustUse' => 1,
							'id' => 'InfoEntityCurrentConfig',
							'strTitle' => '', 'strExplain' => '', 'value' => '',
							'flagErrorNow' => 0,
							'arrayError' => array(),
							'flagContentUse' => 0,
							'flagCommentUse' => 1, 'strCommentTitle' => 'まだ選択した作業事業体の初期設定が済んでいません。',
							'strComment' => '
								1、当ウィンドウにあるナビボックスのメニューから 『初期設定』 を選んで案内に従ってください。
							',
							'flagTag' => 'input', 'flagInputType' => 'text', 'numMaxlength' => 1000,
							'numWidth' => 80, 'unitWidth' => '%', 'numHeight' => 0, 'unitHeight' => '',
							'arrayOption' => array(),
							'flagFoldUse' => 1, 'flagFoldNow' => 0,
						),
					),
				),
				'InfoEntityNoneUser' => array(
					'strTitle' => '設定不足詳細',
					'strClass' => 'codeLibBaseImgInfo',
					'varsDetail' => array(
						array(
							'flagMustUse' => 1,
							'id' => 'InfoEntityNoneUser',
							'strTitle' => '', 'strExplain' => '', 'value' => '',
							'flagErrorNow' => 0,
							'arrayError' => array(),
							'flagContentUse' => 0,
							'flagCommentUse' => 1, 'strCommentTitle' => 'まだ管理者の設定が済んでいないようです。',
							'strComment' => '
								1、管理者に設定確認を促してください。
							',
							'flagTag' => 'input', 'flagInputType' => 'text', 'numMaxlength' => 1000,
							'numWidth' => 80, 'unitWidth' => '%', 'numHeight' => 0, 'unitHeight' => '',
							'arrayOption' => array(),
							'flagFoldUse' => 1, 'flagFoldNow' => 0,
						),
					),
				),
			),
			'varsEnd' => array(
				'strTitle' => '処理完了',
				'strClass' => 'codeLibBaseImgSheet',
				'varsEdit' => array( 'flagReloadUse' => 0, ),
				'varsBtn' => array(
					array(
						'flagUse' => 1, 'flagLeftUse' => 0, 'flagRightUse' => 1, 'flagTextUse' => 0, 'flagBtnUse' => 1,
						'id' => 'Back',
						'vars' => array( 'flagBack' => 1, ),
						'strTitle' => '戻る',
					),
					array(
						'flagUse' => 1, 'flagLeftUse' => 0, 'flagRightUse' => 1, 'flagTextUse' => 0, 'flagBtnUse' => 1,
						'id' => 'Hide',
						'vars' => array( 'flagHide' => 1, ),
						'strTitle' => '閉じる',
					),
				),
				'varsDetail' => array(
					array(
						'flagMustUse' => 0,
						'id' => 'End',
						'strTitle' => '', 'strExplain' => '', 'value' => '',
						'flagErrorNow' => 0,
						'arrayError' => array(),
						'flagContentUse' => 0,
						'flagCommentUse' => 1, 'strCommentTitle' => '', 'strComment' => '処理が無事完了しました。',
						'flagTag' => 'input', 'flagInputType' => 'text', 'numMaxlength' => 0,
						'numWidth' => 80, 'unitWidth' => '%', 'numHeight' => 0, 'unitHeight' => '',
						'arrayOption' => array(),
						'flagFoldUse' => 0, 'flagFoldNow' => 0,
					),
				),
			),
			'varsStatus' => array(
				'flagUse' => 1,
				'flagNow' => 'form',
				'flagCakeUse' => 0,
				'flagViewUse' => 0,
				'flagFormUse' => 1,
				'switchList' => array('form'),
			),
			'varsBtn' => array(),
			'varsPage' => array(),
			'varsDetail' => array(),
			'view' => array(),
			'form' => array(
				'varsFormat' => array(
					'id' => '',
					'flagType' => 'normalFormat',
					'numHeight' => 0,
					'numWidth' => 0,
					'flagHeaderLeftUse' => 1,
					'strTitleHeaderLeft' => '',
					'strClassHeaderLeft' => 'codeLibBaseImgBlank',
					'flagHeaderRightUse' => 1,
					'strTitleHeaderRight' => '',
					'strClassHeaderRight' => 'codeLibBaseImgUnloading',
					'flagBodyAutoUse' => 1,
					'strBody' => '',
					'strClassBody' => '',
					'flagFooderUse' => 1,
					'flagFooderLeftUse' => 1,
					'strTitleFooderLeft' => '',
					'strClassFooderLeft' => '',
					'flagFooderRightUse' => 1,
					'strTitleFooderRight' => '',
					'strClassFooderRight' => '',
					'flagHeaderLeftWidth' => 1,
					'numWidthHeaderLeft' => 0,
					'flagHeaderRightWidth' => 0,
					'numWidthHeaderRight' => 0,
					'flagFooderLeftWidth' => 0,
					'numWidthFooderLeft' => 0,
					'flagFooderRightWidth' => 0,
					'numWidthFooderRight' => 0,
				),
				'varsEdit' => array( 'flagReloadUse' => 0, ),
				'varsDetail' => array(
					'varsStatus' => array(
						'flagBtnBottomUse' => 1,
					),
					'varsBtn' => array(),
					'varsDetail' => array(),
				),
			),
		),
		'varsTemplateLayout' => array(
			'varsStatus' => array(
				'flagNaviUse' => 1,
				'flagNaviToolUse' => 1,
				'flagListUse' => 0,
				'flagListToolUse' => 0,
				'flagDetailUse' => 1,
				'flagDetailToolUse' => 1,
			),
			'varsLayout' => array(
				'varsStatus' => array(
					'flagNow' => 2,
					'flagResizeUse' => 1,
					'flagMoveUse' => 1,
					'flagCakeUse' => 1,
					'flagSwitchUse' => 1,
					'flagSwitchNow' => 'Standard',
					'switchList' => array('Standard','Wide'),
				),
				'varsDetail' => array(
					array(
						'id' => 'Navi',
						'flagBoxUse' => 1,
						'numPriority' => 0,
						'numSort' => 0,
						'numWidth' => 250,			'numHeight' => 200,
						'numWidthMin' => 200,		'numHeightMin' => 200,
						'numWidthStandard' => 200,	'numHeightStandard' => 200,
						'numWidthWide' => 200,		'numHeightWide' => 200,
						'numWidthClassic' => 200,	'numHeightClassic' => 200,
						'numHeightBox' => 0,		'numWidthBox' => 0,//auto
					),
					array(
						'id' => 'Detail',
						'flagBoxUse' => 1,
						'numPriority' => 2,
						'numSort' => 2,
						'numWidth' => 200,			'numHeight' => 200,
						'numWidthMin' => 200,		'numHeightMin' => 200,
						'numWidthStandard' => 200,	'numHeightStandard' => 200,
						'numWidthWide' => 200,		'numHeightWide' => 200,
						'numWidthClassic' => 200,	'numHeightClassic' => 200,
						'numHeightBox' => 0,		'numWidthBox' => 0,//auto
					),
				)
			),
			'navi' => array(
				'varsFormat' => array(
					'id' => '',
					'flagType' => 'normalFormat',
					'numHeight' => 0,
					'numWidth' => 0,
					'flagHeaderLeftUse' => 1,
					'strTitleHeaderLeft' => '',
					'strClassHeaderLeft' => '',
					'flagHeaderRightUse' => 1,
					'strTitleHeaderRight' => '',
					'strClassHeaderRight' => 'codeLibBaseImgUnloading',
					'flagBodyAutoUse' => 0,
					'strBody' => '',
					'strClassBody' => '',
					'flagFooderUse' => 1,
					'flagFooderLeftUse' => 1,
					'strTitleFooderLeft' => '',
					'strClassFooderLeft' => '',
					'flagFooderRightUse' => 1,
					'strTitleFooderRight' => '',
					'strClassFooderRight' => '',
					'flagHeaderLeftWidth' => 1,
					'numWidthHeaderLeft' => 0,
					'flagHeaderRightWidth' => 0,
					'numWidthHeaderRight' => 0,
					'flagFooderLeftWidth' => 0,
					'numWidthFooderLeft' => 0,
					'flagFooderRightWidth' => 1,
					'numWidthFooderRight' => 0,
				),
				'varsTool' => array(
					'varsDetail' => array(
						array(
							'flagUse' => 1,
							'flagNow' => 0,
							'id' => 'Reload',
							'strClass' => 'codeLibBtnImgReload',
							'strClassOver' => 'codeLibBtnImgReloadOver',
							'strClassNoactive' => 'codeLibBtnImgReloadNoactive',
							'strTitle' => '更新',
						),
					),
				),
			),
			'detail' => array(
				'varsFormat' => array(
					'id' => '',
					'flagType' => 'normalFormat',
					'numHeight' => 0,
					'numWidth' => 0,
					'flagHeaderLeftUse' => 1,
					'strTitleHeaderLeft' => '',
					'strClassHeaderLeft' => '',
					'flagHeaderRightUse' => 1,
					'strTitleHeaderRight' => '',
					'strClassHeaderRight' => 'codeLibBaseImgUnloading',
					'flagBodyAutoUse' => 0,
					'strBody' => '',
					'strClassBody' => '',
					'flagFooderUse' => 1,
					'flagFooderLeftUse' => 1,
					'strTitleFooderLeft' => '',
					'strClassFooderLeft' => '',
					'flagFooderRightUse' => 1,
					'strTitleFooderRight' => '',
					'strClassFooderRight' => '',
					'flagHeaderLeftWidth' => 1,
					'numWidthHeaderLeft' => 0,
					'flagHeaderRightWidth' => 0,
					'numWidthHeaderRight' => 0,
					'flagFooderLeftWidth' => 0,
					'numWidthFooderLeft' => 0,
					'flagFooderRightWidth' => 1,
					'numWidthFooderRight' => 0,
				),
				'varsTool' => array(
					'varsDetail' => array(
						array(
							'flagUse' => 1,
							'flagNow' => 0,
							'id' => 'Reload',
							'strClass' => 'codeLibBtnImgReload',
							'strClassOver' => 'codeLibBtnImgReloadOver',
							'strClassNoactive' => 'codeLibBtnImgReloadNoactive',
							'strTitle' => '更新',
						),
					),
				),
			),
		),
	),
	'child' => array(
		'templateWindow' => array(
			'id' => '',
			'strTitle' => '<%child%> - <%parent%>',
			'strClass' => 'codePluginAccountingImgIcon',
			'flagLockUse' => 0,
			'flagLockNow' => '',
			'flagCakeUse' => 1,
			'flagRemoveUse' => 0,
			'flagCoverUse' => 1,
			'flagHideUse' => 1,
			'flagHideNow' => 0,
			'flagReloadUse' => 0,
			'flagFoldUse' => 1,
			'flagFoldNow' => 0,
			'flagMoveUse' => 1,
			'flagZIndexUse' => 0,
			'flagResizeUse' => 1,
			'flagResizeIni' => 'all',
			'flagResizeNow' => 'all',
			'flagSkeletonUse' => 0,
			'flagBootUse' => 'auto',
			'flagSwitchUse' => 1,
			'flagMenuUse' => 1,
			'flagMenuShowUse' => 1,
			'numWidthTitle' => 0,
			'numLeft' => 50,
			'numTop' => 50,
			'numWidth' => 950,
			'numHeight' => 600,
			'numWidthMin' => 800,
			'numHeightMin' => 600,
			'numZIndex' => 0
		),
	),

);


