<?php

$vars = array(
	'strTitle' => '会計モジュール',
	'varsGlobal' => array(
		'numZIndex'=> 0,
		'numLeft'=> 22,
		'numTop'=> 138,
		'numSort'=> 3,
		'id'=> 'Accounting',
		'strTitle'=> '会計モジュール',
		'strClass'=> 'codePluginAccountingImgIcon',
		'strClassOver'=> 'codePluginAccountingImgIconOver',
		'strClassSmall'=> 'codePluginAccountingImgIconSmall',
	),

	'varsWindow' => array(
		'id' => 'Accounting',
		'strTitle' => '会計モジュール',
		'strClass' => 'codePluginAccountingImgIcon',
		'flagLockUse' => 0,
		'flagLockNow' => '',
		'flagCakeUse' => 1,
		'flagRemoveUse' => 0,
		'flagCoverUse' => 1,
		'flagHideUse' => 1,
		'flagHideNow' => 1,
		'flagFoldUse' => 1,
		'flagFoldNow' => 0,
		'flagMoveUse' => 1,
		'flagZIndexUse' => 1,
		'flagResizeUse' => 1,
		'flagResizeIni' => 'all',
		'flagResizeNow' => 'all',
		'flagSkeletonUse' => 0,
		'flagBootUse' => 1,
		'flagSwitchUse' => 1,
		'flagMenuUse' => 1,
		'flagMenuShowUse' => 1,
		'numWidthTitle' => 0,
		'numLeft' => 50,
		'numTop' => 50,
		'numWidth' => 950,
		'numHeight' => 600,
		'numWidthMin' => 800,
		'numHeightMin' => 600,
		'numZIndex' => 0
	),
	'varsChoice' => array(
		array(
			'id' => 'PluginAccountingEntity',
			'idModule'  => 'Accounting',
			'strTitle' => '事業体',
			'flagCheckUse' => 0,
			'strClass' => 'codePluginAccountingImgIcon',
			'varsRequest' => array(
				'strClass'  => 'Plugin',
				'idModule'  => 'Accounting',
				'strExt'    => 'Entity',
				'strChild'  => 'Choice',
				'strFunc'   => 'Js',
			),
		),
		array(
			'id' => 'PluginAccountingEntityWithoutConfig',
			'idModule'  => 'Accounting',
			'strTitle' => '事業体',
			'flagCheckUse' => 0,
			'strClass' => 'codePluginAccountingImgIcon',
			'varsRequest' => array(
				'strClass'  => 'Plugin',
				'idModule'  => 'Accounting',
				'strExt'    => 'Entity',
				'strChild'  => 'ChoiceWithoutConfig',
				'strFunc'   => 'Js',
			),
		),
		array(
			'id' => 'PluginAccountingAccount',
			'idModule'  => 'Accounting',
			'strTitle' => 'アカウント',
			'flagCheckUse' => 0,
			'strClass' => 'codePluginAccountingImgIcon',
			'varsRequest' => array(
				'strClass'  => 'Plugin',
				'idModule'  => 'Accounting',
				'strExt'    => 'Account',
				'strChild'  => 'Choice',
				'strFunc'   => 'Js',
			),
		),
		array(
			'id' => 'PluginAccountingAccountEntityPermit',
			'idModule'  => 'Accounting',
			'strTitle' => 'アカウント',
			'flagCheckUse' => 0,
			'strClass' => 'codePluginAccountingImgIcon',
			'varsRequest' => array(
				'strClass'  => 'Plugin',
				'idModule'  => 'Accounting',
				'strExt'    => 'AccountEntity',
				'strChild'  => 'ChoicePermit',
				'strFunc'   => 'Js',
			),
		),
		array(
			'id' => 'PluginAccountingAuthority',
			'idModule'  => 'Accounting',
			'strTitle' => 'アクセス権限パターン',
			'flagCheckUse' => 0,
			'strClass' => 'codePluginAccountingImgIcon',
			'varsRequest' => array(
				'strClass'  => 'Plugin',
				'idModule'  => 'Accounting',
				'strExt'    => 'Authority',
				'strChild'  => 'Choice',
				'strFunc'   => 'Js',
			),
		),
		array(
			'id' => 'PluginAccountingAccess',
			'idModule'  => 'Accounting',
			'strTitle' => 'アクセス可能項目パターン',
			'flagCheckUse' => 0,
			'strClass' => 'codePluginAccountingImgIcon',
			'varsRequest' => array(
				'strClass'  => 'Plugin',
				'idModule'  => 'Accounting',
				'strExt'    => 'Access',
				'strChild'  => 'Choice',
				'strFunc'   => 'Js',
			),
		),
		array(
			'id' => 'PluginAccountingLogFile',
			'idModule'  => 'Accounting',
			'strTitle' => '証憑ファイル',
			'flagCheckUse' => 0,
			'strClass' => 'codePluginAccountingImgIcon',
			'varsRequest' => array(
				'strClass'  => 'Plugin',
				'idModule'  => 'Accounting',
				'strExt'    => 'File',
				'strChild'  => 'Choice',
				'strFunc'   => 'Js',
			),
		),
	),
);





