<?php

$vars = array(
	'strUnique' => array(
		array('before' => '①', 'after' => '(1)'),
		array('before' => '②', 'after' => '(2)'),
		array('before' => '③', 'after' => '(3)'),
		array('before' => '④', 'after' => '(4)'),
		array('before' => '⑤', 'after' => '(5)'),
		array('before' => '⑥', 'after' => '(6)'),
		array('before' => '⑦', 'after' => '(7)'),
		array('before' => '⑧', 'after' => '(8)'),
		array('before' => '⑨', 'after' => '(9)'),
		array('before' => '⑩', 'after' => '(10)'),
		array('before' => '⑪', 'after' => '(11)'),
		array('before' => '⑫', 'after' => '(12)'),
		array('before' => '⑬', 'after' => '(13)'),
		array('before' => '⑭', 'after' => '(14)'),
		array('before' => '⑮', 'after' => '(15)'),
		array('before' => '⑯', 'after' => '(16)'),
		array('before' => '⑰', 'after' => '(17)'),
		array('before' => '⑱', 'after' => '(18)'),
		array('before' => '⑲', 'after' => '(19)'),
		array('before' => '⑳', 'after' => '(20)'),
		array('before' => 'Ⅰ', 'after' => '[1]'),
		array('before' => 'Ⅱ', 'after' => '[2]'),
		array('before' => 'Ⅲ', 'after' => '[3]'),
		array('before' => 'Ⅳ', 'after' => '[4]'),
		array('before' => 'Ⅴ', 'after' => '[5]'),
		array('before' => 'Ⅵ', 'after' => '[6]'),
		array('before' => 'Ⅶ', 'after' => '[7]'),
		array('before' => 'Ⅷ', 'after' => '[8]'),
		array('before' => 'Ⅸ', 'after' => '[9]'),
		array('before' => 'Ⅹ', 'after' => '[10]'),
		array('before' => '㍉', 'after' => 'ミリ'),
		array('before' => '㌔', 'after' => 'キロ'),
		array('before' => '㌢', 'after' => 'センチ'),
		array('before' => '㍍', 'after' => 'メートル'),
		array('before' => '㌘', 'after' => 'グラム'),
		array('before' => '㌧', 'after' => 'トン'),
		array('before' => '㌃', 'after' => 'アール'),
		array('before' => '㌶', 'after' => 'ヘクタール'),
		array('before' => '㍑', 'after' => 'リットル'),
		array('before' => '㍗', 'after' => 'ワット'),
		array('before' => '㌍', 'after' => 'カロリー'),
		array('before' => '㍗', 'after' => 'ワット'),
		array('before' => '㌦', 'after' => 'ドル'),
		array('before' => '㍗', 'after' => 'ワット'),
		array('before' => '㌣', 'after' => 'セント'),
		array('before' => '㌫', 'after' => 'パーセント'),
		array('before' => '㍊', 'after' => 'ミリバール'),
		array('before' => '㎜', 'after' => 'mm'),
		array('before' => '㎝', 'after' => 'cm'),
		array('before' => '㎞', 'after' => 'km'),
		array('before' => '㎎', 'after' => 'mg'),
		array('before' => '㎏', 'after' => 'kg'),
		array('before' => '㏄', 'after' => 'cc'),
		array('before' => '㎡', 'after' => '平方メートル'),
		array('before' => '㍻', 'after' => '平成'),
		array('before' => '〝', 'after' => '”'),
		array('before' => '〟', 'after' => '〟'),
		array('before' => '№', 'after' => 'No.'),
		array('before' => '㏍', 'after' => 'kk'),
		array('before' => '℡', 'after' => 'TEL'),
		array('before' => '㊤', 'after' => '(上)'),
		array('before' => '㊥', 'after' => '(中)'),
		array('before' => '㊦', 'after' => '(下)'),
		array('before' => '㊧', 'after' => '(左)'),
		array('before' => '㊨', 'after' => '(右)'),
		array('before' => '㈱', 'after' => '(株)'),
		array('before' => '㈲', 'after' => '(有)'),
		array('before' => '㈹', 'after' => '(代)'),
		array('before' => '㍾', 'after' => '明治'),
		array('before' => '㍽', 'after' => '大正'),
		array('before' => '㍼', 'after' => '昭和'),
		array('before' => '≒', 'after' => ''),
		array('before' => '≡', 'after' => ''),
		array('before' => '∫', 'after' => ''),
		array('before' => '∮', 'after' => ''),
		array('before' => '∑', 'after' => ''),
		array('before' => '√', 'after' => ''),
		array('before' => '⊥', 'after' => ''),
		array('before' => '∠', 'after' => ''),
		array('before' => '∟', 'after' => ''),
		array('before' => '⊿', 'after' => ''),
		array('before' => '∵', 'after' => ''),
		array('before' => '∩', 'after' => ''),
		array('before' => '∪', 'after' => ''),
		array('before' => '∟', 'after' => ''),
		array('before' => 'ｱ',  'after' => 'ア'),
		array('before' => 'ｲ',  'after' => 'イ'),
		array('before' => 'ｳ',  'after' => 'ウ'),
		array('before' => 'ｴ',  'after' => 'エ'),
		array('before' => 'ｵ',  'after' => 'オ'),
		array('before' => 'ｶ',  'after' => 'カ'),
		array('before' => 'ｷ',  'after' => 'キ'),
		array('before' => 'ｸ',  'after' => 'ク'),
		array('before' => 'ｹ',  'after' => 'ケ'),
		array('before' => 'ｺ',  'after' => 'コ'),
		array('before' => 'ｻ',  'after' => 'サ'),
		array('before' => 'ｼ',  'after' => 'シ'),
		array('before' => 'ｽ',  'after' => 'ス'),
		array('before' => 'ｾ',  'after' => 'セ'),
		array('before' => 'ｿ',  'after' => 'ソ'),
		array('before' => 'ﾀ',  'after' => 'タ'),
		array('before' => 'ﾁ',  'after' => 'チ'),
		array('before' => 'ﾂ',  'after' => 'ツ'),
		array('before' => 'ﾃ',  'after' => 'テ'),
		array('before' => 'ﾄ',  'after' => 'ト'),
		array('before' => 'ﾅ',  'after' => 'ナ'),
		array('before' => 'ﾆ',  'after' => 'ニ'),
		array('before' => 'ﾇ',  'after' => 'ヌ'),
		array('before' => 'ﾈ',  'after' => 'ネ'),
		array('before' => 'ﾉ',  'after' => 'ノ'),
		array('before' => 'ﾊ',  'after' => 'ハ'),
		array('before' => 'ﾋ',  'after' => 'ヒ'),
		array('before' => 'ﾌ',  'after' => 'フ'),
		array('before' => 'ﾍ',  'after' => 'ヘ'),
		array('before' => 'ﾎ',  'after' => 'ホ'),
		array('before' => 'ﾏ',  'after' => 'マ'),
		array('before' => 'ﾐ',  'after' => 'ミ'),
		array('before' => 'ﾑ',  'after' => 'ム'),
		array('before' => 'ﾒ',  'after' => 'メ'),
		array('before' => 'ﾓ',  'after' => 'モ'),
		array('before' => 'ﾔ',  'after' => 'ヤ'),
		array('before' => 'ﾕ',  'after' => 'ユ'),
		array('before' => 'ﾖ',  'after' => 'ヨ'),
		array('before' => 'ﾗ',  'after' => 'ラ'),
		array('before' => 'ﾘ',  'after' => 'リ'),
		array('before' => 'ﾙ',  'after' => 'ル'),
		array('before' => 'ﾚ',  'after' => 'レ'),
		array('before' => 'ﾛ',  'after' => 'ロ'),
		array('before' => 'ﾜ',  'after' => 'ワ'),
		array('before' => 'ｦ',  'after' => 'ヲ'),
		array('before' => 'ﾝ',  'after' => 'ン'),

		array('before' => 'カ゛',  'after' => 'ガ'),
		array('before' => 'キ゛',  'after' => 'ギ'),
		array('before' => 'ク゛',  'after' => 'グ'),
		array('before' => 'ケ゛',  'after' => 'ゲ'),
		array('before' => 'コ゛',  'after' => 'ゴ'),
		array('before' => 'サ゛',  'after' => 'ザ'),
		array('before' => 'シ゛',  'after' => 'ジ'),
		array('before' => 'ス゛',  'after' => 'ズ'),
		array('before' => 'セ゛',  'after' => 'ゼ'),
		array('before' => 'ソ゛',  'after' => 'ゾ'),
		array('before' => 'タ゛',  'after' => 'ダ'),
		array('before' => 'チ゛',  'after' => 'ヂ'),
		array('before' => 'ツ゛',  'after' => 'ヅ'),
		array('before' => 'テ゛',  'after' => 'デ'),
		array('before' => 'ト゛',  'after' => 'ド'),
		array('before' => 'ハ゛',  'after' => 'バ'),
		array('before' => 'ヒ゛',  'after' => 'ビ'),
		array('before' => 'フ゛',  'after' => 'ブ'),
		array('before' => 'ヘ゛',  'after' => 'ベ'),
		array('before' => 'ホ゛',  'after' => 'ボ'),

		array('before' => 'ハ゜',  'after' => 'パ'),
		array('before' => 'ヒ゜',  'after' => 'ピ'),
		array('before' => 'フ゜',  'after' => 'プ'),
		array('before' => 'ヘ゜',  'after' => 'ペ'),
		array('before' => 'ホ゜',  'after' => 'ポ'),

		array('before' => 'ｧ',  'after' => 'ァ'),
		array('before' => 'ｨ',  'after' => 'ィ'),
		array('before' => 'ｩ',  'after' => 'ゥ'),
		array('before' => 'ｪ',  'after' => 'ェ'),
		array('before' => 'ｫ',  'after' => 'ォ'),
		array('before' => 'ｬ',  'after' => 'ャ'),
		array('before' => 'ｭ',  'after' => 'ュ'),
		array('before' => 'ｮ',  'after' => 'ョ'),
		array('before' => 'ｯ',  'after' => 'ッ'),
		array('before' => 'ｰ',  'after' => 'ー'),
		array('before' => 'ﾞ',  'after' => '”'),
		array('before' => 'ﾟ',  'after' => '゜'),
		array('before' => '｡',  'after' => '。'),
		array('before' => '｢',  'after' => '「'),
		array('before' => '｣',  'after' => '」'),
		array('before' => '､',  'after' => '、'),
		array('before' => '･',  'after' => '・'),
	),
	'to' => array(
		array('before' => '&',	'after' => '&amp;'),
		array('before' => '<',	'after' => '&lt;'),
		array('before' => '>',	'after' => '&gt;'),
		array('before' => "\r\n", 'after' => "\n"),
	  array('before' => "\r",   'after' => "\n"),
	),
	'br' => array(
		array('before' => "\r\n", 'after' => '<br>'),
		array('before' => "\r",   'after' => '<br>'),
		array('before' => "\n",   'after' => '<br>'),
	),
	'comma' => array(
		array('before' => ",", 'after' => '、'),
	),
	'obfuscate' => array(
	  array('before' => "\t|\n",	   'after' => ''),
		array('before' => "\/\*.*?\*\/", 'after' => ''),
	),
	'strSplit' => '[一-龠]+|[ぁ-ん]+|[ァ-ヴー]+|[a-zA-Z0-9]+|[ａ-ｚＡ-Ｚ０-９]',
	'strKana' => '[ァ-ヴー]',
	'strKanji' => '[一-龠]',
	'strHiragana' => '[ぁ-ん]',
	'mojibake' => array(
		array('before' => "～", 'after' => '~'),
		array('before' => "－", 'after' => '-'),
	),
);


