<?php

$vars = array(
	'token' => '',
	'portal' => array(
		'varsDetail' => array(
			'varsStatus' => array(
				'flagNow' => 'form',
				'flagCakeUse' => 0,
				'flagViewUse' => 0,
				'flagFormUse' => 1,
				'switchList' => array('form'),
			),
			'varsPage' => array(),
			'varsDetail' => array(
				'start' => array(
					'strTitle' => 'ログイン',
					'varsDetail' => array(
						array(
							'flagMustUse' => 1,
							'id' => 'IdLogin',
							'strTitle' => 'ID', 'strExplain' => 'ログインIDを記入してください。', 'value' => '',
							'flagErrorNow' => 0,
							'arrayError' => array(
								array( 'flagCheck' => 'blank', 'flagUse' => 1, 'flagNow' => 0, 'flagType' => 'empty', 'strComment' => array('common' => '記入漏れがあるようです。', ), ),
								array( 'flagCheck' => 'attest', 'flagUse' => 1, 'strComment' => array('common' => '認証に失敗したようです。', ),),
							),
							'flagContentUse' => 0,
							'flagCommentUse' => 0, 'strCommentTitle' => '', 'strComment' => '',
							'flagTag' => 'input', 'flagInputType' => 'text', 'numMaxlength' => 0,
							'numWidth' => 80, 'unitWidth' => '%', 'numHeight' => 0, 'unitHeight' => '',
							'arrayOption' => array(),
							'flagFoldUse' => 0, 'flagFoldNow' => 0,
						),
						array(
							'flagMustUse' => 1,
							'id' => 'StrPassword',
							'strTitle' => 'パスワード', 'strExplain' => 'ログインパスワードを記入してください。', 'value' => '',
							'flagErrorNow' => 0,
							'arrayError' => array(
								array( 'flagCheck' => 'blank', 'flagUse' => 1, 'flagNow' => 0, 'flagType' => 'empty', 'strComment' => array('common' => '記入漏れがあるようです。', ), ),
								array( 'flagCheck' => 'attest', 'flagUse' => 1, 'strComment' => array('common' => '認証に失敗したようです。', ),),
							),
							'flagContentUse' => 0,
							'flagCommentUse' => 0, 'strCommentTitle' => '', 'strComment' => '',
							'flagTag' => 'input', 'flagInputType' => 'password', 'numMaxlength' => 0,
							'numWidth' => 80, 'unitWidth' => '%', 'numHeight' => 0, 'unitHeight' => '',
							'arrayOption' => array(),
							'flagFoldUse' => 0, 'flagFoldNow' => 0,
						),
					),
					'varsBtn' => array(
						array(
							'flagUse' => 1, 'flagLeftUse' => 0, 'flagRightUse' => 1,
							'flagTextUse' => 0, 'flagBtnUse' => 1,
							'id' => 'Start', 'vars' => array('flag' => 'save',),
							'strTitle' => 'ログイン' ,
						),
/*
						array(
							'flagUse' => 1, 'flagLeftUse' => 1, 'flagRightUse' => 0, 'flagTextUse' => 1, 'flagBtnUse' => 0,
							'id' => 'Lang', 'vars' => array('flag' => 'lang',),
							'strTitle' => '表示言語' ,
						),
*/
						array(
							'flagUse' => 1, 'flagLeftUse' => 1, 'flagRightUse' => 0, 'flagTextUse' => 1, 'flagBtnUse' => 0,
							'id' => 'Sign', 'vars' => array('flag' => 'sign',),
							'strTitle' => '登録申請' ,
						),
						array(
							'flagUse' => 1, 'flagLeftUse' => 1, 'flagRightUse' => 0, 'flagTextUse' => 1, 'flagBtnUse' => 0,
							'id' => 'Forgot', 'vars' => array('flag' => 'forgot',),
							'strTitle' => '再発行' ,
						),
					),
				),
				'lang' => array(
					'strTitle' => '表示言語',
					'varsDetail' => array(
						array(
							'flagMustUse' => 1,
							'id' => 'StrLang',
							'strTitle' => '表示言語', 'strExplain' => '表示言語を設定することができます。<br> ※ページ更新後に反映されます。', 'value' => '',
							'flagErrorNow' => 0,
							'arrayError' => array(
								array( 'flagCheck' => 'blank', 'flagUse' => 1, 'flagNow' => 0, 'flagType' => 'empty', 'strComment' => array('common' => '記入漏れがあるようです。', ), ),
								array( 'flagCheck' => 'word', 'flagUse' => 1, 'flagNow' => 0, 'flagArray' => 0, 'flagType' => 'half', 'strComment' => array('common' => '半角英数で記入されていないようです。', ), ),
							),
							'flagContentUse' => 0,
							'flagCommentUse' => 0, 'strCommentTitle' => '', 'strComment' => '',
							'flagTag' => 'select', 'flagInputType' => '', 'numMaxlength' => 0,
							'numWidth' => 40, 'unitWidth' => '%', 'numHeight' => 0, 'unitHeight' => '',
							'arrayOption' => array(),
							'flagFoldUse' => 0, 'flagFoldNow' => 0,
						),
					),
					'varsBtn' => array(
						array(
							'flagUse' => 1, 'flagLeftUse' => 0, 'flagRightUse' => 1, 'flagTextUse' => 0, 'flagBtnUse' => 1,
							'id' => 'Lang', 'vars' => array('flag' => 'save',),
							'strTitle' => '保存' ,
						),
						array(
							'flagUse' => 1, 'flagLeftUse' => 1, 'flagRightUse' => 0, 'flagTextUse' => 1, 'flagBtnUse' => 0,
							'id' => 'Back', 'vars' => array('flag' => 'start',),
							'strTitle' => '戻る' ,
						),
					),
				),
				'forgot' => array(
					'strTitle' => 'パスワード再発行',
					'varsDetail' => array(
						array(
							'flagMustUse' => 1,
							'id' => 'StrMailPc',
							'strTitle' => 'メールアドレス', 'strExplain' => '※半角英数で記入してください。', 'value' => '',
							'flagErrorNow' => 0,
							'arrayError' => array(
								array( 'flagCheck' => 'blank', 'flagUse' => 1, 'flagNow' => 0, 'flagType' => 'empty', 'strComment' => array('common' => '記入漏れがあるようです。', ), ),
								array( 'flagCheck' => 'word', 'flagUse' => 1, 'flagNow' => 0, 'flagArray' => 0, 'flagType' => 'mail', 'strComment' => array('common' => 'メールで通常、予定されていない文字が使用されているようです。', ), ),
								array( 'flagCheck' => 'format', 'flagUse' => 1, 'flagNow' => 0, 'flagArray' => 0, 'flagType' => 'mail', 'strComment' => array('common' => 'メール構文にエラーがあるようです。', ), ),
							),
							'flagContentUse' => 0,
							'flagCommentUse' => 0, 'strCommentTitle' => '', 'strComment' => '',
							'flagTag' => 'input', 'flagInputType' => 'text', 'numMaxlength' => 0,
							'numWidth' => 80, 'unitWidth' => '%', 'numHeight' => 0, 'unitHeight' => '',
							'arrayOption' => array(),
							'flagFoldUse' => 0, 'flagFoldNow' => 0,
						),
					),
					'varsBtn' => array(
						array(
							'flagUse' => 1, 'flagLeftUse' => 0, 'flagRightUse' => 1, 'flagTextUse' => 0, 'flagBtnUse' => 1,
							'id' => 'Forgot', 'vars' => array('flag' => 'save',),
							'strTitle' => '再発行' ,
						),
						array(
							'flagUse' => 1, 'flagLeftUse' => 1, 'flagRightUse' => 0, 'flagTextUse' => 1, 'flagBtnUse' => 0,
							'id' => 'Back', 'vars' => array('flag' => 'start',),
							'strTitle' => '戻る' ,
						),
					),
				),
				'endSecond' => array(
					'strTitle' => '二段階認証',
					'varsDetail' => array(
						array(
							'flagMustUse' => 1,
							'id' => '',
							'strTitle' => '', 'strExplain' => '', 'value' => '',
							'flagErrorNow' => 0,
							'arrayError' => array(),
							'flagContentUse' => 0,
							'flagCommentUse' => 1, 'strCommentTitle' => '二段階認証メール送付', 'strComment' => '二段階認証メールを送付致しました。<br>　※ 遅延が生じる場合があることをご承知ください。<br>　※ メールが届かない場合は、直接運営者に連絡してください。',
							'flagTag' => 'input', 'flagInputType' => 'text', 'numMaxlength' => 0,
							'numWidth' => 80, 'unitWidth' => '%', 'numHeight' => 0, 'unitHeight' => '',
							'arrayOption' => array(),
							'flagFoldUse' => 0, 'flagFoldNow' => 0,
						),
					),
					'varsBtn' => array(),
				),
				'endSign' => array(
					'strTitle' => 'メール送付完了',
					'varsDetail' => array(
						array(
							'flagMustUse' => 1,
							'id' => '',
							'strTitle' => '', 'strExplain' => '', 'value' => '',
							'flagErrorNow' => 0,
							'arrayError' => array(),
							'flagContentUse' => 0,
							'flagCommentUse' => 1, 'strCommentTitle' => '認証手続案内メール送付', 'strComment' => '認証手続の案内メールを送付致しました。<br>　※ 遅延が生じる場合があることをご承知ください。<br>　※ メールが届かない場合は、直接運営者に連絡してください。',
							'flagTag' => 'input', 'flagInputType' => 'text', 'numMaxlength' => 0,
							'numWidth' => 80, 'unitWidth' => '%', 'numHeight' => 0, 'unitHeight' => '',
							'arrayOption' => array(),
							'flagFoldUse' => 0, 'flagFoldNow' => 0,
						),
					),
					'varsBtn' => array(),
				),
				'endForgot' => array(
					'strTitle' => 'メール送付完了',
					'varsDetail' => array(
						array(
							'flagMustUse' => 1,
							'id' => '',
							'strTitle' => '', 'strExplain' => '', 'value' => '',
							'flagErrorNow' => 0,
							'arrayError' => array(),
							'flagContentUse' => 0,
							'flagCommentUse' => 1, 'strCommentTitle' => '認証手続案内メール送付', 'strComment' => '認証手続の案内メールを送付致しました。<br>　※ 遅延が生じる場合があることをご承知ください。<br>　※ メールが届かない場合は、直接運営者に連絡してください。',
							'flagTag' => 'input', 'flagInputType' => 'text', 'numMaxlength' => 0,
							'numWidth' => 80, 'unitWidth' => '%', 'numHeight' => 0, 'unitHeight' => '',
							'arrayOption' => array(),
							'flagFoldUse' => 0, 'flagFoldNow' => 0,
						),
					),
					'varsBtn' => array(),
				),
				'sign' => array(
					'strTitle' => '登録申請',
					'varsDetail' => array(
						array(
							'flagMustUse' => 1,
							'id' => 'StrCodeName',
							'strTitle' => 'システム内表示名', 'strExplain' => 'システム内で表示される名前を記入してください。', 'value' => '',
							'flagErrorNow' => 0,
							'arrayError' => array(
								array( 'flagCheck' => 'blank', 'flagUse' => 1, 'flagNow' => 0, 'flagType' => 'empty', 'strComment' => array('common' => '記入漏れがあるようです。', ), ),
								array( 'flagCheck' => 'strUnique', 'flagUse' => 1, 'flagNow' => 0, 'strComment' => array('common' => '機種依存文字が混入しているようです。', ), ),
								array( 'flagCheck' => 'already', 'flagUse' => 1, 'flagNow' => 0, 'strComment' => array('common' => '当該表示名は既に使用されているようです。', ), ),
							),
							'flagContentUse' => 0,
							'flagCommentUse' => 0, 'strCommentTitle' => '', 'strComment' => '',
							'flagTag' => 'input', 'flagInputType' => 'text', 'numMaxlength' => 0,
							'numWidth' => 80, 'unitWidth' => '%', 'numHeight' => 0, 'unitHeight' => '',
							'arrayOption' => array(),
							'flagFoldUse' => 0, 'flagFoldNow' => 0,
						),
						array(
							'flagMustUse' => 1,
							'id' => 'IdLogin',
							'strTitle' => 'ログインID', 'strExplain' => 'ログインの際使用するIDを設定してください。<br>　※ 半角英数で記入してください。<br>　※ 5文字以上記入してください。', 'value' => '',
							'flagErrorNow' => 0,
							'arrayError' => array(
								array( 'flagCheck' => 'blank', 'flagUse' => 1, 'flagNow' => 0, 'flagType' => 'empty', 'strComment' => array('common' => '記入漏れがあるようです。', ), ),
								array( 'flagCheck' => 'word', 'flagUse' => 1, 'flagNow' => 0, 'flagArr' => 0, 'flagType' => 'half', 'strComment' => array('common' => '半角英数で記入されていないようです。', ), ),
								array( 'flagCheck' => 'min', 'flagUse' => 1, 'flagNow' => 0, 'flagType' => 'str', 'flagArr' => 0, 'num' => 5, 'strComment' => array('common' => '入力文字数が少ないようです。', ), ),
							),
							'flagContentUse' => 0,
							'flagCommentUse' => 0, 'strCommentTitle' => '', 'strComment' => '',
							'flagTag' => 'input', 'flagInputType' => 'text', 'numMaxlength' => 10,
							'numWidth' => 80, 'unitWidth' => '%', 'numHeight' => 0, 'unitHeight' => '',
							'arrayOption' => array(),
							'flagFoldUse' => 0, 'flagFoldNow' => 0,
						),
						array(
							'flagMustUse' => 1,
							'id' => 'StrMailPc',
							'strTitle' => 'メールアドレス(PC)', 'strExplain' => '※半角英数で記入してください。', 'value' => '',
							'flagErrorNow' => 0,
							'arrayError' => array(
								array( 'flagCheck' => 'blank', 'flagUse' => 1, 'flagNow' => 0, 'flagType' => 'empty', 'strComment' => array('common' => '記入漏れがあるようです。', ), ),
								array( 'flagCheck' => 'word', 'flagUse' => 1, 'flagNow' => 0, 'flagArray' => 0, 'flagType' => 'mail', 'strComment' => array('common' => 'メールで通常、予定されていない文字が使用されているようです。', ), ),
								array( 'flagCheck' => 'format', 'flagUse' => 1, 'flagNow' => 0, 'flagArray' => 0, 'flagType' => 'mail', 'strComment' => array('common' => 'メール構文にエラーがあるようです。', ), ),
								array( 'flagCheck' => 'attest', 'flagUse' => 1, 'strComment' => array('mail' => '違うメールアドレスを設定して頂く必要があるようです。', 'mailHost' => '違うメールホストを設定して頂く必要があるようです',),),
							),
							'flagContentUse' => 0,
							'flagCommentUse' => 0, 'strCommentTitle' => '', 'strComment' => '',
							'flagTag' => 'input', 'flagInputType' => 'text', 'numMaxlength' => 200,
							'numWidth' => 80, 'unitWidth' => '%', 'numHeight' => 0, 'unitHeight' => '',
							'arrayOption' => array(),
							'flagFoldUse' => 0, 'flagFoldNow' => 0,
						),
					),
					'varsBtn' => array(
						array(
							'flagUse' => 1, 'flagLeftUse' => 0, 'flagRightUse' => 1, 'flagTextUse' => 0, 'flagBtnUse' => 1,
							'id' => 'Sign', 'vars' => array('flag' => 'save',),
							'strTitle' => '登録申請' ,
						),
						array(
							'flagUse' => 1, 'flagLeftUse' => 1, 'flagRightUse' => 0, 'flagTextUse' => 1, 'flagBtnUse' => 0,
							'id' => 'Back', 'vars' => array('flag' => 'start',),
							'strTitle' => '戻る' ,
						),
					),
				),
			),
			'view' => array(),
			'form' => array(
				'varsFormat' => array(
					'id' => '',
					'flagType' => 'normalFormat',
					'numHeight' => 0,
					'numWidth' => 0,
					'flagHeaderLeftUse' => 1,
					'strTitleHeaderLeft' => 'ログイン',
					'strClassHeaderLeft' => 'codeLibBaseImgDb',
					'flagHeaderRightUse' => 1,
					'strTitleHeaderRight' => '',
					'strClassHeaderRight' => 'codeLibBaseImgUnloading',
					'flagBodyAutoUse' => 1,
					'strBody' => '',
					'strClassBody' => '',
					'flagFooderUse' => 1,
					'flagFooderLeftUse' => 1,
					'strTitleFooderLeft' => '',
					'strClassFooderLeft' => '',
					'flagFooderRightUse' => 1,
					'strTitleFooderRight' => '',
					'strClassFooderRight' => '',
					'flagHeaderLeftWidth' => 1,
					'numWidthHeaderLeft' => 0,
					'flagHeaderRightWidth' => 0,
					'numWidthHeaderRight' => 0,
					'flagFooderLeftWidth' => 0,
					'numWidthFooderLeft' => 0,
					'flagFooderRightWidth' => 0,
					'numWidthFooderRight' => 0,
				),
				'varsEdit' => array(),
				'varsDetail' => array(
					'varsStatus' => array(
						'flagBtnBottomUse' => 1,
					),
					'varsBtn' => array(),
					'varsDetail' => array(),
				),
			),
		),
		'varsTemplateLayout' => array(
			'varsStatus' => array(
				'flagNaviUse' => 0,
				'flagNaviToolUse' => 0,
				'flagListUse' => 0,
				'flagListToolUse' => 0,
				'flagDetailUse' => 1,
				'flagDetailToolUse' => 0,
			),
			'varsLayout' => array(
				'varsStatus' => array(
					'flagNow' => 1,
					'flagResizeUse' => 0,
					'flagMoveUse' => 0,
					'flagCakeUse' => 0,
					'flagSwitchUse' => 0,
					'flagSwitchNow' => 'Standard',
					'switchList' => array('Standard','Wide','Classic'),
				),
				'varsDetail' => array(
					array(
						'id' => 'Detail',
						'flagBoxUse' => 0,
						'numPriority' => 2,
						'numSort' => 2,
						'numWidth' => 100,			'numHeight' => 200,
						'numWidthMin' => 100,		'numHeightMin' => 200,
						'numWidthStandard' => 100,	'numHeightStandard' => 200,
						'numWidthWide' => 100,		'numHeightWide' => 200,
						'numWidthClassic' => 100,	'numHeightClassic' => 200,
						'numHeightBox' => 0,		'numWidthBox' => 0,//auto
					),
				)
			),
			'detail' => array(
				'varsFormat' => array(
					'id' => '',
					'flagType' => 'normalFormat',
					'numHeight' => 0,
					'numWidth' => 0,
					'flagHeaderLeftUse' => 1,
					'strTitleHeaderLeft' => '',
					'strClassHeaderLeft' => '',
					'flagHeaderRightUse' => 1,
					'strTitleHeaderRight' => '',
					'strClassHeaderRight' => 'codeLibBaseImgUnloading',
					'flagBodyAutoUse' => 1,
					'strBody' => '',
					'strClassBody' => '',
					'flagFooderUse' => 1,
					'flagFooderLeftUse' => 1,
					'strTitleFooderLeft' => '',
					'strClassFooderLeft' => '',
					'flagFooderRightUse' => 1,
					'strTitleFooderRight' => '',
					'strClassFooderRight' => '',
					'flagHeaderLeftWidth' => 1,
					'numWidthHeaderLeft' => 0,
					'flagHeaderRightWidth' => 0,
					'numWidthHeaderRight' => 0,
					'flagFooderLeftWidth' => 0,
					'numWidthFooderLeft' => 0,
					'flagFooderRightWidth' => 1,
					'numWidthFooderRight' => 0,
				),
				'varsTool' => array(),
			),
		),
	),
);
