1568087760	127.0.0.1	localhost	0	slave	else					
1568087761	127.0.0.1	localhost	0	slave	else	Login		Portal	Vars	{"class":"Core","module":"Login","ext":"Portal","child":"","func":"Vars","db":"slave","_":""}
1568087763	127.0.0.1	localhost	0	master	else	Login		Start	Value	{"class":"Core","module":"Login","ext":"Start","child":"","func":"Value","db":"master","jsonValue":{"flag":"","vars":{"IdLogin":"admin","StrPassword":"***"},"idTarget":""},"_":""}
1568087763	127.0.0.1	localhost	1	slave	else					
1568087764	127.0.0.1	localhost	1	slave	else	Base		Portal	Js	{"class":"Core","module":"Base","ext":"Portal","child":"","func":"Js","db":"slave","jsonStamp":[],"_":""}
1568087765	127.0.0.1	localhost	1	slave	else	Accounting		Portal	Js	{"class":"Plugin","module":"Accounting","ext":"Portal","child":"","func":"Js","db":"slave","jsonStamp":[],"_":""}
1568087779	127.0.0.1	localhost	1	master	else	Accounting		Portal	DetailEdit	{"class":"Plugin","module":"Accounting","ext":"Portal","child":"","func":"DetailEdit","db":"master","jsonValue":{"vars":{"NextData":"1","NumFiscalClosingMonth":"6","FlagCR":"0"},"idTarget":"nextData"},"jsonSearch":{"flagReload":0,"numLotNow":0,"ph":{"arrWhere":[],"arrOrder":[]}},"_":""}
1568773085	127.0.0.1	localhost	0	slave	else					
1568773085	127.0.0.1	localhost	0	slave	else	Login		Portal	Vars	{"class":"Core","module":"Login","ext":"Portal","child":"","func":"Vars","db":"slave","_":""}
1568773088	127.0.0.1	localhost	0	master	else	Login		Start	Value	{"class":"Core","module":"Login","ext":"Start","child":"","func":"Value","db":"master","jsonValue":{"flag":"","vars":{"IdLogin":"admin","StrPassword":"***"},"idTarget":""},"_":""}
1568773088	127.0.0.1	localhost	1	slave	else					
1568773088	127.0.0.1	localhost	1	slave	else	Base		Portal	Js	{"class":"Core","module":"Base","ext":"Portal","child":"","func":"Js","db":"slave","jsonStamp":[],"_":""}
1568773091	127.0.0.1	localhost	1	slave	else	Accounting		Portal	Js	{"class":"Plugin","module":"Accounting","ext":"Portal","child":"","func":"Js","db":"slave","jsonStamp":[],"_":""}
1568773104	127.0.0.1	localhost	1	slave	else	Accounting		Ledger	Js	{"class":"Plugin","module":"Accounting","ext":"Ledger","child":"","func":"Js","db":"slave","_":""}
1568773214	127.0.0.1	localhost	1	slave	else	Accounting		Ledger	NaviSearch	{"class":"Plugin","module":"Accounting","ext":"Ledger","child":"","func":"NaviSearch","db":"slave","jsonStamp":{"id":"Plugin-Accounting-Ledger--NaviSearch","stamp":0},"jsonValue":{"vars":{"FlagFiscalPeriod":"f1","IdDepartment":"none","IdAccountTitle":"ordinaryDeposit","IdSubAccountTitle":"none"},"idTarget":""},"jsonSearch":{"flagReload":1,"numLotNow":0,"ph":{"arrWhere":[],"arrOrder":[]}},"_":""}
1568773218	127.0.0.1	localhost	1	slave	else	Accounting		Ledger	ListReload	{"class":"Plugin","module":"Accounting","ext":"Ledger","child":"","func":"ListReload","db":"slave","jsonStamp":{"id":"Plugin-Accounting-Ledger--ListReload","stamp":0},"jsonValue":{"vars":{"FlagFiscalPeriod":"f1","IdDepartment":"none","IdAccountTitle":"ordinaryDeposit","IdSubAccountTitle":"none"},"idTarget":""},"jsonSearch":{"flagReload":0,"numLotNow":1,"ph":{"arrWhere":[],"arrOrder":[]}},"_":""}
1568773270	127.0.0.1	localhost	1	slave	else	Accounting		Ledger	NaviSearch	{"class":"Plugin","module":"Accounting","ext":"Ledger","child":"","func":"NaviSearch","db":"slave","jsonStamp":{"id":"Plugin-Accounting-Ledger--NaviSearch","stamp":"1568773214"},"jsonValue":{"vars":{"FlagFiscalPeriod":"f1","IdDepartment":"none","IdAccountTitle":"shortTermLoansPayable","IdSubAccountTitle":"none"},"idTarget":""},"jsonSearch":{"flagReload":0,"numLotNow":0,"ph":{"arrWhere":[],"arrOrder":[]}},"_":""}
1568773273	127.0.0.1	localhost	1	slave	else	Accounting		Ledger	ListReload	{"class":"Plugin","module":"Accounting","ext":"Ledger","child":"","func":"ListReload","db":"slave","jsonStamp":{"id":"Plugin-Accounting-Ledger--ListReload","stamp":"1568773218"},"jsonValue":{"vars":{"FlagFiscalPeriod":"f1","IdDepartment":"none","IdAccountTitle":"shortTermLoansPayable","IdSubAccountTitle":"none"},"idTarget":""},"jsonSearch":{"flagReload":0,"numLotNow":1,"ph":{"arrWhere":[],"arrOrder":[]}},"_":""}
