<?php

$vars = array(
	'varsStatus' =>  array(
		'flagAppearUse' =>  1,
		'flagNow' =>  'logout',
	),
	'reload' =>  array(
		'varsWindow' =>  array(
			'id' =>  'window' ,
			'strTitle' =>  'Information' ,
			'strClass' =>  'codeLibPopupImgConnect' ,
			'flagLockUse' =>  1,
			'flagLockNow' =>  'fixed',
			'flagCakeUse' =>  0,
			'flagRemoveUse' =>  0,
			'flagCoverUse' =>  0,
			'flagCoverNow' =>  0,
			'flagHideUse' =>  0,
			'flagHideNow' =>  1,
			'flagFoldUse' =>  0,
			'flagFoldNow' =>  0,
			'flagMoveUse' =>  0,
			'flagZIndexUse' =>  1,
			'flagResizeUse' =>  0,
			'flagResizeIni' =>  'all',
			'flagResizeNow' =>  'all',
			'flagSkeletonUse' =>  0,
			'flagBootUse' =>  0,
			'flagSwitchUse' =>  0,
			'numWidthTitle' =>  0,
			'numLeft' =>  0,
			'numTop' =>  0,
			'numWidth' =>  250 ,
			'numHeight' =>  60,
			'numWidthMin' =>  250 ,
			'numHeightMin' =>  60,
			'numZIndex' =>  10000000
		),
		'varsForm' =>  array(
			'varsStatus' => array(
				'flagBtnBottomUse' => 0,
			),
			'varsBtn' =>  array(),
			'varsDetail' =>  array(
				array(
					'flagMustUse' =>  0,
					'id' =>  'comment',
					'strTitle' =>  '' , 'strExplain' =>  '' , 'value' =>  1,
					'flagErrorNow' =>  0,
					'arrayError' =>  array(),
					'flagContentUse' =>  0,
					'flagCommentUse' =>  1, 'strCommentTitle' =>  '自動ページ更新始動', 'strComment' =>  'データを更新するためページを更新します...<br>しばらくお待ちください。',
					'flagTag' =>  '', 'inputType' =>  '', 'maxlength' =>  0,
					'unitWidth' =>  '', 'numWidth' =>  0, 'unitHeight' =>  '', 'numHeight' =>  0,
					'arrayOption' =>  array(),
				),
			),
		),
	),
	'version' =>  array(
		'varsWindow' =>  array(
			'id' =>  'window' ,
			'strTitle' =>  'Information' ,
			'strClass' =>  'codeLibPopupImgConnect' ,
			'flagLockUse' =>  1,
			'flagLockNow' =>  'fixed',
			'flagCakeUse' =>  0,
			'flagRemoveUse' =>  0,
			'flagCoverUse' =>  0,
			'flagCoverNow' =>  0,
			'flagHideUse' =>  0,
			'flagHideNow' =>  1,
			'flagFoldUse' =>  0,
			'flagFoldNow' =>  0,
			'flagMoveUse' =>  0,
			'flagZIndexUse' =>  1,
			'flagResizeUse' =>  0,
			'flagResizeIni' =>  'all',
			'flagResizeNow' =>  'all',
			'flagSkeletonUse' =>  0,
			'flagBootUse' =>  0,
			'flagSwitchUse' =>  0,
			'numWidthTitle' =>  0,
			'numLeft' =>  0,
			'numTop' =>  0,
			'numWidth' =>  250 ,
			'numHeight' =>  60,
			'numWidthMin' =>  250 ,
			'numHeightMin' =>  60,
			'numZIndex' =>  10000000
		),
		'varsForm' =>  array(
			'varsStatus' => array(
				'flagBtnBottomUse' => 0,
			),
			'varsBtn' =>  array(),
			'varsDetail' =>  array(
				array(
					'flagMustUse' =>  0,
					'id' =>  'comment',
					'strTitle' =>  '' , 'strExplain' =>  '' , 'value' =>  1,
					'flagErrorNow' =>  0,
					'arrayError' =>  array(),
					'flagContentUse' =>  0,
					'flagCommentUse' =>  1, 'strCommentTitle' =>  'バージョン更新作業開始', 'strComment' =>  'ページを更新します...<br>しばらくお待ちください。',
					'flagTag' =>  '', 'inputType' =>  '', 'maxlength' =>  0,
					'unitWidth' =>  '', 'numWidth' =>  0, 'unitHeight' =>  '', 'numHeight' =>  0,
					'arrayOption' =>  array(),
				),
			),
		),
	),
	'logout' =>  array(
		'varsWindow' =>  array(
			'id' =>  'window' ,
			'strTitle' =>  'Information' ,
			'strClass' =>  'codeLibPopupImgConnect' ,
			'flagLockUse' =>  1,
			'flagLockNow' =>  'fixed',
			'flagCakeUse' =>  0,
			'flagRemoveUse' =>  0,
			'flagCoverUse' =>  0,
			'flagCoverNow' =>  0,
			'flagHideUse' =>  0,
			'flagHideNow' =>  1,
			'flagFoldUse' =>  0,
			'flagFoldNow' =>  0,
			'flagMoveUse' =>  0,
			'flagZIndexUse' =>  1,
			'flagResizeUse' =>  0,
			'flagResizeIni' =>  'all',
			'flagResizeNow' =>  'all',
			'flagSkeletonUse' =>  0,
			'flagBootUse' =>  0,
			'flagSwitchUse' =>  0,
			'numWidthTitle' =>  0,#auto
			'numLeft' =>  0,
			'numTop' =>  0,
			'numWidth' =>  200 ,
			'numHeight' =>  60,
			'numWidthMin' =>  200 ,
			'numHeightMin' =>  60,
			'numZIndex' =>  10000000
		),
		'varsForm' =>  array(
			'varsStatus' => array(
				'flagBtnBottomUse' => 0,
			),
			'varsBtn' =>  array(),
			'varsDetail' =>  array(
				array(
					'flagMustUse' =>  0,
					'id' =>  'comment',
					'strTitle' =>  '' , 'strExplain' =>  '' , 'value' =>  1,
					'flagErrorNow' =>  0,
					'arrayError' =>  array(),
					'flagContentUse' =>  0,
					'flagCommentUse' =>  1, 'strCommentTitle' =>  'ログアウト始動', 'strComment' =>  'ログアウト処理中...<br>しばらくお待ちください。',
					'flagTag' =>  '', 'inputType' =>  '', 'maxlength' =>  0,
					'unitWidth' =>  '', 'numWidth' =>  0, 'unitHeight' =>  '', 'numHeight' =>  0,
					'arrayOption' =>  array(),
				),
			),
		),
	),
	'autoLogout' =>  array(
		'varsWindow' =>  array(
			'id' =>  'window' ,
			'strTitle' =>  'Information' ,
			'strClass' =>  'codeLibPopupImgConnect' ,
			'flagLockUse' =>  1,
			'flagLockNow' =>  'fixed',
			'flagCakeUse' =>  0,
			'flagRemoveUse' =>  0,
			'flagCoverUse' =>  0,
			'flagCoverNow' =>  0,
			'flagHideUse' =>  0,
			'flagHideNow' =>  1,
			'flagFoldUse' =>  0,
			'flagFoldNow' =>  0,
			'flagMoveUse' =>  0,
			'flagZIndexUse' =>  1,
			'flagResizeUse' =>  0,
			'flagResizeIni' =>  'all',
			'flagResizeNow' =>  'all',
			'flagSkeletonUse' =>  0,
			'flagBootUse' =>  0,
			'flagSwitchUse' =>  0,
			'numWidthTitle' =>  0,#auto
			'numLeft' =>  0,
			'numTop' =>  0,
			'numWidth' =>  200 ,
			'numHeight' =>  60,
			'numWidthMin' =>  200 ,
			'numHeightMin' =>  60,
			'numZIndex' =>  10000000
		),
		'varsForm' =>  array(
			'varsStatus' => array(
				'flagBtnBottomUse' => 0,
			),
			'templateComment' => '<%replace%>分ほど操作がなかったため、<br>強制的にログアウト致します。',
			'varsBtn' =>  array(),
			'varsDetail' =>  array(
				array(
					'flagMustUse' =>  0,
					'id' =>  'comment',
					'strTitle' =>  '' , 'strExplain' =>  '' , 'value' =>  1,
					'flagErrorNow' =>  0,
					'arrayError' =>  array(),
					'flagContentUse' =>  0,
					'flagCommentUse' =>  1, 'strCommentTitle' =>  '自動ログアウト始動', 'strComment' =>  '',
					'flagTag' =>  '', 'inputType' =>  '', 'maxlength' =>  0,
					'unitWidth' =>  '', 'numWidth' =>  0, 'unitHeight' =>  '', 'numHeight' =>  0,
					'arrayOption' =>  array(),
				),
			),
		),
	),
	'news' =>  array(
		'varsWindow' =>  array(
			'id' =>  'News' ,
			'strTitle' =>  'Information' ,
			'strClass' =>  'codeLibPopupImgConnect' ,
			'flagLockUse' =>  1,
			'flagLockNow' =>  'temp',
			'flagCakeUse' =>  0,
			'flagRemoveUse' =>  1,
			'flagCoverUse' =>  0,
			'flagCoverNow' =>  0,
			'flagHideUse' =>  0,
			'flagHideNow' =>  1,
			'flagFoldUse' =>  0,
			'flagFoldNow' =>  0,
			'flagMoveUse' =>  0,
			'flagZIndexUse' =>  1,
			'flagResizeUse' =>  0,
			'flagResizeIni' =>  'all',
			'flagResizeNow' =>  'all',
			'flagSkeletonUse' =>  0,
			'flagBootUse' =>  0,
			'flagSwitchUse' =>  0,
			'numWidthTitle' =>  0,
			'numLeft' =>  0,
			'numTop' =>  0,
			'numWidth' =>  200 ,
			'numHeight' =>  45,
			'numWidthMin' =>  200 ,
			'numHeightMin' =>  45,
			'numZIndex' =>  10000000
		),

		'varsForm' =>  array(
			'varsStatus' => array(
				'flagBtnBottomUse' => 0,
			),
			'templateComment' => '<%replace%>件新着ログを確認しました。',
			'varsBtn' =>  array(),
			'varsDetail' =>  array(
				array(
					'flagMustUse' =>  0,
					'id' =>  'Comment',
					'strTitle' =>  '' , 'strExplain' =>  '' , 'value' =>  1,
					'flagErrorNow' =>  0,
					'arrayError' =>  array(),
					'flagContentUse' =>  0,
					'flagCommentUse' =>  1, 'strCommentTitle' =>  '新着ログ確認', 'strComment' =>  '',
					'flagTag' =>  'select', 'inputType' =>  '', 'maxlength' =>  0,
					'unitWidth' =>  '%', 'numWidth' =>  40, 'unitHeight' =>  '', 'numHeight' =>  0,
					'arrayOption' =>  array(),
				),
			),
		),
	),
);









