<?php
$vars = array(
	array(
		'id' => '', 'flagUse' => 1, 'flagMoveUse' => 0, 'flagInsertUse' => 0, 'flagBtnUse' => 0, 'flagFoldUse' => 1, 'flagFoldNow' => 1, 'flagChildrenUse' => 1,
		'strTitle' => '売上(収入)金額等',
		'strClass' => 'codeLibBaseImgFolder',
		'vars' => array(
			'idTarget' => 'sales', 'flagDebit' => 0,
		),
		'child' => array(
			array(
				'id' => '', 'flagUse' => 1, 'flagMoveUse' => 1, 'flagInsertUse' => 0, 'flagBtnUse' => 1, 'flagFoldUse' => 0, 'flagFoldNow' => 1, 'flagChildrenUse' => 0, 'flagDefault' => 1,
				'strTitle' => '売上高',
				'strClass' => 'codeLibBaseImgSheet',
				'vars' => array(
					'idTarget' => 'netSales', 'idAccountTitleJgaapFS' => 'netSales',
					'varsJgaapCS' => array(),
					'flagUse' => 1, 'flagDebit' => 0,
					'flagConsumptionTaxGeneralRuleEach' => 'tax', 'flagConsumptionTaxGeneralRuleProration' => 'tax', 'flagConsumptionTaxSimpleRule' => 'tax-Default',
					'varsValue' => array(), 'flagSortUse' => 1,
				),
				'child' => array(),
			),
			array(
				'id' => '', 'flagUse' => 1, 'flagMoveUse' => 1, 'flagInsertUse' => 0, 'flagBtnUse' => 1, 'flagFoldUse' => 0, 'flagFoldNow' => 1, 'flagChildrenUse' => 0, 'flagDefault' => 1,
				'strTitle' => '売上値引高',
				'strClass' => 'codeLibBaseImgSheet',
				'vars' => array(
					'idTarget' => 'salesAllowance', 'idAccountTitleJgaapFS' => 'netSales',
					'varsJgaapCS' => array(),
					'flagUse' => 1, 'flagDebit' => 1,
					'flagConsumptionTaxGeneralRuleEach' => 'tax-Back', 'flagConsumptionTaxGeneralRuleProration' => 'tax-Back', 'flagConsumptionTaxSimpleRule' => 'tax-Back-Default',
					'varsValue' => array(), 'flagSortUse' => 1,
				),
				'child' => array(),
			),
			array(
				'id' => '', 'flagUse' => 1, 'flagMoveUse' => 1, 'flagInsertUse' => 0, 'flagBtnUse' => 1, 'flagFoldUse' => 0, 'flagFoldNow' => 1, 'flagChildrenUse' => 0, 'flagDefault' => 1,
				'strTitle' => '売上戻り高',
				'strClass' => 'codeLibBaseImgSheet',
				'vars' => array(
					'idTarget' => 'salesBack', 'idAccountTitleJgaapFS' => 'netSales',
					'varsJgaapCS' => array(),
					'flagUse' => 1, 'flagDebit' => 1,
					'flagConsumptionTaxGeneralRuleEach' => 'tax-Back', 'flagConsumptionTaxGeneralRuleProration' => 'tax-Back', 'flagConsumptionTaxSimpleRule' => 'tax-Back-Default',
					'varsValue' => array(), 'flagSortUse' => 1,
				),
				'child' => array(),
			),
			array(
				'id' => '', 'flagUse' => 1, 'flagMoveUse' => 1, 'flagInsertUse' => 0, 'flagBtnUse' => 1, 'flagFoldUse' => 0, 'flagFoldNow' => 1, 'flagChildrenUse' => 0, 'flagDefault' => 1,
				'strTitle' => '売上割戻し高',
				'strClass' => 'codeLibBaseImgSheet',
				'vars' => array(
					'idTarget' => 'salesRebate', 'idAccountTitleJgaapFS' => 'netSales',
					'varsJgaapCS' => array(),
					'flagUse' => 1, 'flagDebit' => 1,
					'flagConsumptionTaxGeneralRuleEach' => 'tax-Back', 'flagConsumptionTaxGeneralRuleProration' => 'tax-Back', 'flagConsumptionTaxSimpleRule' => 'tax-Back-Default',
					'varsValue' => array(), 'flagSortUse' => 1,
				),
				'child' => array(),
			),
			array(
				'id' => '', 'flagUse' => 1, 'flagMoveUse' => 1, 'flagInsertUse' => 0, 'flagBtnUse' => 1, 'flagFoldUse' => 0, 'flagFoldNow' => 1, 'flagChildrenUse' => 0, 'flagDefault' => 1,
				'strTitle' => '事業分量配当金',
				'strClass' => 'codeLibBaseImgSheet',
				'vars' => array(
					'idTarget' => 'dividendFromBusiness', 'idAccountTitleJgaapFS' => 'netSales',
					'varsJgaapCS' => array(),
					'flagUse' => 1, 'flagDebit' => 0, 'flagConsumptionTaxGeneralRuleEach' => 'taxDebit-Getback', 'flagConsumptionTaxGeneralRuleProration' => 'taxDebit-Getback', 'flagConsumptionTaxSimpleRule' => 'taxDebit-Getback',
					'varsValue' => array(), 'flagSortUse' => 1,
				),
				'child' => array(),
			),
			array(
				'id' => '', 'flagUse' => 1, 'flagMoveUse' => 1, 'flagInsertUse' => 0, 'flagBtnUse' => 1, 'flagFoldUse' => 0, 'flagFoldNow' => 1, 'flagChildrenUse' => 0, 'flagDefault' => 1,
				'strTitle' => '家事消費等',
				'strClass' => 'codeLibBaseImgSheet',
				'vars' => array(
					'idTarget' => 'selfConsumption', 'idAccountTitleJgaapFS' => 'selfConsumption',
					'varsJgaapCS' => array(),
					'flagUse' => 1, 'flagDebit' => 0, 'flagConsumptionTaxGeneralRuleEach' => 'tax', 'flagConsumptionTaxGeneralRuleProration' => 'tax', 'flagConsumptionTaxSimpleRule' => 'tax-Default',
					'varsValue' => array(), 'flagSortUse' => 1,
				),
				'child' => array(),
			),
			array(
				'id' => '', 'flagUse' => 1, 'flagMoveUse' => 1, 'flagInsertUse' => 0, 'flagBtnUse' => 1, 'flagFoldUse' => 0, 'flagFoldNow' => 1, 'flagChildrenUse' => 0, 'flagDefault' => 1,
				'strTitle' => '雑収入',
				'strClass' => 'codeLibBaseImgSheet',
				'vars' => array(
					'idTarget' => 'miscellaneousIncome', 'idAccountTitleJgaapFS' => 'miscellaneousIncome',
					'varsJgaapCS' => array(),
					'flagUse' => 1, 'flagDebit' => 0, 'flagConsumptionTaxGeneralRuleEach' => 'tax', 'flagConsumptionTaxGeneralRuleProration' => 'tax', 'flagConsumptionTaxSimpleRule' => 'tax-Default',
					'varsValue' => array(), 'flagSortUse' => 1,
				),
				'child' => array(),
			),
			array(
				'id' => '', 'flagUse' => 1, 'flagMoveUse' => 1, 'flagInsertUse' => 0, 'flagBtnUse' => 1, 'flagFoldUse' => 0, 'flagFoldNow' => 1, 'flagChildrenUse' => 0, 'flagDefault' => 1,
				'strTitle' => '仕入割引',
				'strClass' => 'codeLibBaseImgSheet',
				'vars' => array(
					'idTarget' => 'purchaseDiscounts', 'idAccountTitleJgaapFS' => 'netSales',
					'varsJgaapCS' => array(),
					'flagUse' => 1, 'flagDebit' => 0, 'flagConsumptionTaxGeneralRuleEach' => 'taxDebit-Getback', 'flagConsumptionTaxGeneralRuleProration' => 'taxDebit-Getback', 'flagConsumptionTaxSimpleRule' => 'taxDebit-Getback',
					'varsValue' => array(), 'flagSortUse' => 1,
				),
				'child' => array(),
			),
		),
	),
	array(
		'id' => '', 'flagUse' => 1, 'flagMoveUse' => 0, 'flagInsertUse' => 0, 'flagBtnUse' => 0, 'flagFoldUse' => 1, 'flagFoldNow' => 1, 'flagChildrenUse' => 0, 'flagDefault' => 1,
		'strTitle' => '売上(収入)金額等合計',
		'strClass' => 'codeLibBaseImgSheet',
		'vars' => array(
			'idTarget' => 'salesSum', 'flagDebit' => 0, 'flagCalc' => 'sum', 'varsValue' => array(),
		),
		'child' => array(),
	),
	array(
		'id' => '', 'flagUse' => 1, 'flagMoveUse' => 0, 'flagInsertUse' => 0, 'flagBtnUse' => 0, 'flagFoldUse' => 1, 'flagFoldNow' => 1, 'flagChildrenUse' => 1,
		'strTitle' => '売上原価',
		'strClass' => 'codeLibBaseImgFolder',
		'vars' => array(
			'idTarget' => 'costOfSales', 'flagDebit' => 1,
		),
		'child' => array(
			array(
				'id' => '', 'flagUse' => 1, 'flagMoveUse' => 0, 'flagInsertUse' => 0, 'flagBtnUse' => 0, 'flagFoldUse' => 1, 'flagFoldNow' => 1, 'flagChildrenUse' => 1,
				'strTitle' => '商品',
				'strClass' => 'codeLibBaseImgFolder',
				'vars' => array(
					'idTarget' => 'goods', 'flagDebit' => 1,
				),
				'child' => array(
					array(
						'id' => '', 'flagUse' => 1, 'flagMoveUse' => 0, 'flagInsertUse' => 1, 'flagBtnUse' => 0, 'flagFoldUse' => 1, 'flagFoldNow' => 1, 'flagChildrenUse' => 1,
						'strTitle' => '期首商品棚卸高',
						'strClass' => 'codeLibBaseImgFolder',
						'vars' => array(
							'idTarget' => 'goodsOpeningInventoryWrap', 'flagDebit' => 1,
						),
						'child' => array(
							array(
								'id' => '', 'flagUse' => 1, 'flagMoveUse' => 1, 'flagInsertUse' => 0, 'flagBtnUse' => 1, 'flagFoldUse' => 0, 'flagFoldNow' => 1, 'flagChildrenUse' => 0, 'flagDefault' => 1,
								'strTitle' => '期首商品棚卸高',
								'strClass' => 'codeLibBaseImgSheet',
								'vars' => array(
									'idTarget' => 'goodsOpeningInventory', 'idAccountTitleJgaapFS' => 'goodsOpeningInventory',
									'varsJgaapCS' => array(),
									'flagUse' => 1, 'flagDebit' => 1,
									'flagConsumptionTaxGeneralRuleEach' => 'none', 'flagConsumptionTaxGeneralRuleProration' => 'none', 'flagConsumptionTaxSimpleRule' => 'none',
									'varsValue' => array(), 'flagSortUse' => 1,
								),
								'child' => array(),
							),
						),
					),
					array(
						'id' => '', 'flagUse' => 1, 'flagMoveUse' => 0, 'flagInsertUse' => 0, 'flagBtnUse' => 0, 'flagFoldUse' => 1, 'flagFoldNow' => 1, 'flagChildrenUse' => 0, 'flagDefault' => 1,
						'strTitle' => '期首商品棚卸高合計',
						'strClass' => 'codeLibBaseImgSheet',
						'vars' => array(
							'idTarget' => 'goodsOpeningInventoryWrapSum', 'flagDebit' => 1, 'flagCalc' => 'sum', 'varsValue' => array(),
						),
						'child' => array(),
					),
					array(
						'id' => '', 'flagUse' => 1, 'flagMoveUse' => 0, 'flagInsertUse' => 1, 'flagBtnUse' => 0, 'flagFoldUse' => 1, 'flagFoldNow' => 1, 'flagChildrenUse' => 1,
						'strTitle' => '当期商品仕入高',
						'strClass' => 'codeLibBaseImgFolder',
						'vars' => array(
							'idTarget' => 'goodsPurchesesWrap', 'flagDebit' => 1,
						),
						'child' => array(
							array(
								'id' => '', 'flagUse' => 1, 'flagMoveUse' => 1, 'flagInsertUse' => 0, 'flagBtnUse' => 1, 'flagFoldUse' => 0, 'flagFoldNow' => 1, 'flagChildrenUse' => 0, 'flagDefault' => 1,
								'strTitle' => '当期商品仕入高',
								'strClass' => 'codeLibBaseImgSheet',
								'vars' => array(
									'idTarget' => 'goodsPurcheses', 'idAccountTitleJgaapFS' => 'goodsPurcheses',
									'varsJgaapCS' => array(),
									'flagUse' => 1, 'flagDebit' => 1,
									'flagConsumptionTaxGeneralRuleEach' => 'taxDebit', 'flagConsumptionTaxGeneralRuleProration' => 'taxDebit', 'flagConsumptionTaxSimpleRule' => 'taxDebit',
									'varsValue' => array(), 'flagSortUse' => 1,
								),
								'child' => array(),
							),
							array(
								'id' => '', 'flagUse' => 1, 'flagMoveUse' => 1, 'flagInsertUse' => 0, 'flagBtnUse' => 1, 'flagFoldUse' => 0, 'flagFoldNow' => 1, 'flagChildrenUse' => 0, 'flagDefault' => 1,
								'strTitle' => '仕入値引高',
								'strClass' => 'codeLibBaseImgSheet',
								'vars' => array(
									'idTarget' => 'goodsAllowance', 'idAccountTitleJgaapFS' => 'goodsPurcheses',
									'varsJgaapCS' => array(),
									'flagUse' => 1, 'flagDebit' => 0,
									'flagConsumptionTaxGeneralRuleEach' => 'taxDebit-Getback', 'flagConsumptionTaxGeneralRuleProration' => 'taxDebit-Getback', 'flagConsumptionTaxSimpleRule' => 'taxDebit-Getback',
									'varsValue' => array(), 'flagSortUse' => 1,
								),
								'child' => array(),
							),
							array(
								'id' => '', 'flagUse' => 1, 'flagMoveUse' => 1, 'flagInsertUse' => 0, 'flagBtnUse' => 1, 'flagFoldUse' => 0, 'flagFoldNow' => 1, 'flagChildrenUse' => 0, 'flagDefault' => 1,
								'strTitle' => '仕入戻し高',
								'strClass' => 'codeLibBaseImgSheet',
								'vars' => array(
									'idTarget' => 'goodsBack', 'idAccountTitleJgaapFS' => 'goodsPurcheses',
									'varsJgaapCS' => array(),
									'flagUse' => 1, 'flagDebit' => 0, 'flagConsumptionTaxGeneralRuleEach' => 'taxDebit-Getback', 'flagConsumptionTaxGeneralRuleProration' => 'taxDebit-Getback', 'flagConsumptionTaxSimpleRule' => 'taxDebit-Getback',
									'varsValue' => array(), 'flagSortUse' => 1,
								),
								'child' => array(),
							),
							array(
								'id' => '', 'flagUse' => 1, 'flagMoveUse' => 1, 'flagInsertUse' => 0, 'flagBtnUse' => 1, 'flagFoldUse' => 0, 'flagFoldNow' => 1, 'flagChildrenUse' => 0, 'flagDefault' => 1,
								'strTitle' => '仕入割戻し高',
								'strClass' => 'codeLibBaseImgSheet',
								'vars' => array(
									'idTarget' => 'goodsRevate', 'idAccountTitleJgaapFS' => 'goodsPurcheses',
									'varsJgaapCS' => array(),
									'flagUse' => 1, 'flagDebit' => 0, 'flagConsumptionTaxGeneralRuleEach' => 'taxDebit-Getback', 'flagConsumptionTaxGeneralRuleProration' => 'taxDebit-Getback', 'flagConsumptionTaxSimpleRule' => 'taxDebit-Getback',
									'varsValue' => array(), 'flagSortUse' => 1,
								),
								'child' => array(),
							),
						),
					),
					array(
						'id' => '', 'flagUse' => 1, 'flagMoveUse' => 0, 'flagInsertUse' => 0, 'flagBtnUse' => 0, 'flagFoldUse' => 1, 'flagFoldNow' => 1, 'flagChildrenUse' => 0, 'flagDefault' => 1,
						'strTitle' => '当期商品仕入高合計',
						'strClass' => 'codeLibBaseImgSheet',
						'vars' => array(
							'idTarget' => 'goodsPurchesesWrapSum', 'flagDebit' => 1, 'flagCalc' => 'sum', 'varsValue' => array(),
						),
						'child' => array(),
					),
					array(
						'id' => '', 'flagUse' => 1, 'flagMoveUse' => 0, 'flagInsertUse' => 0, 'flagBtnUse' => 0, 'flagFoldUse' => 1, 'flagFoldNow' => 1, 'flagChildrenUse' => 0, 'flagDefault' => 1,
						'strTitle' => '合計',
						'strClass' => 'codeLibBaseImgSheet',
						'vars' => array(
							'idTarget' => 'goodsDebitNet', 'flagDebit' => 1, 'flagCalc' => 'net', 'varsValue' => array(),
						),
						'child' => array(),
					),
					array(
						'id' => '', 'flagUse' => 1, 'flagMoveUse' => 0, 'flagInsertUse' => 1, 'flagBtnUse' => 0, 'flagFoldUse' => 1, 'flagFoldNow' => 1, 'flagChildrenUse' => 1,
						'strTitle' => '期末商品棚卸高',
						'strClass' => 'codeLibBaseImgFolder',
						'vars' => array(
							'idTarget' => 'goodsClosingInventoryWrap', 'flagDebit' => 0,
						),
						'child' => array(
							array(
								'id' => '', 'flagUse' => 1, 'flagMoveUse' => 1, 'flagInsertUse' => 0, 'flagBtnUse' => 1, 'flagFoldUse' => 0, 'flagFoldNow' => 1, 'flagChildrenUse' => 0, 'flagDefault' => 1,
								'strTitle' => '期末商品棚卸高',
								'strClass' => 'codeLibBaseImgSheet',
								'vars' => array(
									'idTarget' => 'goodsClosingInventory', 'idAccountTitleJgaapFS' => 'goodsClosingInventory',
									'varsJgaapCS' => array(),
									'flagUse' => 1, 'flagDebit' => 0, 'flagConsumptionTaxGeneralRuleEach' => 'none', 'flagConsumptionTaxGeneralRuleProration' => 'none', 'flagConsumptionTaxSimpleRule' => 'none',
									'varsValue' => array(), 'flagSortUse' => 1,
								),
								'child' => array(),
							),
						),
					),
					array(
						'id' => '', 'flagUse' => 1, 'flagMoveUse' => 0, 'flagInsertUse' => 0, 'flagBtnUse' => 0, 'flagFoldUse' => 1, 'flagFoldNow' => 1, 'flagChildrenUse' => 0, 'flagDefault' => 1,
						'strTitle' => '期末商品棚卸高合計',
						'strClass' => 'codeLibBaseImgSheet',
						'vars' => array(
							'idTarget' => 'goodsClosingInventoryWrapSum', 'flagDebit' => 0, 'flagCalc' => 'sum', 'varsValue' => array(),
						),
						'child' => array(),
					),
				),
			),
			array(
				'id' => '', 'flagUse' => 1, 'flagMoveUse' => 0, 'flagInsertUse' => 0, 'flagBtnUse' => 0, 'flagFoldUse' => 1, 'flagFoldNow' => 1, 'flagChildrenUse' => 0, 'flagDefault' => 1,
				'strTitle' => '商品売上原価',
				'strClass' => 'codeLibBaseImgSheet',
				'vars' => array(
					'idTarget' => 'goodsSum', 'flagDebit' => 1, 'flagCalc' => 'sum', 'varsValue' => array(),
				),
				'child' => array(),
			),
			array(
				'id' => '', 'flagUse' => 1, 'flagMoveUse' => 0, 'flagInsertUse' => 0, 'flagBtnUse' => 0, 'flagFoldUse' => 1, 'flagFoldNow' => 1, 'flagChildrenUse' => 1,
				'strTitle' => '製品',
				'strClass' => 'codeLibBaseImgFolder',
				'vars' => array(
					'idTarget' => 'products', 'flagDebit' => 1,
				),
				'child' => array(
					array(
						'id' => '', 'flagUse' => 1, 'flagMoveUse' => 0, 'flagInsertUse' => 1, 'flagBtnUse' => 0, 'flagFoldUse' => 1, 'flagFoldNow' => 1, 'flagChildrenUse' => 1,
						'strTitle' => '期首製品棚卸高',
						'strClass' => 'codeLibBaseImgFolder',
						'vars' => array(
							'idTarget' => 'productsOpeningInventoryWrap', 'flagDebit' => 1,
						),
						'child' => array(
							array(
								'id' => '', 'flagUse' => 1, 'flagMoveUse' => 1, 'flagInsertUse' => 0, 'flagBtnUse' => 1, 'flagFoldUse' => 0, 'flagFoldNow' => 1, 'flagChildrenUse' => 0, 'flagDefault' => 1,
								'strTitle' => '期首製品棚卸高',
								'strClass' => 'codeLibBaseImgSheet',
								'vars' => array(
									'idTarget' => 'productsOpeningInventory', 'idAccountTitleJgaapFS' => 'goodsOpeningInventory',
									'varsJgaapCS' => array(),
									'flagUse' => 1, 'flagDebit' => 1, 'flagConsumptionTaxGeneralRuleEach' => 'none', 'flagConsumptionTaxGeneralRuleProration' => 'none', 'flagConsumptionTaxSimpleRule' => 'none',
									'varsValue' => array(), 'flagSortUse' => 1,
								),
								'child' => array(),
							),
						),
					),
					array(
						'id' => '', 'flagUse' => 1, 'flagMoveUse' => 0, 'flagInsertUse' => 0, 'flagBtnUse' => 0, 'flagFoldUse' => 1, 'flagFoldNow' => 1, 'flagChildrenUse' => 0, 'flagDefault' => 1,
						'strTitle' => '期首製品棚卸高合計',
						'strClass' => 'codeLibBaseImgSheet',
						'vars' => array(
							'idTarget' => 'productsOpeningInventoryWrapSum', 'flagDebit' => 1, 'flagCalc' => 'sum', 'varsValue' => array(),
						),
						'child' => array(),
					),
					array(
						'id' => '', 'flagUse' => 1, 'flagMoveUse' => 1, 'flagInsertUse' => 0, 'flagBtnUse' => 0, 'flagFoldUse' => 0, 'flagFoldNow' => 1, 'flagChildrenUse' => 0, 'flagDefault' => 1,
						'strTitle' => '当期製品製造原価',
						'strClass' => 'codeLibBaseImgSheet',
						'vars' => array(
							'idTarget' => 'currentTermProductsCost', 'flagDebit' => 1, 'varsValue' => array(),
						),
						'child' => array(),
					),
					array(
						'id' => '', 'flagUse' => 1, 'flagMoveUse' => 0, 'flagInsertUse' => 0, 'flagBtnUse' => 0, 'flagFoldUse' => 1, 'flagFoldNow' => 1, 'flagChildrenUse' => 0, 'flagDefault' => 1,
						'strTitle' => '合計',
						'strClass' => 'codeLibBaseImgSheet',
						'vars' => array(
							'idTarget' => 'productsDebitNet', 'flagDebit' => 1, 'flagCalc' => 'net', 'varsValue' => array(),
						),
						'child' => array(),
					),
					array(
						'id' => '', 'flagUse' => 1, 'flagMoveUse' => 0, 'flagInsertUse' => 1, 'flagBtnUse' => 0, 'flagFoldUse' => 1, 'flagFoldNow' => 1, 'flagChildrenUse' => 1,
						'strTitle' => '期末製品棚卸高',
						'strClass' => 'codeLibBaseImgFolder',
						'vars' => array(
							'idTarget' => 'productsClosingInventoryWrap', 'flagDebit' => 0,
						),
						'child' => array(
							array(
								'id' => '', 'flagUse' => 1, 'flagMoveUse' => 1, 'flagInsertUse' => 0, 'flagBtnUse' => 1, 'flagFoldUse' => 0, 'flagFoldNow' => 1, 'flagChildrenUse' => 0, 'flagDefault' => 1,
								'strTitle' => '期末製品棚卸高',
								'strClass' => 'codeLibBaseImgSheet',
								'vars' => array(
									'idTarget' => 'productsClosingInventory', 'idAccountTitleJgaapFS' => 'goodsClosingInventory',
									'varsJgaapCS' => array(),
									'flagUse' => 1, 'flagDebit' => 0, 'flagConsumptionTaxGeneralRuleEach' => 'none', 'flagConsumptionTaxGeneralRuleProration' => 'none', 'flagConsumptionTaxSimpleRule' => 'none',
									'varsValue' => array(), 'flagSortUse' => 1,
								),
								'child' => array(),
							),
						),
					),
					array(
						'id' => '', 'flagUse' => 1, 'flagMoveUse' => 0, 'flagInsertUse' => 0, 'flagBtnUse' => 0, 'flagFoldUse' => 1, 'flagFoldNow' => 1, 'flagChildrenUse' => 0, 'flagDefault' => 1,
						'strTitle' => '期末製品棚卸高合計',
						'strClass' => 'codeLibBaseImgSheet',
						'vars' => array(
							'idTarget' => 'productsClosingInventoryWrapSum', 'flagDebit' => 0, 'flagCalc' => 'sum', 'varsValue' => array(),
						),
						'child' => array(),
					),
				),
			),
			array(
				'id' => '', 'flagUse' => 1, 'flagMoveUse' => 0, 'flagInsertUse' => 0, 'flagBtnUse' => 0, 'flagFoldUse' => 1, 'flagFoldNow' => 1, 'flagChildrenUse' => 0, 'flagDefault' => 1,
				'strTitle' => '製品売上原価',
				'strClass' => 'codeLibBaseImgSheet',
				'vars' => array(
					'idTarget' => 'productsSum', 'flagDebit' => 1, 'flagCalc' => 'sum', 'varsValue' => array(),
				),
				'child' => array(),
			),
		),
	),
	array(
		'id' => '', 'flagUse' => 1, 'flagMoveUse' => 0, 'flagInsertUse' => 0, 'flagBtnUse' => 0, 'flagFoldUse' => 1, 'flagFoldNow' => 1, 'flagChildrenUse' => 0, 'flagDefault' => 1,
		'strTitle' => '売上原価合計',
		'strClass' => 'codeLibBaseImgSheet',
		'vars' => array(
			'idTarget' => 'costOfSalesSum', 'flagDebit' => 1, 'flagCalc' => 'sum', 'varsValue' => array(),
		),
		'child' => array(),
	),
	array(
		'id' => '', 'flagUse' => 1, 'flagMoveUse' => 0, 'flagInsertUse' => 0, 'flagBtnUse' => 0, 'flagFoldUse' => 1, 'flagFoldNow' => 1, 'flagChildrenUse' => 0, 'flagDefault' => 1,
		'strTitle' => '差引金額',
		'strClass' => 'codeLibBaseImgSheet',
		'vars' => array(
			'idTarget' => 'grossProfitOrLossNet', 'flagDebit' => 0, 'flagCalc' => 'net', 'varsValue' => array(),
		),
		'child' => array(),
	),
	array(
		'id' => '', 'flagUse' => 1, 'flagMoveUse' => 0, 'flagInsertUse' => 0, 'flagBtnUse' => 0, 'flagFoldUse' => 1, 'flagFoldNow' => 1, 'flagChildrenUse' => 1,
		'strTitle' => '経費',
		'strClass' => 'codeLibBaseImgFolder',
		'vars' => array(
			'idTarget' => 'expense', 'flagDebit' => 1,
		),
		'child' => array(
			array(
				'id' => '', 'flagUse' => 1, 'flagMoveUse' => 1, 'flagInsertUse' => 0, 'flagBtnUse' => 1, 'flagFoldUse' => 0, 'flagFoldNow' => 1, 'flagChildrenUse' => 0, 'flagDefault' => 1,
				'strTitle' => '租税公課',
				'strClass' => 'codeLibBaseImgSheet',
				'vars' => array(
					'idTarget' => 'taxesAndDues', 'idAccountTitleJgaapFS' => 'taxesAndDues',
					'varsJgaapCS' => array(),
					'flagUse' => 1, 'flagDebit' => 1, 'flagConsumptionTaxGeneralRuleEach' => 'none', 'flagConsumptionTaxGeneralRuleProration' => 'none', 'flagConsumptionTaxSimpleRule' => 'none',
					'varsValue' => array(), 'flagSortUse' => 1,
				),
				'child' => array(),
			),
			array(
				'id' => '', 'flagUse' => 1, 'flagMoveUse' => 1, 'flagInsertUse' => 0, 'flagBtnUse' => 1, 'flagFoldUse' => 0, 'flagFoldNow' => 1, 'flagChildrenUse' => 0, 'flagDefault' => 1,
				'strTitle' => '荷造運賃手数料',
				'strClass' => 'codeLibBaseImgSheet',
				'vars' => array(
					'idTarget' => 'packingAndFreight', 'idAccountTitleJgaapFS' => 'packingAndFreight',
					'varsJgaapCS' => array(),
					'flagUse' => 1, 'flagDebit' => 1, 'flagConsumptionTaxGeneralRuleEach' => 'taxDebit', 'flagConsumptionTaxGeneralRuleProration' => 'taxDebit', 'flagConsumptionTaxSimpleRule' => 'taxDebit',
					'varsValue' => array(), 'flagSortUse' => 1,
				),
				'child' => array(),
			),
			array(
				'id' => '', 'flagUse' => 1, 'flagMoveUse' => 1, 'flagInsertUse' => 0, 'flagBtnUse' => 1, 'flagFoldUse' => 0, 'flagFoldNow' => 1, 'flagChildrenUse' => 0, 'flagDefault' => 1,
				'strTitle' => '運賃',
				'strClass' => 'codeLibBaseImgSheet',
				'vars' => array(
					'idTarget' => 'packingAndFreightExpenses', 'idAccountTitleJgaapFS' => 'packingAndFreight',
					'varsJgaapCS' => array(),
					'flagUse' => 1, 'flagDebit' => 1, 'flagConsumptionTaxGeneralRuleEach' => 'taxDebit', 'flagConsumptionTaxGeneralRuleProration' => 'taxDebit', 'flagConsumptionTaxSimpleRule' => 'taxDebit',
					'varsValue' => array(), 'flagSortUse' => 1,
				),
				'child' => array(),
			),
			array(
				'id' => '', 'flagUse' => 1, 'flagMoveUse' => 1, 'flagInsertUse' => 0, 'flagBtnUse' => 1, 'flagFoldUse' => 0, 'flagFoldNow' => 1, 'flagChildrenUse' => 0, 'flagDefault' => 1,
				'strTitle' => '水道光熱費',
				'strClass' => 'codeLibBaseImgSheet',
				'vars' => array(
					'idTarget' => 'waterPowerExpenses', 'idAccountTitleJgaapFS' => 'waterPowerExpenses',
					'varsJgaapCS' => array(),
					'flagUse' => 1, 'flagDebit' => 1, 'flagConsumptionTaxGeneralRuleEach' => 'taxDebit', 'flagConsumptionTaxGeneralRuleProration' => 'taxDebit', 'flagConsumptionTaxSimpleRule' => 'taxDebit',
					'varsValue' => array(), 'flagSortUse' => 1,
				),
				'child' => array(),
			),
			array(
				'id' => '', 'flagUse' => 1, 'flagMoveUse' => 1, 'flagInsertUse' => 0, 'flagBtnUse' => 1, 'flagFoldUse' => 0, 'flagFoldNow' => 1, 'flagChildrenUse' => 0, 'flagDefault' => 1,
				'strTitle' => '旅費交通費',
				'strClass' => 'codeLibBaseImgSheet',
				'vars' => array(
					'idTarget' => 'transportationExpenses', 'idAccountTitleJgaapFS' => 'transportationExpenses',
					'varsJgaapCS' => array(),
					'flagUse' => 1, 'flagDebit' => 1, 'flagConsumptionTaxGeneralRuleEach' => 'taxDebit', 'flagConsumptionTaxGeneralRuleProration' => 'taxDebit', 'flagConsumptionTaxSimpleRule' => 'taxDebit',
					'varsValue' => array(), 'flagSortUse' => 1,
				),
				'child' => array(),
			),
			array(
				'id' => '', 'flagUse' => 1, 'flagMoveUse' => 1, 'flagInsertUse' => 0, 'flagBtnUse' => 1, 'flagFoldUse' => 0, 'flagFoldNow' => 1, 'flagChildrenUse' => 0, 'flagDefault' => 1,
				'strTitle' => '通信費',
				'strClass' => 'codeLibBaseImgSheet',
				'vars' => array(
					'idTarget' => 'correspondenceExpenses', 'idAccountTitleJgaapFS' => 'correspondenceExpenses',
					'varsJgaapCS' => array(),
					'flagUse' => 1, 'flagDebit' => 1, 'flagConsumptionTaxGeneralRuleEach' => 'taxDebit', 'flagConsumptionTaxGeneralRuleProration' => 'taxDebit', 'flagConsumptionTaxSimpleRule' => 'taxDebit',
					'varsValue' => array(), 'flagSortUse' => 1,
				),
				'child' => array(),
			),
			array(
				'id' => '', 'flagUse' => 1, 'flagMoveUse' => 1, 'flagInsertUse' => 0, 'flagBtnUse' => 1, 'flagFoldUse' => 0, 'flagFoldNow' => 1, 'flagChildrenUse' => 0, 'flagDefault' => 1,
				'strTitle' => '広告宣伝費',
				'strClass' => 'codeLibBaseImgSheet',
				'vars' => array(
					'idTarget' => 'advertisingExpenses', 'idAccountTitleJgaapFS' => 'advertisingExpenses',
					'varsJgaapCS' => array(),
					'flagUse' => 1, 'flagDebit' => 1, 'flagConsumptionTaxGeneralRuleEach' => 'taxDebit', 'flagConsumptionTaxGeneralRuleProration' => 'taxDebit', 'flagConsumptionTaxSimpleRule' => 'taxDebit',
					'varsValue' => array(), 'flagSortUse' => 1,
				),
				'child' => array(),
			),
			array(
				'id' => '', 'flagUse' => 1, 'flagMoveUse' => 1, 'flagInsertUse' => 0, 'flagBtnUse' => 1, 'flagFoldUse' => 0, 'flagFoldNow' => 1, 'flagChildrenUse' => 0, 'flagDefault' => 1,
				'strTitle' => '接待交際費',
				'strClass' => 'codeLibBaseImgSheet',
				'vars' => array(
					'idTarget' => 'entertainmentExpenses', 'idAccountTitleJgaapFS' => 'entertainmentExpenses',
					'varsJgaapCS' => array(),
					'flagUse' => 1, 'flagDebit' => 1, 'flagConsumptionTaxGeneralRuleEach' => 'taxDebit', 'flagConsumptionTaxGeneralRuleProration' => 'taxDebit', 'flagConsumptionTaxSimpleRule' => 'taxDebit',
					'varsValue' => array(), 'flagSortUse' => 1,
				),
				'child' => array(),
			),
			array(
				'id' => '', 'flagUse' => 1, 'flagMoveUse' => 1, 'flagInsertUse' => 0, 'flagBtnUse' => 1, 'flagFoldUse' => 0, 'flagFoldNow' => 1, 'flagChildrenUse' => 0, 'flagDefault' => 1,
				'strTitle' => '保険料',
				'strClass' => 'codeLibBaseImgSheet',
				'vars' => array(
					'idTarget' => 'insuranceExpenses', 'idAccountTitleJgaapFS' => 'insuranceExpenses',
					'varsJgaapCS' => array(),
					'flagUse' => 1, 'flagDebit' => 1, 'flagConsumptionTaxGeneralRuleEach' => 'none', 'flagConsumptionTaxGeneralRuleProration' => 'none', 'flagConsumptionTaxSimpleRule' => 'none',
					'varsValue' => array(), 'flagSortUse' => 1,
				),
				'child' => array(),
			),
			array(
				'id' => '', 'flagUse' => 1, 'flagMoveUse' => 1, 'flagInsertUse' => 0, 'flagBtnUse' => 1, 'flagFoldUse' => 0, 'flagFoldNow' => 1, 'flagChildrenUse' => 0, 'flagDefault' => 1,
				'strTitle' => '修繕費',
				'strClass' => 'codeLibBaseImgSheet',
				'vars' => array(
					'idTarget' => 'repair', 'idAccountTitleJgaapFS' => 'repair',
					'varsJgaapCS' => array(),
					'flagUse' => 1, 'flagDebit' => 1, 'flagConsumptionTaxGeneralRuleEach' => 'taxDebit', 'flagConsumptionTaxGeneralRuleProration' => 'taxDebit', 'flagConsumptionTaxSimpleRule' => 'taxDebit',
					'varsValue' => array(), 'flagSortUse' => 1,
				),
				'child' => array(),
			),
			array(
				'id' => '', 'flagUse' => 1, 'flagMoveUse' => 1, 'flagInsertUse' => 0, 'flagBtnUse' => 1, 'flagFoldUse' => 0, 'flagFoldNow' => 1, 'flagChildrenUse' => 0, 'flagDefault' => 1,
				'strTitle' => '消耗品費',
				'strClass' => 'codeLibBaseImgSheet',
				'vars' => array(
					'idTarget' => 'suppliesExpenses', 'idAccountTitleJgaapFS' => 'suppliesExpenses',
					'varsJgaapCS' => array(),
					'flagUse' => 1, 'flagDebit' => 1, 'flagConsumptionTaxGeneralRuleEach' => 'taxDebit', 'flagConsumptionTaxGeneralRuleProration' => 'taxDebit', 'flagConsumptionTaxSimpleRule' => 'taxDebit',
					'varsValue' => array(), 'flagSortUse' => 1,
				),
				'child' => array(),
			),
			array(
				'id' => '', 'flagUse' => 1, 'flagMoveUse' => 1, 'flagInsertUse' => 0, 'flagBtnUse' => 1, 'flagFoldUse' => 0, 'flagFoldNow' => 1, 'flagChildrenUse' => 0, 'flagDefault' => 1,
				'strTitle' => '事務用品費',
				'strClass' => 'codeLibBaseImgSheet',
				'vars' => array(
					'idTarget' => 'stationeryExpenses', 'idAccountTitleJgaapFS' => 'suppliesExpenses',
					'varsJgaapCS' => array(),
					'flagUse' => 1, 'flagDebit' => 1, 'flagConsumptionTaxGeneralRuleEach' => 'taxDebit', 'flagConsumptionTaxGeneralRuleProration' => 'taxDebit', 'flagConsumptionTaxSimpleRule' => 'taxDebit',
					'varsValue' => array(), 'flagSortUse' => 1,
				),
				'child' => array(),
			),
			array(
				'id' => '', 'flagUse' => 1, 'flagMoveUse' => 1, 'flagInsertUse' => 0, 'flagBtnUse' => 1, 'flagFoldUse' => 0, 'flagFoldNow' => 1, 'flagChildrenUse' => 0, 'flagDefault' => 1,
				'strTitle' => '減価償却費',
				'strClass' => 'codeLibBaseImgSheet',
				'vars' => array(
					'idTarget' => 'depreciation', 'idAccountTitleJgaapFS' => 'depreciation',
					'varsJgaapCS' => array(),
					'flagUse' => 1, 'flagDebit' => 1, 'flagConsumptionTaxGeneralRuleEach' => 'none', 'flagConsumptionTaxGeneralRuleProration' => 'none', 'flagConsumptionTaxSimpleRule' => 'none',
					'varsValue' => array(), 'flagSortUse' => 1,
				),
				'child' => array(),
			),
			array(
				'id' => '', 'flagUse' => 1, 'flagMoveUse' => 1, 'flagInsertUse' => 0, 'flagBtnUse' => 1, 'flagFoldUse' => 0, 'flagFoldNow' => 1, 'flagChildrenUse' => 0, 'flagDefault' => 1,
				'strTitle' => '給料手当',
				'strClass' => 'codeLibBaseImgSheet',
				'vars' => array(
					'idTarget' => 'employeeSalariesAndAllowances', 'idAccountTitleJgaapFS' => 'employeeSalariesAndAllowances',
					'varsJgaapCS' => array(),
					'flagUse' => 1, 'flagDebit' => 1, 'flagConsumptionTaxGeneralRuleEach' => 'none', 'flagConsumptionTaxGeneralRuleProration' => 'none', 'flagConsumptionTaxSimpleRule' => 'none',
					'varsValue' => array(), 'flagSortUse' => 1,
				),
				'child' => array(),
			),
			array(
				'id' => '', 'flagUse' => 1, 'flagMoveUse' => 1, 'flagInsertUse' => 0, 'flagBtnUse' => 1, 'flagFoldUse' => 0, 'flagFoldNow' => 1, 'flagChildrenUse' => 0, 'flagDefault' => 1,
				'strTitle' => '雑給',
				'strClass' => 'codeLibBaseImgSheet',
				'vars' => array(
					'idTarget' => 'miscellaneousSalaries', 'idAccountTitleJgaapFS' => 'employeeSalariesAndAllowances',
					'varsJgaapCS' => array(),
					'flagUse' => 1, 'flagDebit' => 1, 'flagConsumptionTaxGeneralRuleEach' => 'none', 'flagConsumptionTaxGeneralRuleProration' => 'none', 'flagConsumptionTaxSimpleRule' => 'none',
					'varsValue' => array(), 'flagSortUse' => 1,
				),
				'child' => array(),
			),
			array(
				'id' => '', 'flagUse' => 1, 'flagMoveUse' => 1, 'flagInsertUse' => 0, 'flagBtnUse' => 1, 'flagFoldUse' => 0, 'flagFoldNow' => 1, 'flagChildrenUse' => 0, 'flagDefault' => 1,
				'strTitle' => '賞与',
				'strClass' => 'codeLibBaseImgSheet',
				'vars' => array(
					'idTarget' => 'bonus', 'idAccountTitleJgaapFS' => 'employeeSalariesAndAllowances',
					'varsJgaapCS' => array(),
					'flagUse' => 1, 'flagDebit' => 1, 'flagConsumptionTaxGeneralRuleEach' => 'none', 'flagConsumptionTaxGeneralRuleProration' => 'none', 'flagConsumptionTaxSimpleRule' => 'none',
					'varsValue' => array(), 'flagSortUse' => 1,
				),
				'child' => array(),
			),
			array(
				'id' => '', 'flagUse' => 1, 'flagMoveUse' => 1, 'flagInsertUse' => 0, 'flagBtnUse' => 1, 'flagFoldUse' => 0, 'flagFoldNow' => 1, 'flagChildrenUse' => 0, 'flagDefault' => 1,
				'strTitle' => '退職金',
				'strClass' => 'codeLibBaseImgSheet',
				'vars' => array(
					'idTarget' => 'retirementPayments', 'idAccountTitleJgaapFS' => 'employeeSalariesAndAllowances',
					'varsJgaapCS' => array(),
					'flagUse' => 1, 'flagDebit' => 1, 'flagConsumptionTaxGeneralRuleEach' => 'none', 'flagConsumptionTaxGeneralRuleProration' => 'none', 'flagConsumptionTaxSimpleRule' => 'none',
					'varsValue' => array(), 'flagSortUse' => 1,
				),
				'child' => array(),
			),
			array(
				'id' => '', 'flagUse' => 1, 'flagMoveUse' => 1, 'flagInsertUse' => 0, 'flagBtnUse' => 1, 'flagFoldUse' => 0, 'flagFoldNow' => 1, 'flagChildrenUse' => 0, 'flagDefault' => 1,
				'strTitle' => '退職金掛金',
				'strClass' => 'codeLibBaseImgSheet',
				'vars' => array(
					'idTarget' => 'provisionForLiabilityForRetirementBenefits', 'idAccountTitleJgaapFS' => 'employeeSalariesAndAllowances',
					'varsJgaapCS' => array(),
					'flagUse' => 1, 'flagDebit' => 1, 'flagConsumptionTaxGeneralRuleEach' => 'none', 'flagConsumptionTaxGeneralRuleProration' => 'none', 'flagConsumptionTaxSimpleRule' => 'none',
					'varsValue' => array(), 'flagSortUse' => 1,
				),
				'child' => array(),
			),
			array(
				'id' => '', 'flagUse' => 1, 'flagMoveUse' => 1, 'flagInsertUse' => 0, 'flagBtnUse' => 1, 'flagFoldUse' => 0, 'flagFoldNow' => 1, 'flagChildrenUse' => 0, 'flagDefault' => 1,
				'strTitle' => '福利厚生費',
				'strClass' => 'codeLibBaseImgSheet',
				'vars' => array(
					'idTarget' => 'welfareExpenses', 'idAccountTitleJgaapFS' => 'welfareExpenses',
					'varsJgaapCS' => array(),
					'flagUse' => 1, 'flagDebit' => 1, 'flagConsumptionTaxGeneralRuleEach' => 'taxDebit', 'flagConsumptionTaxGeneralRuleProration' => 'taxDebit', 'flagConsumptionTaxSimpleRule' => 'taxDebit',
					'varsValue' => array(), 'flagSortUse' => 1,
				),
				'child' => array(),
			),
			array(
				'id' => '', 'flagUse' => 1, 'flagMoveUse' => 1, 'flagInsertUse' => 0, 'flagBtnUse' => 1, 'flagFoldUse' => 0, 'flagFoldNow' => 1, 'flagChildrenUse' => 0, 'flagDefault' => 1,
				'strTitle' => '法定福利費',
				'strClass' => 'codeLibBaseImgSheet',
				'vars' => array(
					'idTarget' => 'legalWelfareExpenses', 'idAccountTitleJgaapFS' => 'welfareExpenses',
					'varsJgaapCS' => array(),
					'flagUse' => 1, 'flagDebit' => 1, 'flagConsumptionTaxGeneralRuleEach' => 'none', 'flagConsumptionTaxGeneralRuleProration' => 'none', 'flagConsumptionTaxSimpleRule' => 'none',
					'varsValue' => array(), 'flagSortUse' => 1,
				),
				'child' => array(),
			),
			array(
				'id' => '', 'flagUse' => 1, 'flagMoveUse' => 1, 'flagInsertUse' => 0, 'flagBtnUse' => 1, 'flagFoldUse' => 0, 'flagFoldNow' => 1, 'flagChildrenUse' => 0, 'flagDefault' => 1,
				'strTitle' => '外注費',
				'strClass' => 'codeLibBaseImgSheet',
				'vars' => array(
					'idTarget' => 'outsourcingExpenses', 'idAccountTitleJgaapFS' => 'outsourcingExpenses',
					'varsJgaapCS' => array(),
					'flagUse' => 1, 'flagDebit' => 1, 'flagConsumptionTaxGeneralRuleEach' => 'taxDebit', 'flagConsumptionTaxGeneralRuleProration' => 'taxDebit', 'flagConsumptionTaxSimpleRule' => 'taxDebit',
					'varsValue' => array(), 'flagSortUse' => 1,
				),
				'child' => array(),
			),
			array(
				'id' => '', 'flagUse' => 1, 'flagMoveUse' => 1, 'flagInsertUse' => 0, 'flagBtnUse' => 1, 'flagFoldUse' => 0, 'flagFoldNow' => 1, 'flagChildrenUse' => 0, 'flagDefault' => 1,
				'strTitle' => '支払利息',
				'strClass' => 'codeLibBaseImgSheet',
				'vars' => array(
					'idTarget' => 'interestPaid', 'idAccountTitleJgaapFS' => 'commissionPaid',
					'varsJgaapCS' => array(),
					'flagUse' => 1, 'flagDebit' => 1, 'flagConsumptionTaxGeneralRuleEach' => 'none', 'flagConsumptionTaxGeneralRuleProration' => 'none', 'flagConsumptionTaxSimpleRule' => 'none',
					'varsValue' => array(), 'flagSortUse' => 1,
				),
				'child' => array(),
			),
			array(
				'id' => '', 'flagUse' => 1, 'flagMoveUse' => 1, 'flagInsertUse' => 0, 'flagBtnUse' => 1, 'flagFoldUse' => 0, 'flagFoldNow' => 1, 'flagChildrenUse' => 0, 'flagDefault' => 1,
				'strTitle' => '支払割引料',
				'strClass' => 'codeLibBaseImgSheet',
				'vars' => array(
					'idTarget' => 'discountPaid', 'idAccountTitleJgaapFS' => 'commissionPaid',
					'varsJgaapCS' => array(),
					'flagUse' => 1, 'flagDebit' => 1, 'flagConsumptionTaxGeneralRuleEach' => 'none', 'flagConsumptionTaxGeneralRuleProration' => 'none', 'flagConsumptionTaxSimpleRule' => 'none',
					'varsValue' => array(), 'flagSortUse' => 1,
				),
				'child' => array(),
			),
			array(
				'id' => '', 'flagUse' => 1, 'flagMoveUse' => 1, 'flagInsertUse' => 0, 'flagBtnUse' => 1, 'flagFoldUse' => 0, 'flagFoldNow' => 1, 'flagChildrenUse' => 0, 'flagDefault' => 1,
				'strTitle' => '地代家賃',
				'strClass' => 'codeLibBaseImgSheet',
				'vars' => array(
					'idTarget' => 'rents', 'idAccountTitleJgaapFS' => 'rents',
					'varsJgaapCS' => array(),
					'flagUse' => 1, 'flagDebit' => 1, 'flagConsumptionTaxGeneralRuleEach' => 'taxDebit', 'flagConsumptionTaxGeneralRuleProration' => 'taxDebit', 'flagConsumptionTaxSimpleRule' => 'taxDebit',
					'varsValue' => array(), 'flagSortUse' => 1,
				),
				'child' => array(),
			),
			array(
				'id' => '', 'flagUse' => 1, 'flagMoveUse' => 1, 'flagInsertUse' => 0, 'flagBtnUse' => 1, 'flagFoldUse' => 0, 'flagFoldNow' => 1, 'flagChildrenUse' => 0, 'flagDefault' => 1,
				'strTitle' => '貸倒損失',
				'strClass' => 'codeLibBaseImgSheet',
				'vars' => array(
					'idTarget' => 'badDebtsExpenses', 'idAccountTitleJgaapFS' => 'provisionOfAllowanceForDoubtfulAccounts',
					'varsJgaapCS' => array(),
					'flagUse' => 1, 'flagDebit' => 1, 'flagConsumptionTaxGeneralRuleEach' => 'tax-Bad', 'flagConsumptionTaxGeneralRuleProration' => 'tax-Bad', 'flagConsumptionTaxSimpleRule' => 'tax-Bad',
					'varsValue' => array(), 'flagSortUse' => 1,
				),
				'child' => array(),
			),
			array(
				'id' => '', 'flagUse' => 1, 'flagMoveUse' => 1, 'flagInsertUse' => 0, 'flagBtnUse' => 1, 'flagFoldUse' => 0, 'flagFoldNow' => 1, 'flagChildrenUse' => 0, 'flagDefault' => 1,
				'strTitle' => '支払手数料',
				'strClass' => 'codeLibBaseImgSheet',
				'vars' => array(
					'idTarget' => 'commissionPaid', 'idAccountTitleJgaapFS' => 'sellingGeneralAndAdministrationExpensesElse',
					'varsJgaapCS' => array(),
					'flagUse' => 1, 'flagDebit' => 1, 'flagConsumptionTaxGeneralRuleEach' => 'taxDebit', 'flagConsumptionTaxGeneralRuleProration' => 'taxDebit', 'flagConsumptionTaxSimpleRule' => 'taxDebit',
					'varsValue' => array(), 'flagSortUse' => 1,
				),
				'child' => array(),
			),
			array(
				'id' => '', 'flagUse' => 1, 'flagMoveUse' => 1, 'flagInsertUse' => 0, 'flagBtnUse' => 1, 'flagFoldUse' => 0, 'flagFoldNow' => 1, 'flagChildrenUse' => 0, 'flagDefault' => 1,
				'strTitle' => '車両費',
				'strClass' => 'codeLibBaseImgSheet',
				'vars' => array(
					'idTarget' => 'vehicleExpense', 'idAccountTitleJgaapFS' => 'sellingGeneralAndAdministrationExpensesElse',
					'varsJgaapCS' => array(),
					'flagUse' => 1, 'flagDebit' => 1, 'flagConsumptionTaxGeneralRuleEach' => 'taxDebit', 'flagConsumptionTaxGeneralRuleProration' => 'taxDebit', 'flagConsumptionTaxSimpleRule' => 'taxDebit',
					'varsValue' => array(), 'flagSortUse' => 1,
				),
				'child' => array(),
			),
			array(
				'id' => '', 'flagUse' => 1, 'flagMoveUse' => 1, 'flagInsertUse' => 0, 'flagBtnUse' => 1, 'flagFoldUse' => 0, 'flagFoldNow' => 1, 'flagChildrenUse' => 0, 'flagDefault' => 1,
				'strTitle' => '燃料費',
				'strClass' => 'codeLibBaseImgSheet',
				'vars' => array(
					'idTarget' => 'fuelExpense', 'idAccountTitleJgaapFS' => 'sellingGeneralAndAdministrationExpensesElse',
					'varsJgaapCS' => array(),
					'flagUse' => 1, 'flagDebit' => 1, 'flagConsumptionTaxGeneralRuleEach' => 'taxDebit', 'flagConsumptionTaxGeneralRuleProration' => 'taxDebit', 'flagConsumptionTaxSimpleRule' => 'taxDebit',
					'varsValue' => array(), 'flagSortUse' => 1,
				),
				'child' => array(),
			),
			array(
				'id' => '', 'flagUse' => 1, 'flagMoveUse' => 1, 'flagInsertUse' => 0, 'flagBtnUse' => 1, 'flagFoldUse' => 0, 'flagFoldNow' => 1, 'flagChildrenUse' => 0, 'flagDefault' => 1,
				'strTitle' => '賃借料',
				'strClass' => 'codeLibBaseImgSheet',
				'vars' => array(
					'idTarget' => 'rentExpense', 'idAccountTitleJgaapFS' => 'sellingGeneralAndAdministrationExpensesElse',
					'varsJgaapCS' => array(),
					'flagUse' => 1, 'flagDebit' => 1, 'flagConsumptionTaxGeneralRuleEach' => 'taxDebit', 'flagConsumptionTaxGeneralRuleProration' => 'taxDebit', 'flagConsumptionTaxSimpleRule' => 'taxDebit',
					'varsValue' => array(), 'flagSortUse' => 1,
				),
				'child' => array(),
			),
			array(
				'id' => '', 'flagUse' => 1, 'flagMoveUse' => 1, 'flagInsertUse' => 0, 'flagBtnUse' => 1, 'flagFoldUse' => 0, 'flagFoldNow' => 1, 'flagChildrenUse' => 0, 'flagDefault' => 1,
				'strTitle' => 'リース料',
				'strClass' => 'codeLibBaseImgSheet',
				'vars' => array(
					'idTarget' => 'leaseChargesPaid', 'idAccountTitleJgaapFS' => 'sellingGeneralAndAdministrationExpensesElse',
					'varsJgaapCS' => array(),
					'flagUse' => 1, 'flagDebit' => 1, 'flagConsumptionTaxGeneralRuleEach' => 'taxDebit', 'flagConsumptionTaxGeneralRuleProration' => 'taxDebit', 'flagConsumptionTaxSimpleRule' => 'taxDebit',
					'varsValue' => array(), 'flagSortUse' => 1,
				),
				'child' => array(),
			),
			array(
				'id' => '', 'flagUse' => 1, 'flagMoveUse' => 1, 'flagInsertUse' => 0, 'flagBtnUse' => 1, 'flagFoldUse' => 0, 'flagFoldNow' => 1, 'flagChildrenUse' => 0, 'flagDefault' => 1,
				'strTitle' => '採用教育費',
				'strClass' => 'codeLibBaseImgSheet',
				'vars' => array(
					'idTarget' => 'trainingExpenses', 'idAccountTitleJgaapFS' => 'sellingGeneralAndAdministrationExpensesElse',
					'varsJgaapCS' => array(),
					'flagUse' => 1, 'flagDebit' => 1, 'flagConsumptionTaxGeneralRuleEach' => 'taxDebit', 'flagConsumptionTaxGeneralRuleProration' => 'taxDebit', 'flagConsumptionTaxSimpleRule' => 'taxDebit',
					'varsValue' => array(), 'flagSortUse' => 1,
				),
				'child' => array(),
			),
			array(
				'id' => '', 'flagUse' => 1, 'flagMoveUse' => 1, 'flagInsertUse' => 0, 'flagBtnUse' => 1, 'flagFoldUse' => 0, 'flagFoldNow' => 1, 'flagChildrenUse' => 0, 'flagDefault' => 1,
				'strTitle' => '会議費',
				'strClass' => 'codeLibBaseImgSheet',
				'vars' => array(
					'idTarget' => 'conferenceExpense', 'idAccountTitleJgaapFS' => 'sellingGeneralAndAdministrationExpensesElse',
					'varsJgaapCS' => array(),
					'flagUse' => 1, 'flagDebit' => 1, 'flagConsumptionTaxGeneralRuleEach' => 'taxDebit', 'flagConsumptionTaxGeneralRuleProration' => 'taxDebit', 'flagConsumptionTaxSimpleRule' => 'taxDebit',
					'varsValue' => array(), 'flagSortUse' => 1,
				),
				'child' => array(),
			),
			array(
				'id' => '', 'flagUse' => 1, 'flagMoveUse' => 1, 'flagInsertUse' => 0, 'flagBtnUse' => 1, 'flagFoldUse' => 0, 'flagFoldNow' => 1, 'flagChildrenUse' => 0, 'flagDefault' => 1,
				'strTitle' => '新聞図書費',
				'strClass' => 'codeLibBaseImgSheet',
				'vars' => array(
					'idTarget' => 'booksExpense', 'idAccountTitleJgaapFS' => 'sellingGeneralAndAdministrationExpensesElse',
					'varsJgaapCS' => array(),
					'flagUse' => 1, 'flagDebit' => 1, 'flagConsumptionTaxGeneralRuleEach' => 'taxDebit', 'flagConsumptionTaxGeneralRuleProration' => 'taxDebit', 'flagConsumptionTaxSimpleRule' => 'taxDebit',
					'varsValue' => array(), 'flagSortUse' => 1,
				),
				'child' => array(),
			),
			array(
				'id' => '', 'flagUse' => 1, 'flagMoveUse' => 1, 'flagInsertUse' => 0, 'flagBtnUse' => 1, 'flagFoldUse' => 0, 'flagFoldNow' => 1, 'flagChildrenUse' => 0, 'flagDefault' => 1,
				'strTitle' => '販売手数料',
				'strClass' => 'codeLibBaseImgSheet',
				'vars' => array(
					'idTarget' => 'sellingConcession', 'idAccountTitleJgaapFS' => 'sellingGeneralAndAdministrationExpensesElse',
					'varsJgaapCS' => array(),
					'flagUse' => 1, 'flagDebit' => 1, 'flagConsumptionTaxGeneralRuleEach' => 'taxDebit', 'flagConsumptionTaxGeneralRuleProration' => 'taxDebit', 'flagConsumptionTaxSimpleRule' => 'taxDebit',
					'varsValue' => array(), 'flagSortUse' => 1,
				),
				'child' => array(),
			),
			array(
				'id' => '', 'flagUse' => 1, 'flagMoveUse' => 1, 'flagInsertUse' => 0, 'flagBtnUse' => 1, 'flagFoldUse' => 0, 'flagFoldNow' => 1, 'flagChildrenUse' => 0, 'flagDefault' => 1,
				'strTitle' => '販売促進費',
				'strClass' => 'codeLibBaseImgSheet',
				'vars' => array(
					'idTarget' => 'salesPromotionExpenses', 'idAccountTitleJgaapFS' => 'sellingGeneralAndAdministrationExpensesElse',
					'varsJgaapCS' => array(),
					'flagUse' => 1, 'flagDebit' => 1, 'flagConsumptionTaxGeneralRuleEach' => 'taxDebit', 'flagConsumptionTaxGeneralRuleProration' => 'taxDebit', 'flagConsumptionTaxSimpleRule' => 'taxDebit',
					'varsValue' => array(), 'flagSortUse' => 1,
				),
				'child' => array(),
			),
			array(
				'id' => '', 'flagUse' => 1, 'flagMoveUse' => 1, 'flagInsertUse' => 0, 'flagBtnUse' => 1, 'flagFoldUse' => 0, 'flagFoldNow' => 1, 'flagChildrenUse' => 0, 'flagDefault' => 1,
				'strTitle' => '諸会費',
				'strClass' => 'codeLibBaseImgSheet',
				'vars' => array(
					'idTarget' => 'dues', 'idAccountTitleJgaapFS' => 'sellingGeneralAndAdministrationExpensesElse',
					'varsJgaapCS' => array(),
					'flagUse' => 1, 'flagDebit' => 1, 'flagConsumptionTaxGeneralRuleEach' => 'taxDebit', 'flagConsumptionTaxGeneralRuleProration' => 'taxDebit', 'flagConsumptionTaxSimpleRule' => 'taxDebit',
					'varsValue' => array(), 'flagSortUse' => 1,
				),
				'child' => array(),
			),
			array(
				'id' => '', 'flagUse' => 1, 'flagMoveUse' => 1, 'flagInsertUse' => 0, 'flagBtnUse' => 1, 'flagFoldUse' => 0, 'flagFoldNow' => 1, 'flagChildrenUse' => 0, 'flagDefault' => 1,
				'strTitle' => '売上割引',
				'strClass' => 'codeLibBaseImgSheet',
				'vars' => array(
					'idTarget' => 'salesDiscount', 'idAccountTitleJgaapFS' => 'sellingGeneralAndAdministrationExpensesElse',
					'varsJgaapCS' => array(),
					'flagUse' => 1, 'flagDebit' => 1, 'flagConsumptionTaxGeneralRuleEach' => 'tax-Back', 'flagConsumptionTaxGeneralRuleProration' => 'tax-Back', 'flagConsumptionTaxSimpleRule' => 'tax-Back-Default',
					'varsValue' => array(), 'flagSortUse' => 1,
				),
				'child' => array(),
			),
			array(
				'id' => '', 'flagUse' => 1, 'flagMoveUse' => 1, 'flagInsertUse' => 0, 'flagBtnUse' => 1, 'flagFoldUse' => 0, 'flagFoldNow' => 1, 'flagChildrenUse' => 0, 'flagDefault' => 1,
				'strTitle' => '長期前払費用償却',
				'strClass' => 'codeLibBaseImgSheet',
				'vars' => array(
					'idTarget' => 'longTermPrepaidExpensesDep', 'idAccountTitleJgaapFS' => 'sellingGeneralAndAdministrationExpensesElse',
					'flagUse' => 1, 'flagDebit' => 1, 'flagConsumptionTaxGeneralRuleEach' => 'none', 'flagConsumptionTaxGeneralRuleProration' => 'none', 'flagConsumptionTaxSimpleRule' => 'none',
					'varsJgaapCS' => array(),
					'varsValue' => array(), 'flagSortUse' => 1,
				),
				'child' => array(),
			),
			array(
				'id' => '', 'flagUse' => 1, 'flagMoveUse' => 1, 'flagInsertUse' => 0, 'flagBtnUse' => 1, 'flagFoldUse' => 0, 'flagFoldNow' => 1, 'flagChildrenUse' => 0, 'flagDefault' => 1,
				'strTitle' => '繰延資産償却',
				'strClass' => 'codeLibBaseImgSheet',
				'vars' => array(
					'idTarget' => 'shortTermDeferredTaxDepreciation', 'idAccountTitleJgaapFS' => 'depreciation',
					'varsJgaapCS' => array(),
					'flagUse' => 1, 'flagDebit' => 1, 'flagConsumptionTaxGeneralRuleEach' => 'none', 'flagConsumptionTaxGeneralRuleProration' => 'none', 'flagConsumptionTaxSimpleRule' => 'none',
					'varsValue' => array(), 'flagSortUse' => 1,
				),
				'child' => array(),
			),
			array(
				'id' => '', 'flagUse' => 1, 'flagMoveUse' => 1, 'flagInsertUse' => 0, 'flagBtnUse' => 1, 'flagFoldUse' => 0, 'flagFoldNow' => 1, 'flagChildrenUse' => 0, 'flagDefault' => 1,
				'strTitle' => '雑損失',
				'strClass' => 'codeLibBaseImgSheet',
				'vars' => array(
					'idTarget' => 'badMiscellaneousExpenses', 'idAccountTitleJgaapFS' => 'sellingGeneralAndAdministrationExpensesElse',
					'varsJgaapCS' => array(),
					'flagUse' => 1, 'flagDebit' => 1, 'flagConsumptionTaxGeneralRuleEach' => 'taxDebit', 'flagConsumptionTaxGeneralRuleProration' => 'taxDebit', 'flagConsumptionTaxSimpleRule' => 'taxDebit',
					'varsValue' => array(), 'flagSortUse' => 1,
				),
				'child' => array(),
			),
			array(
				'id' => '', 'flagUse' => 1, 'flagMoveUse' => 1, 'flagInsertUse' => 0, 'flagBtnUse' => 1, 'flagFoldUse' => 0, 'flagFoldNow' => 1, 'flagChildrenUse' => 0, 'flagDefault' => 1,
				'strTitle' => '雑費',
				'strClass' => 'codeLibBaseImgSheet',
				'vars' => array(
					'idTarget' => 'miscellaneousExpenses', 'idAccountTitleJgaapFS' => 'miscellaneousExpenses',
					'varsJgaapCS' => array(),
					'flagUse' => 1, 'flagDebit' => 1, 'flagConsumptionTaxGeneralRuleEach' => 'taxDebit', 'flagConsumptionTaxGeneralRuleProration' => 'taxDebit', 'flagConsumptionTaxSimpleRule' => 'taxDebit',
					'varsValue' => array(), 'flagSortUse' => 1,
				),
				'child' => array(),
			),
		),
	),
	array(
		'id' => '', 'flagUse' => 1, 'flagMoveUse' => 0, 'flagInsertUse' => 0, 'flagBtnUse' => 0, 'flagFoldUse' => 1, 'flagFoldNow' => 1, 'flagChildrenUse' => 0, 'flagDefault' => 1,
		'strTitle' => '経費合計',
		'strClass' => 'codeLibBaseImgSheet',
		'vars' => array(
			'idTarget' => 'expenseSum', 'flagDebit' => 1, 'flagCalc' => 'sum', 'varsValue' => array(),
		),
		'child' => array(),
	),
	array(
		'id' => '', 'flagUse' => 1, 'flagMoveUse' => 0, 'flagInsertUse' => 0, 'flagBtnUse' => 0, 'flagFoldUse' => 1, 'flagFoldNow' => 1, 'flagChildrenUse' => 0, 'flagDefault' => 1,
		'strTitle' => '差引金額',
		'strClass' => 'codeLibBaseImgSheet',
		'vars' => array(
			'idTarget' => 'operateProfitOrLossNet', 'flagDebit' => 0, 'flagCalc' => 'net', 'varsValue' => array(),
		),
		'child' => array(),
	),
	array(
		'id' => '', 'flagUse' => 1, 'flagMoveUse' => 0, 'flagInsertUse' => 0, 'flagBtnUse' => 0, 'flagFoldUse' => 1, 'flagFoldNow' => 1, 'flagChildrenUse' => 1,
		'strTitle' => '繰戻額等',
		'strClass' => 'codeLibBaseImgFolder',
		'vars' => array(
			'idTarget' => 'backExpenses', 'flagDebit' => 0,
		),
		'child' => array(
			array(
				'id' => '', 'flagUse' => 1, 'flagMoveUse' => 1, 'flagInsertUse' => 0, 'flagBtnUse' => 1, 'flagFoldUse' => 0, 'flagFoldNow' => 1, 'flagChildrenUse' => 0, 'flagDefault' => 1,
				'strTitle' => '貸倒引当金戻入益',
				'strClass' => 'codeLibBaseImgSheet',
				'vars' => array(
					'idTarget' => 'reversalOfAllowanceForDoubtfulReceivables', 'idAccountTitleJgaapFS' => 'reversalOfAllowanceForDoubtfulReceivables',
					'varsJgaapCS' => array(),
					'flagUse' => 1, 'flagDebit' => 0, 'flagConsumptionTaxGeneralRuleEach' => 'none', 'flagConsumptionTaxGeneralRuleProration' => 'none', 'flagConsumptionTaxSimpleRule' => 'none',
					'varsValue' => array(), 'flagSortUse' => 1,
				),
				'child' => array(),
			),
		),
	),
	array(
		'id' => '', 'flagUse' => 1, 'flagMoveUse' => 0, 'flagInsertUse' => 0, 'flagBtnUse' => 0, 'flagFoldUse' => 1, 'flagFoldNow' => 1, 'flagChildrenUse' => 0, 'flagDefault' => 1,
		'strTitle' => '繰戻額等合計',
		'strClass' => 'codeLibBaseImgSheet',
		'vars' => array(
			'idTarget' => 'backExpensesSum', 'flagDebit' => 1, 'flagCalc' => 'sum', 'varsValue' => array(),
		),
		'child' => array(),
	),
	array(
		'id' => '', 'flagUse' => 1, 'flagMoveUse' => 0, 'flagInsertUse' => 0, 'flagBtnUse' => 0, 'flagFoldUse' => 1, 'flagFoldNow' => 1, 'flagChildrenUse' => 1,
		'strTitle' => '繰入額等',
		'strClass' => 'codeLibBaseImgFolder',
		'vars' => array(
			'idTarget' => 'doubtfulDebtAccount', 'flagDebit' => 1,
		),
		'child' => array(
			array(
				'id' => '', 'flagUse' => 1, 'flagMoveUse' => 1, 'flagInsertUse' => 0, 'flagBtnUse' => 1, 'flagFoldUse' => 0, 'flagFoldNow' => 1, 'flagChildrenUse' => 0, 'flagDefault' => 1,
				'strTitle' => '専従者給与',
				'strClass' => 'codeLibBaseImgSheet',
				'vars' => array(
					'idTarget' => 'familyEmployee', 'idAccountTitleJgaapFS' => 'familyEmployee',
					'varsJgaapCS' => array(),
					'flagUse' => 1, 'flagDebit' => 1, 'flagConsumptionTaxGeneralRuleEach' => 'none', 'flagConsumptionTaxGeneralRuleProration' => 'none', 'flagConsumptionTaxSimpleRule' => 'none',
					'varsValue' => array(), 'flagSortUse' => 1,
				),
				'child' => array(),
			),
			array(
				'id' => '', 'flagUse' => 1, 'flagMoveUse' => 1, 'flagInsertUse' => 0, 'flagBtnUse' => 1, 'flagFoldUse' => 0, 'flagFoldNow' => 1, 'flagChildrenUse' => 0, 'flagDefault' => 1,
				'strTitle' => '貸倒引当金繰入',
				'strClass' => 'codeLibBaseImgSheet',
				'vars' => array(
					'idTarget' => 'doubtfulDebtAccounts', 'idAccountTitleJgaapFS' => 'provisionOfAllowanceForDoubtfulAccountsNon',
					'varsJgaapCS' => array(),
					'flagUse' => 1, 'flagDebit' => 1, 'flagConsumptionTaxGeneralRuleEach' => 'none', 'flagConsumptionTaxGeneralRuleProration' => 'none', 'flagConsumptionTaxSimpleRule' => 'none',
					'varsValue' => array(), 'flagSortUse' => 1,
				),
				'child' => array(),
			),

		),
	),
	array(
		'id' => '', 'flagUse' => 1, 'flagMoveUse' => 0, 'flagInsertUse' => 0, 'flagBtnUse' => 0, 'flagFoldUse' => 1, 'flagFoldNow' => 1, 'flagChildrenUse' => 0, 'flagDefault' => 1,
		'strTitle' => '繰入額等合計',
		'strClass' => 'codeLibBaseImgSheet',
		'vars' => array(
			'idTarget' => 'doubtfulDebtAccountSum', 'flagDebit' => 1, 'flagCalc' => 'sum', 'varsValue' => array(),
		),
		'child' => array(),
	),
	array(
		'id' => '', 'flagUse' => 1, 'flagMoveUse' => 0, 'flagInsertUse' => 0, 'flagBtnUse' => 0, 'flagFoldUse' => 1, 'flagFoldNow' => 1, 'flagChildrenUse' => 0, 'flagDefault' => 1,
		'strTitle' => '控除前所得金額',
		'strClass' => 'codeLibBaseImgSheet',
		'vars' => array(
			'idTarget' => 'currentTermProfitOrLossNet', 'flagDebit' => 0, 'flagCalc' => 'net', 'varsValue' => array(),
		),
		'child' => array(),
	),
);
