<?php

$vars = array(
	'portal' => array(
		'varsDetail' => array(
			'varsStatus' => array(
				'flagNow' => 'form',
				'flagCakeUse' => 0,
				'flagViewUse' => 0,
				'flagFormUse' => 1,
				'switchList' => array('form'),
			),
			'varsPage' => array(),
			'varsDetailEnd' => array(
				'strTitle' => '認証完了',
				'varsDetail' => array(
					array(
						'flagMustUse' => 1,
						'id' => '',
						'strTitle' => '', 'strExplain' => '', 'value' => 'admin',
						'flagErrorNow' => 0,
						'arrayError' => array(),
						'flagContentUse' => 0,
						'flagCommentUse' => 1, 'strCommentTitle' => '認証完了', 'strComment' => '認証が完了しました。管理者が承認するまでしばらくお待ちください。',
						'flagTag' => 'input', 'flagInputType' => 'text', 'numMaxlength' => 0,
						'numWidth' => 80, 'unitWidth' => '%', 'numHeight' => 0, 'unitHeight' => '',
						'arrayOption' => array(),
						'flagFoldUse' => 0, 'flagFoldNow' => 0,
					),
				),
				'varsBtn' => array(),
			),
			'varsDetailCaution' => array(
				'strTitle' => 'アカウント変更申請について',
				'varsDetail' => array(
					array(
						'flagMustUse' => 1,
						'id' => '',
						'strTitle' => '', 'strExplain' => '', 'value' => 'admin',
						'flagErrorNow' => 0,
						'arrayError' => array(),
						'flagContentUse' => 0,
						'flagCommentUse' => 1, 'strCommentTitle' => '認証上の注意', 'strComment' => 'あらかじめログインした状態を保っておかないと認証手続は進まないようです。',
						'flagTag' => 'input', 'flagInputType' => 'text', 'numMaxlength' => 0,
						'numWidth' => 80, 'unitWidth' => '%', 'numHeight' => 0, 'unitHeight' => '',
						'arrayOption' => array(),
						'flagFoldUse' => 0, 'flagFoldNow' => 0,
					),
				),
				'varsBtn' => array(),
			),
			'varsDetailPassword' => array(
				'strTitle' => 'パスワード再発行',
				'varsDetail' => array(
					array(
						'flagMustUse' => 1,
						'id' => '',
						'strTitle' => '', 'strExplain' => '', 'value' => 'admin',
						'flagErrorNow' => 0,
						'arrayError' => array(),
						'flagContentUse' => 0,
						'flagCommentUse' => 1, 'strCommentTitle' => 'パスワード再発行', 'strComment' => '新しいパスワードは、以下の色文字となります。以下のパスワードを用いてログインしてください。<br>『 <span class="codeLibBaseFontTypeCheck" style="float:none;"><%replace%></span> 』',
						'flagTag' => 'input', 'flagInputType' => 'text', 'numMaxlength' => 0,
						'numWidth' => 80, 'unitWidth' => '%', 'numHeight' => 0, 'unitHeight' => '',
						'arrayOption' => array(),
						'flagFoldUse' => 0, 'flagFoldNow' => 0,
					),
				),
				'varsBtn' => array(
					array(
						'flagUse' => 1, 'flagLeftUse' => 0, 'flagRightUse' => 1, 'flagTextUse' => 0, 'flagBtnUse' => 1, 'flagATag' => 1, 'path' => 'index.php',
						'id' => 'Login',
						'vars' => array(),
						'strTitle' => 'ログイン画面へ',
					),
				),
			),
			'varsDetailAccount' => array(
				'strTitle' => '新アカウント発行',
				'varsDetail' => array(
					array(
						'flagMustUse' => 1,
						'id' => '',
						'strTitle' => '', 'strExplain' => '', 'value' => 'admin',
						'flagErrorNow' => 0,
						'arrayError' => array(),
						'flagContentUse' => 0,
						'flagCommentUse' => 1, 'strCommentTitle' => '新アカウント発行', 'strComment' => '新しいログインIDとパスワードは、以下の色文字となります。<br>　※ 一度しか閲覧できませんので忘れないようにメモしてください。<br>　『 ログインID : <span class="codeLibBaseFontTypeCheck" style="float:none;"><%idLogin%></span> 』<br>　『 パスワード : <span class="codeLibBaseFontTypeCheck" style="float:none;"><%strPassword%></span> 』',
						'flagTag' => 'input', 'flagInputType' => 'text', 'numMaxlength' => 0,
						'numWidth' => 80, 'unitWidth' => '%', 'numHeight' => 0, 'unitHeight' => '',
						'arrayOption' => array(),
						'flagFoldUse' => 0, 'flagFoldNow' => 0,
					),
				),
				'varsBtn' => array(
					array(
						'flagUse' => 1, 'flagLeftUse' => 0, 'flagRightUse' => 1, 'flagTextUse' => 0, 'flagBtnUse' => 1, 'flagATag' => 1, 'path' => 'index.php',
						'id' => 'Login',
						'vars' => array(),
						'strTitle' => 'ログイン画面へ',
					),
				),
			),
			'varsDetailLogin' => array(
				'strTitle' => '二段階認証完了',
				'idCookie' => '',
				'varsDetail' => array(
					array(
						'flagMustUse' => 1,
						'id' => '',
						'strTitle' => '', 'strExplain' => '', 'value' => 'admin',
						'flagErrorNow' => 0,
						'arrayError' => array(),
						'flagContentUse' => 0,
						'flagCommentUse' => 1, 'strCommentTitle' => '二段階認証完了', 'strComment' => '認証が完了しました。まもなくログイン画面へ自動で移動します。<br>自動で移動しない場合は下記ボタンを押してください。',
						'flagTag' => 'input', 'flagInputType' => 'text', 'numMaxlength' => 0,
						'numWidth' => 80, 'unitWidth' => '%', 'numHeight' => 0, 'unitHeight' => '',
						'arrayOption' => array(),
						'flagFoldUse' => 0, 'flagFoldNow' => 0,
					),
				),
				'varsBtn' => array(
					array(
						'flagUse' => 1, 'flagLeftUse' => 0, 'flagRightUse' => 1, 'flagTextUse' => 0, 'flagBtnUse' => 1, 'flagATag' => 1, 'path' => 'index.php',
						'id' => 'Login',
						'vars' => array(),
						'strTitle' => 'ログイン画面へ',
					),
				),
			),
			'varsDetail' => array(
				'strTitle' => '認証失敗',
				'varsDetail' => array(
					array(
						'flagMustUse' => 1,
						'id' => '',
						'strTitle' => '', 'strExplain' => '', 'value' => 'admin',
						'flagErrorNow' => 0,
						'arrayError' => array(),
						'flagContentUse' => 0,
						'flagCommentUse' => 1, 'strCommentTitle' => 'セッション失効', 'strComment' => '発行されたセッションは既に失効しているようです。',
						'flagTag' => 'input', 'flagInputType' => 'text', 'numMaxlength' => 0,
						'numWidth' => 80, 'unitWidth' => '%', 'numHeight' => 0, 'unitHeight' => '',
						'arrayOption' => array(),
						'flagFoldUse' => 0, 'flagFoldNow' => 0,
					),
				),
				'varsBtn' => array(),
			),
			'view' => array(),
			'form' => array(
				'varsFormat' => array(
					'id' => '',
					'flagType' => 'normalFormat',
					'numHeight' => 0,
					'numWidth' => 0,
					'flagHeaderLeftUse' => 1,
					'strTitleHeaderLeft' => '',
					'strClassHeaderLeft' => 'codeLibBaseImgDb',
					'flagHeaderRightUse' => 1,
					'strTitleHeaderRight' => '',
					'strClassHeaderRight' => 'codeLibBaseImgUnloading',
					'flagBodyAutoUse' => 1,
					'strBody' => '',
					'strClassBody' => '',
					'flagFooderUse' => 1,
					'flagFooderLeftUse' => 1,
					'strTitleFooderLeft' => '',
					'strClassFooderLeft' => '',
					'flagFooderRightUse' => 1,
					'strTitleFooderRight' => '',
					'strClassFooderRight' => '',
					'flagHeaderLeftWidth' => 1,
					'numWidthHeaderLeft' => 0,
					'flagHeaderRightWidth' => 0,
					'numWidthHeaderRight' => 0,
					'flagFooderLeftWidth' => 0,
					'numWidthFooderLeft' => 0,
					'flagFooderRightWidth' => 0,
					'numWidthFooderRight' => 0,
				),
				'varsEdit' => array(),
				'varsDetail' => array(
					'varsStatus' => array(
						'flagBtnBottomUse' => 1,
					),
					'varsBtn' => array(),
					'varsDetail' => array(),
				),
			),
		),
		'varsTemplateLayout' => array(
			'varsStatus' => array(
				'flagNaviUse' => 0,
				'flagNaviToolUse' => 0,
				'flagListUse' => 0,
				'flagListToolUse' => 0,
				'flagDetailUse' => 1,
				'flagDetailToolUse' => 0,
			),
			'varsLayout' => array(
				'varsStatus' => array(
					'flagNow' => 1,
					'flagResizeUse' => 0,
					'flagMoveUse' => 0,
					'flagCakeUse' => 0,
					'flagSwitchUse' => 0,
					'flagSwitchNow' => 'Standard',
					'switchList' => array('Standard','Wide','Classic'),
				),
				'varsDetail' => array(
					array(
						'id' => 'Detail',
						'flagBoxUse' => 0,
						'numPriority' => 2,
						'numSort' => 2,
						'numWidth' => 100,			'numHeight' => 200,
						'numWidthMin' => 100,		'numHeightMin' => 200,
						'numWidthStandard' => 100,	'numHeightStandard' => 200,
						'numWidthWide' => 100,		'numHeightWide' => 200,
						'numWidthClassic' => 100,	'numHeightClassic' => 200,
						'numHeightBox' => 0,		'numWidthBox' => 0,//auto
					),
				)
			),
			'detail' => array(
				'varsFormat' => array(
					'id' => '',
					'flagType' => 'normalFormat',
					'numHeight' => 0,
					'numWidth' => 0,
					'flagHeaderLeftUse' => 1,
					'strTitleHeaderLeft' => '',
					'strClassHeaderLeft' => '',
					'flagHeaderRightUse' => 1,
					'strTitleHeaderRight' => '',
					'strClassHeaderRight' => 'codeLibBaseImgUnloading',
					'flagBodyAutoUse' => 1,
					'strBody' => '',
					'strClassBody' => '',
					'flagFooderUse' => 1,
					'flagFooderLeftUse' => 1,
					'strTitleFooderLeft' => '',
					'strClassFooderLeft' => '',
					'flagFooderRightUse' => 1,
					'strTitleFooderRight' => '',
					'strClassFooderRight' => '',
					'flagHeaderLeftWidth' => 1,
					'numWidthHeaderLeft' => 0,
					'flagHeaderRightWidth' => 0,
					'numWidthHeaderRight' => 0,
					'flagFooderLeftWidth' => 0,
					'numWidthFooderLeft' => 0,
					'flagFooderRightWidth' => 1,
					'numWidthFooderRight' => 0,
				),
				'varsTool' => array(),
			),
		),
	),
);
