<?php

$vars = array(
	'varsSystem' => array(
		'num' => array(
			'zIndex' => 0
		),
		'path' => array(
			'jump' => 'index.php',
			'post' => 'config.php',
		),
		'id' => array(
			'root' => 'Root',
			'window' => 'Window',
		),
		'str' => array(
			'errorServer' =>  'サーバエラー',
			'strConfirm' => 'コンフィグ設定を強制的に続行することも可能ですが、一部機能が制限されるか不具合が起きる可能性があります。本当によろしいでしょうか。',
			'errorConnect' =>  'サーバ接続エラー'
		)
	),
	'varsWindow' => array(
		'id' => 'Config' ,
		'strTitle' => 'コンフィグ設定' ,
		'strClass' => 'codeConfigPreference',
		'flagLockUse' => 0,
		'flagLockNow' => '',
		'flagCakeUse' => 1,
		'flagRemoveUse' => 0,
		'flagCoverUse' => 0,
		'flagHideUse' => 0,
		'flagHideNow' => 0,
		'flagReloadUse' => 0,
		'flagFoldUse' => 0,
		'flagFoldNow' => 0,
		'flagMoveUse' => 1,
		'flagZIndexUse' => 0,
		'flagResizeUse' => 0,
		'flagResizeIni' => 'all',
		'flagResizeNow' => 'all',
		'flagSkeletonUse' => 0,
		'flagBootUse' => 'auto',
		'flagSwitchUse' => 1,
		'numWidthTitle' => 0,
		'numLeft' => 50 ,
		'numTop' => 50,
		'numWidth' => 400 ,
		'numHeight' => 370,
		'numWidthMin' => 300 ,
		'numHeightMin' => 250,
		'numZIndex' => 0
	),
	'portal' => array(
		'varsDetail' => array(
			'varsStatus' => array(
				'flagNow' => 'form',
				'flagCakeUse' => 0,
				'flagViewUse' => 0,
				'flagFormUse' => 1,
				'switchList' => array('form'),
			),
			'varsPage' => array(),
			'varsDetail' => array(
				'start' => array(
					'varsDetail' => array(
						array(
							'flagMustUse' => 1,
							'id' => 'StrDbName',
							'strTitle' => 'データベース名' , 'strExplain' => '※半角英数で記入してください。' , 'value' => '',
							'flagErrorNow' => 0,
							'arrayError' => array(
								array( 'flagCheck' => 'blank', 'flagUse' => 1, 'flagNow' => 0, 'flagType' => 'empty', 'strComment' => array( 'common' => '記入漏れがあるようです。', ),),
								array( 'flagCheck' =>  'attest', 'flagUse' =>  1, 'strComment' => array('common' =>  'データベース接続ができませんでした。もう一度、データベース名を確認してください。', ),),
							),
							'flagContentUse' => 0,
							'flagCommentUse' => 0, 'strCommentTitle' => '', 'strComment' => '',
							'flagTag' => 'input', 'flagInputType' => 'text', 'numMaxlength' => 0,
							'numWidth' => 80, 'unitWidth' => '%', 'numHeight' => 0, 'unitHeight' => '',
							'arrayOption' => array(),
							'flagFoldUse' => 0, 'flagFoldNow' => 0,
						),
						array(
							'flagMustUse' => 1,
							'id' => 'StrDbUser',
							'strTitle' => 'データベースのユーザ名' , 'strExplain' => '※半角英数で記入してください。' , 'value' => '',
							'flagErrorNow' => 0,
							'arrayError' => array(
								array( 'flagCheck' => 'blank', 'flagUse' => 1, 'flagNow' => 0, 'flagType' => 'empty', 'strComment' => array( 'common' => '記入漏れがあるようです。', ),),
								array( 'flagCheck' =>  'attest', 'flagUse' =>  1, 'strComment' => array('common' =>  'データベース接続ができませんでした。もう一度、ユーザ名を確認してください。', ),),
							),
							'flagContentUse' => 0,
							'flagCommentUse' => 0, 'strCommentTitle' => '', 'strComment' => '',
							'flagTag' => 'input', 'flagInputType' => 'text', 'numMaxlength' => 0,
							'numWidth' => 80, 'unitWidth' => '%', 'numHeight' => 0, 'unitHeight' => '',
							'arrayOption' => array(),
							'flagFoldUse' => 0, 'flagFoldNow' => 0,
						),
						array(
							'flagMustUse' => 1,
							'id' => 'StrDbPassword',
							'strTitle' => 'データベースのパスワード' , 'strExplain' => '※半角英数で記入してください。' , 'value' => '',
							'flagErrorNow' => 0,
							'arrayError' => array(
								array( 'flagCheck' => 'blank', 'flagUse' => 1, 'flagNow' => 0, 'flagType' => 'empty', 'strComment' => array( 'common' => '記入漏れがあるようです。', ),),
								array( 'flagCheck' =>  'attest', 'flagUse' =>  1, 'strComment' => array('common' =>  'データベース接続ができませんでした。もう一度、パスワードを確認してください。', ),),
							),
							'flagContentUse' => 0,
							'flagCommentUse' => 0, 'strCommentTitle' => '', 'strComment' => '',
							'flagTag' => 'input', 'flagInputType' => 'password', 'numMaxlength' => 0,
							'numWidth' => 80, 'unitWidth' => '%', 'numHeight' => 0, 'unitHeight' => '',
							'arrayOption' => array(),
							'flagFoldUse' => 0, 'flagFoldNow' => 0,
						),
						array(
							'flagMustUse' => 1,
							'id' => 'StrDbHost',
							'strTitle' => 'データベースのホスト名' , 'strExplain' => '※半角英数で記入してください。' , 'value' => '',
							'flagErrorNow' => 0,
							'arrayError' => array(
								array( 'flagCheck' => 'blank', 'flagUse' => 1, 'flagNow' => 0, 'flagType' => 'empty', 'strComment' => array( 'common' => '記入漏れがあるようです。',  ),),
								array( 'flagCheck' =>  'attest', 'flagUse' =>  1, 'strComment' => array('common' =>  'データベース接続ができませんでした。もう一度、ホスト名を確認してください。', ),),
							),
							'flagContentUse' => 0,
							'flagCommentUse' => 0, 'strCommentTitle' => '', 'strComment' => '',
							'flagTag' => 'input', 'flagInputType' => 'text', 'numMaxlength' => 0,
							'numWidth' => 80, 'unitWidth' => '%', 'numHeight' => 0, 'unitHeight' => '',
							'arrayOption' => array(),
							'flagFoldUse' => 0, 'flagFoldNow' => 0,
						),
					),
					'varsBtn' => array(
						array(
							'flagUse' => 1, 'flagLeftUse' => 0, 'flagRightUse' => 1,
							'flagTextUse' => 0, 'flagBtnUse' => 1,
							'id' => 'Btn' ,
							'vars' => array( 'id' => 'Btn' , ),
							'strTitle' => '設定開始' ,
						),
					),
				),
				'end' => array(
					'strTitle' => 'コンフィグ設定完了' ,
					'varsDetail' => array(
						array(
							'flagMustUse' => 0,
							'id' => '',
							'strTitle' => '' , 'strExplain' => '' , 'value' => '',
							'flagErrorNow' => 0,
							'arrayError' => array(),
							'flagContentUse' => 0,
							'flagCommentUse' => 1, 'strCommentTitle' => 'コンフィグ設定完了', 'strComment' => '<p>データベースへの初期設定が完了しました。ログイン画面へ移動してください。</p><p>※ ログイン初期値、ID : <span class="codeLibBaseFontRed codeLibBaseFontTwelve" style="float:none;">admin</span>、Password : <span class="codeLibBaseFontRed codeLibBaseFontTwelve" style="float:none;">test=3A</span>',
							'flagTag' => 'input', 'flagInputType' => 'text', 'numMaxlength' => 0,
							'numWidth' => 80, 'unitWidth' => '%', 'numHeight' => 0, 'unitHeight' => '',
							'arrayOption' => array(),
							'flagFoldUse' => 0, 'flagFoldNow' => 0,
						),
					),
					'varsBtn' => array(
						array(
							'flagUse' => 1, 'flagLeftUse' => 0, 'flagRightUse' => 1,
							'flagTextUse' => 0, 'flagBtnUse' =>  1, 'flagATag' =>  1, 'path' =>  'index.php',
							'id' => 'Btn' ,
							'vars' => array( 'id' => 'Btn' , ),
							'strTitle' => 'ログイン画面へ' ,
						),
					),
				),
				'rebuild' => array(
					'strTitle' => 'コンフィグ再構築エラー' ,
					'varsDetail' => array(
						array(
							'flagMustUse' => 0,
							'id' => '',
							'strTitle' => '' , 'strExplain' => '' , 'value' => '',
							'flagErrorNow' => 0,
							'arrayError' => array(),
							'flagContentUse' => 0,
							'flagCommentUse' => 1, 'strCommentTitle' => '再構築エラー', 'strComment' => 'システムを再構築できませんでした。<br>ご自身のサーバまわり、インストールしようとしているシステム又はプラグインを再度見直してください。',
							'flagTag' => 'input', 'flagInputType' => 'text', 'numMaxlength' => 0,
							'numWidth' => 80, 'unitWidth' => '%', 'numHeight' => 0, 'unitHeight' => '',
							'arrayOption' => array(),
							'flagFoldUse' => 0, 'flagFoldNow' => 0,
						),
					),
					'varsBtn' => array(),
				),
				'php' => array(
					'strTitle' => 'コンフィグ設定エラー' ,
					'varsDetail' => array(
						array(
							'flagMustUse' => 0,
							'id' => '',
							'strTitle' => '' , 'strExplain' => '' , 'value' => '',
							'flagErrorNow' => 0,
							'arrayError' => array(),
							'flagContentUse' => 0,
							'flagCommentUse' => 1, 'strCommentTitle' => 'PHPバージョンエラー', 'strComment' => 'サーバにインストールされているPHPのバージョンが5以上ではないようです。<br>PHPのバージョンを5にしてから再度設定をし直して下さい。',
							'flagTag' => 'input', 'flagInputType' => 'text', 'numMaxlength' => 0,
							'numWidth' => 80, 'unitWidth' => '%', 'numHeight' => 0, 'unitHeight' => '',
							'arrayOption' => array(),
							'flagFoldUse' => 0, 'flagFoldNow' => 0,
						),
					),
					'varsBtn' => array(),
				),
				'class' => array(
					'strTitle' => 'コンフィグ設定エラー' ,
					'varsDetail' => array(
						array(
							'flagMustUse' => 0,
							'id' => '',
							'strTitle' => '' , 'strExplain' => '' , 'value' => '',
							'flagErrorNow' => 0,
							'arrayError' => array(),
							'flagContentUse' => 0,
							'flagCommentUse' => 1, 'strCommentTitle' => 'PHPクラス不足', 'strComment' => 'PHP設定で足らないクラスがあるようです。<br>以下のクラスに関連するPHP設定を有効にするか、インストールしてから再度設定をし直して下さい。<p><%replace%></p>',
							'flagTag' => 'input', 'flagInputType' => 'text', 'numMaxlength' => 0,
							'numWidth' => 80, 'unitWidth' => '%', 'numHeight' => 0, 'unitHeight' => '',
							'arrayOption' => array(),
							'flagFoldUse' => 0, 'flagFoldNow' => 0,
						),
					),
					'varsBtn' => array(),
				),
				'func' => array(
					'strTitle' => 'コンフィグ設定エラー' ,
					'varsDetail' => array(
						array(
							'flagMustUse' => 0,
							'id' => '',
							'strTitle' => '' , 'strExplain' => '' , 'value' => '',
							'flagErrorNow' => 0,
							'arrayError' => array(),
							'flagContentUse' => 0,
							'flagCommentUse' => 1, 'strCommentTitle' => 'PHP関数不足', 'strComment' => '
								有効に機能しない関数があるようです。以下の関数に関連するPHP設定を有効にするか、インストールしてから再度設定をし直して下さい。<br>
								<p><%replace%></p>',
							'flagTag' => 'input', 'flagInputType' => 'text', 'numMaxlength' => 0,
							'numWidth' => 80, 'unitWidth' => '%', 'numHeight' => 0, 'unitHeight' => '',
							'arrayOption' => array(),
							'flagFoldUse' => 0, 'flagFoldNow' => 0,
						),
					),
					'varsBtn' => array(
						array(
							'flagUse' => 1, 'flagLeftUse' => 0, 'flagRightUse' => 1,
							'flagTextUse' => 0, 'flagBtnUse' => 1,
							'id' => 'Btn' ,
							'vars' => array( 'id' => 'Btn' , ),
							'strTitle' => 'コンフィグ設定強制続行' ,
						),

					),
				),
			),
			'view' => array(),
			'form' => array(
				'varsFormat' => array(
					'id' => '',
					'flagType' => 'normalFormat',
					'numHeight' => 0,
					'numWidth' => 0,
					'flagHeaderLeftUse' => 1,
					'strTitleHeaderLeft' => 'データベース設定',
					'strClassHeaderLeft' => 'codeLibBaseImgDb',
					'flagHeaderRightUse' => 1,
					'strTitleHeaderRight' => '',
					'strClassHeaderRight' => 'codeLibBaseImgUnloading',
					'flagBodyAutoUse' => 1,
					'strBody' => '',
					'strClassBody' => '',
					'flagFooderUse' => 1,
					'flagFooderLeftUse' => 1,
					'strTitleFooderLeft' => '',
					'strClassFooderLeft' => '',
					'flagFooderRightUse' => 1,
					'strTitleFooderRight' => '',
					'strClassFooderRight' => '',
					'flagHeaderLeftWidth' => 1,
					'numWidthHeaderLeft' => 0,
					'flagHeaderRightWidth' => 0,
					'numWidthHeaderRight' => 0,
					'flagFooderLeftWidth' => 0,
					'numWidthFooderLeft' => 0,
					'flagFooderRightWidth' => 0,
					'numWidthFooderRight' => 0,
				),
				'varsEdit' => array(),
				'varsDetail' => array(
					'varsStatus' => array(
						'flagBtnBottomUse' => 1,
					),
					'varsBtn' => array(),
					'varsDetail' => array(),
				),
			),
		),
		'varsTemplateLayout' => array(
			'varsStatus' => array(
				'flagNaviUse' => 0,
				'flagNaviToolUse' => 0,
				'flagListUse' => 0,
				'flagListToolUse' => 0,
				'flagDetailUse' => 1,
				'flagDetailToolUse' => 0,
			),
			'varsLayout' => array(
				'varsStatus' => array(
					'flagNow' => 1,
					'flagResizeUse' => 0,
					'flagMoveUse' => 0,
					'flagCakeUse' => 0,
					'flagSwitchUse' => 0,
					'flagSwitchNow' => 'Standard',
					'switchList' => array('Standard','Wide','Classic'),
				),
				'varsDetail' => array(
					array(
						'id' => 'Detail',
						'flagBoxUse' => 0,
						'numPriority' => 2,
						'numSort' => 2,
						'numWidth' => 100,			'numHeight' => 200,
						'numWidthMin' => 100,		'numHeightMin' => 200,
						'numWidthStandard' => 100,	'numHeightStandard' => 200,
						'numWidthWide' => 100,		'numHeightWide' => 200,
						'numWidthClassic' => 100,	'numHeightClassic' => 200,
						'numHeightBox' => 0,		'numWidthBox' => 0,//auto
					),
				),
			),
			'detail' => array(
				'varsFormat' => array(
					'id' => '',
					'flagType' => 'normalFormat',
					'numHeight' => 0,
					'numWidth' => 0,
					'flagHeaderLeftUse' => 1,
					'strTitleHeaderLeft' => '',
					'strClassHeaderLeft' => '',
					'flagHeaderRightUse' => 1,
					'strTitleHeaderRight' => '',
					'strClassHeaderRight' => 'codeLibBaseImgUnloading',
					'flagBodyAutoUse' => 1,
					'strBody' => '',
					'strClassBody' => '',
					'flagFooderUse' => 1,
					'flagFooderLeftUse' => 1,
					'strTitleFooderLeft' => '',
					'strClassFooderLeft' => '',
					'flagFooderRightUse' => 1,
					'strTitleFooderRight' => '',
					'strClassFooderRight' => '',
					'flagHeaderLeftWidth' => 1,
					'numWidthHeaderLeft' => 0,
					'flagHeaderRightWidth' => 0,
					'numWidthHeaderRight' => 0,
					'flagFooderLeftWidth' => 0,
					'numWidthFooderLeft' => 0,
					'flagFooderRightWidth' => 1,
					'numWidthFooderRight' => 0,
				),
				'varsTool' => array(),
			),
		),
	),

);
