<?php

$vars = array(
	'varsTmpl' => array(
		'look' => array(
			'varsSelectFlagFiscalPeriod' => array(
				'flagMustUse' => 0,
				'id' => 'SelectFlagFiscalPeriod',
				'strTitle' => '参照期間',
				'value' => 'f1', 'valueStr' => '年度決算期', 'flagValueType' => 'select',
				'flagErrorNow' => 0,
				'arrayError' => array(
					array( 'flagCheck' => 'blank', 'flagUse' => 1, 'flagNow' => 0, 'flagType' => 'empty', 'strComment' => array( 'common' => '記入漏れがあるようです。', ),),
				),
				'flagTag' => 'select', 'flagInputType' => '', 'numMaxlength' => 0,
				'numWidth' => 40, 'unitWidth' => 'px', 'numHeight' => 0, 'unitHeight' => 'px',
				'arrayOption' => array(),
				'varsTmpl' => array(
					'varsPeriod' => array( 'strTitle' => '年度決算期', 'value' => 'f1', ),
					'arrayOption' => array(
						array( 'strTitle' => '年度決算期', 'value' => 'f1', ),
						array( 'strTitle' => '中間(前半期)', 'value' => 'f21', ),
						array( 'strTitle' => '中間(後半期)', 'value' => 'f22', ),
						array( 'strTitle' => '第1四半期', 'value' => 'f41', ),
						array( 'strTitle' => '第2四半期', 'value' => 'f42', ),
						array( 'strTitle' => '第3四半期', 'value' => 'f43', ),
						array( 'strTitle' => '第4四半期', 'value' => 'f44', ),
					),
					'strMonth' => '月期',
				),
				'flagForm' => 'active',
			),
		),
		'calc' => array(
			'varsSelectGeneralSales' => array(
				'flagMustUse' => 0,
				'id' => 'SelectGeneralSales',
				'strTitle' => '売上の処理方法',
				'value' => 'sum', 'valueStr' => '総額', 'flagValueType' => 'select',
				'flagErrorNow' => 0,
				'arrayError' => array(
					array( 'flagCheck' => 'blank', 'flagUse' => 1, 'flagNow' => 0, 'flagType' => 'empty', 'strComment' => array( 'common' => '記入漏れがあるようです。', ),),
				),
				'flagTag' => 'select', 'flagInputType' => '', 'numMaxlength' => 0,
				'numWidth' => 40, 'unitWidth' => 'px', 'numHeight' => 0, 'unitHeight' => 'px',
				'arrayOption' => array(
					array( 'strTitle' => '総額', 'value' => 'sum', ),
					array( 'strTitle' => '積上', 'value' => 'add', ),
				),
				'flagForm' => 'active',
				'flagGeneralRule' => 1,
			),
			'varsSelectGeneralStock' => array(
				'flagMustUse' => 0,
				'id' => 'SelectGeneralStock',
				'strTitle' => '仕入の処理方法',
				'value' => 'sum', 'valueStr' => '総額', 'flagValueType' => 'select',
				'flagErrorNow' => 0,
				'arrayError' => array(
					array( 'flagCheck' => 'blank', 'flagUse' => 1, 'flagNow' => 0, 'flagType' => 'empty', 'strComment' => array( 'common' => '記入漏れがあるようです。', ),),
				),
				'flagTag' => 'select', 'flagInputType' => '', 'numMaxlength' => 0,
				'numWidth' => 40, 'unitWidth' => 'px', 'numHeight' => 0, 'unitHeight' => 'px',
				'arrayOption' => array(
					array( 'strTitle' => '総額', 'value' => 'sum', ),
					array( 'strTitle' => '積上', 'value' => 'add', ),
				),
				'flagForm' => 'active',
				'flagGeneralRule' => 1,
			),
			'varsSelectSimpleSale' => array(
				'flagMustUse' => 0,
				'id' => 'SelectSimpleSale',
				'strTitle' => '売上の処理方法',
				'strExplain' => '',
				'value' => 'sum', 'valueStr' => '総額', 'flagValueType' => 'select',
				'flagErrorNow' => 0,
				'arrayError' => array(
					array( 'flagCheck' => 'blank', 'flagUse' => 1, 'flagNow' => 0, 'flagType' => 'empty', 'strComment' => array( 'common' => '記入漏れがあるようです。', ),),
				),
				'flagTag' => 'select', 'flagInputType' => '', 'numMaxlength' => 0,
				'numWidth' => 40, 'unitWidth' => 'px', 'numHeight' => 0, 'unitHeight' => 'px',
				'arrayOption' => array(
					array( 'strTitle' => '総額', 'value' => 'sum', ),
					array( 'strTitle' => '積上', 'value' => 'add', ),
				),
				'flagForm' => 'active',
				'flagGeneralRule' => 0,
			),
		),
	),
	'arrSelectTag' => array(
		'look' => array(),
		'calc' => array(),
		'head' => array(
			array(
				'flagMustUse' => 0,
				'id' => 'TextTaxBoss',
				'strTitle' => '管轄税務署名',
				'value' => '', 'valueStr' => '', 'flagValueType' => 'str',
				'arrayError' => array(
					array( 'flagCheck' => 'blank', 'flagUse' => 1, 'flagNow' => 0, 'flagType' => 'empty', 'strComment' => array( 'common' => '記入が必要なようです。', ),),
					array( 'flagCheck' => 'max', 'flagUse' => 1, 'flagNow' => 0, 'flagType' => 'str', 'num' => 30, 'strComment' => array( 'common' => '入力文字数が多すぎるようです。', ),),
				),
				'flagTag' => 'input', 'flagInputType' => 'text', 'numMaxlength' => 30,
				'numWidth' => 40, 'unitWidth' => 'px', 'numHeight' => 0, 'unitHeight' => 'px',
				'arrayOption' => array(),
				'flagForm' => 'active',
			),
			array(
				'flagMustUse' => 0,
				'id' => 'TextTaxAddress',
				'strTitle' => '納税地',
				'value' => '', 'valueStr' => '', 'flagValueType' => 'str',
				'arrayError' => array(
					array( 'flagCheck' => 'blank', 'flagUse' => 1, 'flagNow' => 0, 'flagType' => 'empty', 'strComment' => array( 'common' => '記入が必要なようです。', ),),
					array( 'flagCheck' => 'max', 'flagUse' => 1, 'flagNow' => 0, 'flagType' => 'str', 'num' => 40, 'strComment' => array( 'common' => '入力文字数が多すぎるようです。', ),),
				),
				'flagTag' => 'input', 'flagInputType' => 'text', 'numMaxlength' => 40,
				'numWidth' => 40, 'unitWidth' => 'px', 'numHeight' => 0, 'unitHeight' => 'px',
				'arrayOption' => array(),
				'flagForm' => 'active',
			),
			array(
				'flagMustUse' => 0,
				'id' => 'TextPhone',
				'strTitle' => '電話番号',
				'value' => '000-0000-0000', 'valueStr' => '000-0000-0000', 'flagValueType' => 'str',
				'arrayError' => array(
					array( 'flagCheck' => 'blank', 'flagUse' => 1, 'flagNow' => 0, 'flagType' => 'empty', 'strComment' => array( 'common' => '記入が必要なようです。', ),),
					array( 'flagCheck' => 'max', 'flagUse' => 1, 'flagNow' => 0, 'flagType' => 'str', 'num' => 15, 'strComment' => array( 'common' => '入力文字数が多すぎるようです。', ),),
					array( 'flagCheck' => 'format', 'flagUse' => 1, 'flagNow' => 0, 'flagType' => 'phone', 'strComment' => array( 'common' => 'フォーマットが正しくないようです。', ),),
				),
				'flagTag' => 'input', 'flagInputType' => 'text', 'numMaxlength' => 15,
				'numWidth' => 40, 'unitWidth' => 'px', 'numHeight' => 0, 'unitHeight' => 'px',
				'arrayOption' => array(),
				'flagForm' => 'active',
			),
			array(
				'flagMustUse' => 0,
				'id' => 'TextSignCompanyKana',
				'strTitle' => '（フリガナ）',
				'value' => '', 'valueStr' => '', 'flagValueType' => 'str',
				'arrayError' => array(
					array( 'flagCheck' => 'blank', 'flagUse' => 1, 'flagNow' => 0, 'flagType' => 'empty', 'strComment' => array( 'common' => '記入が必要なようです。', ),),
					array( 'flagCheck' => 'max', 'flagUse' => 1, 'flagNow' => 0, 'flagType' => 'str', 'num' => 30, 'strComment' => array( 'common' => '入力文字数が多すぎるようです。', ),),
				),
				'flagTag' => 'input', 'flagInputType' => 'text', 'numMaxlength' => 30,
				'numWidth' => 40, 'unitWidth' => 'px', 'numHeight' => 0, 'unitHeight' => 'px',
				'arrayOption' => array(),
				'flagForm' => 'active',
			),
			array(
				'flagMustUse' => 0,
				'id' => 'TextSignCompany',
				'strTitle' => '名称又は屋号',
				'value' => '', 'valueStr' => '', 'flagValueType' => 'str',
				'arrayError' => array(
					array( 'flagCheck' => 'blank', 'flagUse' => 1, 'flagNow' => 0, 'flagType' => 'empty', 'strComment' => array( 'common' => '記入が必要なようです。', ),),
					array( 'flagCheck' => 'max', 'flagUse' => 1, 'flagNow' => 0, 'flagType' => 'str', 'num' => 30, 'strComment' => array( 'common' => '入力文字数が多すぎるようです。', ),),
				),
				'flagTag' => 'input', 'flagInputType' => 'text', 'numMaxlength' => 30,
				'numWidth' => 40, 'unitWidth' => 'px', 'numHeight' => 0, 'unitHeight' => 'px',
				'arrayOption' => array(),
				'flagForm' => 'active',
			),
			array(
				'flagMustUse' => 0,
				'id' => 'TextSignBossKana',
				'strTitle' => '（フリガナ）',
				'value' => '', 'valueStr' => '', 'flagValueType' => 'str',
				'arrayError' => array(
					array( 'flagCheck' => 'blank', 'flagUse' => 1, 'flagNow' => 0, 'flagType' => 'empty', 'strComment' => array( 'common' => '記入が必要なようです。', ),),
					array( 'flagCheck' => 'max', 'flagUse' => 1, 'flagNow' => 0, 'flagType' => 'str', 'num' => 30, 'strComment' => array( 'common' => '入力文字数が多すぎるようです。', ),),
				),
				'flagTag' => 'input', 'flagInputType' => 'text', 'numMaxlength' => 30,
				'numWidth' => 40, 'unitWidth' => 'px', 'numHeight' => 0, 'unitHeight' => 'px',
				'arrayOption' => array(),
				'flagForm' => 'active',
			),
			array(
				'flagMustUse' => 0,
				'id' => 'TextSignBoss',
				'strTitle' => '代表者氏名又は氏名',
				'value' => '', 'valueStr' => '', 'flagValueType' => 'str',
				'arrayError' => array(
					array( 'flagCheck' => 'blank', 'flagUse' => 1, 'flagNow' => 0, 'flagType' => 'empty', 'strComment' => array( 'common' => '記入が必要なようです。', ),),
					array( 'flagCheck' => 'max', 'flagUse' => 1, 'flagNow' => 0, 'flagType' => 'str', 'num' => 30, 'strComment' => array( 'common' => '入力文字数が多すぎるようです。', ),),
				),
				'flagTag' => 'input', 'flagInputType' => 'text', 'numMaxlength' => 30,
				'numWidth' => 40, 'unitWidth' => 'px', 'numHeight' => 0, 'unitHeight' => 'px',
				'arrayOption' => array(),
				'flagForm' => 'active',
			),
			array(
				'flagMustUse' => 0,
				'id' => 'TextCompanyAccouting',
				'strTitle' => '経理担当者氏名',
				'value' => '', 'valueStr' => '', 'flagValueType' => 'str',
				'arrayError' => array(
					array( 'flagCheck' => 'blank', 'flagUse' => 1, 'flagNow' => 0, 'flagType' => 'empty', 'strComment' => array( 'common' => '記入が必要なようです。', ),),
					array( 'flagCheck' => 'max', 'flagUse' => 1, 'flagNow' => 0, 'flagType' => 'str', 'num' => 30, 'strComment' => array( 'common' => '入力文字数が多すぎるようです。', ),),
				),
				'flagTag' => 'input', 'flagInputType' => 'text', 'numMaxlength' => 30,
				'numWidth' => 40, 'unitWidth' => 'px', 'numHeight' => 0, 'unitHeight' => 'px',
				'arrayOption' => array(),
				'flagForm' => 'active',
			),
		),
		'back' => array(
			array(
				'flagMustUse' => 0,
				'id' => 'TextBank',
				'strTitle' => '金融機関',
				'value' => '', 'valueStr' => '', 'flagValueType' => 'str',
				'arrayError' => array(
					array( 'flagCheck' => 'blank', 'flagUse' => 1, 'flagNow' => 0, 'flagType' => 'empty', 'strComment' => array( 'common' => '記入が必要なようです。', ),),
					array( 'flagCheck' => 'max', 'flagUse' => 1, 'flagNow' => 0, 'flagType' => 'str', 'num' => 10, 'strComment' => array( 'common' => '入力文字数が多すぎるようです。', ),),
				),
				'flagTag' => 'input', 'flagInputType' => 'text', 'numMaxlength' => 10,
				'numWidth' => 40, 'unitWidth' => 'px', 'numHeight' => 0, 'unitHeight' => 'px',
				'arrayOption' => array(),
				'flagForm' => 'active',
			),
			array(
				'flagMustUse' => 0,
				'id' => 'SelectBank',
				'strTitle' => '',
				'value' => 'none', 'valueStr' => '[　] 未選択', 'flagValueType' => 'select',
				'arrayError' => array(
					array( 'flagCheck' => 'blank', 'flagUse' => 1, 'flagNow' => 0, 'flagType' => 'empty', 'strComment' => array( 'common' => '記入が必要なようです。', ),),
				),
				'flagTag' => 'select', 'flagInputType' => '', 'numMaxlength' => 0,
				'numWidth' => 40, 'unitWidth' => 'px', 'numHeight' => 0, 'unitHeight' => 'px',
				'arrayOption' => array(
					array( 'strTitle' => '[　] 未選択', 'value' => 'none', ),
					array( 'strTitle' => '[○] 銀行', 'value' => 'bank', ),
					array( 'strTitle' => '[○] 金庫', 'value' => 'safe', ),
					array( 'strTitle' => '[○] 組合', 'value' => 'union', ),
					array( 'strTitle' => '[○] 農協', 'value' => 'agri', ),
					array( 'strTitle' => '[○] 漁協', 'value' => 'fish', ),
				),
				'flagForm' => 'active',
			),
			array(
				'flagMustUse' => 0,
				'id' => 'TextBranch',
				'strTitle' => '',
				'value' => '', 'valueStr' => '', 'flagValueType' => 'str',
				'arrayError' => array(
					array( 'flagCheck' => 'blank', 'flagUse' => 1, 'flagNow' => 0, 'flagType' => 'empty', 'strComment' => array( 'common' => '記入が必要なようです。', ),),
					array( 'flagCheck' => 'max', 'flagUse' => 1, 'flagNow' => 0, 'flagType' => 'str', 'num' => 10, 'strComment' => array( 'common' => '入力文字数が多すぎるようです。', ),),
				),
				'flagTag' => 'input', 'flagInputType' => 'text', 'numMaxlength' => 10,
				'numWidth' => 40, 'unitWidth' => 'px', 'numHeight' => 0, 'unitHeight' => 'px',
				'arrayOption' => array(),
				'flagForm' => 'active',
			),
			array(
				'flagMustUse' => 0,
				'id' => 'SelectBranch',
				'strTitle' => '',
				'value' => 'none', 'valueStr' => '[　] 未選択', 'flagValueType' => 'select',
				'arrayError' => array(
					array( 'flagCheck' => 'blank', 'flagUse' => 1, 'flagNow' => 0, 'flagType' => 'empty', 'strComment' => array( 'common' => '記入が必要なようです。', ),),
				),
				'flagTag' => 'select', 'flagInputType' => '', 'numMaxlength' => 0,
				'numWidth' => 40, 'unitWidth' => 'px', 'numHeight' => 0, 'unitHeight' => 'px',
				'arrayOption' => array(
					array( 'strTitle' => '[　] 未選択', 'value' => 'none', ),
					array( 'strTitle' => '[○] 本店', 'value' => 'center', ),
					array( 'strTitle' => '[○] 支店', 'value' => 'branch', ),
					array( 'strTitle' => '[○] 出張所', 'value' => 'agency', ),
					array( 'strTitle' => '[○] 本所', 'value' => 'officeCenter', ),
					array( 'strTitle' => '[○] 支所', 'value' => 'officeBranch', ),
				),
				'flagForm' => 'active',
			),
			array(
				'flagMustUse' => 0,
				'id' => 'TextDeposits',
				'strTitle' => '種類',
				'value' => '', 'valueStr' => '', 'flagValueType' => 'str',
				'arrayError' => array(
					array( 'flagCheck' => 'blank', 'flagUse' => 1, 'flagNow' => 0, 'flagType' => 'empty', 'strComment' => array( 'common' => '記入が必要なようです。', ),),
					array( 'flagCheck' => 'max', 'flagUse' => 1, 'flagNow' => 0, 'flagType' => 'str', 'num' => 10, 'strComment' => array( 'common' => '入力文字数が多すぎるようです。', ),),
				),
				'flagTag' => 'input', 'flagInputType' => 'text', 'numMaxlength' => 10,
				'numWidth' => 40, 'unitWidth' => 'px', 'numHeight' => 0, 'unitHeight' => 'px',
				'arrayOption' => array(),
				'flagForm' => 'active',
			),
			array(
				'flagMustUse' => 0,
				'id' => 'TextDepositsAccount',
				'strTitle' => '口座番号',
				'value' => '', 'valueStr' => '', 'flagValueType' => 'str',
				'arrayError' => array(
					array( 'flagCheck' => 'blank', 'flagUse' => 1, 'flagNow' => 0, 'flagType' => 'empty', 'strComment' => array( 'common' => '記入が必要なようです。', ),),
					array( 'flagCheck' => 'max', 'flagUse' => 1, 'flagNow' => 0, 'flagType' => 'str', 'num' => 7, 'strComment' => array( 'common' => '入力文字数が多すぎるようです。', ),),
				),
				'flagTag' => 'input', 'flagInputType' => 'text', 'numMaxlength' => 7,
				'numWidth' => 40, 'unitWidth' => 'px', 'numHeight' => 0, 'unitHeight' => 'px',
				'arrayOption' => array(),
				'flagForm' => 'active',
			),
			array(
				'flagMustUse' => 0,
				'id' => 'TextDepositsAccountJp',
				'strTitle' => 'ゆうちょ銀行の貯金記号番号',
				'value' => '', 'valueStr' => '', 'flagValueType' => 'str',
				'arrayError' => array(
					array( 'flagCheck' => 'blank', 'flagUse' => 1, 'flagNow' => 0, 'flagType' => 'empty', 'strComment' => array( 'common' => '記入が必要なようです。', ),),
					array( 'flagCheck' => 'max', 'flagUse' => 1, 'flagNow' => 0, 'flagType' => 'str', 'num' => 5, 'strComment' => array( 'common' => '入力文字数が多すぎるようです。', ),),
				),
				'flagTag' => 'input', 'flagInputType' => 'text', 'numMaxlength' => 5,
				'numWidth' => 40, 'unitWidth' => 'px', 'numHeight' => 0, 'unitHeight' => 'px',
				'arrayOption' => array(),
				'flagForm' => 'active',
			),
			array(
				'flagMustUse' => 0,
				'id' => 'TextDepositsAccountJpAfter',
				'strTitle' => '-',
				'value' => '', 'valueStr' => '', 'flagValueType' => 'str',
				'arrayError' => array(
					array( 'flagCheck' => 'blank', 'flagUse' => 1, 'flagNow' => 0, 'flagType' => 'empty', 'strComment' => array( 'common' => '記入が必要なようです。', ),),
					array( 'flagCheck' => 'max', 'flagUse' => 1, 'flagNow' => 0, 'flagType' => 'str', 'num' => 8, 'strComment' => array( 'common' => '入力文字数が多すぎるようです。', ),),
				),
				'flagTag' => 'input', 'flagInputType' => 'text', 'numMaxlength' => 8,
				'numWidth' => 40, 'unitWidth' => 'px', 'numHeight' => 0, 'unitHeight' => 'px',
				'arrayOption' => array(),
				'flagForm' => 'active',
			),
			array(
				'flagMustUse' => 0,
				'id' => 'TextDepositsJp',
				'strTitle' => '郵便局名等',
				'value' => '', 'valueStr' => '', 'flagValueType' => 'str',
				'arrayError' => array(
					array( 'flagCheck' => 'blank', 'flagUse' => 1, 'flagNow' => 0, 'flagType' => 'empty', 'strComment' => array( 'common' => '記入が必要なようです。', ),),
					array( 'flagCheck' => 'max', 'flagUse' => 1, 'flagNow' => 0, 'flagType' => 'str', 'num' => 10, 'strComment' => array( 'common' => '入力文字数が多すぎるようです。', ),),
				),
				'flagTag' => 'input', 'flagInputType' => 'text', 'numMaxlength' => 10,
				'numWidth' => 40, 'unitWidth' => 'px', 'numHeight' => 0, 'unitHeight' => 'px',
				'arrayOption' => array(),
				'flagForm' => 'active',
			),
		),
		'tax' => array(
			array(
				'flagMustUse' => 0,
				'id' => 'TextName',
				'strTitle' => '税理士名',
				'value' => '', 'valueStr' => '', 'flagValueType' => 'str',
				'arrayError' => array(
					array( 'flagCheck' => 'blank', 'flagUse' => 1, 'flagNow' => 0, 'flagType' => 'empty', 'strComment' => array( 'common' => '記入が必要なようです。', ),),
					array( 'flagCheck' => 'max', 'flagUse' => 1, 'flagNow' => 0, 'flagType' => 'str', 'num' => 30, 'strComment' => array( 'common' => '入力文字数が多すぎるようです。', ),),
				),
				'flagTag' => 'input', 'flagInputType' => 'text', 'numMaxlength' => 30,
				'numWidth' => 40, 'unitWidth' => 'px', 'numHeight' => 0, 'unitHeight' => 'px',
				'arrayOption' => array(),
				'flagForm' => 'active',
			),
			array(
				'flagMustUse' => 0,
				'id' => 'TextPhone',
				'strTitle' => '電話番号',
				'value' => '000-0000-0000', 'valueStr' => '000-0000-0000', 'flagValueType' => 'str',
				'arrayError' => array(
					array( 'flagCheck' => 'blank', 'flagUse' => 1, 'flagNow' => 0, 'flagType' => 'empty', 'strComment' => array( 'common' => '記入が必要なようです。', ),),
					array( 'flagCheck' => 'max', 'flagUse' => 1, 'flagNow' => 0, 'flagType' => 'str', 'num' => 15, 'strComment' => array( 'common' => '入力文字数が多すぎるようです。', ),),
					array( 'flagCheck' => 'format', 'flagUse' => 1, 'flagNow' => 0, 'flagType' => 'phone', 'strComment' => array( 'common' => 'フォーマットが正しくないようです。', ),),
				),
				'flagTag' => 'input', 'flagInputType' => 'text', 'numMaxlength' => 15,
				'numWidth' => 40, 'unitWidth' => 'px', 'numHeight' => 0, 'unitHeight' => 'px',
				'arrayOption' => array(),
				'flagForm' => 'active',
			),
			array(
				'flagMustUse' => 0,
				'id' => 'SelectLaw30',
				'strTitle' => '税理士法第30条の書面提出有',
				'value' => 0, 'valueStr' => '[　] 未選択', 'flagValueType' => 'select',
				'arrayError' => array(
					array( 'flagCheck' => 'blank', 'flagUse' => 1, 'flagNow' => 0, 'flagType' => 'empty', 'strComment' => array( 'common' => '記入が必要なようです。', ),),
				),
				'flagTag' => 'select', 'flagInputType' => '', 'numMaxlength' => 0,
				'numWidth' => 40, 'unitWidth' => 'px', 'numHeight' => 0, 'unitHeight' => 'px',
				'arrayOption' => array(
					array( 'strTitle' => '[　] 未選択', 'value' => 0, ),
					array( 'strTitle' => '[○] 選択', 'value' => 1, ),
				),
				'flagForm' => 'active',
			),
			array(
				'flagMustUse' => 0,
				'id' => 'SelectLaw302',
				'strTitle' => '税理士法第33条の2の書面提出有',
				'value' => 0, 'valueStr' => '[　] 未選択', 'flagValueType' => 'select',
				'arrayError' => array(
					array( 'flagCheck' => 'blank', 'flagUse' => 1, 'flagNow' => 0, 'flagType' => 'empty', 'strComment' => array( 'common' => '記入が必要なようです。', ),),
				),
				'flagTag' => 'select', 'flagInputType' => '', 'numMaxlength' => 0,
				'numWidth' => 40, 'unitWidth' => 'px', 'numHeight' => 0, 'unitHeight' => 'px',
				'arrayOption' => array(
					array( 'strTitle' => '[　] 未選択', 'value' => 0, ),
					array( 'strTitle' => '[○] 選択', 'value' => 1, ),
				),
				'flagForm' => 'active',
			),
		),
	),
	'varsStr' => array(
		'look' => array(
			'strTitle' => '消費税参照先',
		),
		'calc' => array(
			'strTitle' => '消費税集計方法',
			'flagGeneralRule' => 0,
		),
		'head' => array(
			'strTaxBossUnit' => '税務署',
		),
		'back' => array(
			'strTitle' => '還付を受けようとする金融機関等',
			'strDepositsUnit' => '預金',

		),
		'tax' => array(
			'strTitle' => '税理士名等',
		),
	),
	'varsFlagCalcBtn' => array(

	),


);
