<?php

$vars = array(
	'varsItem'  => array(
		'strClassError' => 'codeLibBaseFontRed',
		'strClassBlank' => 'codeLibBaseImgBlank',
		'strEscape' => '、',
		'strSpace' => '　',
		'strDate' => '日',
		'varsOutput' => array(),
	),
	'pathCss' => '',
	'portal' => array(
		'varsNavi' => array(
			'varsStatus' => array(
				'flagNow' => 'search',
				'flagCakeUse' => 1,
				'flagTreeUse' => 0,
				'flagSearchUse' => 1,
				'flagFolderUse' => 0,
				'switchList' => array('search',),
			),
			'varsFolder' => array(),
			'varsDetail' => array(),
			'tree' => array(),
			'search' => array(
				'varsFormat' => array(
					'id' => '',
					'flagType' => 'normalFormat',
					'numHeight' => 0,
					'numWidth' => 0,
					'flagHeaderLeftUse' => 1,
					'strTitleHeaderLeft' => '詳細検索',
					'strClassHeaderLeft' => 'codeLibBaseImgDb',
					'flagHeaderRightUse' => 1,
					'strTitleHeaderRight' => '',
					'strClassHeaderRight' => 'codeLibBaseImgUnloading',
					'flagBodyAutoUse' => 1,
					'strBody' => '',
					'strClassBody' => '',
					'flagFooderUse' => 1,
					'flagFooderLeftUse' => 1,
					'strTitleFooderLeft' => '',
					'strClassFooderLeft' => '',
					'flagFooderRightUse' => 1,
					'strTitleFooderRight' => '',
					'strClassFooderRight' => '',
					'flagHeaderLeftWidth' => 1,
					'numWidthHeaderLeft' => 0,
					'flagHeaderRightWidth' => 0,
					'numWidthHeaderRight' => 0,
					'flagFooderLeftWidth' => 0,
					'numWidthFooderLeft' => 0,
					'flagFooderRightWidth' => 0,
					'numWidthFooderRight' => 0,
				),
				'varsEdit' => array(
					'flagReloadUse' => 1,
				),
				'varsDetail' => array(
					'varsStatus' => array(
						'flagNow' => 'item',
						'flagSwitchUse' => 1,
						'flagItemUse' => 1,
						'flagWordUse' => 1,
						'flagTagUse' => 1,
						'flagMyRecordUse' => 1,
						'idColumnTagList' => array('arrSpaceStrTag'),
						'idColumnWordList' => array('strTitle'),
						'switchList' => array('word','tag','item'),
					),
					'varsDetail' => array(
						'varsStatus' => array(
							'flagBtnBottomUse' => 1,
						),
						'varsTag' => array(),
						'varsItem' => array(),
						'varsWord' => array(),
						'varsDetail' => array(),
						'varsBtn' => array(
							array(
								'flagUse' => 1, 'flagLeftUse' => 0, 'flagRightUse' => 1, 'flagTextUse' => 0, 'flagBtnUse' => 1,
								'id' => 'EventFormBtnSave',
								'vars' => array( 'idTarget' => 'eventFormBtnSave', ),
								'strTitle' => '保存',
							),
							array(
								'flagUse' => 1, 'flagLeftUse' => 0, 'flagRightUse' => 1, 'flagTextUse' => 0, 'flagBtnUse' => 1,
								'id' => 'EventFormBtnDelete',
								'vars' => array( 'idTarget' => 'eventFormBtnDelete', ),
								'strTitle' => '削除',
							),
							array(
								'flagUse' => 1, 'flagLeftUse' => 0, 'flagRightUse' => 1, 'flagTextUse' => 0, 'flagBtnUse' => 1,
								'id' => 'EventFormBtn',
								'vars' => array( 'idTarget' => 'eventFormBtn', ),
								'strTitle' => '検索',
							),
						),
						'templateDetail' => array(
							'switchTarget' => array(
								'flagMustUse' => 1,
								'id' => 'SwitchTarget',
								'strTitle' => '検索対象', 'strExplain' => '', 'value' => 'word',
								'flagErrorNow' => 0,
								'arrayError' => array(
									array( 'flagCheck' => 'blank', 'flagUse' => 1, 'flagNow' => 0, 'flagType' => 'empty', 'strComment' => array( 'common' => '記入が必要なようです。', ), ),
								),
								'flagContentUse' => 0,
								'flagCommentUse' => 0, 'strCommentTitle' => '', 'strComment' => '',
								'flagTag' => 'select', 'flagInputType' => '', 'numMaxlength' => 0,
								'unitWidth' => '%', 'numWidth' => 40, 'unitHeight' => '', 'numHeight' => 0,
								'arrayOption' => array(
									array( 'strTitle' => 'ワード', 'value' => 'word', ),
									array( 'strTitle' => 'タグ', 'value' => 'tag', ),
									array( 'strTitle' => '項目', 'value' => 'item', ),
								),
							),
							'wordTarget' => array(
								'flagMustUse' => 1,
								'id' => 'Word',
								'strTitle' => '検索ワード', 'strExplain' => '', 'value' => '',
								'flagErrorNow' => 0,
								'arrayError' => array(
									array( 'flagCheck' => 'blank', 'flagUse' => 1, 'flagNow' => 0, 'flagType' => 'empty', 'strComment' => array( 'common' => '記入が必要なようです。', ), ),
								),
								'flagContentUse' => 0,
								'flagCommentUse' => 0, 'strCommentTitle' => '', 'strComment' => '',
								'flagTag' => 'input', 'flagInputType' => 'text', 'numMaxlength' => 0,
								'unitWidth' => '%', 'numWidth' => 80, 'unitHeight' => '', 'numHeight' => 0,
								'arrayOption' => array(),
							),
							'tagTarget' => array(
								'flagMustUse' => 1,
								'id' => 'Tag',
								'strTitle' => '検索タグ', 'strExplain' => '', 'value' => '',
								'flagErrorNow' => 0,
								'arrayError' => array(
									array( 'flagCheck' => 'blank', 'flagUse' => 1, 'flagNow' => 0, 'flagType' => 'empty', 'strComment' => array( 'common' => '記入が必要なようです。', ), ),
								),
								'flagContentUse' => 0,
								'flagCommentUse' => 0, 'strCommentTitle' => '', 'strComment' => '',
								'flagTag' => 'input', 'flagInputType' => 'text', 'numMaxlength' => 0,
								'unitWidth' => '%', 'numWidth' => 80, 'unitHeight' => '', 'numHeight' => 0,
								'arrayOption' => array(),
							),
							'itemTarget' => array(
								'flagMustUse' => 1,
								'id' => 'JsonItem',
								'strTitle' => '検索項目', 'strExplain' => '', 'value' => '',
								'flagErrorNow' => 0,
								'arrayError' => array(
									array( 'flagCheck' => 'blank', 'flagUse' => 1, 'flagNow' => 0, 'flagType' => 'empty', 'strComment' => array( 'common' => '記入が必要なようです。', ), ),
								),
								'flagContentUse' => 1,
								'flagCommentUse' => 0, 'strCommentTitle' => '', 'strComment' => '',
								'flagTag' => 'input', 'flagInputType' => 'text', 'numMaxlength' => 0,
								'unitWidth' => '%', 'numWidth' => 40, 'unitHeight' => '', 'numHeight' => 0,
								'arrayOption' => array(),
							),
							'jsonSort' => array(
								'flagMustUse' => 1,
								'id' => 'JsonSort',
								'strTitle' => '並び順', 'strExplain' => '', 'value' => '',
								'flagErrorNow' => 0,
								'arrayError' => array(
									array( 'flagCheck' => 'blank', 'flagUse' => 1, 'flagNow' => 0, 'flagType' => 'empty', 'strComment' => array( 'common' => '記入が必要なようです。', ), ),
								),
								'flagContentUse' => 1,
								'flagCommentUse' => 0, 'strCommentTitle' => '', 'strComment' => '',
								'flagTag' => 'input', 'flagInputType' => 'text', 'numMaxlength' => 0,
								'unitWidth' => '%', 'numWidth' => 40, 'unitHeight' => '', 'numHeight' => 0,
								'arrayOption' => array(),
							),
							'myRecord' => array(
								'flagMustUse' => 0,
								'id' => 'MyRecord',
								'strTitle' => '', 'strExplain' => '', 'value' => '',
								'flagErrorNow' => 0,
								'arrayError' => array(),
								'flagContentUse' => 0,
								'flagCommentUse' => 1, 'strCommentTitle' => 'My条件', 'strComment' => '',
								'flagTag' => 'input', 'flagInputType' => 'text', 'numMaxlength' => 0,
								'unitWidth' => '%', 'numWidth' => 40, 'unitHeight' => '', 'numHeight' => 0,
								'arrayOption' => array(),
							),
						),
					),
					'varsMyRecord' => array(
						'varsFormList' => array(
							'varsStatus' => array(
								'flagSortUse' => 1,
								'flagCopyUse' => 0,
								'flagRemoveUse' => 1,
								'flagAddUse' => 0,
								'flagEditUse' => 1,
								'flagFormUse' => 1,
								'flagBtnUse' => 1,
							),
							'templateDetail' => array(
								'id' => '',
								'flagSortUse' => 1,
								'flagCopyUse' => 0,
								'flagRemoveUse' => 1,
								'flagEditUse' => 1,
								'flagFormUse' => 0,
								'flagBtnUse' => 1,
								'numSort' => 0,
								'value' => '',
								'vars' => '',
							),
							'varsDetail' => array(),
						),
					),
					'varsSearchSort' => array(
						'varsStatus' => array(
							'flagUse' => 1,
							'flagAscUse' => 1,
							'flagDescUse' => 1,
						),
						'varsDetail' => array(
							'id' => 0,
							'itemValue' => 'id',
							'sortValue' => 'desc'
						),
						'itemOption' => array(
							array( 'strTitle' => '記録日時', 'value' => 'id', ),
							array( 'strTitle' => '更新日時', 'value' => 'stampUpdate', ),
						),
						'sortOption' => array(
							array( 'strTitle' => '降順', 'value' => 'desc', ),
							array( 'strTitle' => '昇順', 'value' => 'asc', ),
						),
					),
					'varsSearchItem' => array(
						'varsStatus' => array(
							'flagUse' => 1,
							'flagAddUse' => 1,
							'flagCopyUse' => 1,
							'flagRemoveUse' => 1,
							'flagCalenderUse' => 1,
						),
						'varsCalender' => array(
							'varsStatus' => array(
								'numLeft' => 0,
								'numTop' => 0,
								'flagMaxUse' => 0,
								'flagMaxAutoUse' => 1,
								'stampMax' => 0,//1260198000000
								'flagMainUse' => 1,
								'flagMainAutoUse' => 1,
								'stampMain' => 0,
								'flagMinUse' => 0,
								'flagMinAutoUse' => 0,
								'stampMin' => 0,
								'stampPoint' => 0,
							),
						),
						'varsDetail' => array(
							array(
								'id' => 0,
								'flagType' => 'num',
								'flagOption' => '',
								'firstValue' => 'num-idLogAccount',
								'secondValue' => 'eq',
								'restValue' => '',
							),
						),
						'templateDetail' => array(
							'varsDetail' => array(
								'id' => 0,
								'flagType' => 'num',
								'flagOption' => '',//set option str ex)moduleOption
								'firstValue' => 'num-idLogAccount',
								'secondValue' => 'eq',
								'restValue' => '',
							),
							'firstOption' => array(
								array( 'strTitle' => '通番', 'value' => 'num-idLogAccount', ),
								array( 'strTitle' => '記録日時', 'value' => 'stamp-stampRegister', ),
								array( 'strTitle' => '更新日時', 'value' => 'stamp-stampUpdate', ),
								array( 'strTitle' => '口座名', 'value' => 'str-strTitle', ),
								array( 'strTitle' => '金融機関', 'value' => 'flagBank-flagBank-flagBank', ),
								array( 'strTitle' => '最終確認取引日', 'value' => 'stamp-stampCheck', ),
								array( 'strTitle' => 'タグ', 'value' => 'tag-arrSpaceStrTag', ),
							),
							'strOption' => array(
								array( 'strTitle' => '～を含む。', 'value' => 'like', ),
								array( 'strTitle' => '～を含まない。', 'value' => 'notlike', ),
								array( 'strTitle' => '～と一致。', 'value' => 'eq', ),
								array( 'strTitle' => '～と不一致。', 'value' => 'ne', ),
								array( 'strTitle' => '～で始まる。', 'value' => 'start', ),
								array( 'strTitle' => '～で終わる。', 'value' => 'end', ),
							),
							'tagOption' => array(
								array( 'strTitle' => '～と一致。', 'value' => 'like', ),
								array( 'strTitle' => '～と不一致。', 'value' => 'notlike', ),
							),
							'flagBankOption' => array(
								array( 'strTitle' => '～と一致。', 'value' => 'eq', ),
								array( 'strTitle' => '～と不一致。', 'value' => 'ne', ),
							),
							'stampOption' => array(
								array( 'strTitle' => '～と一致。', 'value' => 'eq', ),
								array( 'strTitle' => '～と不一致。', 'value' => 'ne', ),
								array( 'strTitle' => '～より前。', 'value' => 'before', ),
								array( 'strTitle' => '～より後。', 'value' => 'after', ),
								array( 'strTitle' => '～以前。', 'value' => 'eqBefore', ),
								array( 'strTitle' => '～以後。', 'value' => 'eqAfter', ),
							),
							'numOption' => array(
								array( 'strTitle' => '～と一致。', 'value' => 'eq', ),
								array( 'strTitle' => '～と不一致。', 'value' => 'ne', ),
								array( 'strTitle' => '～未満。', 'value' => 'small', ),
								array( 'strTitle' => '～超。', 'value' => 'big', ),
								array( 'strTitle' => '～以下。', 'value' => 'eqSmall', ),
								array( 'strTitle' => '～以上。', 'value' => 'eqBig', ),
							),
							'restOption' => array(
								'flagBank' => array(),
							),
						),
					),
				),
			),
			'templateFolder' => array(),
		),
		'varsList' => array(
			'varsStart' => array(
				'varsStatus' => array(
					'strTitle' => '金融機関リスト',
					'strClass' => 'codeLibBaseImgFolder',
				),
				'varsEdit' => array(
					'flagReloadUse' => 1,
					'flagSwitchUse' => 1,
					'flagSearchUse' => 1,
				),
				'varsDetail' => array(),
			),
			'varsStatus' => array(
				'flagNow' => 'table',
				'flagCakeUse' => 1,
				'flagTableUse' => 1,
				'flagScheduleUse' => 1,
				'flagThumbnailUse' => 0,
				'flagTreeUse' => 0,
				'flagBoldUse' => 0,
				'flagFontUse' => 0,
				'flagBgUse' => 0,
				'switchList' => array('table','schedule'),
				'flagReloadUse' => 1,
				'flagReloadNow' => 'start',
				'switchReloadList' => array('same', 'start'),
			),
			'templateDetail' => array(
				'flagBtnUse' => 1,
				'flagMoveUse' => 0,
				'id' => '0',
				'idTarget' => '0',
				'strTitle' => '',
				'flagBoldNow' => 0,
				'strClassFont' => '',
				'strClassBg' => '',
				'numSort' => 0,
				'strClass' => 'codeLibBaseImgSheet',
				'strClassLoad' => 'codeLibTableLineLoad',
				'flagCheckboxUse' => 1,
				'flagCheckboxNow' => 0,
				'varsColumnDetail' => array(
					'id' => '',
					'strTitle' => '',
					'stampRegister' => 0,
					'stampUpdate' => 0,
				),
				'varsScheduleDetail' => array(
					'flagType' => 'stamp',//stamp,term,loop
					'flagResizeUse' => 1,
					'strTitle' => '',
					'stamp' => 0,
					'term' => array(
						'stampStart' => 0,
						'stampEnd' => 0,
					),
					'loop' => array(),
				),
			),
			'varsPage' => array(
				'varsStatus' => array(
					'flagStatusUse' => 1,
					'flagLockUse' => 1,
					'flagLockNow' => 0,
					'flagTopUse' => 1,
					'flagEndUse' => 1,
					'flagNextUse' => 1,
					'flagPrevUse' => 1,
					'numRows' => 0,
					'numLotNow' => 0,
				),
			),
			'varsEdit' => array(
				'flagReloadUse' => 1,
				'flagSwitchUse' => 1,
				'flagSearchUse' => 1,
			),
			'varsDetail' => array(),
			'varsBtn' => array(
				array(
					'flagUse' => 1, 'flagLeftUse' => 0, 'flagRightUse' => 1, 'flagTextUse' => 0, 'flagBtnUse' => 1,
					'id' => 'eventBtnDelete',
					'vars' => array( 'idTarget' => 'Delete', ),
					'strTitle' => '一括削除',
				),
			),
			'table' => array(
				'varsFormat' => array(
					'id' => '',
					'flagType' => 'normalFormat',
					'numHeight' => 0,
					'numWidth' => 0,
					'flagHeaderLeftUse' => 1,
					'strTitleHeaderLeft' => '',
					'strClassHeaderLeft' => '',
					'flagHeaderRightUse' => 1,
					'strTitleHeaderRight' => '',
					'strClassHeaderRight' => 'codeLibBaseImgUnloading',
					'flagBodyAutoUse' => 0,
					'strBody' => '',
					'strClassBody' => '',
					'flagFooderUse' => 1,
					'flagFooderLeftUse' => 1,
					'strTitleFooderLeft' => '',
					'strClassFooderLeft' => '',
					'flagFooderRightUse' => 1,
					'strTitleFooderRight' => '',
					'strClassFooderRight' => '',
					'flagHeaderLeftWidth' => 1,
					'numWidthHeaderLeft' => 0,
					'flagHeaderRightWidth' => 0,
					'numWidthHeaderRight' => 0,
					'flagFooderLeftWidth' => 0,
					'numWidthFooderLeft' => 0,
					'flagFooderRightWidth' => 0,
					'numWidthFooderRight' => 0,
				),
				'varsHtml' => array(),
				'varsEdit' => array(
					'flagReloadUse' => 1,
					'flagSwitchUse' => 1,
					'flagSearchUse' => 1,
				),
				'varsDetail' => array(
					'varsStatus' => array(
						'flagMenuUse' => 1,
						'flagColumnUse' => 0,
						'flagResizeUse' => 1,
						'flagSortColumnUse' => 1,
						'flagSortColumnLineUse' => 0,
						'flagSortColumnLineNow' => '',
						'flagMoveUse' => 0,
						'flagMoveSortUse' => 0,
						'flagCakeUse' => 1,
						'flagPageUse' => 1,
						'flagInnerPageUse' => 1,
						'flagBtnBottomUse' => 1,
						'flagBtnUse' => 0,
						'flagKeyBtnUse' => 0,
						'flagBgUse' => 1,
						'flagFontUse' => 1,
						'flagBoldUse' => 0,
					),
					'varsFormat' => array(
						'id' => '',
						'flagType' => 'singleFormat',
						'numHeight' => 0,
						'numWidth' => 0,
						'flagHeaderUse' => 1,
						'flagHeaderLeftUse' => 1,
						'strTitleHeaderLeft' => '',
						'strClassHeaderLeft' => 'codeLibBaseImgBlank',
						'flagHeaderRightUse' => 0,
						'strTitleHeaderRight' => '',
						'strClassHeaderRight' => '',
						'flagBodyAutoUse' => 1,
						'strBody' => '',
						'strClassBody' => '',
						'flagFooderUse' => 1,
						'flagFooderLeftUse' => 1,
						'strTitleFooderLeft' => '',
						'strClassFooderLeft' => '',
						'flagFooderRightUse' => 1,
						'strTitleFooderRight' => '',
						'strClassFooderRight' => '',

						'flagHeaderLeftWidth' => 1,
						'numWidthHeaderLeft' => 0,
						'flagHeaderRightWidth' => 0,
						'numWidthHeaderRight' => 0,
						'flagFooderLeftWidth' => 0,
						'numWidthFooderLeft' => 0,
						'flagFooderRightWidth' => 0,
						'numWidthFooderRight' => 0,
					),
					'varsPage' => array(),
					'varsHtml' => array(),
					'varsBtn' => array(),
					'varsContext' => array(
						'varsStatus' => array(
							'numTop' => 0,
							'numLeft' => 0,
						),
						'varsDetail' => array(),
					),
					'varsColumn' => array(
						array(
							'flagUse' => 1,
							'flagCheckUse' => 0,
							'flagCheckNow' => 1,
							'id' => 'FlagCheck',
							'flagSortColumnLineUse' => 0,
							'flagSortColumnLineNow' => 0,
							'strTitle' => '',
							'numSort' => 0,
							'numWidth' => 26,
							'numWidthMin' => 26,
							'flagType' => 'checkbox',
							'flagTimeType' => '',
							'flagAllCheckbox' => 1,
							'flagAllCheckboxNow' => 0,
							'vars' => array(),
							'child' => array(),
						),
						array(
							'flagUse' => 1,
							'flagCheckUse' => 1,
							'flagCheckNow' => 1,
							'id' => 'FlagBank',
							'flagSortColumnLineUse' => 0,
							'flagSortColumnLineNow' => 0,
							'strTitle' => '金融機関',
							'numSort' => 1,
							'numWidth' => 100,
							'numWidthMin' => 26,
							'flagType' => 'str',
							'flagTimeType' => '',
							'flagAllCheckbox' => 0,
							'flagAllCheckboxNow' => 0,
							'vars' => array(),
							'child' => array(),
						),
						array(
							'flagUse' => 1,
							'flagCheckUse' => 1,
							'flagCheckNow' => 1,
							'id' => 'StrTitle',
							'flagSortColumnLineUse' => 0,
							'flagSortColumnLineNow' => 0,
							'strTitle' => '口座名',
							'numSort' => 2,
							'numWidth' => 100,
							'numWidthMin' => 26,
							'flagType' => 'str',
							'flagTimeType' => '',
							'flagAllCheckbox' => 0,
							'flagAllCheckboxNow' => 0,
							'vars' => array(),
							'child' => array(),
						),
						array(
							'flagUse' => 1,
							'flagCheckUse' => 1,
							'flagCheckNow' => 1,
							'id' => 'NumBalance',
							'flagSortColumnLineUse' => 0,
							'flagSortColumnLineNow' => 0,
							'strTitle' => '残高金額',
							'numSort' => 3,
							'numWidth' => 80,
							'numWidthMin' => 26,
							'flagType' => 'str',
							'flagTimeType' => '',
							'flagAllCheckbox' => 0,
							'flagAllCheckboxNow' => 0,
							'flagAlign' => 'right',
							'vars' => array(),
							'child' => array(),
						),
						array(
							'flagUse' => 1,
							'flagCheckUse' => 1,
							'flagCheckNow' => 1,
							'id' => 'StampCheck',
							'flagSortColumnLineUse' => 0,
							'flagSortColumnLineNow' => 0,
							'strTitle' => '最終確認取引日',
							'numSort' => 4,
							'numWidth' => 100,
							'numWidthMin' => 26,
							'flagType' => 'stamp',
							'flagTimeType' => '2',
							'flagAllCheckbox' => 0,
							'flagAllCheckboxNow' => 0,
							'vars' => array(),
							'child' => array(),
						),
						array(
							'flagUse' => 1,
							'flagCheckUse' => 1,
							'flagCheckNow' => 1,
							'id' => 'Id',
							'flagSortColumnLineUse' => 0,
							'flagSortColumnLineNow' => 0,
							'strTitle' => '通番',
							'numSort' => 5,
							'numWidth' => 50,
							'numWidthMin' => 26,
							'flagType' => 'str',
							'flagTimeType' => '',
							'flagAllCheckbox' => 0,
							'flagAllCheckboxNow' => 0,
							'vars' => array(),
							'child' => array(),
						),
					),
					'varsDetail' => array(),
				),
			),
			'schedule' => array(
				'varsFormat' => array(
					'id' => '',
					'flagType' => 'normalFormat',
					'numHeight' => 0,
					'numWidth' => 0,
					'flagHeaderLeftUse' => 1,
					'strTitleHeaderLeft' => '',
					'strClassHeaderLeft' => '',
					'flagHeaderRightUse' => 1,
					'strTitleHeaderRight' => '',
					'strClassHeaderRight' => 'codeLibBaseImgUnloading',
					'flagBodyAutoUse' => 0,
					'strBody' => '',
					'strClassBody' => '',
					'flagFooderUse' => 1,
					'flagFooderLeftUse' => 1,
					'strTitleFooderLeft' => '',
					'strClassFooderLeft' => '',
					'flagFooderRightUse' => 1,
					'strTitleFooderRight' => '',
					'strClassFooderRight' => '',
					'flagHeaderLeftWidth' => 1,
					'numWidthHeaderLeft' => 0,
					'flagHeaderRightWidth' => 0,
					'numWidthHeaderRight' => 0,
					'flagFooderLeftWidth' => 0,
					'numWidthFooderLeft' => 0,
					'flagFooderRightWidth' => 0,
					'numWidthFooderRight' => 0,
				),
				'varsEdit' => array(
					'flagReloadUse' => 1,
					'flagSwitchUse' => 1,
					'flagSearchUse' => 1,
				),
				'varsDetail' => array(
					'varsStatus' => array(
						'flagNow' => 'month',// 'month','week'
						'flagFoldUse' => 1,
						'flagBgUse' => 1,
						'flagFontUse' => 1,
						'flagBoldUse' => 0,
						'flagMoveUse' => 0,
						'flagMoveRangeUse' => 0,
						'flagResizeUse' => 0,
						'flagDateEventUse' => 0,
						'flagMaxUse' => 0,
						'flagMaxAutoUse' => 0,
						'stampMax' => 0,
						'flagMainUse' => 1,
						'flagMainAutoUse' => 1,
						'stampMain' => 0,
						'flagMinUse' => 0,
						'flagMinAutoUse' => 0,
						'stampMin' => 0,
						'flagBtnBottomUse' => 0,
						'flagPageUse' => 1,
						'flagInnerPageUse' => 1,
					),
					'varsFormat' => array(
						'id' => '',
						'flagType' => 'scheduleFormat',
						'numHeight' => 0,
						'numWidth' => 0,
						'flagFooderUse' => 1,
					),
					'varsBtn' => array(),
					'varsPage' => array(),
					'varsDetail' => array(),
					'month' => array(
						'varsFold' => array(
							array( 'flagFoldNow' => 1,),array( 'flagFoldNow' => 1,),array( 'flagFoldNow' => 1,),array( 'flagFoldNow' => 1,),array( 'flagFoldNow' => 1,),array( 'flagFoldNow' => 1,),
						),
					),
					'week' => array(
						'varsFold' => array(
							array( 'flagFoldNow' => 1,),array( 'flagFoldNow' => 1,),array( 'flagFoldNow' => 1,),array( 'flagFoldNow' => 1,),array( 'flagFoldNow' => 1,),array( 'flagFoldNow' => 1,),array( 'flagFoldNow' => 1,),
						),
					),
				),
			),
			'thumbnail' => array(),
			'tree' => array(),
		),
		'varsDetail' => array(
			'varsStatus' => array(
				'flagUse' => 1,
				'flagNow' => 'view',
				'flagCakeUse' => 1,
				'flagFoldUse' => 1,
				'flagViewUse' => 1,
				'flagFormUse' => 0,
				'flagMoveUse' => 0,
				'switchList' => array('view'),
			),
			'templateDetail' => array(
				array(
					'flagMustUse' => 0,
					'id' => 'DummyInfo',
					'strTitle' => 'お知らせ', 'strExplain' => '', 'value' => '',
					'flagErrorNow' => 0,
					'arrayError' => array(),
					'flagContentUse' => 0,
					'flagCommentUse' => 0, 'strCommentTitle' => '', 'strComment' => '',
					'flagTag' => 'input', 'flagInputType' => 'text', 'numMaxlength' => 100,
					'numWidth' => 90, 'unitWidth' => '%', 'numHeight' => 0, 'unitHeight' => '',
					'arrayOption' => array(),
					'flagFoldUse' => 1, 'flagFoldNow' => 0,
					'varsTmpl' => array(
						'strAttest' => '『 WEB明細インポート停止中 』<br>金融機関側のアクセス制限設定か、エディタで設定された認証が間違っていたため、情報が取得できなかったようです。再度、実際の金融機関で認証が正しくできるかどうかも含め設定が正しいかどうか確認する必要があるようです。',
						'strWord' => '『 WEB明細インポート停止中 』<br>未知の質問があったため合言葉を設定されるまでロックされているようです。未知の質問に対する合言葉を設定してください。',
						'strService' => '『 WEB明細インポート停止中 』<br>オフィシャルサイトでWEB明細をインポートするために必要な手続を経ていないようです。',
						'strAll' => '『 WEB明細インポート停止中 』<br>基本メニューの設定によってすべての金融機関のWEB明細インポートを停止しています。',
					),
				),
				array(
					'flagMustUse' => 1,
					'id' => 'FlagBank',
					'strTitle' => '金融機関' , 'strExplain' => '金融機関の選択を行ってください。' ,
					'value' => '',
					'flagErrorNow' => 0,
					'arrayError' => array(
						array( 'flagCheck' => 'blank', 'flagUse' => 1, 'flagNow' => 0, 'flagType' => 'empty', 'strComment' => array( 'common' => '選択漏れがあるようです。',  ),),
					),
					'flagContentUse' => 0,
					'flagCommentUse' => 0, 'strCommentTitle' => '', 'strComment' => '',
					'flagTag' => 'selectShortCut', 'flagInputType' => '', 'numMaxlength' => 0,
					'numWidth' => 90, 'unitWidth' => '%', 'numHeight' => 0, 'unitHeight' => '',
					'arrayOption' => array(),
					'varsFormTemp' => array(
						'varsStatus' => array(
							'numLeft' => 0,
							'numTop' => 0,
						),
						'varsDetail' => array(
							'flagTag'       => '',
							'flagInputType' => '',
							'numMaxlength'  => 100,
							'numWidth'      => 0,
							'unitWidth'     => 'px',
							'numHeight'     => 0,
							'unitHeight'    => 'px',
							'arrayOption'   => array(),
							'value'         => '',
							'vars'          => array(),
						),
					),
					'flagFoldUse' => 0, 'flagFoldNow' => 0,
				),
				array(
					'flagMustUse' => 0,
					'id' => 'DummyFlagBank',
					'strTitle' => '金融機関',
					'strExplain' => '',
					'value' => '',
					'flagErrorNow' => 0,
					'arrayError' => array(
						array( 'flagCheck' => 'blank', 'flagUse' => 1, 'flagNow' => 0, 'flagType' => 'empty', 'strComment' => array( 'common' => '記入漏れがあるようです。', ),),
					),
					'flagContentUse' => 0,
					'flagCommentUse' => 0, 'strCommentTitle' => '', 'strComment' => '',
					'flagTag' => 'input', 'flagInputType' => 'text', 'numMaxlength' => 100,
					'numWidth' => 90, 'unitWidth' => '%', 'numHeight' => 0, 'unitHeight' => '',
					'arrayOption' => array(),
					'flagFoldUse' => 1, 'flagFoldNow' => 0,
					'flagDisabled' => 0,
					'varsTextBtn' => array(),
				),
				array(
					'flagMustUse' => 1,
					'id' => 'StrTitle',
					'strTitle' => '口座名', 'strExplain' => '口座名を記入してください。', 'value' => '',
					'flagErrorNow' => 0,
					'arrayError' => array(
						array( 'flagCheck' => 'blank', 'flagUse' => 1, 'flagNow' => 0, 'flagType' => 'empty', 'strComment' => array( 'common' => '記入が必要なようです。', ),),
						array( 'flagCheck' => 'max', 'flagUse' => 1, 'flagNow' => 0, 'flagType' => 'str', 'num' => 100, 'strComment' => array( 'common' => '入力文字数が多すぎるようです。', ),),
						array( 'flagCheck' => 'attest', 'flagUse' => 1, 'strComment' => array(
							'strTitle' => '既に同じ口座名が使用されているようです。',
						),),
					),
					'flagContentUse' => 0,
					'flagCommentUse' => 0, 'strCommentTitle' => '', 'strComment' => '',
					'flagTag' => 'input', 'flagInputType' => 'text', 'numMaxlength' => 100,
					'numWidth' => 90, 'unitWidth' => '%', 'numHeight' => 0, 'unitHeight' => '',
					'arrayOption' => array(),
					'flagFoldUse' => 1, 'flagFoldNow' => 0,
					'varsTextBtn' => array(),
				),
				array(
					'flagMustUse' => 0,
					'id' => 'DummyNumBalance',
					'strTitle' => '残高金額(単位：円)', 'strExplain' => '', 'value' => '',
					'flagErrorNow' => 0,
					'arrayError' => array(),
					'flagContentUse' => 0,
					'flagCommentUse' => 0, 'strCommentTitle' => '', 'strComment' => '',
					'flagTag' => '', 'flagInputType' => '', 'numMaxlength' => 0,
					'numWidth' => 0, 'unitWidth' => '', 'numHeight' => 0, 'unitHeight' => '',
					'arrayOption' => array(),
					'flagFoldUse' => 1, 'flagFoldNow' => 0,
				),
				array(
					'flagMustUse' => 0,
					'id' => 'DummyJsonDetail',
					'strTitle' => 'ログイン認証', 'strExplain' => '', 'value' => 'エディタで確認できます。',
					'flagErrorNow' => 0,
					'arrayError' => array(),
					'flagContentUse' => 0,
					'flagCommentUse' => 0, 'strCommentTitle' => '', 'strComment' => '',
					'flagTag' => '', 'flagInputType' => '', 'numMaxlength' => 0,
					'numWidth' => 0, 'unitWidth' => '', 'numHeight' => 0, 'unitHeight' => '',
					'arrayOption' => array(),
					'flagFoldUse' => 1, 'flagFoldNow' => 0,
				),
				array(
					'flagMustUse' => 0,
					'id' => 'JsonDetail',
					'strTitle' => 'ログイン認証', 'strExplain' => 'WEB明細を自動取得したい場合は設定してください。', 'value' => 'dummy',
					'flagErrorNow' => 0,
					'arrayError' => array(
						array( 'flagCheck' => 'blank', 'flagUse' => 1, 'flagNow' => 0, 'flagType' => 'empty', 'strComment' => array( 'common' => '記入が必要なようです。', ),),
						array( 'flagCheck' => 'attest', 'flagUse' => 1, 'strComment' => array(
							'flagErrorComment' => 'dummy',
							'sign' => '合言葉に必要な認証の設定が必要なようです。',
							'serviceAdmin' => 'WEB明細の自動取得に必要なアクセスコードの設定が済んでいないようです。',
							'serviceUser' => '管理者がWEB明細の自動取得に必要なアクセスコードの設定が済んでいないようです。',
							'strBlank' => '入力漏れがあるようです。',
						),),
					),
					'flagContentUse' => 1,
					'flagCommentUse' => 0, 'strCommentTitle' => '', 'strComment' => '',
					'flagTag' => 'input', 'flagInputType' => 'text', 'numMaxlength' => 0,
					'numWidth' => 90, 'unitWidth' => '%', 'numHeight' => 0, 'unitHeight' => '',
					'arrayOption' => array(),
					'flagFoldUse' => 1, 'flagFoldNow' => 0,
					'flagHideUse' => 1, 'flaHideNow' => 0,
					'varsFormSensitive' => array(
						'varsStatus' => array(
							'id' => 'Sensitive',
							'numLeft' => 0,
							'numTop' => 0,
						),
						'varsHtml' => array(),
						'tmplHtml' => array(),
						'varsDetail' => array(),
						'varsTmpl' => array(
							'varsDetail' => array(),
							'varsFormTemp' => array(
								'varsStatus' => array(
									'numLeft' => 0,
									'numTop' => 0,
								),
								'varsDetail' => array(
									'flagTag'       => '',
									'flagInputType' => '',
									'numMaxlength'  => 9,
									'numWidth'      => 0,
									'unitWidth'     => 'px',
									'numHeight'     => 0,
									'unitHeight'    => 'px',
									'arrayOption'   => array(),
									'value'         => '',
									'vars'          => array(),
								),
							),
						),
					),
				),
				array(
					'flagMustUse' => 0,
					'id' => 'StampCheck',
					'strTitle' => '最終確認取引日', 'strExplain' => '最終確認取引日を変更することでインポート対象を操作することができます。<br>　※ 設定例) <%stampMin%><br>　※ 半角英数で記入してください。', 'value' => '',
					'flagErrorNow' => 0,
					'arrayError' => array(
						array( 'flagCheck' => 'blank', 'flagUse' => 1, 'flagNow' => 0, 'flagType' => 'empty', 'strComment' => array( 'common' => '記入が必要なようです。', ),),
						array( 'flagCheck' => 'format', 'flagUse' => 1, 'flagNow' => 0, 'flagArr' => 0, 'flagType' => 'year-date', 'strComment' => array( 'common' => '指定されたフォーマットに沿って記入されていないようです。',  ), ),
					),
					'flagContentUse' => 0,
					'flagCommentUse' => 0, 'strCommentTitle' => '', 'strComment' => '',
					'flagTag' => 'input', 'flagInputType' => 'text', 'numMaxlength' => 10,
					'numWidth' => 90, 'unitWidth' => '%', 'numHeight' => 0, 'unitHeight' => '',
					'arrayOption' => array(),
					'flagFoldUse' => 1, 'flagFoldNow' => 0,
					'varsFormCalender' => array(
						'varsStatus' => array(
							'numLeft' => 0,
							'numTop' => 0,
							'flagMaxUse' => 1,
							'flagMaxAutoUse' => 0,
							'stampMax' => 0,
							'flagMainUse' => 1,
							'flagMainAutoUse' => 1,
							'stampMain' => 0,
							'flagMinUse' => 1,
							'flagMinAutoUse' => 0,
							'stampMin' => 0,
							'stampPoint' => 0,
							'flagFormatDisplay' => 4,
							'flagFormatCheck' => 'year-date',
						),
					),
					'varsTextBtn' => array(),
				),
				array(
					'flagMustUse' => 0,
					'id' => 'ArrSpaceStrTag',
					'strTitle' => 'タグ', 'strExplain' => '必要なタグを空白区切りで設定してください。', 'value' => '',
					'flagErrorNow' => 0,
					'arrayError' => array(
						array( 'flagCheck' => 'blank', 'flagUse' => 1, 'flagNow' => 0, 'flagType' => 'empty', 'strComment' => array( 'common' => '記入が必要なようです。', ),),
						array(	'flagCheck' => 'max', 'flagUse' => 1, 'flagNow' => 0, 'flagType' => 'str', 'num' => 1000, 'strComment' => array( 'common' => '入力文字数が多すぎるようです。', ),),
					),
					'flagContentUse' => 0,
					'flagCommentUse' => 0, 'strCommentTitle' => '', 'strComment' => '',
					'flagTag' => 'input', 'flagInputType' => 'text', 'numMaxlength' => 1000,
					'numWidth' => 90, 'unitWidth' => '%', 'numHeight' => 0, 'unitHeight' => '',
					'arrayOption' => array(),
					'flagFoldUse' => 1, 'flagFoldNow' => 0,
					'varsTextBtn' => array(),
				),
				array(
					'flagMustUse' => 0,
					'id' => 'StampRegister',
					'strTitle' => '記録日時', 'strExplain' => '', 'value' => '',
					'flagErrorNow' => 0,
					'arrayError' => array(),
					'flagContentUse' => 0,
					'flagCommentUse' => 1, 'strCommentTitle' => '', 'strComment' => '',
					'flagTag' => '', 'flagInputType' => '', 'numMaxlength' => 0,
					'numWidth' => 0, 'unitWidth' => '', 'numHeight' => 0, 'unitHeight' => '',
					'arrayOption' => array(),
					'flagFoldUse' => 1, 'flagFoldNow' => 0,
				),
				array(
					'flagMustUse' => 0,
					'id' => 'StampUpdate',
					'strTitle' => '更新日時', 'strExplain' => '', 'value' => '',
					'flagErrorNow' => 0,
					'arrayError' => array(),
					'flagContentUse' => 0,
					'flagCommentUse' => 1, 'strCommentTitle' => '', 'strComment' => '',
					'flagTag' => '', 'flagInputType' => '', 'numMaxlength' => 0,
					'numWidth' => 0, 'unitWidth' => '', 'numHeight' => 0, 'unitHeight' => '',
					'arrayOption' => array(),
					'flagFoldUse' => 1, 'flagFoldNow' => 0,
				),
				array(
					'flagMustUse' => 0,
					'id' => 'Id',
					'strTitle' => '通番', 'strExplain' => '', 'value' => '',
					'flagErrorNow' => 0,
					'arrayError' => array(),
					'flagContentUse' => 0,
					'flagCommentUse' => 1, 'strCommentTitle' => '', 'strComment' => '',
					'flagTag' => '', 'flagInputType' => '', 'numMaxlength' => 0,
					'numWidth' => 0, 'unitWidth' => '', 'numHeight' => 0, 'unitHeight' => '',
					'arrayOption' => array(),
					'flagFoldUse' => 1, 'flagFoldNow' => 0,
					'varsTextBtn' => array(),
				),
			),
			'varsPage' => array(),
			'varsDetail' => array(),
			'varsBtn' => array(
				array(
					'flagUse' => 0, 'flagLeftUse' => 0, 'flagRightUse' => 1, 'flagTextUse' => 0, 'flagBtnUse' => 1,
					'id' => 'BtnDelete',
					'vars' => array( 'idTarget' => 'delete', ),
					'strTitle' => '削除',
				),
			),
			'varsStart' => array(
				'strTitle' => '詳細',
				'strClass' => 'codeLibBaseImgSheet',
				'varsEdit' => array(
					'flagAddUse' => 1,
				),
			),
			'view' => array(
				'varsFormat' => array(
					'id' => '',
					'flagType' => 'normalFormat',
					'numHeight' => 0,
					'numWidth' => 0,
					'flagHeaderLeftUse' => 1,
					'strTitleHeaderLeft' => '詳細',
					'strClassHeaderLeft' => '',
					'flagHeaderRightUse' => 1,
					'strTitleHeaderRight' => '',
					'strClassHeaderRight' => 'codeLibBaseImgUnloading',
					'flagBodyAutoUse' => 0,
					'strBody' => '',
					'strClassBody' => '',
					'flagFooderUse' => 1,
					'flagFooderLeftUse' => 1,
					'strTitleFooderLeft' => '',
					'strClassFooderLeft' => '',
					'flagFooderRightUse' => 1,
					'strTitleFooderRight' => '',
					'strClassFooderRight' => '',
					'flagHeaderLeftWidth' => 1,
					'numWidthHeaderLeft' => 0,
					'flagHeaderRightWidth' => 0,
					'numWidthHeaderRight' => 0,
					'flagFooderLeftWidth' => 0,
					'numWidthFooderLeft' => 0,
					'flagFooderRightWidth' => 0,
					'numWidthFooderRight' => 0,
				),
				'varsEdit' => array(
					'flagReloadUse' => 1,
					'flagAddUse' => 1,
					'flagCopyUse' => 1,
					'flagEditUse' => 1,
				),
				'varsDetail' => array(
					'varsStatus' => array(
						'flagCakeUse' => 1,
						'flagFoldUse' => 1,
						'flagFoldNow' => 0,
						'flagLineStatusUse' => 0,
						'flagAddUse' => 0,
						'flagRemoveUse' => 0,
						'flagEditUse' => 0,
						'flagBarUse' => 1,
						'flagPageUse' => 0,
						'flagInnerPageUse' => 0,
						'flagBtnBottomUse' => 1,
						'flagFindUse' => 0,
						'flagInnerFindUse' => 0,
					),
					'varsFormat' => array(
						'id' => '',
						'flagType' => 'singleFormat',
						'numHeight' => 0,
						'numWidth' => 0,
						'flagHeaderUse' => 1,
						'flagHeaderLeftUse' => 1,
						'strTitleHeaderLeft' => '',
						'strClassHeaderLeft' => '',
						'flagHeaderRightUse' => 0,
						'strTitleHeaderRight' => '',
						'strClassHeaderRight' => '',
						'flagBodyAutoUse' => 1,
						'strBody' => '',
						'strClassBody' => '',
						'flagFooderUse' => 0,
						'flagFooderLeftUse' => 1,
						'strTitleFooderLeft' => '',
						'strClassFooderLeft' => '',
						'flagFooderRightUse' => 1,
						'strTitleFooderRight' => '',
						'strClassFooderRight' => '',

						'flagHeaderLeftWidth' => 0,
						'numWidthHeaderLeft' => 0,
						'flagHeaderRightWidth' => 0,
						'numWidthHeaderRight' => 0,
						'flagFooderLeftWidth' => 0,
						'numWidthFooderLeft' => 0,
						'flagFooderRightWidth' => 0,
						'numWidthFooderRight' => 0,
					),
					'varsFind' => array(
						'strTitle' => 'ハイライト検索',
						'numWidth' => 70,//%
					),
					'varsPage' => array(),
					'varsBtn' => array(),
					'varsDetail' => array(),
				),
			),
			'form' => array(),
		),
		'varsTemplateLayout' => array(
			'varsStatus' => array(
				'flagNaviUse' => 0,
				'flagNaviToolUse' => 0,
				'flagListUse' => 1,
				'flagListToolUse' => 1,
				'flagDetailUse' => 1,
				'flagDetailToolUse' => 1,
			),
			'varsLayout' => array(
				'varsStatus' => array(
					'flagNow' => 2,
					'flagResizeUse' => 1,
					'flagMoveUse' => 1,
					'flagCakeUse' => 1,
					'flagSwitchUse' => 1,
					'flagSwitchNow' => 'Standard',
					'switchList' => array('Standard','Wide'),
				),
				'varsDetail' => array(
					array(
						'id' => 'List',
						'flagBoxUse' => 1,
						'numPriority' => 2,
						'numSort' => 1,
						'numWidth' => 300,			'numHeight' => 200,
						'numWidthMin' => 200,		'numHeightMin' => 200,
						'numWidthStandard' => 300,	'numHeightStandard' => 200,
						'numWidthWide' => 300,		'numHeightWide' => 300,
						'numWidthClassic' => 300,	'numHeightClassic' => 300,
						'numHeightBox' => 0,		'numWidthBox' => 0,//auto
					),
					array(
						'id' => 'Detail',
						'flagBoxUse' => 1,
						'numPriority' => 1,
						'numSort' => 2,
						'numWidth' => 300,			'numHeight' => 300,
						'numWidthMin' => 300,		'numHeightMin' => 300,
						'numWidthStandard' => 300,	'numHeightStandard' => 300,
						'numWidthWide' => 300,		'numHeightWide' => 300,
						'numWidthClassic' => 300,	'numHeightClassic' => 300,
						'numHeightBox' => 0,		'numWidthBox' => 0,//auto
					),
				),
			),
			'navi' => array(),
			'list' => array(
				'varsFormat' => array(
					'id' => '',
					'flagType' => 'normalFormat',
					'numHeight' => 0,
					'numWidth' => 0,
					'flagHeaderLeftUse' => 1,
					'strTitleHeaderLeft' => '',
					'strClassHeaderLeft' => 'codeLibBaseImgBlank',
					'flagHeaderRightUse' => 1,
					'strTitleHeaderRight' => '',
					'strClassHeaderRight' => 'codeLibBaseImgUnloading',
					'flagBodyAutoUse' => 1,
					'strBody' => '',
					'strClassBody' => '',
					'flagFooderUse' => 1,
					'flagFooderLeftUse' => 1,
					'strTitleFooderLeft' => '',
					'strClassFooderLeft' => '',
					'flagFooderRightUse' => 1,
					'strTitleFooderRight' => '',
					'strClassFooderRight' => '',
					'flagHeaderLeftWidth' => 1,
					'numWidthHeaderLeft' => 0,
					'flagHeaderRightWidth' => 0,
					'numWidthHeaderRight' => 0,
					'flagFooderLeftWidth' => 0,
					'numWidthFooderLeft' => 0,
					'flagFooderRightWidth' => 1,
					'numWidthFooderRight' => 0,
				),
				'varsTool' => array(
					'varsDetail' => array(
						array(
							'flagUse' => 1,
							'flagNow' => 1,
							'id' => 'Reload',
							'strClass' => 'codeLibBtnImgReload',
							'strClassOver' => 'codeLibBtnImgReloadOver',
							'strClassNoactive' => 'codeLibBtnImgReloadNoactive',
							'strTitle' => '更新',
							'varsContext' => array(
								'varsStatus' => array(
									'numTop' => 0,
									'numLeft' => 0,
									'flagNow' => 'start',
								),
								'varsDetail' => array(
									array(
										'id' => 'Start', 'flagCheckUse' => 1, 'flagCheckNow' => 0,
										'strTitle' => '条件初期化', 'strClass' => 'codeLibBaseImgSheet',
										'vars' => array( 'idTarget' => 'start',),
										'child' => array(),
									),
									array(
										'id' => 'Same', 'flagCheckUse' => 1, 'flagCheckNow' => 0,
										'strTitle' => 'データ更新', 'strClass' => 'codeLibBaseImgSheet',
										'vars' => array( 'idTarget' => 'same',),
										'child' => array(),
									),
								),
							),
						),
						array(
							'flagUse' => 1,
							'flagNow' => 1,
							'id' => 'Switch',
							'strClass' => 'codeLibBtnImgSwitch',
							'strClassOver' => 'codeLibBtnImgSwitchOver',
							'strClassNoactive' => 'codeLibBtnImgSwitchNoactive',
							'strTitle' => '表示切替',
							'varsContext' => array(
								'varsStatus' => array(
									'numTop' => 0,
									'numLeft' => 0,
									'flagNow' => 'table',
								),
								'varsDetail' => array(
									array(
										'id' => 'Table', 'flagCheckUse' => 1, 'flagCheckNow' => 0,
										'strTitle' => 'テーブル形式', 'strClass' => 'codeLibBaseImgSheet',
										'vars' => array( 'idTarget' => 'table',),
										'child' => array(),
									),
									array(
										'id' => 'Schedule', 'flagCheckUse' => 1, 'flagCheckNow' => 0,
										'strTitle' => 'カレンダー形式', 'strClass' => 'codeLibBaseImgSheet',
										'vars' => array( 'idTarget' => 'schedule',),
										'child' => array(),
									),
								),
							),
						),
						array(
							'flagUse' => 1, 'flagNow' => 0,
							'id' => 'Search',
							'strClass' => 'codeLibBtnImgSearch',
							'strClassOver' => 'codeLibBtnImgSearchOver',
							'strClassNoactive' => 'codeLibBtnImgSearchNoactive',
							'strTitle' => '詳細検索',
						),
					),
				),
			),
			'detail' => array(
				'varsFormat' => array(
					'id' => '',
					'flagType' => 'normalFormat',
					'numHeight' => 0,
					'numWidth' => 0,
					'flagHeaderLeftUse' => 1,
					'strTitleHeaderLeft' => '',
					'strClassHeaderLeft' => '',
					'flagHeaderRightUse' => 1,
					'strTitleHeaderRight' => '',
					'strClassHeaderRight' => 'codeLibBaseImgUnloading',
					'flagBodyAutoUse' => 1,
					'strBody' => '',
					'strClassBody' => '',
					'flagFooderUse' => 1,
					'flagFooderLeftUse' => 1,
					'strTitleFooderLeft' => '',
					'strClassFooderLeft' => '',
					'flagFooderRightUse' => 1,
					'strTitleFooderRight' => '',
					'strClassFooderRight' => '',
					'flagHeaderLeftWidth' => 1,
					'numWidthHeaderLeft' => 0,
					'flagHeaderRightWidth' => 0,
					'numWidthHeaderRight' => 0,
					'flagFooderLeftWidth' => 0,
					'numWidthFooderLeft' => 0,
					'flagFooderRightWidth' => 1,
					'numWidthFooderRight' => 0,
				),
				'varsTool' => array(
					'varsDetail' => array(
						array(
							'flagUse' => 1, 'flagNow' => 0,
							'id' => 'Reload',
							'strClass' => 'codeLibBtnImgReload',
							'strClassOver' => 'codeLibBtnImgReloadOver',
							'strClassNoactive' => 'codeLibBtnImgReloadNoactive',
							'strTitle' => '更新',
						),
						array(
							'flagUse' => 1, 'flagNow' => 0,
							'id' => 'Add',
							'strClass' => 'codeLibBtnImgAdd',
							'strClassOver' => 'codeLibBtnImgAddOver',
							'strClassNoactive' => 'codeLibBtnImgAddNoactive',
							'strTitle' => '新規',
						),
						array(
							'flagUse' => 1, 'flagNow' => 0,
							'id' => 'Copy',
							'strClass' => 'codeLibBtnImgCopy',
							'strClassOver' => 'codeLibBtnImgCopyOver',
							'strClassNoactive' => 'codeLibBtnImgCopyNoactive',
							'strTitle' => 'コピー',
						),
						array(
							'flagUse' => 1, 'flagNow' => 0,
							'id' => 'Edit',
							'strClass' => 'codeLibBtnImgEdit',
							'strClassOver' => 'codeLibBtnImgEditOver',
							'strClassNoactive' => 'codeLibBtnImgEditNoactive',
							'strTitle' => '修正',
						),
					),
				),
			),
		),
	),
	'child' => array(
		'varsTitle' => array(
			'editor' => 'エディタ',
			'Search' => '詳細検索',
		),
		'templateWindow' => array(
			'id' => '',
			'strTitle' => '<%child%> - <%parent%>',
			'strClass' => 'codePluginAccountingImgIcon',
			'flagLockUse' => 0,
			'flagLockNow' => '',
			'flagCakeUse' => 1,
			'flagRemoveUse' => 0,
			'flagCoverUse' => 1,
			'flagHideUse' => 1,
			'flagHideNow' => 0,
			'flagReloadUse' => 0,
			'flagFoldUse' => 1,
			'flagFoldNow' => 0,
			'flagMoveUse' => 1,
			'flagZIndexUse' => 0,
			'flagResizeUse' => 1,
			'flagResizeIni' => 'all',
			'flagResizeNow' => 'all',
			'flagSkeletonUse' => 0,
			'flagBootUse' => 'auto',
			'flagSwitchUse' => 1,
			'flagMenuUse' => 1,
			'flagMenuShowUse' => 0,
			'numWidthTitle' => 0,
			'numLeft' => 50,
			'numTop' => 50,
			'numWidth' => 800,
			'numHeight' => 600,//180 285
			'numWidthMin' => 800,
			'numHeightMin' => 600,
			'numZIndex' => 0
		),
		'editor' => array(
			'id' => '',
			'strTitle' => '<%child%> - <%parent%>',
			'strClass' => 'codePluginAccountingImgIcon',
			'flagLockUse' => 0,
			'flagLockNow' => '',
			'flagCakeUse' => 1,
			'flagRemoveUse' => 0,
			'flagCoverUse' => 1,
			'flagHideUse' => 1,
			'flagHideNow' => 0,
			'flagReloadUse' => 0,
			'flagFoldUse' => 1,
			'flagFoldNow' => 0,
			'flagMoveUse' => 1,
			'flagZIndexUse' => 0,
			'flagResizeUse' => 1,
			'flagResizeIni' => 'all',
			'flagResizeNow' => 'all',
			'flagSkeletonUse' => 0,
			'flagBootUse' => 'auto',
			'flagSwitchUse' => 0,
			'flagMenuUse' => 1,
			'flagMenuShowUse' => 0,
			'numWidthTitle' => 0,
			'numLeft' => 50,
			'numTop' => 50,
			'numWidth' => 500,
			'numHeight' => 500,//180 285
			'numWidthMin' => 275,
			'numHeightMin' => 500,
			'numZIndex' => 0
		),
		'search' => array(
			'id' => '',
			'strTitle' => '<%child%> - <%parent%>',
			'strClass' => 'codePluginAccountingImgIcon',
			'flagLockUse' => 0,
			'flagLockNow' => '',
			'flagCakeUse' => 1,
			'flagRemoveUse' => 0,
			'flagCoverUse' => 1,
			'flagHideUse' => 1,
			'flagHideNow' => 0,
			'flagReloadUse' => 0,
			'flagFoldUse' => 1,
			'flagFoldNow' => 0,
			'flagMoveUse' => 1,
			'flagZIndexUse' => 0,
			'flagResizeUse' => 1,
			'flagResizeIni' => 'all',
			'flagResizeNow' => 'all',
			'flagSkeletonUse' => 0,
			'flagBootUse' => 'auto',
			'flagSwitchUse' => 0,
			'flagMenuUse' => 1,
			'flagMenuShowUse' => 0,
			'numWidthTitle' => 0,
			'numLeft' => 50,
			'numTop' => 50,
			'numWidth' => 500,
			'numHeight' => 450,//180 285
			'numWidthMin' => 275,
			'numHeightMin' => 400,
			'numZIndex' => 0
		),
	),
);


