<?php

$vars = array(
	'varsRule'  => array(),
	'varsCheck'  => array(),
	'varsItem'  => array(
		'strEscape' => '、',
		'varsId' => array(
			'id' => '識別番号',
			'stampBook' => '取引日時',
			'flagFiscalReport' => '決算整理仕訳',
			'strTitle' => '摘要',
			'idAccountTitleDebit' => '借方勘定科目',
			'flagFSDebit' => '借方F/S',
			'numValueDebit' => '借方金額',
			'idSubAccountTitleDebit' => '借方補助科目',
			'idDepartmentDebit' => '借方部門',
			'flagConsumptionTaxDebit' => '借方消費税区分',
			'flagConsumptionTaxWithoutCalcDebit' => '借方消費税入力方法',
			'numValueConsumptionTaxDebit' => '借方消費税金額',
			'idAccountTitleCredit' => '貸方勘定科目',
			'flagFSCredit' => '貸方F/S',
			'numValueCredit' => '貸方金額',
			'idSubAccountTitleCredit' => '貸方補助科目',
			'idDepartmentCredit' => '貸方部門',
			'flagConsumptionTaxCredit' => '貸方消費税区分',
			'flagConsumptionTaxWithoutCalcCredit' => '貸方消費税入力方法',
			'numValueConsumptionTaxCredit' => '貸方消費税金額',
			'idAccount' => '担当者',
			'arrSpaceStrTag' => 'タグ',
		),
		'varsDetail' => array(
			'id' => '',
			'arrDebit' => array(
				'idAccountTitle' => '',
				'numValue' => '',
				'numValueConsumptionTax' => '',
				'idDepartment' => '',
				'idSubAccountTitle' => '',
				'flagConsumptionTaxFree' => '',
				'flagConsumptionTaxIncluding' => '',
				'flagConsumptionTaxGeneralRuleEach' => '',
				'flagConsumptionTaxGeneralRuleProration' => '',
				'flagConsumptionTaxSimpleRule' => '',
				'flagConsumptionTaxWithoutCalc' => '',
				'flagConsumptionTaxCalc' => '',
			),
			'arrCredit' => array(
				'idAccountTitle' => '',
				'numValue' => '',
				'numValueConsumptionTax' => '',
				'idDepartment' => '',
				'idSubAccountTitle' => '',
				'flagConsumptionTaxFree' => '',
				'flagConsumptionTaxIncluding' => '',
				'flagConsumptionTaxGeneralRuleEach' => '',
				'flagConsumptionTaxGeneralRuleProration' => '',
				'flagConsumptionTaxSimpleRule' => '',
				'flagConsumptionTaxWithoutCalc' => '',
				'flagConsumptionTaxCalc' => '',
			),
		),
		'varsMenu' => array(
			'strList' => '外部仕訳エクスポート',
		),
	),
	'pathCss' => '',
	'portal' => array(
		'varsNavi' => array(
			'varsStatus' => array(
				'flagNow' => 'form',
				'flagCakeUse' => 0,
				'flagViewUse' => 0,
				'flagFormUse' => 1,
				'switchList' => array('form'),
			),
			'templateDetail' => array(
				array(
						'flagMustUse' => 1,
						'id' => 'NumLotNow',
						'strTitle' => '',
						'strExplain' => '',
						'value' => 'utf8',
						'flagErrorNow' => 0,
						'arrayError' => array(
								array( 'flagCheck' => 'blank', 'flagUse' => 1, 'flagNow' => 0, 'flagType' => 'empty', 'strComment' => array( 'common' => '記入漏れがあるようです。', ),),
						),
						'flagContentUse' => 0,
						'flagCommentUse' => 1, 'strCommentTitle' => '確定済の仕訳のみエクスポートすることができます。', 'strComment' => '',
						'flagTag' => 'select', 'flagInputType' => '', 'numMaxlength' => 0,
						'numWidth' => 80, 'unitWidth' => '%', 'numHeight' => 0, 'unitHeight' => '',
						'arrayOption' => array(),
				),
			),
			'varsPage' => array(),
			'varsDetail' => array(),
			'varsBtn' => array(
				array(
					'flagUse' => 1, 'flagLeftUse' => 0, 'flagRightUse' => 1, 'flagTextUse' => 0, 'flagBtnUse' => 1,
					'id' => 'EventFormBtn',
					'vars' => array( 'idTarget' => 'output', ),
					'strTitle' => 'エクスポート',
				),
			),
			'varsStart' => array(
				'strTitle' => '外部仕訳エクスポート',
				'strClass' => 'codeLibBaseImgDb',
				'varsEdit' => array( 'flagReloadUse' => 0, ),
			),
			'view' => array(),
			'form' => array(
				'varsFormat' => array(
					'id' => '',
					'flagType' => 'normalFormat',
					'numHeight' => 0,
					'numWidth' => 0,
					'flagHeaderLeftUse' => 1,
					'strTitleHeaderLeft' => '',
					'strClassHeaderLeft' => 'codeLibBaseImgDb',
					'flagHeaderRightUse' => 1,
					'strTitleHeaderRight' => '',
					'strClassHeaderRight' => 'codeLibBaseImgUnloading',
					'flagBodyAutoUse' => 1,
					'strBody' => '',
					'strClassBody' => '',
					'flagFooderUse' => 1,
					'flagFooderLeftUse' => 1,
					'strTitleFooderLeft' => '',
					'strClassFooderLeft' => '',
					'flagFooderRightUse' => 1,
					'strTitleFooderRight' => '',
					'strClassFooderRight' => '',
					'flagHeaderLeftWidth' => 1,
					'numWidthHeaderLeft' => 0,
					'flagHeaderRightWidth' => 0,
					'numWidthHeaderRight' => 0,
					'flagFooderLeftWidth' => 0,
					'numWidthFooderLeft' => 0,
					'flagFooderRightWidth' => 0,
					'numWidthFooderRight' => 0,
				),
				'varsEdit' => array( 'flagReloadUse' => 0, ),
				'varsDetail' => array(
					'varsStatus' => array(
						'flagBtnBottomUse' => 1,
					),
					'varsBtn' => array(),
					'varsDetail' => array(),
				),
			),
		),
		'varsList' => array(),
		'varsDetail' => array(),
		'varsTemplateLayout' => array(
			'varsStatus' => array(
				'flagNaviUse' => 1,
				'flagNaviToolUse' => 1,
				'flagListUse' => 0,
				'flagListToolUse' => 0,
				'flagDetailUse' => 0,
				'flagDetailToolUse' => 0,
			),
			'varsLayout' => array(
				'varsStatus' => array(
					'flagNow' => 1,
					'flagResizeUse' => 1,
					'flagMoveUse' => 1,
					'flagCakeUse' => 1,
					'flagSwitchUse' => 1,
					'flagSwitchNow' => 'Standard',
					'switchList' => array('Standard'),
				),
				'varsDetail' => array(
					array(
						'id' => 'Navi',
						'flagBoxUse' => 1,
						'numPriority' => 0,
						'numSort' => 0,
						'numWidth' => 250,			'numHeight' => 200,
						'numWidthMin' => 200,		'numHeightMin' => 200,
						'numWidthStandard' => 200,	'numHeightStandard' => 200,
						'numWidthWide' => 200,		'numHeightWide' => 200,
						'numWidthClassic' => 200,	'numHeightClassic' => 200,
						'numHeightBox' => 0,		'numWidthBox' => 0,//auto
					),
				)
			),
			'navi' => array(
				'varsFormat' => array(
					'id' => '',
					'flagType' => 'normalFormat',
					'numHeight' => 0,
					'numWidth' => 0,
					'flagHeaderLeftUse' => 1,
					'strTitleHeaderLeft' => '',
					'strClassHeaderLeft' => '',
					'flagHeaderRightUse' => 1,
					'strTitleHeaderRight' => '',
					'strClassHeaderRight' => 'codeLibBaseImgUnloading',
					'flagBodyAutoUse' => 1,
					'strBody' => '',
					'strClassBody' => '',
					'flagFooderUse' => 1,
					'flagFooderLeftUse' => 1,
					'strTitleFooderLeft' => '',
					'strClassFooderLeft' => '',
					'flagFooderRightUse' => 1,
					'strTitleFooderRight' => '',
					'strClassFooderRight' => '',
					'flagHeaderLeftWidth' => 1,
					'numWidthHeaderLeft' => 0,
					'flagHeaderRightWidth' => 0,
					'numWidthHeaderRight' => 0,
					'flagFooderLeftWidth' => 0,
					'numWidthFooderLeft' => 0,
					'flagFooderRightWidth' => 1,
					'numWidthFooderRight' => 0,
				),
				'varsTool' => array(
					'varsDetail' => array(
						array(
							'flagUse' => 1,
							'flagNow' => 0,
							'id' => 'Reload',
							'strClass' => 'codeLibBtnImgReload',
							'strClassOver' => 'codeLibBtnImgReloadOver',
							'strClassNoactive' => 'codeLibBtnImgReloadNoactive',
							'strTitle' => '更新',
						),
					),
				),
			),
			'list' => array(),
			'detail' => array(),
		),
	),
	'child' => array(),
);


