<?php

$vars = array(
	'idEntity' => '',
	'flagAuthorityLedger' => 0,
	'flagAuthorityCash' => 0,
	'flagAuthorityFixedAssets' => 0,
	'flagAuthorityLogHouse' => 0,
	'varsRule'  => array(
		'arrSelectTagAccountTitle' => array(),
		'arrSelectTagDepartment' => array(),
		'arrIdSubAccountTitle' => array(),
		'varsConsumptionTax' => array(),
		'arrStrTitleReport' => array(),
	),
	'varsItem'  => array(
		'flagStatus' => '',
		'strEscape' => '、',
		'arrBlank' => array(
			'strTitle' => '指定なし',
			'value' => '',
		),

		'strAuthorityNone' => 'アクセス権限がないため閲覧できないようです。',
		'strMailImportRetry' => 'フィルタと一致せず不一致になったデータがあるようです。詳細はフィルタリトライを参照してください。',
		'varsJsonChargeHistory' => array(
			'varsStatus' => array(
				'numFontSize' => '10',
				'varsColumnId' => array('id', 'stampRegister', 'idAccount',),
			),
			'varsColumn' => array('No', '担当日時', '担当者',),
			'varsDetail' => array(),
			'tmplDetail' => array(
				'id' => '',
				'varsDetail' => array(),
			),
			'tmplData' => array(
				'value' => '',
			),
		),
		'strTitleAccounting' => '仕訳帳',
		'strPage' => '頁',
		'strSummary' => '摘要',
		'strSundries' => '諸口',
		'strApply' => '申請中',
		'strApplyOpen' => '公開申請中',
		'strApplyBack' => '申請却下',
		'strPermitDone' => '(済)判断',
		'strPermitNeed' => '(要)判断',
		'strPermit' => '承認',
		'strBack' => '差戻し',
		'strDone' => '確定',
		'strNone' => 'なし',
		'strRevocation' => '取消',
		'strRemove' => '削除',
		'strRemoveFake' => '削除扱い',
		'strAccountLost' => 'アカウント削除',
		'strClassBg' => 'codeLibBaseBgLine',

		'strLost' => '現在使われてません',
		'strClassBlank' => 'codeLibBaseImgBlank',
		'strClassNone' => 'codeLibBaseFontCcc',
		'strClassBack' => 'codeLibBaseFontRed',
		'strClassApply' => 'codeLibBaseFontOrange',
		'strClassImgDone' => 'codeLibBaseImgCheck',
		'strClassImgNone' => 'codeLibBaseImgCheckNone',
		'strClassImgBack' => 'codeLibBaseImgRemove',
		'arrayFS' => array( 'BS' => '貸借科目', 'PL' => '損益科目', 'CR' => '製造原価科目',  ),
		'arrayOptionNone' => array( 'strTitle' => '指定なし', 'value' => 'none', ),

		'varsOutput' => array(
			'strEntityExt' => '事業体(<%replace%>)',
			'strNumExt' => '会期(第<%replace%>期)',
		    /*20190401 start*/
			'strPeriodExt' => '会計期間(自 平成<%strStartHeisei%>年<%strStartMonth%>月1日  至 平成<%strEndHeisei%>年<%strEndMonth%>月末日)',
		    'strPeriodExt20190401' => '会計期間(自 <%strStartNengoYear%>年<%strStartMonth%>月1日  至 <%strEndNengoYear%>年<%strEndMonth%>月末日)',
		    /*20190401 end*/
			'strTitle' => '仕訳帳',
			'strTitleList' => '外部仕訳エクスポート(RUCARO形式)',
			'strTitleListYayoi' => '外部仕訳エクスポート(弥生形式)',
			'strBlank' => '　',
			'strDate' => '日付',
			'strStatus' => '状態',
			'strId' => '仕訳通番',
			'strIdFile' => '証憑通番',
			'strIdCharge' => '担当通番',
			'strFiscalReport' => '決整',
			'strMemo' => '摘要',
			'strDebit' => '借方',
			'strCredit' => '貸方',
			'strAccountTitle' => '勘定科目',
			'strSubAccountTitle' => '補助科目',
			'strDepartment' => '部門',
			'strValue' => '金額',
			'strNumValueConsumptionTax' => '税額',
			'strNumRateConsumptionTax' => '税率',
			'strRateConsumptionTax' => '税率',
			'strConsumptionTax' => '税区分',
			'strConsumptionTaxCalc' => '税入力',
			'strEntity' => '',
			'strNum' => '第<%replace%>期',
			'strUnit' => '単位(円)',
			'strSumCalc' => '合算',
			'strSumDetail' => '各合算',
			'strSum' => '合計',
			'strSumIn' => '内税合計',
			'strSumOut' => '外税合計',
			'strFiscalReport1' => '年決',
			'strFiscalReportYayoi1' => '本決',
			'strFiscalReport2' => '中決',
			'strNone' => '対象外',
			'strRemoveFake' => '削扱',
			'strNumAllLog' => '仕訳数',
			'strIncluding' => '込',
			'strNumAllLogReport1' => '年度決算整理仕訳数',
			'strNumAllLogReport2' => '中間決算整理仕訳数',
		),
		'varsId' => array(
			'id' => '識別番号',
			'stampBook' => '取引日時',
			'flagFiscalReport' => '決算整理仕訳',
			'strTitle' => '摘要',
			'idAccountTitleDebit' => '借方勘定科目',
			'flagFSDebit' => '借方F/S',
			'numValueDebit' => '借方金額',
			'idSubAccountTitleDebit' => '借方補助科目',
			'idDepartmentDebit' => '借方部門',
			'flagConsumptionTaxDebit' => '借方消費税区分',
			'numRateConsumptionTaxDebit' => '借方消費税率',
			'flagConsumptionTaxWithoutCalcDebit' => '借方消費税入力方法',
			'numValueConsumptionTaxDebit' => '借方消費税金額',
			'idAccountTitleCredit' => '貸方勘定科目',
			'flagFSCredit' => '貸方F/S',
			'numValueCredit' => '貸方金額',
			'idSubAccountTitleCredit' => '貸方補助科目',
			'idDepartmentCredit' => '貸方部門',
			'flagConsumptionTaxCredit' => '貸方消費税区分',
			'numRateConsumptionTaxCredit' => '貸方消費税率',
			'flagConsumptionTaxWithoutCalcCredit' => '貸方消費税入力方法',
			'numValueConsumptionTaxCredit' => '貸方消費税金額',
			'idAccount' => '担当者',
			'arrSpaceStrTag' => 'タグ',
		),
		'varsDetail' => array(
			'id' => '',
			'arrDebit' => array(
				'idAccountTitle' => '',
				'numValue' => '',
				'numValueConsumptionTax' => '',
				'numRateConsumptionTax' => '',
				'idDepartment' => '',
				'idSubAccountTitle' => '',
				'flagConsumptionTaxFree' => '',
				'flagConsumptionTaxIncluding' => '',
				'flagConsumptionTaxGeneralRuleEach' => '',
				'flagConsumptionTaxGeneralRuleProration' => '',
				'flagConsumptionTaxSimpleRule' => '',
				'flagConsumptionTaxWithoutCalc' => '',
				'flagConsumptionTaxCalc' => '',
			),
			'arrCredit' => array(
				'idAccountTitle' => '',
				'numValue' => '',
				'numValueConsumptionTax' => '',
				'numRateConsumptionTax' => '',
				'idDepartment' => '',
				'idSubAccountTitle' => '',
				'flagConsumptionTaxFree' => '',
				'flagConsumptionTaxIncluding' => '',
				'flagConsumptionTaxGeneralRuleEach' => '',
				'flagConsumptionTaxGeneralRuleProration' => '',
				'flagConsumptionTaxSimpleRule' => '',
				'flagConsumptionTaxWithoutCalc' => '',
				'flagConsumptionTaxCalc' => '',
			),
		),
	),
	'varsPrint' => array(
		'varsStatus' => array(
			'strTitle'  => '',
			'pathCss'   => '',
			'strBlank'   => '　',
			'idInsertTable' => 'insertTable',
			'idHeight'  => 'idHeight',
			'numHeight' => 1060,
			'varsTmpl' => array(
				'tmplWrap'   => '',
				'tmplPage'   => '',
				'tmplTable'  => '',
				'tmplColumn' => '',
			),
		),
		'varsDetailTmpl' => array(
			'id' => '',
			'idTmplColumn' => 'tmplColumn',
			'idTmplTable' => 'tmplTable',
			'strRow' => '',
			'numTr' => 4,
		),
		'varsDetail' => array(),
	),
	'portal' => array(
		'varsNavi' => array(
			'varsStatus' => array(
				'flagNow' => 'search',
				'flagCakeUse' => 1,
				'flagTreeUse' => 0,
				'flagSearchUse' => 1,
				'flagFolderUse' => 0,
				'switchList' => array('search', ),
			),
			'varsFolder' => array(),
			'varsDetail' => array(),
			'tree' => array(),
			'search' => array(
				'varsFormat' => array(
					'id' => '',
					'flagType' => 'normalFormat',
					'numHeight' => 0,
					'numWidth' => 0,
					'flagHeaderLeftUse' => 1,
					'strTitleHeaderLeft' => '詳細検索',
					'strClassHeaderLeft' => 'codeLibBaseImgDb',
					'flagHeaderRightUse' => 1,
					'strTitleHeaderRight' => '',
					'strClassHeaderRight' => 'codeLibBaseImgUnloading',
					'flagBodyAutoUse' => 1,
					'strBody' => '',
					'strClassBody' => '',
					'flagFooderUse' => 1,
					'flagFooderLeftUse' => 1,
					'strTitleFooderLeft' => '',
					'strClassFooderLeft' => '',
					'flagFooderRightUse' => 1,
					'strTitleFooderRight' => '',
					'strClassFooderRight' => '',
					'flagHeaderLeftWidth' => 1,
					'numWidthHeaderLeft' => 0,
					'flagHeaderRightWidth' => 0,
					'numWidthHeaderRight' => 0,
					'flagFooderLeftWidth' => 0,
					'numWidthFooderLeft' => 0,
					'flagFooderRightWidth' => 0,
					'numWidthFooderRight' => 0,
				),
				'varsEdit' => array(
					'flagReloadUse' => 1,
				),
				'varsDetail' => array(
					'varsStatus' => array(
						'flagNow' => 'item',
						'flagSwitchUse' => 1,
						'flagItemUse' => 1,
						'flagWordUse' => 1,
						'flagTagUse' => 1,
						'flagMyRecordUse' => 1,
						'idColumnTagList' => array('arrSpaceStrTag'),
						'idColumnWordList' => array('strTitle'),
						'switchList' => array('word','tag','item'),
					),
					'varsDetail' => array(
						'varsStatus' => array(
							'flagBtnBottomUse' => 1,
						),
						'varsTag' => array(),
						'varsItem' => array(),
						'varsWord' => array(),
						'varsDetail' => array(),
						'varsBtn' => array(
							array(
								'flagUse' => 1, 'flagLeftUse' => 0, 'flagRightUse' => 1, 'flagTextUse' => 0, 'flagBtnUse' => 1,
								'id' => 'EventFormBtnSave',
								'vars' => array( 'idTarget' => 'eventFormBtnSave', ),
								'strTitle' => '保存',
							),
							array(
								'flagUse' => 1, 'flagLeftUse' => 0, 'flagRightUse' => 1, 'flagTextUse' => 0, 'flagBtnUse' => 1,
								'id' => 'EventFormBtnDelete',
								'vars' => array( 'idTarget' => 'eventFormBtnDelete', ),
								'strTitle' => '削除',
							),
							array(
								'flagUse' => 1, 'flagLeftUse' => 0, 'flagRightUse' => 1, 'flagTextUse' => 0, 'flagBtnUse' => 1,
								'id' => 'EventFormBtn',
								'vars' => array( 'idTarget' => 'eventFormBtn', ),
								'strTitle' => '検索',
							),
						),
						'templateDetail' => array(
							'switchTarget' => array(
								'flagMustUse' => 1,
								'id' => 'SwitchTarget',
								'strTitle' => '検索対象', 'strExplain' => '', 'value' => 'word',
								'flagErrorNow' => 0,
								'arrayError' => array(
									array( 'flagCheck' => 'blank', 'flagUse' => 1, 'flagNow' => 0, 'flagType' => 'empty', 'strComment' => array( 'common' => '記入が必要なようです。', ), ),
								),
								'flagContentUse' => 0,
								'flagCommentUse' => 0, 'strCommentTitle' => '', 'strComment' => '',
								'flagTag' => 'select', 'flagInputType' => '', 'numMaxlength' => 0,
								'unitWidth' => '%', 'numWidth' => 40, 'unitHeight' => '', 'numHeight' => 0,
								'arrayOption' => array(
									array( 'strTitle' => 'ワード', 'value' => 'word', ),
									array( 'strTitle' => 'タグ', 'value' => 'tag', ),
									array( 'strTitle' => '項目', 'value' => 'item', ),
								),
							),
							'wordTarget' => array(
								'flagMustUse' => 1,
								'id' => 'Word',
								'strTitle' => '検索ワード', 'strExplain' => '', 'value' => '',
								'flagErrorNow' => 0,
								'arrayError' => array(
									array( 'flagCheck' => 'blank', 'flagUse' => 1, 'flagNow' => 0, 'flagType' => 'empty', 'strComment' => array( 'common' => '記入が必要なようです。', ), ),
								),
								'flagContentUse' => 0,
								'flagCommentUse' => 0, 'strCommentTitle' => '', 'strComment' => '',
								'flagTag' => 'input', 'flagInputType' => 'text', 'numMaxlength' => 0,
								'unitWidth' => '%', 'numWidth' => 80, 'unitHeight' => '', 'numHeight' => 0,
								'arrayOption' => array(),
							),
							'tagTarget' => array(
								'flagMustUse' => 1,
								'id' => 'Tag',
								'strTitle' => '検索タグ', 'strExplain' => '', 'value' => '',
								'flagErrorNow' => 0,
								'arrayError' => array(
									array( 'flagCheck' => 'blank', 'flagUse' => 1, 'flagNow' => 0, 'flagType' => 'empty', 'strComment' => array( 'common' => '記入が必要なようです。', ), ),
								),
								'flagContentUse' => 0,
								'flagCommentUse' => 0, 'strCommentTitle' => '', 'strComment' => '',
								'flagTag' => 'input', 'flagInputType' => 'text', 'numMaxlength' => 0,
								'unitWidth' => '%', 'numWidth' => 80, 'unitHeight' => '', 'numHeight' => 0,
								'arrayOption' => array(),
							),
							'itemTarget' => array(
								'flagMustUse' => 1,
								'id' => 'JsonItem',
								'strTitle' => '検索項目', 'strExplain' => '', 'value' => '',
								'flagErrorNow' => 0,
								'arrayError' => array(
									array( 'flagCheck' => 'blank', 'flagUse' => 1, 'flagNow' => 0, 'flagType' => 'empty', 'strComment' => array( 'common' => '記入が必要なようです。', ), ),
								),
								'flagContentUse' => 1,
								'flagCommentUse' => 0, 'strCommentTitle' => '', 'strComment' => '',
								'flagTag' => 'input', 'flagInputType' => 'text', 'numMaxlength' => 0,
								'unitWidth' => '%', 'numWidth' => 40, 'unitHeight' => '', 'numHeight' => 0,
								'arrayOption' => array(),
							),
							'logApply' => array(
								'flagMustUse' => 1,
								'id' => 'FlagApply',
								'strTitle' => '状態', 'strExplain' => '', 'value' => 'none',
								'flagErrorNow' => 0,
								'arrayError' => array(
									array( 'flagCheck' => 'blank', 'flagUse' => 1, 'flagNow' => 0, 'flagType' => 'empty', 'strComment' => array( 'common' => '記入が必要なようです。', ), ),
								),
								'flagContentUse' => 0,
								'flagCommentUse' => 0, 'strCommentTitle' => '', 'strComment' => '',
								'flagTag' => 'select', 'flagInputType' => '', 'numMaxlength' => 0,
								'unitWidth' => '%', 'numWidth' => 40, 'unitHeight' => '', 'numHeight' => 0,
								'arrayOption' => array(
									array( 'strTitle' => '指定なし', 'value' => 'none', ),
									array( 'strTitle' => '確定', 'value' => 'done', ),
									array( 'strTitle' => '申請', 'value' => 'apply', ),
									array( 'strTitle' => '差戻', 'value' => 'back', ),
									array( 'strTitle' => '削除扱い', 'value' => 'remove', ),
								),
							),
							'jsonSort' => array(
								'flagMustUse' => 1,
								'id' => 'JsonSort',
								'strTitle' => '並び順', 'strExplain' => '', 'value' => '',
								'flagErrorNow' => 0,
								'arrayError' => array(
									array( 'flagCheck' => 'blank', 'flagUse' => 1, 'flagNow' => 0, 'flagType' => 'empty', 'strComment' => array( 'common' => '記入が必要なようです。', ), ),
								),
								'flagContentUse' => 1,
								'flagCommentUse' => 0, 'strCommentTitle' => '', 'strComment' => '',
								'flagTag' => 'input', 'flagInputType' => 'text', 'numMaxlength' => 0,
								'unitWidth' => '%', 'numWidth' => 40, 'unitHeight' => '', 'numHeight' => 0,
								'arrayOption' => array(),
							),
							'myRecord' => array(
								'flagMustUse' => 0,
								'id' => 'MyRecord',
								'strTitle' => '', 'strExplain' => '', 'value' => '',
								'flagErrorNow' => 0,
								'arrayError' => array(),
								'flagContentUse' => 0,
								'flagCommentUse' => 1, 'strCommentTitle' => 'My条件', 'strComment' => '',
								'flagTag' => 'input', 'flagInputType' => 'text', 'numMaxlength' => 0,
								'unitWidth' => '%', 'numWidth' => 40, 'unitHeight' => '', 'numHeight' => 0,
								'arrayOption' => array(),
							),
						),
					),
					'varsMyRecord' => array(
						'varsFormList' => array(
							'varsStatus' => array(
								'flagSortUse' => 1,
								'flagCopyUse' => 0,
								'flagRemoveUse' => 1,
								'flagAddUse' => 0,
								'flagEditUse' => 1,
								'flagFormUse' => 1,
								'flagBtnUse' => 1,
							),
							'templateDetail' => array(
								'id' => '',
								'flagSortUse' => 1,
								'flagCopyUse' => 0,
								'flagRemoveUse' => 1,
								'flagEditUse' => 1,
								'flagFormUse' => 0,
								'flagBtnUse' => 1,
								'numSort' => 0,
								'value' => '',
								'vars' => '',
							),
							'varsDetail' => array(),
						),
					),
					'varsSearchSort' => array(
						'varsStatus' => array(
							'flagUse' => 1,
							'flagAscUse' => 1,
							'flagDescUse' => 1,
						),
						'varsDetail' => array(
							'id' => 0,
							'itemValue' => 'id',
							'sortValue' => 'desc'
						),
						'itemOption' => array(
							array( 'strTitle' => '記録日時', 'value' => 'id', ),
							array( 'strTitle' => '更新日時', 'value' => 'stampUpdate', ),
							array( 'strTitle' => '取引日時', 'value' => 'stampBook', ),
						),
						'sortOption' => array(
							array( 'strTitle' => '降順', 'value' => 'desc', ),
							array( 'strTitle' => '昇順', 'value' => 'asc', ),
						),
					),
					'varsSearchItem' => array(
						'varsStatus' => array(
							'flagUse' => 1,
							'flagAddUse' => 1,
							'flagCopyUse' => 1,
							'flagRemoveUse' => 1,
							'flagCalenderUse' => 1,
						),
						'varsCalender' => array(
							'varsStatus' => array(
								'numLeft' => 0,
								'numTop' => 0,
								'flagMaxUse' => 0,
								'flagMaxAutoUse' => 1,
								'stampMax' => 0,//1260198000000
								'flagMainUse' => 1,
								'flagMainAutoUse' => 1,
								'stampMain' => 0,
								'flagMinUse' => 0,
								'flagMinAutoUse' => 0,
								'stampMin' => 0,
								'stampPoint' => 0,
							),
						),
						'varsDetail' => array(
							array(
								'id' => 0,
								'flagType' => 'num',
								'flagOption' => '',
								'firstValue' => 'num-idLog',
								'secondValue' => 'eq',
								'restValue' => '',
							),
						),
						'templateDetail' => array(
							'varsDetail' => array(
								'id' => 0,
								'flagType' => 'num',
								'flagOption' => '',//set option str ex)moduleOption
								'firstValue' => 'num-idLog',
								'secondValue' => 'eq',
								'restValue' => '',
							),
							'firstOption' => array(
								array( 'strTitle' => '通番', 'value' => 'num-idLog', ),
								array( 'strTitle' => '摘要', 'value' => 'str-strTitle', ),
								array( 'strTitle' => '記録日時', 'value' => 'stamp-stampRegister', ),
								array( 'strTitle' => '更新日時', 'value' => 'stamp-stampUpdate', ),
								array( 'strTitle' => '取引日時', 'value' => 'stamp-stampBook', ),
								array( 'strTitle' => '合計金額', 'value' => 'num-numValue', ),

								array( 'strTitle' => '借方勘定科目', 'value' => 'commaFs-arrCommaIdAccountTitleDebit-commaFs', ),
								array( 'strTitle' => '借方補助科目/通番', 'value' => 'comma-arrCommaIdSubAccountTitleDebit', ),
								array( 'strTitle' => '借方部門', 'value' => 'commaDepartment-arrCommaIdDepartmentDebit-commaDepartment', ),
								array( 'strTitle' => '借方税区分', 'value' => 'commaTax-arrCommaConsumptionTaxDebit-commaTax', ),
								array( 'strTitle' => '借方税率', 'value' => 'commaTaxRate-arrCommaRateConsumptionTaxDebit-commaTaxRate', ),
								array( 'strTitle' => '借方税入力', 'value' => 'commaTaxWithoutCalc-arrCommaConsumptionTaxWithoutCalcDebit-commaTaxWithoutCalc', ),

								array( 'strTitle' => '貸方勘定科目', 'value' => 'commaFs-arrCommaIdAccountTitleCredit-commaFs', ),
								array( 'strTitle' => '貸方補助科目/通番', 'value' => 'comma-arrCommaIdSubAccountTitleCredit', ),
								array( 'strTitle' => '貸方部門', 'value' => 'commaDepartment-arrCommaIdDepartmentCredit-commaDepartment', ),
								array( 'strTitle' => '貸方税区分', 'value' => 'commaTax-arrCommaConsumptionTaxCredit-commaTax', ),
								array( 'strTitle' => '貸方税率', 'value' => 'commaTaxRate-arrCommaRateConsumptionTaxCredit-commaTaxRate', ),
								array( 'strTitle' => '貸方税入力', 'value' => 'commaTaxWithoutCalc-arrCommaConsumptionTaxWithoutCalcCredit-commaTaxWithoutCalc', ),

								array( 'strTitle' => '決算整理仕訳', 'value' => 'report-flagFiscalReport-report', ),
								array( 'strTitle' => '証憑ファイル/通番', 'value' => 'comma-arrCommaIdLogFile', ),
								array( 'strTitle' => 'タグ', 'value' => 'tag-arrSpaceStrTag', ),
								array( 'strTitle' => '担当者アカウント/通番', 'value' => 'account-idAccount', ),
								array( 'strTitle' => 'dummy', 'value' => 'commaTax-arrCommaTaxPaymentDebit-commaTax', ),
								array( 'strTitle' => 'dummy', 'value' => 'commaTax-arrCommaTaxReceiptDebit-commaTax', ),
								array( 'strTitle' => 'dummy', 'value' => 'commaTax-arrCommaTaxPaymentCredit-commaTax', ),
								array( 'strTitle' => 'dummy', 'value' => 'commaTax-arrCommaTaxReceiptCredit-commaTax', ),
							),
							'commaFsOption' => array(
								array( 'strTitle' => '～と一致。', 'value' => 'like', ),
								array( 'strTitle' => '～と不一致。', 'value' => 'notlike', ),
							),
							'commaTaxOption' => array(
								array( 'strTitle' => '～と一致。', 'value' => 'like', ),
								array( 'strTitle' => '～と不一致。', 'value' => 'notlike', ),
							),
							'commaTaxWithoutCalcOption' => array(
								array( 'strTitle' => '～と一致。', 'value' => 'like', ),
								array( 'strTitle' => '～と不一致。', 'value' => 'notlike', ),
							),
							'commaTaxRateOption' => array(
								array( 'strTitle' => '～と一致。', 'value' => 'like', ),
								array( 'strTitle' => '～と不一致。', 'value' => 'notlike', ),
							),
							'commaDepartmentOption' => array(
								array( 'strTitle' => '～と一致。', 'value' => 'like', ),
								array( 'strTitle' => '～と不一致。', 'value' => 'notlike', ),
							),
							'commaOption' => array(
								array( 'strTitle' => '～と一致。', 'value' => 'like', ),
								array( 'strTitle' => '～と不一致。', 'value' => 'notlike', ),
							),
							'accountOption' => array(
								array( 'strTitle' => '～と一致。', 'value' => 'eq', ),
								array( 'strTitle' => '～と不一致。', 'value' => 'ne', ),
							),
							'reportOption' => array(
								array( 'strTitle' => '～と一致。', 'value' => 'eq', ),
								array( 'strTitle' => '～と不一致。', 'value' => 'ne', ),
							),
							'tagOption' => array(
								array( 'strTitle' => '～と一致。', 'value' => 'like', ),
								array( 'strTitle' => '～と不一致。', 'value' => 'notlike', ),
							),
							'commaOption' => array(
								array( 'strTitle' => '～と一致。', 'value' => 'like', ),
								array( 'strTitle' => '～と不一致。', 'value' => 'notlike', ),
							),
							'strOption' => array(
								array( 'strTitle' => '～を含む。', 'value' => 'like', ),
								array( 'strTitle' => '～を含まない。', 'value' => 'notlike', ),
								array( 'strTitle' => '～と一致。', 'value' => 'eq', ),
								array( 'strTitle' => '～と不一致。', 'value' => 'ne', ),
								array( 'strTitle' => '～で始まる。', 'value' => 'start', ),
								array( 'strTitle' => '～で終わる。', 'value' => 'end', ),
							),
							'stampOption' => array(
								array( 'strTitle' => '～と一致。', 'value' => 'eq', ),
								array( 'strTitle' => '～と不一致。', 'value' => 'ne', ),
								array( 'strTitle' => '～より前。', 'value' => 'before', ),
								array( 'strTitle' => '～より後。', 'value' => 'after', ),
								array( 'strTitle' => '～以前。', 'value' => 'eqBefore', ),
								array( 'strTitle' => '～以後。', 'value' => 'eqAfter', ),
							),
							'numOption' => array(
								array( 'strTitle' => '～と一致。', 'value' => 'eq', ),
								array( 'strTitle' => '～と不一致。', 'value' => 'ne', ),
								array( 'strTitle' => '～未満。', 'value' => 'small', ),
								array( 'strTitle' => '～超。', 'value' => 'big', ),
								array( 'strTitle' => '～以下。', 'value' => 'eqSmall', ),
								array( 'strTitle' => '～以上。', 'value' => 'eqBig', ),
							),
							'restOption' => array(
								'comma' => array(),
								'commaFs' => array(),
								'commaTax' => array(),
								'commaDepartment' => array(),
								'commaTaxWithoutCalc' => array(),
								'commaTaxRate' => array(
									array( 'strTitle' => '5%', 'value' => 5, ),
									array( 'strTitle' => '8%', 'value' => 8, ),
									/*
									 * 2014-2015 start
									*/
									//array( 'strTitle' => '10%', 'value' => 10, ),
									/*
									 * 2014-2015 end
									*/
								),
								'report' => array(
									array( 'strTitle' => '年度決算整理仕訳', 'value' => 'f1', ),
									array( 'strTitle' => '中間決算整理仕訳', 'value' => 'f21', ),
								),
							),
						),
					),
				),
			),
			'templateFolder' => array(),
		),
		'varsList' => array(
			'varsStart' => array(
				'varsStatus' => array(
					'strTitle' => 'リスト',
					'strClass' => 'codeLibBaseImgFolder',
				),
				'varsEdit' => array(
					'flagReloadUse' => 1,
					'flagSwitchUse' => 1,
					'flagImportUse' => 1,
					'flagOutputUse' => 1,
					'flagPrintUse' => 1,
					'flagSearchUse' => 1,
					'flagPreferenceUse' => 1,
				),
				'varsDetail' => array(),
			),
			'varsStatus' => array(
				'flagNow' => 'table',
				'flagCakeUse' => 1,
				'flagTableUse' => 1,
				'flagScheduleUse' => 1,
				'flagThumbnailUse' => 0,
				'flagTreeUse' => 0,
				'flagBoldUse' => 0,
				'flagFontUse' => 0,
				'flagBgUse' => 0,
				'switchList' => array('table','schedule'),
				'flagOutputUse' => 1,
				'flagOutputNow' => 'listAll',
				'switchOutputList' => array('listAll', 'itemAll', 'itemAllYayoi'),
				'flagImportUse' => 1,
				'flagImportNow' => 'mailAll',
				'switchImportList' => array('mailAll', 'listAll', 'itemAll'),
				'flagReloadUse' => 1,
				'flagReloadNow' => 'start',
				'switchReloadList' => array('same', 'start'),
			),
			'templateDetail' => array(
				'flagBtnUse' => 1,
				'flagMoveUse' => 0,
				'id' => '0',
				'idTarget' => '0',
				'strTitle' => '',
				'flagBoldNow' => 0,
				'strClassFont' => '',
				'strClassBg' => '',
				'numSort' => 0,
				'strClass' => 'codeLibBaseImgSheet',
				'strClassLoad' => 'codeLibTableLineLoad',
				'flagCheckboxUse' => 1,
				'flagCheckboxNow' => 0,
				'varsColumnDetail' => array(
					'id' => '',
					'strTitle' => '',
					'stampRegister' => 0,
					'stampUpdate' => 0,
				),
				'varsScheduleDetail' => array(
					'flagType' => 'stamp',//stamp,term,loop
					'flagResizeUse' => 1,
					'strTitle' => '',
					'stamp' => 0,
					'term' => array(),
					'loop' => array(),
				),
			),
			'varsPage' => array(
				'varsStatus' => array(
					'flagStatusUse' => 1,
					'flagLockUse' => 1,
					'flagLockNow' => 0,
					'flagTopUse' => 1,
					'flagEndUse' => 1,
					'flagNextUse' => 1,
					'flagPrevUse' => 1,
					'numRows' => 0,
					'numLotNow' => 0,
				),
			),
			'varsEdit' => array(
				'flagReloadUse' => 1,
				'flagSwitchUse' => 1,
				'flagImportUse' => 1,
				'flagOutputUse' => 1,
				'flagPrintUse' => 1,
				'flagSearchUse' => 1,
				'flagPreferenceUse' => 1,
			),
			'varsDetail' => array(),
			'varsBtn' => array(
				array(
					'flagUse' => 1, 'flagLeftUse' => 0, 'flagRightUse' => 1, 'flagTextUse' => 0, 'flagBtnUse' => 1,
					'id' => 'eventBtnDelete',
					'vars' => array( 'idTarget' => 'Delete', ),
					'strTitle' => '一括削除扱い',
				),
				array(
					'flagUse' => 1, 'flagLeftUse' => 0, 'flagRightUse' => 1, 'flagTextUse' => 0, 'flagBtnUse' => 1,
					'id' => 'eventBtnApplyBack',
					'vars' => array( 'idTarget' => 'Back', ),
					'strTitle' => '一括差戻し',
				),
				array(
					'flagUse' => 1, 'flagLeftUse' => 0, 'flagRightUse' => 1, 'flagTextUse' => 0, 'flagBtnUse' => 1,
					'id' => 'eventBtnApplyOk',
					'vars' => array( 'idTarget' => 'Permit', ),
					'strTitle' => '一括承認',
				),
			),
			'table' => array(
				'varsFormat' => array(
					'id' => '',
					'flagType' => 'normalFormat',
					'numHeight' => 0,
					'numWidth' => 0,
					'flagHeaderLeftUse' => 1,
					'strTitleHeaderLeft' => '',
					'strClassHeaderLeft' => '',
					'flagHeaderRightUse' => 1,
					'strTitleHeaderRight' => '',
					'strClassHeaderRight' => 'codeLibBaseImgUnloading',
					'flagBodyAutoUse' => 0,
					'strBody' => '',
					'strClassBody' => '',
					'flagFooderUse' => 1,
					'flagFooderLeftUse' => 1,
					'strTitleFooderLeft' => '',
					'strClassFooderLeft' => '',
					'flagFooderRightUse' => 1,
					'strTitleFooderRight' => '',
					'strClassFooderRight' => '',
					'flagHeaderLeftWidth' => 1,
					'numWidthHeaderLeft' => 0,
					'flagHeaderRightWidth' => 0,
					'numWidthHeaderRight' => 0,
					'flagFooderLeftWidth' => 0,
					'numWidthFooderLeft' => 0,
					'flagFooderRightWidth' => 0,
					'numWidthFooderRight' => 0,
				),
				'varsHtml' => array(),
				'varsEdit' => array(
					'flagReloadUse' => 1,
					'flagSwitchUse' => 1,
					'flagImportUse' => 1,
					'flagOutputUse' => 1,
					'flagPrintUse' => 1,
					'flagSearchUse' => 1,
					'flagPreferenceUse' => 1,
				),
				'varsDetail' => array(
					'varsStatus' => array(
						'flagMenuUse' => 1,
						'flagColumnUse' => 0,
						'flagResizeUse' => 1,
						'flagSortColumnUse' => 1,
						'flagSortColumnLineUse' => 0,
						'flagSortColumnLineNow' => '',
						'flagMoveUse' => 0,
						'flagMoveSortUse' => 0,
						'flagCakeUse' => 1,
						'flagPageUse' => 1,
						'flagInnerPageUse' => 1,
						'flagBtnBottomUse' => 1,
						'flagBtnUse' => 0,
						'flagKeyBtnUse' => 0,
						'flagBgUse' => 1,
						'flagFontUse' => 1,
						'flagBoldUse' => 0,
						'flagTextBtnUse' => 1,
					),
					'varsFormat' => array(
						'id' => '',
						'flagType' => 'singleFormat',
						'numHeight' => 0,
						'numWidth' => 0,
						'flagHeaderUse' => 1,
						'flagHeaderLeftUse' => 1,
						'strTitleHeaderLeft' => '',
						'strClassHeaderLeft' => 'codeLibBaseImgBlank',
						'flagHeaderRightUse' => 0,
						'strTitleHeaderRight' => '',
						'strClassHeaderRight' => '',
						'flagBodyAutoUse' => 1,
						'strBody' => '',
						'strClassBody' => '',
						'flagFooderUse' => 1,
						'flagFooderLeftUse' => 1,
						'strTitleFooderLeft' => '',
						'strClassFooderLeft' => '',
						'flagFooderRightUse' => 1,
						'strTitleFooderRight' => '',
						'strClassFooderRight' => '',

						'flagHeaderLeftWidth' => 1,
						'numWidthHeaderLeft' => 0,
						'flagHeaderRightWidth' => 0,
						'numWidthHeaderRight' => 0,
						'flagFooderLeftWidth' => 0,
						'numWidthFooderLeft' => 0,
						'flagFooderRightWidth' => 0,
						'numWidthFooderRight' => 0,
					),
					'varsPage' => array(),
					'varsHtml' => array(),
					'varsBtn' => array(),
					'varsContext' => array(
						'varsStatus' => array(
							'numTop' => 0,
							'numLeft' => 0,
						),
						'varsDetail' => array(),
					),
					'varsColumn' => array(
						array(
							'flagUse' => 1,
							'flagCheckUse' => 0,
							'flagCheckNow' => 1,
							'id' => 'FlagCheck',
							'flagSortColumnLineUse' => 0,
							'flagSortColumnLineNow' => 0,
							'strTitle' => '',
							'numSort' => 0,
							'numWidth' => 26,
							'numWidthMin' => 26,
							'flagType' => 'checkbox',
							'flagTimeType' => '',
							'flagAllCheckbox' => 1,
							'flagAllCheckboxNow' => 0,
							'vars' => array(),
							'child' => array(),
						),
						array(
							'flagUse' => 1,
							'flagCheckUse' => 1,
							'flagCheckNow' => 1,
							'id' => 'StampBook',
							'flagSortColumnLineUse' => 0,
							'flagSortColumnLineNow' => 0,
							'strTitle' => '取引日時',
							'numSort' => 1,
							'numWidth' => 100,
							'numWidthMin' => 26,
							'flagType' => 'stamp',
							'flagTimeType' => '1',
							'flagAllCheckbox' => 0,
							'flagAllCheckboxNow' => 0,
							'vars' => array(),
							'child' => array(),
						),
						array(
							'flagUse' => 1,
							'flagCheckUse' => 1,
							'flagCheckNow' => 1,
							'id' => 'IdAccountTitleDebit',
							'flagSortColumnLineUse' => 0,
							'flagSortColumnLineNow' => 0,
							'strTitle' => '借方勘定科目',
							'numSort' => 2,
							'numWidth' => 80,
							'numWidthMin' => 26,
							'flagType' => 'str',
							'flagTimeType' => '',
							'flagAllCheckbox' => 0,
							'flagAllCheckboxNow' => 0,
							'vars' => array(),
							'child' => array(),
						),
						array(
							'flagUse' => 1,
							'flagCheckUse' => 1,
							'flagCheckNow' => 1,
							'id' => 'NumValueDebit',
							'flagSortColumnLineUse' => 0,
							'flagSortColumnLineNow' => 0,
							'strTitle' => '借方金額',
							'numSort' => 3,
							'numWidth' => 80,
							'numWidthMin' => 26,
							'flagType' => 'str',
							'flagTimeType' => '',
							'flagAllCheckbox' => 0,
							'flagAllCheckboxNow' => 0,
							'flagAlign' => 'right',
							'vars' => array(),
							'child' => array(),
						),
						array(
							'flagUse' => 1,
							'flagCheckUse' => 1,
							'flagCheckNow' => 1,
							'id' => 'NumValueConsumptionTaxDebit',
							'flagSortColumnLineUse' => 0,
							'flagSortColumnLineNow' => 0,
							'strTitle' => '借方消費税',
							'numSort' => 4,
							'numWidth' => 80,
							'numWidthMin' => 26,
							'flagType' => 'str',
							'flagTimeType' => '',
							'flagAllCheckbox' => 0,
							'flagAllCheckboxNow' => 0,
							'flagAlign' => 'right',
							'vars' => array(),
							'child' => array(),
						),
						array(
							'flagUse' => 1,
							'flagCheckUse' => 1,
							'flagCheckNow' => 1,
							'id' => 'IdAccountTitleCredit',
							'flagSortColumnLineUse' => 0,
							'flagSortColumnLineNow' => 0,
							'strTitle' => '貸方勘定科目',
							'numSort' => 5,
							'numWidth' => 80,
							'numWidthMin' => 26,
							'flagType' => 'str',
							'flagTimeType' => '',
							'flagAllCheckbox' => 0,
							'flagAllCheckboxNow' => 0,
							'vars' => array(),
							'child' => array(),
						),
						array(
							'flagUse' => 1,
							'flagCheckUse' => 1,
							'flagCheckNow' => 1,
							'id' => 'NumValueCredit',
							'flagSortColumnLineUse' => 0,
							'flagSortColumnLineNow' => 0,
							'strTitle' => '貸方金額',
							'numSort' => 6,
							'numWidth' => 80,
							'numWidthMin' => 26,
							'flagType' => 'str',
							'flagTimeType' => '',
							'flagAllCheckbox' => 0,
							'flagAllCheckboxNow' => 0,
							'flagAlign' => 'right',
							'vars' => array(),
							'child' => array(),
						),
						array(
							'flagUse' => 1,
							'flagCheckUse' => 1,
							'flagCheckNow' => 1,
							'id' => 'NumValueConsumptionTaxCredit',
							'flagSortColumnLineUse' => 0,
							'flagSortColumnLineNow' => 0,
							'strTitle' => '貸方消費税',
							'numSort' => 7,
							'numWidth' => 80,
							'numWidthMin' => 26,
							'flagType' => 'str',
							'flagTimeType' => '',
							'flagAllCheckbox' => 0,
							'flagAllCheckboxNow' => 0,
							'flagAlign' => 'right',
							'vars' => array(),
							'child' => array(),
						),
						array(
							'flagUse' => 1,
							'flagCheckUse' => 1,
							'flagCheckNow' => 1,
							'id' => 'StrTitle',
							'flagSortColumnLineUse' => 0,
							'flagSortColumnLineNow' => 0,
							'strTitle' => '摘要',
							'numSort' => 8,
							'numWidth' => 100,
							'numWidthMin' => 26,
							'flagType' => 'str',
							'flagTimeType' => '',
							'flagAllCheckbox' => 0,
							'flagAllCheckboxNow' => 0,
							'vars' => array(),
							'child' => array(),
						),
						array(
							'flagUse' => 1,
							'flagCheckUse' => 1,
							'flagCheckNow' => 1,
							'id' => 'IdSubAccountTitleDebit',
							'flagSortColumnLineUse' => 0,
							'flagSortColumnLineNow' => 0,
							'strTitle' => '借方補助科目',
							'numSort' => 9,
							'numWidth' => 80,
							'numWidthMin' => 26,
							'flagType' => 'str',
							'flagTimeType' => '',
							'flagAllCheckbox' => 0,
							'flagAllCheckboxNow' => 0,
							'vars' => array(),
							'child' => array(),
						),
						array(
							'flagUse' => 1,
							'flagCheckUse' => 1,
							'flagCheckNow' => 1,
							'id' => 'IdDepartmentDebit',
							'flagSortColumnLineUse' => 0,
							'flagSortColumnLineNow' => 0,
							'strTitle' => '借方部門',
							'numSort' => 10,
							'numWidth' => 80,
							'numWidthMin' => 26,
							'flagType' => 'str',
							'flagTimeType' => '',
							'flagAllCheckbox' => 0,
							'flagAllCheckboxNow' => 0,
							'vars' => array(),
							'child' => array(),
						),
						array(
							'flagUse' => 1,
							'flagCheckUse' => 1,
							'flagCheckNow' => 1,
							'id' => 'FlagConsumptionTaxDebit',
							'flagSortColumnLineUse' => 0,
							'flagSortColumnLineNow' => 0,
							'strTitle' => '借方税区分',
							'numSort' => 11,
							'numWidth' => 80,
							'numWidthMin' => 26,
							'flagType' => 'str',
							'flagTimeType' => '',
							'flagAllCheckbox' => 0,
							'flagAllCheckboxNow' => 0,
							'vars' => array(),
							'child' => array(),
						),
						array(
							'flagUse' => 1,
							'flagCheckUse' => 1,
							'flagCheckNow' => 1,
							'id' => 'NumRateConsumptionTaxDebit',
							'flagSortColumnLineUse' => 0,
							'flagSortColumnLineNow' => 0,
							'strTitle' => '借方税率',
							'numSort' => 12,
							'numWidth' => 80,
							'numWidthMin' => 26,
							'flagType' => 'str',
							'flagTimeType' => '',
							'flagAllCheckbox' => 0,
							'flagAllCheckboxNow' => 0,
							'vars' => array(),
							'child' => array(),
						),
						array(
							'flagUse' => 1,
							'flagCheckUse' => 1,
							'flagCheckNow' => 1,
							'id' => 'IdSubAccountTitleCredit',
							'flagSortColumnLineUse' => 0,
							'flagSortColumnLineNow' => 0,
							'strTitle' => '貸方補助科目',
							'numSort' => 13,
							'numWidth' => 80,
							'numWidthMin' => 26,
							'flagType' => 'str',
							'flagTimeType' => '',
							'flagAllCheckbox' => 0,
							'flagAllCheckboxNow' => 0,
							'vars' => array(),
							'child' => array(),
						),
						array(
							'flagUse' => 1,
							'flagCheckUse' => 1,
							'flagCheckNow' => 1,
							'id' => 'IdDepartmentCredit',
							'flagSortColumnLineUse' => 0,
							'flagSortColumnLineNow' => 0,
							'strTitle' => '貸方部門',
							'numSort' => 14,
							'numWidth' => 80,
							'numWidthMin' => 26,
							'flagType' => 'str',
							'flagTimeType' => '',
							'flagAllCheckbox' => 0,
							'flagAllCheckboxNow' => 0,
							'vars' => array(),
							'child' => array(),
						),
						array(
							'flagUse' => 1,
							'flagCheckUse' => 1,
							'flagCheckNow' => 1,
							'id' => 'FlagConsumptionTaxCredit',
							'flagSortColumnLineUse' => 0,
							'flagSortColumnLineNow' => 0,
							'strTitle' => '貸方税区分',
							'numSort' => 15,
							'numWidth' => 80,
							'numWidthMin' => 26,
							'flagType' => 'str',
							'flagTimeType' => '',
							'flagAllCheckbox' => 0,
							'flagAllCheckboxNow' => 0,
							'vars' => array(),
							'child' => array(),
						),
						array(
							'flagUse' => 1,
							'flagCheckUse' => 1,
							'flagCheckNow' => 1,
							'id' => 'NumRateConsumptionTaxCredit',
							'flagSortColumnLineUse' => 0,
							'flagSortColumnLineNow' => 0,
							'strTitle' => '貸方税率',
							'numSort' => 16,
							'numWidth' => 80,
							'numWidthMin' => 26,
							'flagType' => 'str',
							'flagTimeType' => '',
							'flagAllCheckbox' => 0,
							'flagAllCheckboxNow' => 0,
							'vars' => array(),
							'child' => array(),
						),
						array(
							'flagUse' => 1,
							'flagCheckUse' => 1,
							'flagCheckNow' => 1,
							'id' => 'FlagFiscalReport',
							'flagSortColumnLineUse' => 0,
							'flagSortColumnLineNow' => 0,
							'strTitle' => '決算整理仕訳',
							'numSort' => 17,
							'numWidth' => 50,
							'numWidthMin' => 26,
							'flagType' => 'str',
							'flagTimeType' => '',
							'flagAllCheckbox' => 0,
							'flagAllCheckboxNow' => 0,
							'vars' => array(),
							'child' => array(),
						),
						array(
							'flagUse' => 1,
							'flagCheckUse' => 1,
							'flagCheckNow' => 1,
							'id' => 'NumFile',
							'flagSortColumnLineUse' => 0,
							'flagSortColumnLineNow' => 0,
							'strTitle' => '証憑ファイル数',
							'numSort' => 18,
							'numWidth' => 50,
							'numWidthMin' => 26,
							'flagType' => 'str',
							'flagTimeType' => '',
							'flagAllCheckbox' => 0,
							'flagAllCheckboxNow' => 0,
							'vars' => array(),
							'child' => array(),
						),
						array(
							'flagUse' => 1,
							'flagCheckUse' => 1,
							'flagCheckNow' => 1,
							'id' => 'Id',
							'flagSortColumnLineUse' => 0,
							'flagSortColumnLineNow' => 0,
							'strTitle' => '通番',
							'numSort' => 19,
							'numWidth' => 50,
							'numWidthMin' => 26,
							'flagType' => 'str',
							'flagTimeType' => '',
							'flagAllCheckbox' => 0,
							'flagAllCheckboxNow' => 0,
							'vars' => array(),
							'child' => array(),
						),
					),
					'varsDetail' => array(),
				),
			),
			'schedule' => array(
				'varsFormat' => array(
					'id' => '',
					'flagType' => 'normalFormat',
					'numHeight' => 0,
					'numWidth' => 0,
					'flagHeaderLeftUse' => 1,
					'strTitleHeaderLeft' => '',
					'strClassHeaderLeft' => '',
					'flagHeaderRightUse' => 1,
					'strTitleHeaderRight' => '',
					'strClassHeaderRight' => 'codeLibBaseImgUnloading',
					'flagBodyAutoUse' => 0,
					'strBody' => '',
					'strClassBody' => '',
					'flagFooderUse' => 1,
					'flagFooderLeftUse' => 1,
					'strTitleFooderLeft' => '',
					'strClassFooderLeft' => '',
					'flagFooderRightUse' => 1,
					'strTitleFooderRight' => '',
					'strClassFooderRight' => '',
					'flagHeaderLeftWidth' => 1,
					'numWidthHeaderLeft' => 0,
					'flagHeaderRightWidth' => 0,
					'numWidthHeaderRight' => 0,
					'flagFooderLeftWidth' => 0,
					'numWidthFooderLeft' => 0,
					'flagFooderRightWidth' => 0,
					'numWidthFooderRight' => 0,
				),
				'varsEdit' => array(
					'flagReloadUse' => 1,
					'flagSwitchUse' => 1,
					'flagImportUse' => 1,
					'flagOutputUse' => 1,
					'flagPrintUse' => 1,
					'flagSearchUse' => 1,
					'flagPreferenceUse' => 1,
				),
				'varsDetail' => array(
					'varsStatus' => array(
						'flagNow' => 'month',// 'month','week'
						'flagFoldUse' => 1,
						'flagBgUse' => 1,
						'flagFontUse' => 1,
						'flagBoldUse' => 0,
						'flagMoveUse' => 0,
						'flagMoveRangeUse' => 0,
						'flagResizeUse' => 0,
						'flagDateEventUse' => 0,
						'flagMaxUse' => 0,
						'flagMaxAutoUse' => 0,
						'stampMax' => 0,
						'flagMainUse' => 1,
						'flagMainAutoUse' => 1,
						'stampMain' => 0,
						'flagMinUse' => 0,
						'flagMinAutoUse' => 0,
						'stampMin' => 0,
						'flagBtnBottomUse' => 0,
						'flagPageUse' => 1,
						'flagInnerPageUse' => 1,
					),
					'varsFormat' => array(
						'id' => '',
						'flagType' => 'scheduleFormat',
						'numHeight' => 0,
						'numWidth' => 0,
						'flagFooderUse' => 1,
					),
					'varsBtn' => array(),
					'varsPage' => array(),
					'varsDetail' => array(),
					'month' => array(
						'varsFold' => array(
							array( 'flagFoldNow' => 1,),array( 'flagFoldNow' => 1,),array( 'flagFoldNow' => 1,),array( 'flagFoldNow' => 1,),array( 'flagFoldNow' => 1,),array( 'flagFoldNow' => 1,),
						),
					),
					'week' => array(
						'varsFold' => array(
							array( 'flagFoldNow' => 1,),array( 'flagFoldNow' => 1,),array( 'flagFoldNow' => 1,),array( 'flagFoldNow' => 1,),array( 'flagFoldNow' => 1,),array( 'flagFoldNow' => 1,),array( 'flagFoldNow' => 1,),
						),
					),
				),
			),
			'thumbnail' => array(),
			'tree' => array(),
		),
		'varsDetail' => array(
			'varsStatus' => array(
				'flagUse' => 1,
				'flagNow' => 'view',
				'flagCakeUse' => 1,
				'flagFoldUse' => 1,
				'flagViewUse' => 1,
				'flagFormUse' => 0,
				'flagMoveUse' => 0,
				'switchList' => array('view'),
			),
			'templateDetail' => array(
				array(
					'flagMustUse' => 1,
					'id' => 'FlagFiscalReport',
					'strTitle' => '決算整理仕訳',
					'strExplain' => '決算整理仕訳の取引日時は会期末になります。',
					'value' => 0,
					'flagErrorNow' => 0,
					'arrayError' => array(
						array( 'flagCheck' => 'blank', 'flagUse' => 1, 'flagNow' => 0, 'flagType' => 'empty', 'strComment' => array( 'common' => '記入漏れがあるようです。', ),),
						array( 'flagCheck' => 'attest', 'flagUse' => 1, 'strComment' => array('spaceMax' => 'バージョン更新するための作業領域が足りないようです。当該仕訳は、削除扱いにして新しく仕訳を切ってください。',),),
					),
					'flagContentUse' => 0,
					'flagCommentUse' => 0, 'strCommentTitle' => '', 'strComment' => '',
					'flagTag' => 'select', 'flagInputType' => '', 'numMaxlength' => 0,
					'numWidth' => 40, 'unitWidth' => '%', 'numHeight' => 0, 'unitHeight' => '',
					'arrayOption' => array(),
					'flagFoldUse' => 1, 'flagFoldNow' => 0,
				),
				array(
					'flagMustUse' => 1,
					'id' => 'StampBook',
					'strTitle' => '取引日時', 'strExplain' => '取引日時を会計期間内 (<%stampMin%> ～ <%stampMax%>) に設定してください。<br>　※ 設定例) <%stampMin%>-12:00<br>　※ 半角英数で記入してください。', 'value' => '',
					'flagErrorNow' => 0,
					'arrayError' => array(
						array( 'flagCheck' => 'blank', 'flagUse' => 1, 'flagNow' => 0, 'flagType' => 'empty', 'strComment' => array( 'common' => '記入が必要なようです。', ),),
						array( 'flagCheck' => 'format', 'flagUse' => 1, 'flagNow' => 0, 'flagArr' => 0, 'flagType' => 'date-time-date', 'strComment' => array( 'common' => '指定されたフォーマットに沿って記入されていないようです。',  ), ),
						array( 'flagCheck' => 'attest', 'flagUse' => 1, 'strComment' => array('term' => '会計期間外の取引日時が設定されているようです。', ),),
					),
					'flagContentUse' => 0,
					'flagCommentUse' => 0, 'strCommentTitle' => '', 'strComment' => '',
					'flagTag' => 'input', 'flagInputType' => 'text', 'numMaxlength' => 16,
					'numWidth' => 90, 'unitWidth' => '%', 'numHeight' => 0, 'unitHeight' => '',
					'arrayOption' => array(),
					'flagFoldUse' => 1, 'flagFoldNow' => 0,
					'varsFormCalender' => array(
						'varsStatus' => array(
							'numLeft' => 0,
							'numTop' => 0,
							'flagMaxUse' => 1,
							'flagMaxAutoUse' => 0,
							'stampMax' => 0,
							'flagMainUse' => 1,
							'flagMainAutoUse' => 1,
							'stampMain' => 0,
							'flagMinUse' => 1,
							'flagMinAutoUse' => 0,
							'stampMin' => 0,
							'stampPoint' => 0,
							'flagFormatDisplay' => 9,
							'flagFormatCheck' => 'date-time-date',
						),
					),
				),
				array(
					'flagMustUse' => 0,
					'id' => 'StrTitle',
					'strTitle' => '摘要', 'strExplain' => '摘要があれば記入してください。', 'value' => '',
					'flagErrorNow' => 0,
					'arrayError' => array(
						array( 'flagCheck' => 'blank', 'flagUse' => 1, 'flagNow' => 0, 'flagType' => 'empty', 'strComment' => array( 'common' => '記入が必要なようです。', ),),
						array( 'flagCheck' => 'max', 'flagUse' => 1, 'flagNow' => 0, 'flagType' => 'str', 'num' => 100, 'strComment' => array( 'common' => '入力文字数が多すぎるようです。', ),),
						array( 'flagCheck' => 'attest', 'flagUse' => 1, 'strComment' => array(
							'blank' => '摘要がないため仕訳予測ができないようです。',
						),),
					),
					'flagContentUse' => 0,
					'flagCommentUse' => 0, 'strCommentTitle' => '', 'strComment' => '',
					'flagTag' => 'input', 'flagInputType' => 'text', 'numMaxlength' => 100,
					'numWidth' => 90, 'unitWidth' => '%', 'numHeight' => 0, 'unitHeight' => '',
					'arrayOption' => array(),
					'flagFoldUse' => 1, 'flagFoldNow' => 0,
					'varsTextBtn' => array(),
				),
				array(
					'flagMustUse' => 0,
					'id' => 'DummyJsonDetail',
					'strTitle' => '仕訳',
					'strExplain' => '',
					'value' => '-',
					'flagErrorNow' => 0,
					'arrayError' => array(),
					'flagContentUse' => 0,
					'flagCommentUse' => 0, 'strCommentTitle' => '', 'strComment' => '',
					'flagTag' => 'input', 'flagInputType' => 'text', 'numMaxlength' => 1000,
					'numWidth' => 90, 'unitWidth' => '%', 'numHeight' => 0, 'unitHeight' => '',
					'arrayOption' => array(),
					'flagFoldUse' => 1, 'flagFoldNow' => 0,
				),
				array(
					'flagMustUse' => 1,
					'id' => 'JsonDetail',
					'strTitle' => '仕訳', 'strExplain' => '', 'value' => 'dummy',
					'flagErrorNow' => 0,
					'arrayError' => array(
						array( 'flagCheck' => 'blank', 'flagUse' => 1, 'flagNow' => 0, 'flagType' => 'empty', 'strComment' => array( 'common' => '記入が必要なようです。', ),),
						array( 'flagCheck' => 'attest', 'flagUse' => 1, 'strComment' => array(
							'numSum' => '貸借合計金額が一致しないようです。',
							'numSumMax' => '貸借合計金額は、99,999,999,999が上限となっています。',
							'numRowMax' => '仕訳行数は、10行までが上限となっています。',
							'strDebit' => '借方に記入漏れの仕訳があるようです。',
							'strCredit' => '貸方に記入漏れの仕訳があるようです。',
							'strRow' => '借方と貸方に記入漏れの仕訳があるようです。',
							'strBlank' => '記入漏れのようです。',
							'strOldConsumption' => '保存されていた仕訳データが前提としている消費税設定が現在の設定と異なるため仕訳データを挿入できなかったようです。',
							'strOldIdAccountTitle' => '保存されていた勘定科目が現在存在しないため仕訳データを挿入できなかったようです。',
							'strOldIdSubAccountTitle' => '保存されていた補助科目が現在存在しないため仕訳データを挿入できなかったようです。',
							'strOldIdDepartment' => '保存されていた部門が現在存在しないため仕訳データを挿入できなかったようです。',
							'strOld' => '陳腐化したデータが混入していたため仕訳データを初期化しました。',
							'strConsumptionTax' => '施行前の消費税率が設定されているようです。',
							'strMonetaryClaim' => '「金銭債権譲渡」は2014年4月1日以後から設定できるようです。',
							'strOldConsumptionTax' => '陳腐化した仕訳データが混入しているようです。フォームを更新してください。',
							'strFlagIdAccountTitle' => '管理者が仕訳予測機能を有効にしていないようです。',
							'strFlagIdAccountTitleAdmin' => '仕訳予測機能が有効になっていないようです。<br>会計モジュール＞ナビボックスのメニュー＞管理者項目＞外部連携＞仕訳予測で仕訳予測を有効にしてください。',
						),),
					),
					'flagContentUse' => 1,
					'flagCommentUse' => 0, 'strCommentTitle' => '', 'strComment' => '',
					'flagTag' => 'input', 'flagInputType' => 'text', 'numMaxlength' => 10,
					'numWidth' => 90, 'unitWidth' => '%', 'numHeight' => 0, 'unitHeight' => '',
					'arrayOption' => array(),
					'flagFoldUse' => 1, 'flagFoldNow' => 0,
					'varsFormJournal' => array(
						'varsStatus' => array(
							'flagAddUse' => 1,
							'flagSortUpUse' => 1,
							'flagSortDownUse' => 1,
							'flagSortSideUse' => 1,
							'flagSummaryUse' => 1,
							'flagEditUse' => 0,
							'flagCopyUse' => 1,
							'flagRemoveUse' => 1,
							'flagBtnTextUse' => 1,
							'flagBtnTextTaxUse' => 1,
							'flagBtnTitleUse' => 1,
							'numLeft' => 0,
							'numTop' => 0,
						),
						'varsSummary' => array(
							'numSumDebit' => 0,
							'numSumCredit' => 0,
							'numSumConsumptionTaxDebit' => 0,
							'numSumConsumptionTaxCredit' => 0,
							'strSumDebit' => '',
							'strSumCredit' => '',
							'strSumConsumptionTaxDebit' => '',
							'strSumConsumptionTaxCredit' => '',
						),
						'varsRule' => array(),
						'varsDetail' => array(),
						'varsTmpl' => array(
							'strBtnDictionary' => '逆引き辞典',
							'strBtnTitle' => '仕訳予測',
							'strDebitSum' => '借方合計',
							'strCreditSum' => '貸方合計',
							'strUnit' => '単位( 円 )',
							'strConsumptionTax' => '消費税',
							'varsSelectTag' => array(
								'flagConsumptionTaxWithoutCalc' => array(
									array('strTitle' => '内税','value' => 1,),
									array('strTitle' => '外税','value' => 2,),
									array('strTitle' => '別記','value' => 3,),
								),
								'numRateConsumptionTax' => array(
									array('strTitle' => '5%','value' => 5,),
									array('strTitle' => '8%','value' => 8,),
									//array('strTitle' => '10%','value' => 10,),
								),
								'varsBtnDictionary' => array(),
							),
							'varsStrTitle' => array(
								'flagConsumptionTaxWithoutCalc' => array(
									'1' => '内税',
									'2' => '外税',
									'3' => '別記',
								),
								'numRateConsumptionTax' => array(
									'5' => '5%',
									'8' => '8%',
									/*
									 * 2014-2015 start
									*/
									//'10' => '10%',
									/*
									 * 2014-2015 end
									*/
								),
							),

							'varsBlank' => array(
								'strTitle' => '指定なし',
								'value' => '',
							),
							'varsDetail' => array(
								'idAccountTitleDebit' => '',
								'idAccountTitleCredit' => '',
								'numSum' => 0,
								'numSumDebit' => 0,
								'numSumCredit' => 0,
								'varsDetail' => array(),
								'varsEntityNation' => array(),
								'numVersionConsumptionTax' => 0,
							),
							'varsDetailVarsDetail' => array(
								'id' => '',
								'arrDebit' => array(
									'idAccountTitle' => '',
									'numValue' => '',
									'numValueConsumptionTax' => '',
									'numRateConsumptionTax' => '',
									'idDepartment' => '',
									'idSubAccountTitle' => '',
									'flagConsumptionTaxFree' => '',
									'flagConsumptionTaxIncluding' => '',
									'flagConsumptionTaxGeneralRuleEach' => '',
									'flagConsumptionTaxGeneralRuleProration' => '',
									'flagConsumptionTaxSimpleRule' => '',
									'flagConsumptionTaxWithoutCalc' => '',
									'flagConsumptionTaxCalc' => '',
								),
								'arrCredit' => array(
									'idAccountTitle' => '',
									'numValue' => '',
									'numValueConsumptionTax' => '',
									'numRateConsumptionTax' => '',
									'idDepartment' => '',
									'idSubAccountTitle' => '',
									'flagConsumptionTaxFree' => '',
									'flagConsumptionTaxIncluding' => '',
									'flagConsumptionTaxGeneralRuleEach' => '',
									'flagConsumptionTaxGeneralRuleProration' => '',
									'flagConsumptionTaxSimpleRule' => '',
									'flagConsumptionTaxWithoutCalc' => '',
									'flagConsumptionTaxCalc' => '',
								),
							),
							'varsFormTemp' => array(
								'varsStatus' => array(
									'numLeft' => 0,
									'numTop' => 0,
								),
								'varsDetail' => array(
									'flagTag'       => '',
									'flagInputType' => '',
									'numMaxlength'  => 11,
									'numWidth'      => 0,
									'unitWidth'     => 'px',
									'numHeight'     => 0,
									'unitHeight'    => 'px',
									'arrayOption'   => array(),
									'flagLine'      => '',
									'flagColumn'    => '',
									'value'         => '',
									'vars'          => array(),
								),
							),
						),
					),
				),
				array(
					'flagMustUse' => 0,
					'id' => 'DummyStampBook',
					'strTitle' => '取引日時', 'strExplain' => '', 'value' => '',
					'flagErrorNow' => 0,
					'arrayError' => array(),
					'flagContentUse' => 0,
					'flagCommentUse' => 0, 'strCommentTitle' => '', 'strComment' => '',
					'flagTag' => 'input', 'flagInputType' => 'text', 'numMaxlength' => 10,
					'numWidth' => 90, 'unitWidth' => '%', 'numHeight' => 0, 'unitHeight' => '',
					'arrayOption' => array(),
					'flagFoldUse' => 1, 'flagFoldNow' => 0,
					'varsTextBtn' => array(),
				),
				array(
					'flagMustUse' => 0,
					'id' => 'DummyFlagFiscalReport',
					'strTitle' => '決算整理仕訳',
					'strExplain' => '',
					'value' => '',
					'flagErrorNow' => 0,
					'arrayError' => array(),
					'flagContentUse' => 0,
					'flagCommentUse' => 0, 'strCommentTitle' => '', 'strComment' => '',
					'flagTag' => 'input', 'flagInputType' => 'text', 'numMaxlength' => 1000,
					'numWidth' => 90, 'unitWidth' => '%', 'numHeight' => 0, 'unitHeight' => '',
					'arrayOption' => array(),
					'flagFoldUse' => 1, 'flagFoldNow' => 0,
					'varsTextBtn' => array(),
				),
				array(
					'flagMustUse' => 0,
					'id' => 'DummyStrTitle',
					'strTitle' => '摘要', 'strExplain' => '摘要があれば記入してください。', 'value' => '',
					'flagErrorNow' => 0,
					'arrayError' => array(
						array( 'flagCheck' => 'blank', 'flagUse' => 1, 'flagNow' => 0, 'flagType' => 'empty', 'strComment' => array( 'common' => '記入が必要なようです。', ),),
						array( 'flagCheck' => 'max', 'flagUse' => 1, 'flagNow' => 0, 'flagType' => 'str', 'num' => 100, 'strComment' => array( 'common' => '入力文字数が多すぎるようです。', ),),
					),
					'flagContentUse' => 0,
					'flagCommentUse' => 0, 'strCommentTitle' => '', 'strComment' => '',
					'flagTag' => 'input', 'flagInputType' => 'text', 'numMaxlength' => 100,
					'numWidth' => 90, 'unitWidth' => '%', 'numHeight' => 0, 'unitHeight' => '',
					'arrayOption' => array(),
					'flagFoldUse' => 1, 'flagFoldNow' => 0,
					'varsTextBtn' => array(),
				),
				array(
					'flagMustUse' => 0,
					'id' => 'ArrCommaIdLogFile',
					'strTitle' => '証憑ファイル', 'strExplain' => '仕訳に関連する証憑があれば選択してください。', 'value' => '',
					'flagErrorNow' => 0,
					'arrayError' => array(
						array( 'flagCheck' => 'blank', 'flagUse' => 1, 'flagNow' => 0, 'flagType' => 'empty', 'strComment' => array( 'common' => '記入が必要なようです。', ),),
						array( 'flagCheck' => 'word', 'flagUse' => 1, 'flagNow' => 0, 'flagArr' => 'comma', 'flagType' => 'num', 'strComment' => array( 'common' => '予定されていない処理が起こりました。システムエラー。', ), ),
						array( 'flagCheck' => 'attest', 'flagUse' => 1, 'strComment' => array('noneFile' => '適切な証憑ファイルが設定されていないようです。古い情報を更新する必要がありそうです。', ),),
					),
					'flagContentUse' => 1,
					'flagCommentUse' => 0, 'strCommentTitle' => '', 'strComment' => '',
					'flagTag' => 'textarea', 'flagInputType' => '', 'numMaxlength' => 0,
					'unitWidth' => '%', 'numWidth' => 90, 'unitHeight' => 'px', 'numHeight' => 100,
					'arrayOption' => array(),
					'varsFormArea' => array(
						'varsStatus' => array(
							'numWidth' => 0,
							'numHeight' => 200,
							'flagTogleUse' => 1,
						),
						'templateDetail' => array(
							'id' => 'Tmpl', 'flagUse' => 1, 'flagMoveUse' => 1, 'flagInsertUse' => 0, 'flagBtnUse' => 1, 'flagFoldUse' => 0, 'flagFoldNow' => 0, 'flagChildrenUse' => 0, 'flagCheckUse' => 0, 'flagCheckNow' => 0, 'flagRemoveUse' => 1, 'flagEditUse' => 1,
							'strTitle' => '',
							'strClass' => 'codeLibBaseImgSheet',
							'vars' => array(
								'idTarget' => '',
							),
							'child' => array()
						),
						'varsChoice' => array(
							'idTarget' => 'PluginAccountingLogFile', 'idModule' => 'Accounting', 'flagCheckUse' => 1,
							'flagId' => 'ArrCommaIdLogFile',
						),
						'varsTree' => array(
							'varsStatus' => array(
								'flagUse' => 1,
								'flagMoveUse' => 0,
								'flagInsertUse' => 0,
								'flagSortUse' => 0,
								'flagFoldNow' => 0,
								'flagFoldUse' => 0,
								'flagCakeUse' => 0,
								'flagCheckUse' => 0,
								'flagCheckNow' => 1,
								'flagBarUse' => 1,
								'flagInnerBtnBottomUse' => 0,
								'flagBtnBottomUse' => 0,
								'flagBtnUse' => 0,
								'flagFindUse' => 0,
								'flagAddUse' => 1,

								'flagEditUse' => 0,
								'flagEditNow' => 0,

								'flagRemoveUse' => 1,
								'flagRemoveNow' => 1,
								'flagPageUse' => 1,
								'flagInnerPageUse' => 1,
								'flagLinkUse' => 1,

								'strAddTitle' => '新規アップロード',
								'strLinkTitle' => '選択',
								'strRemoveTitle' => '全選択解除',
								'id' => 'JsonTree',
							),
							'varsFormat' => array(
								'id' => '',
								'flagType' => 'singleFormat',
								'numHeight' => 0,
								'numWidth' => 0,
								'flagHeaderUse' => 1,
								'flagHeaderLeftUse' => 1,
								'strTitleHeaderLeft' => '',
								'strClassHeaderLeft' => '',
								'flagHeaderRightUse' => 1,
								'strTitleHeaderRight' => '',
								'strClassHeaderRight' => 'codeLibBaseImgUnloading',
								'flagBodyAutoUse' => 1,
								'strBody' => '',
								'strClassBody' => '',
								'flagFooderUse' => 1,
								'flagFooderLeftUse' => 1,

								'strTitleFooderLeft' => '',
								'strClassFooderLeft' => '',
								'flagFooderRightUse' => 1,

								'strTitleFooderRight' => '',
								'strClassFooderRight' => '',

								'flagHeaderLeftWidth' => 0,
								'numWidthHeaderLeft' => 0,
								'flagHeaderRightWidth' => 0,
								'numWidthHeaderRight' => 0,
								'flagFooderLeftWidth' => 0,
								'numWidthFooderLeft' => 0,
								'flagFooderRightWidth' => 0,
								'numWidthFooderRight' => 0,
							),
							'varsFind' => array(),
							'varsBtnBottom' => array(),
							'varsPage' => array(
								'varsStatus' => array(
									'flagStatusUse' => 1,
									'flagTopUse' => 1,
									'flagEndUse' => 1,
									'flagNextUse' => 1,
									'flagPrevUse' => 1,
									'numRows' => 0,
									'numLotNow' => 0,
								),
							),
							'varsDetail' => array(),
						),
						'varsDetail' => array(),
					),
					'flagFoldUse' => 1, 'flagFoldNow' => 0,
				),
				array(
					'flagMustUse' => 0,
					'id' => 'DummyJsonFile',
					'strTitle' => '証憑ファイル',
					'strExplain' => '',
					'value' => '証憑ファイルなし',
					'flagErrorNow' => 0,
					'arrayError' => array(),
					'flagContentUse' => 0,
					'flagCommentUse' => 0, 'strCommentTitle' => '', 'strComment' => '',
					'flagTag' => 'input', 'flagInputType' => 'text', 'numMaxlength' => 1000,
					'numWidth' => 90, 'unitWidth' => '%', 'numHeight' => 0, 'unitHeight' => '',
					'arrayOption' => array(),
					'flagFoldUse' => 1, 'flagFoldNow' => 0,
				),
				array(
					'flagMustUse' => 0,
					'id' => 'JsonFile',
					'strTitle' => '証憑ファイル', 'strExplain' => '', 'value' => 'dummy',
					'flagErrorNow' => 0,
					'arrayError' => array(
						array( 'flagCheck' => 'blank', 'flagUse' => 1, 'flagNow' => 0, 'flagType' => 'empty', 'strComment' => array( 'common' => '記入が必要なようです。', ),),

					),
					'flagContentUse' => 1,
					'flagCommentUse' => 0, 'strCommentTitle' => '', 'strComment' => '',
					'flagTag' => 'input', 'flagInputType' => 'text', 'numMaxlength' => 10,
					'numWidth' => 90, 'unitWidth' => '%', 'numHeight' => 0, 'unitHeight' => '',
					'arrayOption' => array(),
					'flagFoldUse' => 1, 'flagFoldNow' => 0,
					'varsFormCheck' => array(
						'varsStatus' => array(
							'flagBtnUse' => 0,
						),
						'varsColumn' => array(
							array(
								'id' => 'StrNo',
								'flagType' => '',
								'strTitle' => 'No',
								'numWidth' => 30,
							),/*
							array(
								'id' => 'StrStatus',
								'flagType' => '',
								'strTitle' => '状態',
								'numWidth' => 50,
							),*/
							array(
								'id' => 'StrTitle',
								'flagType' => '',
								'strTitle' => 'ファイル',
								'numWidth' => 150,
							),
							array(
								'id' => 'BtnDetail',
								'flagType' => 'btn',
								'strTitle' => 'DLL',
								'numWidth' => 40,
							),
						),
						'varsDetail' => array(),
						'tmplDetail' => array(
							'id' => '',
							'varsContext' => array(),
							'varsColumnDetail' => array(
								'strNo' => '',
								'strStatus' => '',
								'strTitle' => '',
								'btnDetailUse' => 1,
								'btnDetailATagUse' => 0,
								'btnDetailPath' => '',
								'btnDetailLock' => 0,
								'btnDetailStrClass' => 'codeLibFormCheckImgSheet',
								'btnDetailStrClassLock' => 'codeLibFormCheckImgSheetLock',
							),
						),
					),
				),
				array(
					'flagMustUse' => 0,
					'id' => 'ArrCommaIdAccountPermit',
					'strTitle' => '承認アカウント', 'strExplain' => '当該仕訳に対して承認を求める任意のアカウントを選択してください。', 'value' => '',
					'flagErrorNow' => 0,
					'arrayError' => array(
						array( 'flagCheck' => 'blank', 'flagUse' => 1, 'flagNow' => 0, 'flagType' => 'empty', 'strComment' => array( 'common' => '記入が必要なようです。', ),),
						array( 'flagCvarsFormAreaheck' => 'word', 'flagUse' => 1, 'flagNow' => 0, 'flagArr' => 'comma', 'flagType' => 'num', 'strComment' => array( 'common' => '予定されていない処理が起こりました。システムエラー。',  ), ),
						array( 'flagCheck' => 'attest', 'flagUse' => 1, 'strComment' => array(
							'attention' => '【 再確認 】申請者又は担当者が承認アカウントに含まれているようです。',
							'none' => 'アカウント情報が陳腐化しているようです。現在のアカウント情報にて設定する必要がありそうです。',
						),),
					),
					'flagContentUse' => 1,
					'flagCommentUse' => 0, 'strCommentTitle' => '', 'strComment' => '',
					'flagTag' => 'textarea', 'flagInputType' => '', 'numMaxlength' => 0,
					'unitWidth' => '%', 'numWidth' => 90, 'unitHeight' => 'px', 'numHeight' => 100,
					'arrayOption' => array(),
					'varsFormArea' => array(
						'varsStatus' => array(
							'numWidth' => 0,
							'numHeight' => 200,
							'flagTogleUse' => 1,
						),
						'templateDetail' => array(
							'id' => 'Tmpl', 'flagUse' => 1, 'flagMoveUse' => 1, 'flagInsertUse' => 0, 'flagBtnUse' => 1, 'flagFoldUse' => 0, 'flagFoldNow' => 0, 'flagChildrenUse' => 0, 'flagCheckUse' => 0, 'flagCheckNow' => 0, 'flagRemoveUse' => 1, 'flagEditUse' => 1,
							'strTitle' => '',
							'strClass' => 'codeLibBaseImgSheet',
							'strClassFont' => '',
							'vars' => array(
								'idTarget' => '',
							),
							'child' => array()
						),
						'varsTmpl' => array(
							'strClassFont' => 'codeLibBaseFontOrange',
							'strApply' => '【申請者】',
							'strCharge' => '【担当者】',
						),
						'varsChoice' => array(
							'idTarget' => 'PluginAccountingAccountEntityPermit', 'idModule' => 'Accounting', 'flagCheckUse' => 1,
							'flagId' => 'Charge',
						),
						'varsTree' => array(
							'varsStatus' => array(
								'flagUse' => 1,
								'flagMoveUse' => 0,
								'flagInsertUse' => 0,
								'flagSortUse' => 0,
								'flagFoldNow' => 0,
								'flagFoldUse' => 0,
								'flagFontUse' => 1,
								'flagCakeUse' => 0,
								'flagCheckUse' => 0,
								'flagCheckNow' => 1,
								'flagBarUse' => 1,
								'flagInnerBtnBottomUse' => 0,
								'flagBtnBottomUse' => 0,
								'flagBtnUse' => 0,
								'flagFindUse' => 0,
								'flagAddUse' => 0,
								'flagEditUse' => 0,
								'flagEditNow' => 0,
								'flagRemoveUse' => 1,
								'flagRemoveNow' => 1,
								'flagPageUse' => 1,
								'flagLinkUse' => 1,
								'strAddTitle' => '',
								'strLinkTitle' => '選択',
								'strRemoveTitle' => '全選択解除',
								'flagInnerPageUse' => 1,
								'id' => 'JsonTree',
							),
							'varsFormat' => array(
								'id' => '',
								'flagType' => 'singleFormat',
								'numHeight' => 0,
								'numWidth' => 0,
								'flagHeaderUse' => 1,
								'flagHeaderLeftUse' => 1,
								'strTitleHeaderLeft' => '',
								'strClassHeaderLeft' => '',
								'flagHeaderRightUse' => 1,
								'strTitleHeaderRight' => '',
								'strClassHeaderRight' => 'codeLibBaseImgUnloading',
								'flagBodyAutoUse' => 1,
								'strBody' => '',
								'strClassBody' => '',
								'flagFooderUse' => 1,
								'flagFooderLeftUse' => 1,

								'strTitleFooderLeft' => '',
								'strClassFooderLeft' => '',
								'flagFooderRightUse' => 1,

								'strTitleFooderRight' => '',
								'strClassFooderRight' => '',

								'flagHeaderLeftWidth' => 0,
								'numWidthHeaderLeft' => 0,
								'flagHeaderRightWidth' => 0,
								'numWidthHeaderRight' => 0,
								'flagFooderLeftWidth' => 0,
								'numWidthFooderLeft' => 0,
								'flagFooderRightWidth' => 0,
								'numWidthFooderRight' => 0,
							),
							'varsFind' => array(),
							'varsBtnBottom' => array(),
							'varsPage' => array(
								'varsStatus' => array(
									'flagStatusUse' => 1,
									'flagTopUse' => 1,
									'flagEndUse' => 1,
									'flagNextUse' => 1,
									'flagPrevUse' => 1,
									'numRows' => 0,
									'numLotNow' => 0,
								),
							),
							'varsDetail' => array(),
						),
						'varsDetail' => array(),
					),
					'flagFoldUse' => 1, 'flagFoldNow' => 0,
				),
				array(
					'flagMustUse' => 0,
					'id' => 'DummyJsonPermitHistory',
					'strTitle' => '承認履歴',
					'strExplain' => '',
					'value' => '承認申請なし',
					'flagErrorNow' => 0,
					'arrayError' => array(),
					'flagContentUse' => 0,
					'flagCommentUse' => 0, 'strCommentTitle' => '', 'strComment' => '',
					'flagTag' => 'input', 'flagInputType' => 'text', 'numMaxlength' => 1000,
					'numWidth' => 90, 'unitWidth' => '%', 'numHeight' => 0, 'unitHeight' => '',
					'arrayOption' => array(),
					'flagFoldUse' => 1, 'flagFoldNow' => 0,
				),
				array(
					'flagMustUse' => 0,
					'id' => 'JsonPermitHistory',
					'strTitle' => '承認履歴', 'strExplain' => '', 'value' => 'dummy',
					'flagErrorNow' => 0,
					'arrayError' => array(
						array( 'flagCheck' => 'blank', 'flagUse' => 1, 'flagNow' => 0, 'flagType' => 'empty', 'strComment' => array( 'common' => '記入が必要なようです。', ),),
					),
					'flagContentUse' => 1,
					'flagCommentUse' => 0, 'strCommentTitle' => '', 'strComment' => '',
					'flagTag' => 'input', 'flagInputType' => 'text', 'numMaxlength' => 10,
					'numWidth' => 90, 'unitWidth' => '%', 'numHeight' => 0, 'unitHeight' => '',
					'arrayOption' => array(),
					'flagFoldUse' => 1, 'flagFoldNow' => 0,
					'varsFormCheck' => array(
						'varsStatus' => array(
							'flagBtnUse' => 0,
						),
						'varsColumn' => array(
							array(
								'id' => 'StrNo',
								'flagType' => '',
								'strTitle' => 'No',
								'numWidth' => 30,
							),
							array(
								'id' => 'StrStatus',
								'flagType' => '',
								'strTitle' => '状態',
								'numWidth' => 50,
							),
							array(
								'id' => 'StampRegister',
								'flagType' => '',
								'strTitle' => '申請日時',
								'numWidth' => 120,
							),
							array(
								'id' => 'StrCodeName',
								'flagType' => '',
								'strTitle' => '申請者',
								'numWidth' => 100,
							),
							array(
								'id' => 'StampPermit',
								'flagType' => '',
								'strTitle' => '承認日時',
								'numWidth' => 120,
							),
							array(
								'id' => 'StrNumSum',
								'flagType' => '',
								'strTitle' => '賛/反/要/全',
								'numWidth' => 100,
							),
							array(
								'id' => 'BtnDetail',
								'flagType' => 'btn',
								'strTitle' => '詳細',
								'numWidth' => 40,
							),
						),
						'varsDetail' => array(),
						'tmplDetail' => array(
							'id' => '',
							'varsContext' => array(),
							'varsColumnDetail' => array(
								'strNo' => '',
								'strStatus' => '',
								'strCodeName' => '',
								'stampRegister' => '',
								'stampPermit' => '',
								'strNumSum' => '',
								'btnDetailUse' => 1,
								'btnDetailLock' => 0,
								'btnDetailStrClass' => 'codeLibFormCheckImgDetail',
								'btnDetailStrClassLock' => 'codeLibFormCheckImgDetailLock',
							),
						),
						'tmplContext' => array(
							'varsStatus' => array(
								'numTop' => 0,
								'numLeft' => 0,
							),
							'varsDetail' => array(),
						),
						'tmplContextDetail' => array(
							'id' => '', 'flagCheckUse' => 0, 'flagCheckNow' => 0,
							'strTitle' => '', 'strClass' => '',
							'strClassFont' => 'codeLibBaseFontBlack',
							'vars' => array( 'idTarget' => '',),
							'child' => array(),
						),
					),
				),
				array(
					'flagMustUse' => 0,
					'id' => 'NumSumMax',
					'strTitle' => '要承認数',
					'strExplain' => '仕訳が承認されるのに必要な人数を設定してください。',
					'value' => 0,
					'flagErrorNow' => 0,
					'arrayError' => array(
						array( 'flagCheck' => 'blank', 'flagUse' => 1, 'flagNow' => 0, 'flagType' => 'empty', 'strComment' => array( 'common' => '記入漏れがあるようです。', ),),
					),
					'flagContentUse' => 0,
					'flagCommentUse' => 0, 'strCommentTitle' => '', 'strComment' => '',
					'flagTag' => 'select', 'flagInputType' => '', 'numMaxlength' => 0,
					'numWidth' => 40, 'unitWidth' => '%', 'numHeight' => 0, 'unitHeight' => '',
					'arrayOption' => array(
						array('strTitle' => '0人', 'value' => 0,),
					),
					'varsTmpl' => array(
						'strPerson' => '人',
					),
					'flagFoldUse' => 1, 'flagFoldNow' => 0,
					'flagHideUse' => 1, 'flagHideNow' => 1,
				),
				array(
					'flagMustUse' => 0,
					'id' => 'ArrSpaceStrTag',
					'strTitle' => 'タグ', 'strExplain' => '必要なタグを空白区切りで設定してください。', 'value' => '',
					'flagErrorNow' => 0,
					'arrayError' => array(
						array( 'flagCheck' => 'blank', 'flagUse' => 1, 'flagNow' => 0, 'flagType' => 'empty', 'strComment' => array( 'common' => '記入が必要なようです。', ),),
						array(	'flagCheck' => 'max', 'flagUse' => 1, 'flagNow' => 0, 'flagType' => 'str', 'num' => 1000, 'strComment' => array( 'common' => '入力文字数が多すぎるようです。', ),),
					),
					'flagContentUse' => 0,
					'flagCommentUse' => 0, 'strCommentTitle' => '', 'strComment' => '',
					'flagTag' => 'input', 'flagInputType' => 'text', 'numMaxlength' => 1000,
					'numWidth' => 90, 'unitWidth' => '%', 'numHeight' => 0, 'unitHeight' => '',
					'arrayOption' => array(),
					'flagFoldUse' => 1, 'flagFoldNow' => 0,
					'varsTextBtn' => array(),
				),
				array(
					'flagMustUse' => 0,
					'id' => 'JsonChargeHistory',
					'strTitle' => '担当者履歴', 'strExplain' => '', 'value' => 'dummy',
					'flagErrorNow' => 0,
					'arrayError' => array(
						array( 'flagCheck' => 'blank', 'flagUse' => 1, 'flagNow' => 0, 'flagType' => 'empty', 'strComment' => array( 'common' => '記入が必要なようです。', ),),
					),
					'flagContentUse' => 1,
					'flagCommentUse' => 0, 'strCommentTitle' => '', 'strComment' => '',
					'flagTag' => 'input', 'flagInputType' => 'text', 'numMaxlength' => 0,
					'numWidth' => 80, 'unitWidth' => '%', 'numHeight' => 0, 'unitHeight' => '',
					'arrayOption' => array(),
					'flagFoldUse' => 1, 'flagFoldNow' => 0,
					'strHtml' => '',
					'varsTextBtn' => array(),
				),
				array(
					'flagMustUse' => 0,
					'id' => 'StrVersion',
					'strTitle' => 'バージョン', 'strExplain' => '', 'value' => '',
					'flagErrorNow' => 0,
					'arrayError' => array(),
					'flagContentUse' => 0,
					'flagCommentUse' => 0, 'strCommentTitle' => '', 'strComment' => '',
					'flagTag' => 'input', 'flagInputType' => 'text', 'numMaxlength' => 100,
					'numWidth' => 90, 'unitWidth' => '%', 'numHeight' => 0, 'unitHeight' => '',
					'arrayOption' => array(),
					'flagFoldUse' => 1, 'flagFoldNow' => 0,
				),
				array(
					'flagMustUse' => 0,
					'id' => 'StampRegister',
					'strTitle' => '記録日時', 'strExplain' => '', 'value' => '',
					'flagErrorNow' => 0,
					'arrayError' => array(),
					'flagContentUse' => 0,
					'flagCommentUse' => 1, 'strCommentTitle' => '', 'strComment' => '',
					'flagTag' => '', 'flagInputType' => '', 'numMaxlength' => 0,
					'numWidth' => 0, 'unitWidth' => '', 'numHeight' => 0, 'unitHeight' => '',
					'arrayOption' => array(),
					'flagFoldUse' => 1, 'flagFoldNow' => 0,
				),
				array(
					'flagMustUse' => 0,
					'id' => 'StampUpdate',
					'strTitle' => '更新日時', 'strExplain' => '', 'value' => '',
					'flagErrorNow' => 0,
					'arrayError' => array(),
					'flagContentUse' => 0,
					'flagCommentUse' => 1, 'strCommentTitle' => '', 'strComment' => '',
					'flagTag' => '', 'flagInputType' => '', 'numMaxlength' => 0,
					'numWidth' => 0, 'unitWidth' => '', 'numHeight' => 0, 'unitHeight' => '',
					'arrayOption' => array(),
					'flagFoldUse' => 1, 'flagFoldNow' => 0,
				),
				array(
					'flagMustUse' => 0,
					'id' => 'DummyStatus',
					'strTitle' => '状態',
					'strExplain' => '',
					'value' => '',
					'flagErrorNow' => 0,
					'arrayError' => array(),
					'flagContentUse' => 0,
					'flagCommentUse' => 0, 'strCommentTitle' => '', 'strComment' => '',
					'flagTag' => 'input', 'flagInputType' => 'text', 'numMaxlength' => 1000,
					'numWidth' => 90, 'unitWidth' => '%', 'numHeight' => 0, 'unitHeight' => '',
					'arrayOption' => array(),
					'flagFoldUse' => 1, 'flagFoldNow' => 0,
					'varsTextBtn' => array(),
				),
				array(
					'flagMustUse' => 0,
					'id' => 'Id',
					'strTitle' => '通番', 'strExplain' => '', 'value' => '',
					'flagErrorNow' => 0,
					'arrayError' => array(),
					'flagContentUse' => 0,
					'flagCommentUse' => 1, 'strCommentTitle' => '', 'strComment' => '',
					'flagTag' => '', 'flagInputType' => '', 'numMaxlength' => 0,
					'numWidth' => 0, 'unitWidth' => '', 'numHeight' => 0, 'unitHeight' => '',
					'arrayOption' => array(),
					'flagFoldUse' => 1, 'flagFoldNow' => 0,
					'varsTextBtn' => array(),
				),
			),
			'varsPage' => array(),
			'varsDetail' => array(),
			'varsBtn' => array(
				array(
					'flagUse' => 0, 'flagLeftUse' => 0, 'flagRightUse' => 1, 'flagTextUse' => 0, 'flagBtnUse' => 1,
					'id' => 'BtnDelete',
					'vars' => array( 'idTarget' => 'delete', ),
					'strTitle' => '削除扱い',
				),
				array(
					'flagUse' => 0, 'flagLeftUse' => 0, 'flagRightUse' => 1, 'flagTextUse' => 0, 'flagBtnUse' => 1,
					'id' => 'BtnApplyBack',
					'vars' => array( 'idTarget' => 'back', ),
					'strTitle' => '差戻し',
				),
				array(
					'flagUse' => 0, 'flagLeftUse' => 0, 'flagRightUse' => 1, 'flagTextUse' => 0, 'flagBtnUse' => 1,
					'id' => 'BtnApply',
					'vars' => array( 'idTarget' => 'permit', ),
					'strTitle' => '承認',
				),
			),
			'varsStart' => array(
				'strTitle' => '詳細',
				'strClass' => 'codeLibBaseImgSheet',
				'varsEdit' => array(
					'flagAddUse' => 1,
				),
			),
			'view' => array(
				'varsFormat' => array(
					'id' => '',
					'flagType' => 'normalFormat',
					'numHeight' => 0,
					'numWidth' => 0,
					'flagHeaderLeftUse' => 1,
					'strTitleHeaderLeft' => '詳細',
					'strClassHeaderLeft' => '',
					'flagHeaderRightUse' => 1,
					'strTitleHeaderRight' => '',
					'strClassHeaderRight' => 'codeLibBaseImgUnloading',
					'flagBodyAutoUse' => 0,
					'strBody' => '',
					'strClassBody' => '',
					'flagFooderUse' => 1,
					'flagFooderLeftUse' => 1,
					'strTitleFooderLeft' => '',
					'strClassFooderLeft' => '',
					'flagFooderRightUse' => 1,
					'strTitleFooderRight' => '',
					'strClassFooderRight' => '',
					'flagHeaderLeftWidth' => 1,
					'numWidthHeaderLeft' => 0,
					'flagHeaderRightWidth' => 0,
					'numWidthHeaderRight' => 0,
					'flagFooderLeftWidth' => 0,
					'numWidthFooderLeft' => 0,
					'flagFooderRightWidth' => 0,
					'numWidthFooderRight' => 0,
				),
				'varsEdit' => array(
					'flagReloadUse' => 1,
					'flagAddUse' => 1,
					'flagCopyUse' => 1,
					'flagEditUse' => 1,
				),
				'varsDetail' => array(
					'varsStatus' => array(
						'flagCakeUse' => 1,
						'flagFoldUse' => 1,
						'flagFoldNow' => 0,
						'flagLineStatusUse' => 0,
						'flagAddUse' => 0,
						'flagRemoveUse' => 0,
						'flagEditUse' => 0,
						'flagBarUse' => 1,
						'flagPageUse' => 0,
						'flagInnerPageUse' => 0,
						'flagBtnBottomUse' => 1,
						'flagFindUse' => 0,
						'flagInnerFindUse' => 0,
					),
					'varsFormat' => array(
						'id' => '',
						'flagType' => 'singleFormat',
						'numHeight' => 0,
						'numWidth' => 0,
						'flagHeaderUse' => 1,
						'flagHeaderLeftUse' => 1,
						'strTitleHeaderLeft' => '',
						'strClassHeaderLeft' => '',
						'flagHeaderRightUse' => 0,
						'strTitleHeaderRight' => '',
						'strClassHeaderRight' => '',
						'flagBodyAutoUse' => 1,
						'strBody' => '',
						'strClassBody' => '',
						'flagFooderUse' => 0,
						'flagFooderLeftUse' => 1,
						'strTitleFooderLeft' => '',
						'strClassFooderLeft' => '',
						'flagFooderRightUse' => 1,
						'strTitleFooderRight' => '',
						'strClassFooderRight' => '',

						'flagHeaderLeftWidth' => 0,
						'numWidthHeaderLeft' => 0,
						'flagHeaderRightWidth' => 0,
						'numWidthHeaderRight' => 0,
						'flagFooderLeftWidth' => 0,
						'numWidthFooderLeft' => 0,
						'flagFooderRightWidth' => 0,
						'numWidthFooderRight' => 0,
					),
					'varsFind' => array(
						'strTitle' => 'ハイライト検索',
						'numWidth' => 70,//%
					),
					'varsPage' => array(),
					'varsBtn' => array(),
					'varsDetail' => array(),
				),
			),
			'form' => array(),
		),
		'varsTemplateLayout' => array(
			'varsStatus' => array(
				'flagNaviUse' => 0,
				'flagNaviToolUse' => 0,
				'flagListUse' => 1,
				'flagListToolUse' => 1,
				'flagDetailUse' => 1,
				'flagDetailToolUse' => 1,
			),
			'varsLayout' => array(
				'varsStatus' => array(
					'flagNow' => 2,
					'flagResizeUse' => 1,
					'flagMoveUse' => 1,
					'flagCakeUse' => 1,
					'flagSwitchUse' => 1,
					'flagSwitchNow' => 'Standard',
					'switchList' => array('Standard','Wide'),
				),
				'varsDetail' => array(
					array(
						'id' => 'List',
						'flagBoxUse' => 1,
						'numPriority' => 2,
						'numSort' => 1,
						'numWidth' => 300,			'numHeight' => 200,
						'numWidthMin' => 200,		'numHeightMin' => 200,
						'numWidthStandard' => 300,	'numHeightStandard' => 200,
						'numWidthWide' => 300,		'numHeightWide' => 300,
						'numWidthClassic' => 300,	'numHeightClassic' => 300,
						'numHeightBox' => 0,		'numWidthBox' => 0,//auto
					),
					array(
						'id' => 'Detail',
						'flagBoxUse' => 1,
						'numPriority' => 1,
						'numSort' => 2,
						'numWidth' => 300,			'numHeight' => 200,
						'numWidthMin' => 300,		'numHeightMin' => 200,
						'numWidthStandard' => 200,	'numHeightStandard' => 200,
						'numWidthWide' => 300,		'numHeightWide' => 200,
						'numWidthClassic' => 300,	'numHeightClassic' => 200,
						'numHeightBox' => 0,		'numWidthBox' => 0,//auto
					),
				),
			),
			'navi' => array(),
			'list' => array(
				'varsFormat' => array(
					'id' => '',
					'flagType' => 'normalFormat',
					'numHeight' => 0,
					'numWidth' => 0,
					'flagHeaderLeftUse' => 1,
					'strTitleHeaderLeft' => '',
					'strClassHeaderLeft' => 'codeLibBaseImgBlank',
					'flagHeaderRightUse' => 1,
					'strTitleHeaderRight' => '',
					'strClassHeaderRight' => 'codeLibBaseImgUnloading',
					'flagBodyAutoUse' => 1,
					'strBody' => '',
					'strClassBody' => '',
					'flagFooderUse' => 1,
					'flagFooderLeftUse' => 1,
					'strTitleFooderLeft' => '',
					'strClassFooderLeft' => '',
					'flagFooderRightUse' => 1,
					'strTitleFooderRight' => '',
					'strClassFooderRight' => '',
					'flagHeaderLeftWidth' => 1,
					'numWidthHeaderLeft' => 0,
					'flagHeaderRightWidth' => 0,
					'numWidthHeaderRight' => 0,
					'flagFooderLeftWidth' => 0,
					'numWidthFooderLeft' => 0,
					'flagFooderRightWidth' => 1,
					'numWidthFooderRight' => 0,
				),
				'varsTool' => array(
					'varsDetail' => array(
						array(
							'flagUse' => 1,
							'flagNow' => 1,
							'id' => 'Reload',
							'strClass' => 'codeLibBtnImgReload',
							'strClassOver' => 'codeLibBtnImgReloadOver',
							'strClassNoactive' => 'codeLibBtnImgReloadNoactive',
							'strTitle' => '更新',
							'varsContext' => array(
								'varsStatus' => array(
									'numTop' => 0,
									'numLeft' => 0,
									'flagNow' => 'start',
								),
								'varsDetail' => array(
									array(
										'id' => 'Start', 'flagCheckUse' => 1, 'flagCheckNow' => 0,
										'strTitle' => '条件初期化', 'strClass' => 'codeLibBaseImgSheet',
										'vars' => array( 'idTarget' => 'start',),
										'child' => array(),
									),
									array(
										'id' => 'Same', 'flagCheckUse' => 1, 'flagCheckNow' => 0,
										'strTitle' => 'データ更新', 'strClass' => 'codeLibBaseImgSheet',
										'vars' => array( 'idTarget' => 'same',),
										'child' => array(),
									),
								),
							),
						),
						array(
							'flagUse' => 1,
							'flagNow' => 1,
							'id' => 'Switch',
							'strClass' => 'codeLibBtnImgSwitch',
							'strClassOver' => 'codeLibBtnImgSwitchOver',
							'strClassNoactive' => 'codeLibBtnImgSwitchNoactive',
							'strTitle' => '表示切替',
							'varsContext' => array(
								'varsStatus' => array(
									'numTop' => 0,
									'numLeft' => 0,
									'flagNow' => 'table',
								),
								'varsDetail' => array(
									array(
										'id' => 'Table', 'flagCheckUse' => 1, 'flagCheckNow' => 0,
										'strTitle' => 'テーブル形式', 'strClass' => 'codeLibBaseImgSheet',
										'vars' => array( 'idTarget' => 'table',),
										'child' => array(),
									),
									array(
										'id' => 'Schedule', 'flagCheckUse' => 1, 'flagCheckNow' => 0,
										'strTitle' => 'カレンダー形式', 'strClass' => 'codeLibBaseImgSheet',
										'vars' => array( 'idTarget' => 'schedule',),
										'child' => array(),
									),
								),
							),
						),
						array(
							'flagUse' => 1, 'flagNow' => 0,
							'id' => 'Search',
							'strClass' => 'codeLibBtnImgSearch',
							'strClassOver' => 'codeLibBtnImgSearchOver',
							'strClassNoactive' => 'codeLibBtnImgSearchNoactive',
							'strTitle' => '詳細検索',
						),
						array(
							'flagUse' => 1,
							'flagNow' => 1,
							'id' => 'Preference',
							'strClass' => 'codeLibBtnImgPreference',
							'strClassOver' => 'codeLibBtnImgPreferenceOver',
							'strClassNoactive' => 'codeLibBtnImgPreferenceNoactive',
							'strTitle' => '基本メニュー',
						),
						array(
							'flagUse' => 1,
							'flagNow' => 1,
							'id' => 'Import',
							'strClass' => 'codeLibBtnImgUpload',
							'strClassOver' => 'codeLibBtnImgUploadOver',
							'strClassNoactive' => 'codeLibBtnImgUploadNoactive',
							'strTitle' => 'インポート',
							'varsContext' => array(
								'varsStatus' => array(
									'numTop' => 0,
									'numLeft' => 0,
									'flagNow' => 'mailAll',
								),
								'varsDetail' => array(
									array(
										'id' => 'MailAll', 'flagCheckUse' => 1, 'flagCheckNow' => 0,
										'strTitle' => 'フィルタメールインポート', 'strClass' => 'codeLibBaseImgSheet',
										'vars' => array( 'idTarget' => 'mailAll',),
										'child' => array(),
									),
									array(
										'id' => 'ItemAll', 'flagCheckUse' => 1, 'flagCheckNow' => 0,
										'strTitle' => 'フィルタインポート', 'strClass' => 'codeLibBaseImgSheet',
										'vars' => array( 'idTarget' => 'itemAll',),
										'child' => array(),
									),
									array(
										'id' => 'ListAll', 'flagCheckUse' => 1, 'flagCheckNow' => 0,
										'strTitle' => '外部仕訳インポート', 'strClass' => 'codeLibBaseImgSheet',
										'vars' => array( 'idTarget' => 'listAll',),
										'child' => array(),
									),
								),
							),
						),
						array(
							'flagUse' => 1,
							'flagNow' => 1,
							'id' => 'Output',
							'strClass' => 'codeLibBtnImgDownload',
							'strClassOver' => 'codeLibBtnImgDownloadOver',
							'strClassNoactive' => 'codeLibBtnImgDownloadNoactive',
							'strTitle' => 'エクスポート',
							'varsContext' => array(
								'varsStatus' => array(
									'numTop' => 0,
									'numLeft' => 0,
									'flagNow' => 'itemAll',
								),
								'varsDetail' => array(
									array(
										'id' => 'itemAll', 'flagCheckUse' => 1, 'flagCheckNow' => 0,
										'strTitle' => '仕訳帳', 'strClass' => 'codeLibBaseImgSheet',
										'vars' => array( 'idTarget' => 'itemAll',),
										'child' => array(),
									),
									array(
										'id' => 'ListAll', 'flagCheckUse' => 1, 'flagCheckNow' => 0,
										'strTitle' => '外部仕訳エクスポート(RUCARO形式)', 'strClass' => 'codeLibBaseImgSheet',
										'vars' => array( 'idTarget' => 'listAll',),
										'child' => array(),
									),
									array(
										'id' => 'ListAllYayoi', 'flagCheckUse' => 1, 'flagCheckNow' => 0,
										'strTitle' => '外部仕訳エクスポート(弥生形式)', 'strClass' => 'codeLibBaseImgSheet',
										'vars' => array( 'idTarget' => 'listAllYayoi',),
										'child' => array(),
									),
								),
							),
						),
						array(
							'flagUse' => 1,
							'flagNow' => 1,
							'id' => 'Print',
							'strClass' => 'codeLibBtnImgPrint',
							'strClassOver' => 'codeLibBtnImgPrintOver',
							'strClassNoactive' => 'codeLibBtnImgPrintNoactive',
							'strTitle' => '印刷',
						),
					),
				),
			),
			'detail' => array(
				'varsFormat' => array(
					'id' => '',
					'flagType' => 'normalFormat',
					'numHeight' => 0,
					'numWidth' => 0,
					'flagHeaderLeftUse' => 1,
					'strTitleHeaderLeft' => '',
					'strClassHeaderLeft' => '',
					'flagHeaderRightUse' => 1,
					'strTitleHeaderRight' => '',
					'strClassHeaderRight' => 'codeLibBaseImgUnloading',
					'flagBodyAutoUse' => 1,
					'strBody' => '',
					'strClassBody' => '',
					'flagFooderUse' => 1,
					'flagFooderLeftUse' => 1,
					'strTitleFooderLeft' => '',
					'strClassFooderLeft' => '',
					'flagFooderRightUse' => 1,
					'strTitleFooderRight' => '',
					'strClassFooderRight' => '',
					'flagHeaderLeftWidth' => 1,
					'numWidthHeaderLeft' => 0,
					'flagHeaderRightWidth' => 0,
					'numWidthHeaderRight' => 0,
					'flagFooderLeftWidth' => 0,
					'numWidthFooderLeft' => 0,
					'flagFooderRightWidth' => 1,
					'numWidthFooderRight' => 0,
				),
				'varsTool' => array(
					'varsDetail' => array(
						array(
							'flagUse' => 1, 'flagNow' => 0,
							'id' => 'Reload',
							'strClass' => 'codeLibBtnImgReload',
							'strClassOver' => 'codeLibBtnImgReloadOver',
							'strClassNoactive' => 'codeLibBtnImgReloadNoactive',
							'strTitle' => '更新',
							'varsContext' => array(
								'varsStatus' => array(
									'numTop' => 0,
									'numLeft' => 0,
									'flagNow' => 'search',
								),
								'varsDetail' => array(),
								'varsTmpl' => array(
									'id' => 'Reload', 'flagCheckUse' => 1, 'flagCheckNow' => 0,
									'strTitle' => '詳細更新', 'strClass' => 'codeLibBaseImgSheet',
									'vars' => array( 'idTarget' => 'search',),
									'child' => array(),
								),
							),
						),
						array(
							'flagUse' => 1, 'flagNow' => 0,
							'id' => 'Add',
							'strClass' => 'codeLibBtnImgAdd',
							'strClassOver' => 'codeLibBtnImgAddOver',
							'strClassNoactive' => 'codeLibBtnImgAddNoactive',
							'strTitle' => '新規',
						),
						array(
							'flagUse' => 1, 'flagNow' => 0,
							'id' => 'Copy',
							'strClass' => 'codeLibBtnImgCopy',
							'strClassOver' => 'codeLibBtnImgCopyOver',
							'strClassNoactive' => 'codeLibBtnImgCopyNoactive',
							'strTitle' => 'コピー',
						),
						array(
							'flagUse' => 1, 'flagNow' => 0,
							'id' => 'Edit',
							'strClass' => 'codeLibBtnImgEdit',
							'strClassOver' => 'codeLibBtnImgEditOver',
							'strClassNoactive' => 'codeLibBtnImgEditNoactive',
							'strTitle' => '修正',
						),
					),
				),
			),
		),
	),
	'child' => array(
		'varsTitle' => array(
			'Preference' => '基本メニュー',
			'editor' => 'エディタ',
			'listAll' => '外部仕訳インポート',
			'itemAll' => 'フィルタインポート',
			'Search' => '詳細検索',
		),
		'templateWindow' => array(
			'id' => '',
			'strTitle' => '<%child%> - <%parent%>',
			'strClass' => 'codePluginAccountingImgIcon',
			'flagLockUse' => 0,
			'flagLockNow' => '',
			'flagCakeUse' => 1,
			'flagRemoveUse' => 0,
			'flagCoverUse' => 1,
			'flagHideUse' => 1,
			'flagHideNow' => 0,
			'flagReloadUse' => 0,
			'flagFoldUse' => 1,
			'flagFoldNow' => 0,
			'flagMoveUse' => 1,
			'flagZIndexUse' => 0,
			'flagResizeUse' => 1,
			'flagResizeIni' => 'all',
			'flagResizeNow' => 'all',
			'flagSkeletonUse' => 0,
			'flagBootUse' => 'auto',
			'flagSwitchUse' => 1,
			'flagMenuUse' => 1,
			'flagMenuShowUse' => 0,
			'numWidthTitle' => 0,
			'numLeft' => 50,
			'numTop' => 50,
			'numWidth' => 800,
			'numHeight' => 600,//180 285
			'numWidthMin' => 800,
			'numHeightMin' => 600,
			'numZIndex' => 0
		),
		'preference' => array(
			'id' => '',
			'strTitle' => '<%child%> - <%parent%>',
			'strClass' => 'codePluginAccountingImgIcon',
			'flagLockUse' => 0,
			'flagLockNow' => '',
			'flagCakeUse' => 1,
			'flagRemoveUse' => 0,
			'flagCoverUse' => 1,
			'flagHideUse' => 1,
			'flagHideNow' => 0,
			'flagReloadUse' => 0,
			'flagFoldUse' => 1,
			'flagFoldNow' => 0,
			'flagMoveUse' => 1,
			'flagZIndexUse' => 0,
			'flagResizeUse' => 1,
			'flagResizeIni' => 'all',
			'flagResizeNow' => 'all',
			'flagSkeletonUse' => 0,
			'flagBootUse' => 'auto',
			'flagSwitchUse' => 1,
			'flagMenuUse' => 1,
			'flagMenuShowUse' => 0,
			'numWidthTitle' => 0,
			'numLeft' => 50,
			'numTop' => 50,
			'numWidth' => 700,
			'numHeight' => 450,//180 285
			'numWidthMin' => 700,
			'numHeightMin' => 450,
			'numZIndex' => 0
		),
		'logImportList' => array(
			'id' => '',
			'strTitle' => '<%child%> - <%parent%>',
			'strClass' => 'codePluginAccountingImgIcon',
			'flagLockUse' => 0,
			'flagLockNow' => '',
			'flagCakeUse' => 1,
			'flagRemoveUse' => 0,
			'flagCoverUse' => 1,
			'flagHideUse' => 1,
			'flagHideNow' => 0,
			'flagReloadUse' => 0,
			'flagFoldUse' => 1,
			'flagFoldNow' => 0,
			'flagMoveUse' => 1,
			'flagZIndexUse' => 0,
			'flagResizeUse' => 1,
			'flagResizeIni' => 'all',
			'flagResizeNow' => 'all',
			'flagSkeletonUse' => 0,
			'flagBootUse' => 'auto',
			'flagSwitchUse' => 0,
			'flagMenuUse' => 1,
			'flagMenuShowUse' => 0,
			'numWidthTitle' => 0,
			'numLeft' => 50,
			'numTop' => 50,
			'numWidth' => 500,
			'numHeight' => 400,//180 285
			'numWidthMin' => 500,
			'numHeightMin' => 400,
			'numZIndex' => 0
		),
		'logImportItem' => array(
			'id' => '',
			'strTitle' => '<%child%> - <%parent%>',
			'strClass' => 'codePluginAccountingImgIcon',
			'flagLockUse' => 0,
			'flagLockNow' => '',
			'flagCakeUse' => 1,
			'flagRemoveUse' => 0,
			'flagCoverUse' => 1,
			'flagHideUse' => 1,
			'flagHideNow' => 0,
			'flagReloadUse' => 0,
			'flagFoldUse' => 1,
			'flagFoldNow' => 0,
			'flagMoveUse' => 1,
			'flagZIndexUse' => 0,
			'flagResizeUse' => 1,
			'flagResizeIni' => 'all',
			'flagResizeNow' => 'all',
			'flagSkeletonUse' => 0,
			'flagBootUse' => 'auto',
			'flagSwitchUse' => 0,
			'flagMenuUse' => 1,
			'flagMenuShowUse' => 0,
			'numWidthTitle' => 0,
			'numLeft' => 50,
			'numTop' => 50,
			'numWidth' => 500,
			'numHeight' => 400,//180 285
			'numWidthMin' => 500,
			'numHeightMin' => 400,
			'numZIndex' => 0
		),
		'search' => array(
			'id' => '',
			'strTitle' => '<%child%> - <%parent%>',
			'strClass' => 'codePluginAccountingImgIcon',
			'flagLockUse' => 0,
			'flagLockNow' => '',
			'flagCakeUse' => 1,
			'flagRemoveUse' => 0,
			'flagCoverUse' => 1,
			'flagHideUse' => 1,
			'flagHideNow' => 0,
			'flagReloadUse' => 0,
			'flagFoldUse' => 1,
			'flagFoldNow' => 0,
			'flagMoveUse' => 1,
			'flagZIndexUse' => 0,
			'flagResizeUse' => 1,
			'flagResizeIni' => 'all',
			'flagResizeNow' => 'all',
			'flagSkeletonUse' => 0,
			'flagBootUse' => 'auto',
			'flagSwitchUse' => 0,
			'flagMenuUse' => 1,
			'flagMenuShowUse' => 0,
			'numWidthTitle' => 0,
			'numLeft' => 50,
			'numTop' => 50,
			'numWidth' => 500,
			'numHeight' => 450,//180 285
			'numWidthMin' => 275,
			'numHeightMin' => 400,
			'numZIndex' => 0
		),
	),
);


