<?php

$vars = array(
	array(
		'id' => '', 'flagUse' => 1, 'flagMoveUse' => 1, 'flagInsertUse' => 1, 'flagBtnUse' => 1, 'flagFoldUse' => 0, 'flagFoldNow' => 0, 'flagChildrenUse' => 0, 'flagCheckUse' => 0, 'flagCheckNow' => 0, 'flagRemoveUse' => 1, 'flagEditUse' => 1,
		'strTitle' => '初期設定',
		'strClass' => 'codeLibBaseImgSheet',
		'vars' => array(
			'idTarget' => 'flagCorporation',
			'varsEdit' => array( 'flagReloadUse' => 0, ),
			'varsBtn' => array(
				array(
					'flagUse' => 1, 'flagLeftUse' => 0, 'flagRightUse' => 1, 'flagTextUse' => 0, 'flagBtnUse' => 1,
					'id' => 'FlagCorporation',
					'vars' => array( 'idTarget' => 'flagCorporation', 'flagOrder' => 1,),
					'strTitle' => '次へ',
				),
			),
			'varsDetail' => array(
				array(
					'flagMustUse' => 1,
					'id' => 'FlagCorporation',
					'strTitle' => '事業形態',
						'strExplain' => '事業形態を設定してください。',
					'value' => 1,
					'flagErrorNow' => 0,
					'arrayError' => array(
						array( 'flagCheck' => 'blank', 'flagUse' => 1, 'flagNow' => 0, 'flagType' => 'empty', 'strComment' => array( 'common' => '記入漏れがあるようです。', ),),
						array( 'flagCheck' => 'word', 'flagUse' => 1, 'flagNow' => 0, 'flagArr' => 0, 'flagType' => 'num', 'strComment' => array( 'common' => '半角数字以外の文字が混入したようです。', ), ),
					),
					'flagContentUse' => 0,
					'flagCommentUse' => 0, 'strCommentTitle' => '', 'strComment' => '',
					'flagTag' => 'select', 'flagInputType' => '', 'numMaxlength' => 0,
					'numWidth' => 40, 'unitWidth' => '%', 'numHeight' => 0, 'unitHeight' => '',
					'arrayOption' => array(
						array( 'strTitle' => '法人', 'value' => 1, ),
						array( 'strTitle' => '個人一般', 'value' => 2, ),
					),
					'numSize' => 2,
				),
			),
		),
		'varsTmpl' => array(
			'flagCorporation' => array(
				'idTarget' => 'flagCorporation',
				'varsEdit' => array( 'flagReloadUse' => 0, ),
				'varsBtn' => array(
					array(
						'flagUse' => 1, 'flagLeftUse' => 0, 'flagRightUse' => 1, 'flagTextUse' => 0, 'flagBtnUse' => 1,
						'id' => 'FlagCorporation',
						'vars' => array( 'idTarget' => 'flagCorporation', 'flagOrder' => 1,),
						'strTitle' => '次へ',
					),
				),
				'varsDetail' => array(
					array(
						'flagMustUse' => 1,
						'id' => 'FlagCorporation',
						'strTitle' => '事業形態',
							'strExplain' => '事業形態を設定してください。',
						'value' => 1,
						'flagErrorNow' => 0,
						'arrayError' => array(
							array( 'flagCheck' => 'blank', 'flagUse' => 1, 'flagNow' => 0, 'flagType' => 'empty', 'strComment' => array( 'common' => '記入漏れがあるようです。', ),),
							array( 'flagCheck' => 'word', 'flagUse' => 1, 'flagNow' => 0, 'flagArr' => 0, 'flagType' => 'num', 'strComment' => array( 'common' => '半角数字以外の文字が混入したようです。', ), ),
						),
						'flagContentUse' => 0,
						'flagCommentUse' => 0, 'strCommentTitle' => '', 'strComment' => '',
						'flagTag' => 'select', 'flagInputType' => '', 'numMaxlength' => 0,
						'numWidth' => 40, 'unitWidth' => '%', 'numHeight' => 0, 'unitHeight' => '',
						'arrayOption' => array(
							array( 'strTitle' => '法人', 'value' => 1, ),
							array( 'strTitle' => '個人一般', 'value' => 2, ),
						),
						'numSize' => 2,
					),
				),
			),
			'numFiscalBeginningYear' => array(
				'idTarget' => 'numFiscalBeginningYear',
				'varsEdit' => array( 'flagReloadUse' => 0, ),
				'varsBtn' => array(
					array(
						'flagUse' => 1, 'flagLeftUse' => 0, 'flagRightUse' => 1, 'flagTextUse' => 0, 'flagBtnUse' => 1,
						'id' => 'FlagCorporationBack',
						'vars' => array( 'idTarget' => 'flagCorporationBack', 'flagOrder' => 1,),
						'strTitle' => '戻る',
					),
					array(
						'flagUse' => 1, 'flagLeftUse' => 0, 'flagRightUse' => 1, 'flagTextUse' => 0, 'flagBtnUse' => 1,
						'id' => 'numFiscalBeginningYear',
						'vars' => array( 'idTarget' => 'numFiscalBeginningYear', 'flagOrder' => 1,),
						'strTitle' => '次へ',
					),
				),
				'varsDetail' => array(
					array(
						'flagMustUse' => 1,
						'id' => 'numFiscalBeginningYear',
						'strTitle' => '運用開始年度',
						'strExplain' => '運用を開始する期首日に属する年(西暦)を設定してください。',
						'value' => 0,
						'flagErrorNow' => 0,
						'arrayError' => array(
							array( 'flagCheck' => 'blank', 'flagUse' => 1, 'flagNow' => 0, 'flagType' => 'empty', 'strComment' => array( 'common' => '記入漏れがあるようです。', ),),
							array( 'flagCheck' => 'word', 'flagUse' => 1, 'flagNow' => 0, 'flagArr' => 0, 'flagType' => 'num', 'strComment' => array( 'common' => '半角数字以外の文字が混入したようです。', ), ),
						),
						'flagContentUse' => 0,
						'flagCommentUse' => 0, 'strCommentTitle' => '', 'strComment' => '',
						'flagTag' => 'select', 'flagInputType' => '', 'numMaxlength' => 0,
						'numWidth' => 40, 'unitWidth' => '%', 'numHeight' => 0, 'unitHeight' => '',
						'arrayOption' => array(),
						'varsTmpl' => array(
							'strYear' => '年',
						),
					),
				),
			),
			'numFiscalBeginningMonth' => array(
				'idTarget' => 'numFiscalBeginningMonth',
				'varsEdit' => array( 'flagReloadUse' => 0, ),
				'varsBtn' => array(
					array(
						'flagUse' => 1, 'flagLeftUse' => 0, 'flagRightUse' => 1, 'flagTextUse' => 0, 'flagBtnUse' => 1,
						'id' => 'numFiscalBeginningYearBack',
						'vars' => array( 'idTarget' => 'numFiscalBeginningYearBack', 'flagOrder' => 1,),
						'strTitle' => '戻る',
					),
					array(
						'flagUse' => 1, 'flagLeftUse' => 0, 'flagRightUse' => 1, 'flagTextUse' => 0, 'flagBtnUse' => 1,
						'id' => 'NumFiscalBeginningMonth',
						'vars' => array( 'idTarget' => 'numFiscalBeginningMonth', 'flagOrder' => 1,),
						'strTitle' => '次へ',
					),
				),
				'varsDetail' => array(
					array(
						'flagMustUse' => 1,
						'id' => 'NumFiscalBeginningMonth',
						'strTitle' => '年度会計期間',
						'strExplain' => '年度の会計期間を設定してください。',
						'value' => 4,
						'flagErrorNow' => 0,
						'arrayError' => array(
							array( 'flagCheck' => 'blank', 'flagUse' => 1, 'flagNow' => 0, 'flagType' => 'empty', 'strComment' => array( 'common' => '記入漏れがあるようです。', ),),
							array( 'flagCheck' => 'word', 'flagUse' => 1, 'flagNow' => 0, 'flagArr' => 0, 'flagType' => 'num', 'strComment' => array( 'common' => '半角数字以外の文字が混入したようです。', ), ),
						),
						'flagContentUse' => 0,
						'flagCommentUse' => 0, 'strCommentTitle' => '', 'strComment' => '',
						'flagTag' => 'select', 'flagInputType' => '', 'numMaxlength' => 0,
						'numWidth' => 40, 'unitWidth' => '%', 'numHeight' => 0, 'unitHeight' => '',
						'arrayOption' => array(),
						'varsTmpl' => array(
							array( 'strTitle' => '1月1日　～　12月末日', 'value' => 1, ),
							array( 'strTitle' => '2月1日　～　1月末日', 'value' => 2, ),
							array( 'strTitle' => '3月1日　～　2月末日', 'value' => 3, ),
							array( 'strTitle' => '4月1日　～　3月末日', 'value' => 4, ),
							array( 'strTitle' => '5月1日　～　4月末日', 'value' => 5, ),
							array( 'strTitle' => '6月1日　～　5月末日', 'value' => 6, ),
							array( 'strTitle' => '7月1日　～　6月末日', 'value' => 7, ),
							array( 'strTitle' => '8月1日　～　7月末日', 'value' => 8, ),
							array( 'strTitle' => '9月1日　～　8月末日', 'value' => 9, ),
							array( 'strTitle' => '10月1日　～　9月末日', 'value' => 10, ),
							array( 'strTitle' => '11月1日　～　10月末日', 'value' => 11, ),
							array( 'strTitle' => '12月1日　～　11月末日', 'value' => 12, ),
						),
						'numSize' => 12,
					),
				),
			),
			'flagCR' => array(
				'idTarget' => 'flagCR',
				'varsEdit' => array( 'flagReloadUse' => 0, ),
				'varsBtn' => array(
					array(
						'flagUse' => 1, 'flagLeftUse' => 0, 'flagRightUse' => 1, 'flagTextUse' => 0, 'flagBtnUse' => 1,
						'id' => 'NumFiscalBeginningMonthBack',
						'vars' => array( 'idTarget' => 'numFiscalBeginningMonthBack', 'flagOrder' => 1,),
						'strTitle' => '戻る',
					),
					array(
						'flagUse' => 1, 'flagLeftUse' => 0, 'flagRightUse' => 1, 'flagTextUse' => 0, 'flagBtnUse' => 1,
						'id' => 'FlagCR',
						'vars' => array( 'idTarget' => 'flagCR', 'flagOrder' => 1,),
						'strTitle' => '次へ',
					),
				),
				'varsDetail' => array(
					array(
						'flagMustUse' => 1,
						'id' => 'FlagCR',
						'strTitle' => '製造原価報告書',
						'strExplain' => '製造原価報告書の勘定科目を使用するか設定してください。',
						'value' => 1,
						'flagErrorNow' => 0,
						'arrayError' => array(
							array( 'flagCheck' => 'blank', 'flagUse' => 1, 'flagNow' => 0, 'flagType' => 'empty', 'strComment' => array( 'common' => '記入漏れがあるようです。', ),),
							array( 'flagCheck' => 'word', 'flagUse' => 1, 'flagNow' => 0, 'flagArr' => 0, 'flagType' => 'num', 'strComment' => array( 'common' => '半角数字以外の文字が混入したようです。', ), ),
						),
						'flagContentUse' => 0,
						'flagCommentUse' => 0, 'strCommentTitle' => '', 'strComment' => '',
						'flagTag' => 'select', 'flagInputType' => '', 'numMaxlength' => 0,
						'numWidth' => 40, 'unitWidth' => '%', 'numHeight' => 0, 'unitHeight' => '',
						'arrayOption' => array(
							array( 'strTitle' => '使用する', 'value' => 1, ),
							array( 'strTitle' => '使用しない', 'value' => 0, ),
						),
						'numSize' => 2,
					),
					array(
						'flagMustUse' => 0,
						'id' => 'IdEntityAccount',
						'strTitle' => '勘定体系コピー', 'strExplain' => '事業体の勘定体系をそのままコピーしたい場合、ボタンを押して任意の事業体を一つ選択してください。', 'value' => '',
						'flagErrorNow' => 0,
						'arrayError' => array(
							array( 'flagCheck' => 'blank', 'flagUse' => 1, 'flagNow' => 0, 'flagType' => 'empty', 'strComment' => array('common' => '選択漏れがあるようです。', ), ),
							array( 'flagCheck' => 'word', 'flagUse' => 1, 'flagNow' => 0, 'flagArr' => 0, 'flagType' => 'num', 'strComment' => array('common' => '半角数字で記入されていないようです。', ), ),
							array( 'flagCheck' => 'attest', 'flagUse' => 1, 'strComment' => array('idEntity' => '選択された事業体は、既に存在しないようです。',),),
						),
						'flagContentUse' => 1,
						'flagCommentUse' => 0, 'strCommentTitle' => '', 'strComment' => '',
						'flagTag' => 'input', 'flagInputType' => 'text', 'numMaxlength' => 200,
						'numWidth' => 80, 'unitWidth' => '%', 'numHeight' => 0, 'unitHeight' => '',
						'arrayOption' => array(),
						'flagFoldUse' => 1, 'flagFoldNow' => 0,
						'varsFormList' => array(
							'varsStatus' => array( 'flagSortUse' => 0, 'flagCopyUse' => 0, 'flagRemoveUse' => 0, 'flagAddUse' => 1, 'strAddNow' => 'addSelect', 'flagEditUse' => 0, 'flagFormUse' => 0, 'flagBtnUse' => 0, ),
							'templateDetail' => array( 'id' => 'Dummy', 'flagSortUse' => 0, 'flagCopyUse' => 0, 'flagRemoveUse' => 1, 'flagEditUse' => 0, 'flagFormUse' => 0, 'flagBtnUse' => 0, 'numSort' => 0, 'value' => '', ),
							'varsDetail' => array(),
						),
						'flagHideUse' => 1, 'flagHideNow' => 1,
					),
				),
			),
			'flagConsumptionTaxFree' => array(
				'idTarget' => 'flagConsumptionTaxFree',
				'varsEdit' => array( 'flagReloadUse' => 0, ),
				'varsBtn' => array(
					array(
						'flagUse' => 1, 'flagLeftUse' => 0, 'flagRightUse' => 1, 'flagTextUse' => 0, 'flagBtnUse' => 1,
						'id' => 'FlagCRBack',
						'vars' => array( 'idTarget' => 'flagCRBack', 'flagOrder' => 1,),
						'strTitle' => '戻る',
					),
					array(
						'flagUse' => 1, 'flagLeftUse' => 0, 'flagRightUse' => 1, 'flagTextUse' => 0, 'flagBtnUse' => 1,
						'id' => 'FlagConsumptionTaxFree',
						'vars' => array( 'idTarget' => 'flagConsumptionTaxFree', 'flagOrder' => 1,),
						'strTitle' => '次へ',
					),
				),
				'varsDetail' => array(
					array(
						'flagMustUse' => 1,
						'id' => 'FlagConsumptionTaxFree',
						'strTitle' => '消費税事業者区分',
						'strExplain' => '消費税の事業者区分を設定してください。<br>　※ 免税を選択した場合、【経理処理方式】は、税込となります。',
						'value' => 1,
						'flagErrorNow' => 0,
						'arrayError' => array(
							array( 'flagCheck' => 'blank', 'flagUse' => 1, 'flagNow' => 0, 'flagType' => 'empty', 'strComment' => array( 'common' => '記入漏れがあるようです。', ),),
							array( 'flagCheck' => 'word', 'flagUse' => 1, 'flagNow' => 0, 'flagArr' => 0, 'flagType' => 'num', 'strComment' => array( 'common' => '半角数字以外の文字が混入したようです。', ), ),
						),
						'flagContentUse' => 0,
						'flagCommentUse' => 0, 'strCommentTitle' => '', 'strComment' => '',
						'flagTag' => 'select', 'flagInputType' => '', 'numMaxlength' => 0,
						'numWidth' => 40, 'unitWidth' => '%', 'numHeight' => 0, 'unitHeight' => '',
						'arrayOption' => array(
							array( 'strTitle' => '免税', 'value' => 1, ),
							array( 'strTitle' => '課税', 'value' => 0, ),
						),
						'numSize' => 2,
					),
				),
			),
			'flagConsumptionTaxGeneralRule' => array(
				'idTarget' => 'flagConsumptionTaxGeneralRule',
				'varsEdit' => array( 'flagReloadUse' => 0, ),
				'varsBtn' => array(
					array(
						'flagUse' => 1, 'flagLeftUse' => 0, 'flagRightUse' => 1, 'flagTextUse' => 0, 'flagBtnUse' => 1,
						'id' => 'FlagConsumptionTaxFreeBack',
						'vars' => array( 'idTarget' => 'flagConsumptionTaxFreeBack', 'flagOrder' => 1,),
						'strTitle' => '戻る',
					),
					array(
						'flagUse' => 1, 'flagLeftUse' => 0, 'flagRightUse' => 1, 'flagTextUse' => 0, 'flagBtnUse' => 1,
						'id' => 'FlagConsumptionTaxGeneralRule',
						'vars' => array( 'idTarget' => 'flagConsumptionTaxGeneralRule', 'flagOrder' => 1,),
						'strTitle' => '次へ',
					),
				),
				'varsDetail' => array(
					array(
						'flagMustUse' => 1,
						'id' => 'FlagConsumptionTaxGeneralRule',
						'strTitle' => '課税方式',
						'strExplain' => '消費税の課税方式を設定してください。',
						'value' => 1,
						'flagErrorNow' => 0,
						'arrayError' => array(
							array( 'flagCheck' => 'blank', 'flagUse' => 1, 'flagNow' => 0, 'flagType' => 'empty', 'strComment' => array( 'common' => '記入漏れがあるようです。', ),),
							array( 'flagCheck' => 'word', 'flagUse' => 1, 'flagNow' => 0, 'flagArr' => 0, 'flagType' => 'num', 'strComment' => array( 'common' => '半角数字以外の文字が混入したようです。', ), ),
						),
						'flagContentUse' => 0,
						'flagCommentUse' => 0, 'strCommentTitle' => '', 'strComment' => '',
						'flagTag' => 'select', 'flagInputType' => '', 'numMaxlength' => 0,
						'numWidth' => 40, 'unitWidth' => '%', 'numHeight' => 0, 'unitHeight' => '',
						'arrayOption' => array(
							array( 'strTitle' => '本則課税', 'value' => 1, ),
							array( 'strTitle' => '簡易課税', 'value' => 0, ),
						),
						'numSize' => 2,
					),
				),
			),
			'flagConsumptionTaxBusinessType' => array(
				'idTarget' => 'flagConsumptionTaxDeducted',
				'varsEdit' => array( 'flagReloadUse' => 0, ),
				'varsBtn' => array(
					array(
						'flagUse' => 1, 'flagLeftUse' => 0, 'flagRightUse' => 1, 'flagTextUse' => 0, 'flagBtnUse' => 1,
						'id' => 'FlagConsumptionTaxGeneralRuleBack',
						'vars' => array( 'idTarget' => 'flagConsumptionTaxGeneralRuleBack', 'flagOrder' => 1,),
						'strTitle' => '戻る',
					),
					array(
						'flagUse' => 1, 'flagLeftUse' => 0, 'flagRightUse' => 1, 'flagTextUse' => 0, 'flagBtnUse' => 1,
						'id' => 'FlagConsumptionTaxBusinessType',
						'vars' => array( 'idTarget' => 'flagConsumptionTaxBusinessType', 'flagOrder' => 1,),
						'strTitle' => '次へ',
					),
				),
				'varsDetail' => array(
					array(
						'flagMustUse' => 1,
						'id' => 'FlagConsumptionTaxBusinessType',
						'strTitle' => '簡易課税事業区分',
						'strExplain' => '簡易課税事業区分を設定してください。',
						'value' => 1,
						'flagErrorNow' => 0,
						'arrayError' => array(
							array( 'flagCheck' => 'blank', 'flagUse' => 1, 'flagNow' => 0, 'flagType' => 'empty', 'strComment' => array( 'common' => '記入漏れがあるようです。', ),),
							array( 'flagCheck' => 'word', 'flagUse' => 1, 'flagNow' => 0, 'flagArr' => 0, 'flagType' => 'num', 'strComment' => array( 'common' => '半角数字以外の文字が混入したようです。', ), ),
						),
						'flagContentUse' => 0,
						'flagCommentUse' => 0, 'strCommentTitle' => '', 'strComment' => '',
						'flagTag' => 'select', 'flagInputType' => '', 'numMaxlength' => 0,
						'numWidth' => 40, 'unitWidth' => '%', 'numHeight' => 0, 'unitHeight' => '',
						'arrayOption' => array(
							array( 'strTitle' => '第一種事業', 'value' => 1, ),
							array( 'strTitle' => '第二種事業', 'value' => 2, ),
							array( 'strTitle' => '第三種事業', 'value' => 3, ),
							array( 'strTitle' => '第四種事業', 'value' => 4, ),
							array( 'strTitle' => '第五種事業', 'value' => 5, ),
						    array( 'strTitle' => '第六種事業', 'value' => 6, ),
						),
						'numSize' => 5,
					),
				),
			),
			'flagConsumptionTaxDeducted' => array(
				'idTarget' => 'flagConsumptionTaxDeducted',
				'varsEdit' => array( 'flagReloadUse' => 0, ),
				'varsBtn' => array(
					array(
						'flagUse' => 1, 'flagLeftUse' => 0, 'flagRightUse' => 1, 'flagTextUse' => 0, 'flagBtnUse' => 1,
						'id' => 'FlagConsumptionTaxGeneralRuleBack',
						'vars' => array( 'idTarget' => 'flagConsumptionTaxGeneralRuleBack', 'flagOrder' => 1,),
						'strTitle' => '戻る',
					),
					array(
						'flagUse' => 1, 'flagLeftUse' => 0, 'flagRightUse' => 1, 'flagTextUse' => 0, 'flagBtnUse' => 1,
						'id' => 'FlagConsumptionTaxDeducted',
						'vars' => array( 'idTarget' => 'flagConsumptionTaxDeducted', 'flagOrder' => 1,),
						'strTitle' => '次へ',
					),
				),
				'varsDetail' => array(
					array(
						'flagMustUse' => 1,
						'id' => 'FlagConsumptionTaxDeducted',
						'strTitle' => '仕入税額控除方式',
						'strExplain' => '仕入税額控除方式を設定してください。',
						'value' => 0,
						'flagErrorNow' => 0,
						'arrayError' => array(
							array( 'flagCheck' => 'blank', 'flagUse' => 1, 'flagNow' => 0, 'flagType' => 'empty', 'strComment' => array( 'common' => '記入漏れがあるようです。', ),),
							array( 'flagCheck' => 'word', 'flagUse' => 1, 'flagNow' => 0, 'flagArr' => 0, 'flagType' => 'num', 'strComment' => array( 'common' => '半角数字以外の文字が混入したようです。', ), ),
						),
						'flagContentUse' => 0,
						'flagCommentUse' => 0, 'strCommentTitle' => '', 'strComment' => '',
						'flagTag' => 'select', 'flagInputType' => '', 'numMaxlength' => 0,
						'numWidth' => 40, 'unitWidth' => '%', 'numHeight' => 0, 'unitHeight' => '',
						'arrayOption' => array(
							array( 'strTitle' => '比例配分', 'value' => 0, ),
							array( 'strTitle' => '個別対応', 'value' => 1, ),
						),
						'numSize' => 2,
					),
				),
			),
			'flagConsumptionTaxIncluding' => array(
				'idTarget' => 'flagConsumptionTaxIncluding',
				'varsEdit' => array( 'flagReloadUse' => 0, ),
				'varsBtn' => array(
					array(
						'flagUse' => 1, 'flagLeftUse' => 0, 'flagRightUse' => 1, 'flagTextUse' => 0, 'flagBtnUse' => 1,
						'id' => 'FlagConsumptionTaxDeductedBack',
						'vars' => array( 'idTarget' => 'flagConsumptionTaxDeductedBack', 'flagOrder' => 1,),
						'strTitle' => '戻る',
					),
					array(
						'flagUse' => 1, 'flagLeftUse' => 0, 'flagRightUse' => 1, 'flagTextUse' => 0, 'flagBtnUse' => 1,
						'id' => 'FlagConsumptionTaxIncluding',
						'vars' => array( 'idTarget' => 'flagConsumptionTaxIncluding', 'flagOrder' => 1,),
						'strTitle' => '次へ',
					),
				),
				'varsDetail' => array(
					array(
						'flagMustUse' => 1,
						'id' => 'FlagConsumptionTaxIncluding',
						'strTitle' => '経理処理方式',
						'strExplain' => '消費税の経理処理方式を設定してください。',
						'value' => 0,
						'flagErrorNow' => 0,
						'arrayError' => array(
							array( 'flagCheck' => 'blank', 'flagUse' => 1, 'flagNow' => 0, 'flagType' => 'empty', 'strComment' => array( 'common' => '記入漏れがあるようです。', ),),
							array( 'flagCheck' => 'word', 'flagUse' => 1, 'flagNow' => 0, 'flagArr' => 0, 'flagType' => 'num', 'strComment' => array( 'common' => '半角数字以外の文字が混入したようです。', ), ),
						),
						'flagContentUse' => 0,
						'flagCommentUse' => 0, 'strCommentTitle' => '', 'strComment' => '',
						'flagTag' => 'select', 'flagInputType' => '', 'numMaxlength' => 0,
						'numWidth' => 40, 'unitWidth' => '%', 'numHeight' => 0, 'unitHeight' => '',
						'arrayOption' => array(
							array( 'strTitle' => '税抜処理', 'value' => 0, ),
							array( 'strTitle' => '税込処理', 'value' => 1, ),
						),
						'numSize' => 2,
					),
					array(
						'flagMustUse' => 1,
						'id' => 'FlagConsumptionTaxCalc',
						'strTitle' => '消費税端数処理方法',
						'strExplain' => '消費税の端数処理方法を設定してください。',
						'value' => 1,
						'flagErrorNow' => 0,
						'arrayError' => array(
							array( 'flagCheck' => 'blank', 'flagUse' => 1, 'flagNow' => 0, 'flagType' => 'empty', 'strComment' => array( 'common' => '記入漏れがあるようです。', ),),
							array( 'flagCheck' => 'word', 'flagUse' => 1, 'flagNow' => 0, 'flagArr' => 0, 'flagType' => 'num', 'strComment' => array( 'common' => '半角文字以外の文字が混入したようです。', ), ),
						),
						'flagContentUse' => 0,
						'flagCommentUse' => 0, 'strCommentTitle' => '', 'strComment' => '',
						'flagTag' => 'select', 'flagInputType' => '', 'numMaxlength' => 0,
						'numWidth' => 40, 'unitWidth' => '%', 'numHeight' => 0, 'unitHeight' => '',
						'arrayOption' => array(
							array( 'strTitle' => '切り捨て', 'value' => 1, ),
							array( 'strTitle' => '四捨五入', 'value' => 2, ),
							array( 'strTitle' => '切り上げ', 'value' => 3, ),
						),
						'numSize' => 3,
					),
				),
			),
			'flagConsumptionTaxWithoutCalc' => array(
				'idTarget' => 'flagConsumptionTaxWithoutCalc',
				'varsEdit' => array( 'flagReloadUse' => 0, ),
				'varsBtn' => array(
					array(
						'flagUse' => 1, 'flagLeftUse' => 0, 'flagRightUse' => 1, 'flagTextUse' => 0, 'flagBtnUse' => 1,
						'id' => 'FlagConsumptionTaxIncludingBack',
						'vars' => array( 'idTarget' => 'flagConsumptionTaxIncludingBack', 'flagOrder' => 1,),
						'strTitle' => '戻る',
					),
					array(
						'flagUse' => 1, 'flagLeftUse' => 0, 'flagRightUse' => 1, 'flagTextUse' => 0, 'flagBtnUse' => 1,
						'id' => 'FlagConsumptionTaxWithoutCalc',
						'vars' => array( 'idTarget' => 'flagConsumptionTaxWithoutCalc', 'flagOrder' => 1,),
						'strTitle' => '次へ',
					),
				),
				'varsDetail' => array(
					array(
						'flagMustUse' => 1,
						'id' => 'FlagConsumptionTaxWithoutCalc',
						'strTitle' => '消費税入力方法',
						'strExplain' => '税抜処理を使用する場合の消費税の入力方法を設定してください。',
						'value' => 1,
						'flagErrorNow' => 0,
						'arrayError' => array(
							array( 'flagCheck' => 'blank', 'flagUse' => 1, 'flagNow' => 0, 'flagType' => 'empty', 'strComment' => array( 'common' => '記入漏れがあるようです。', ),),
							array( 'flagCheck' => 'word', 'flagUse' => 1, 'flagNow' => 0, 'flagArr' => 0, 'flagType' => 'num', 'strComment' => array( 'common' => '半角数字以外の文字が混入したようです。', ), ),
						),
						'flagContentUse' => 0,
						'flagCommentUse' => 0, 'strCommentTitle' => '', 'strComment' => '',
						'flagTag' => 'select', 'flagInputType' => '', 'numMaxlength' => 0,
						'numWidth' => 40, 'unitWidth' => '%', 'numHeight' => 0, 'unitHeight' => '',
						'arrayOption' => array(
							array( 'strTitle' => '内税', 'value' => 1, ),
							array( 'strTitle' => '外税', 'value' => 2, ),
							array( 'strTitle' => '別記', 'value' => 3, ),
						),
						'numSize' => 3,
					),
				),
			),
			'entityConfigEnd' => array(
				'idTarget' => 'entityConfigEnd',
				'varsEdit' => array( 'flagReloadUse' => 0, ),
				'varsBtn' => array(
					array(
						'flagUse' => 1, 'flagLeftUse' => 0, 'flagRightUse' => 1, 'flagTextUse' => 0, 'flagBtnUse' => 1,
						'id' => 'FlagConsumptionTaxWithoutCalcBack',
						'vars' => array( 'idTarget' => 'flagConsumptionTaxWithoutCalcBack', 'flagOrder' => 1,),
						'strTitle' => '戻る',
					),
					array(
						'flagUse' => 1, 'flagLeftUse' => 0, 'flagRightUse' => 1, 'flagTextUse' => 0, 'flagBtnUse' => 1,
						'id' => 'EntityConfigEnd',
						'vars' => array( 'idTarget' => 'entityConfigEnd', 'flagOrder' => 1,),
						'strTitle' => '保存',
					),
				),
				'varsDetail' => array(
					array(
						'flagMustUse' => 1,
						'id' => 'EntityConfigEnd',
						'strTitle' => '',
						'strExplain' => '',
						'value' => 0,
						'flagErrorNow' => 0,
						'arrayError' => array(
							array( 'flagCheck' => 'attest', 'flagUse' => 1, 'strComment' => array('idEntity' => '選択された事業体は、既に存在しないようです。勘定体系コピーを設定し直して下さい。',),),
						),
						'flagContentUse' => 0,
						'flagCommentUse' => 1, 'strCommentTitle' => '最終確認', 'strComment' => '入力した内容を確認し、よければ保存ボタンを押してください。<br>　※ 保存後、ページを<span class="codeLibBaseFontTypeCheck" style="float:none;">自動更新</span>します。<br>',
						'flagTag' => 'select', 'flagInputType' => '', 'numMaxlength' => 0,
						'numWidth' => 40, 'unitWidth' => '%', 'numHeight' => 0, 'unitHeight' => '',
						'arrayOption' => array(),
						'varsTmpl' => '　【 <%strTitle%> 】　<%strValue%><br>',
					),
				),
			),
		),
		'child' => array(),
	),
);


