<?php

$vars =  array(
	'id' =>  'jp',
	'strTitle' =>  '日本の休日',
	'transfer' =>  '振替休日',
	'varsDetail' =>  array(
/*
		array(
			'flagType' =>  'stamp',
			'strTitle' =>  '国民の休日',
			'stamp' =>  0,'term' =>  array( 'stampStart' =>  0,'stampEnd' =>  0,),
			'loop' =>  array(
				'flagType' =>  '',
				'arrayMonth' =>  array(),
				'arrayWeek' =>  array(),
				'arrayDate' =>  array(),
				'arrayDay' =>  array(),
				'start' =>  array( 'numHour' =>  0, 'numMin' =>  0 ),
				'end' =>  array( 'numHour' =>  0, 'numMin' =>  0 ),
			),
		),
*/
		array(
			'flagType' =>  'loop',
			'strTitle' =>  '元日',
			'stamp' =>  0,'term' =>  array( 'stampStart' =>  0,'stampEnd' =>  0,),
			'loop' =>  array(
				'flagType' =>  'year',
				'arrayMonth' =>  array(0),
				'arrayWeek' =>  array(),
				'arrayDate' =>  array(1),
				'arrayDay' =>  array(),
				'start' =>  array( 'numHour' =>  0, 'numMin' =>  0 ),
				'end' =>  array( 'numHour' =>  0, 'numMin' =>  0 ),
			),
		),
		array(
			'flagType' =>  'loop',
			'strTitle' =>  '成人の日',
			'stamp' =>  0,'term' =>  array( 'stampStart' =>  0,'stampEnd' =>  0,),
			'loop' =>  array(
				'flagType' =>  'year',
				'arrayMonth' =>  array(0),
				'arrayWeek' =>  array(array( 'flagNum' =>  2, 'numDay' =>  1 )),
				'arrayDate' =>  array(),
				'arrayDay' =>  array(),
				'start' =>  array( 'numHour' =>  0, 'numMin' =>  0 ),
				'end' =>  array( 'numHour' =>  0, 'numMin' =>  0 ),
			),
		),
		array(
			'flagType' =>  'loop',
			'strTitle' =>  '建国記念の日',
			'stamp' =>  0,'term' =>  array( 'stampStart' =>  0,'stampEnd' =>  0,),
			'loop' =>  array(
				'flagType' =>  'year',
				'arrayMonth' =>  array(1),
				'arrayWeek' =>  array(),
				'arrayDate' =>  array(11),
				'arrayDay' =>  array(),
				'start' =>  array( 'numHour' =>  0, 'numMin' =>  0 ),
				'end' =>  array( 'numHour' =>  0, 'numMin' =>  0 ),
			),
		),
		array(#2011 only
			'flagType' =>  'term',
			'strTitle' =>  '春分の日',
			'stamp' =>  0,
			'term' =>  array( 'stampStart' => 1300633200000, 'stampEnd' =>  1300719599000,),
			'loop' =>  array(
				'flagType' =>  '',
				'arrayMonth' =>  array(),
				'arrayWeek' =>  array(),
				'arrayDate' =>  array(),
				'arrayDay' =>  array(),
				'start' =>  array( 'numHour' =>  0, 'numMin' =>  0 ),
				'end' =>  array( 'numHour' =>  0, 'numMin' =>  0 ),
			),
		),
		array(#2012 only
			'flagType' =>  'term',
			'strTitle' =>  '春分の日',
			'stamp' =>  0,
			'term' =>  array( 'stampStart' => 1332169200000, 'stampEnd' =>  1332255599000,),
			'loop' =>  array(
				'flagType' =>  '',
				'arrayMonth' =>  array(),
				'arrayWeek' =>  array(),
				'arrayDate' =>  array(),
				'arrayDay' =>  array(),
				'start' =>  array( 'numHour' =>  0, 'numMin' =>  0 ),
				'end' =>  array( 'numHour' =>  0, 'numMin' =>  0 ),
			),
		),
		array(#2013 only
			'flagType' =>  'term',
			'strTitle' =>  '春分の日',
			'stamp' =>  0,
			'term' =>  array( 'stampStart' => 1363705200000, 'stampEnd' =>  1363791599000,),
			'loop' =>  array(
				'flagType' =>  '',
				'arrayMonth' =>  array(),
				'arrayWeek' =>  array(),
				'arrayDate' =>  array(),
				'arrayDay' =>  array(),
				'start' =>  array( 'numHour' =>  0, 'numMin' =>  0 ),
				'end' =>  array( 'numHour' =>  0, 'numMin' =>  0 ),
			),
		),
		array(#2014 only
			'flagType' =>  'term',
			'strTitle' =>  '春分の日',
			'stamp' =>  0,
			'term' =>  array( 'stampStart' => 1395327600000, 'stampEnd' =>  1395413999000,),
			'loop' =>  array(
				'flagType' =>  '',
				'arrayMonth' =>  array(),
				'arrayWeek' =>  array(),
				'arrayDate' =>  array(),
				'arrayDay' =>  array(),
				'start' =>  array( 'numHour' =>  0, 'numMin' =>  0 ),
				'end' =>  array( 'numHour' =>  0, 'numMin' =>  0 ),
			),
		),
		array(#2015 only
			'flagType' =>  'term',
			'strTitle' =>  '春分の日',
			'stamp' =>  0,
			'term' =>  array( 'stampStart' => 1426863600000, 'stampEnd' =>  1426949999000,),
			'loop' =>  array(
				'flagType' =>  '',
				'arrayMonth' =>  array(),
				'arrayWeek' =>  array(),
				'arrayDate' =>  array(),
				'arrayDay' =>  array(),
				'start' =>  array( 'numHour' =>  0, 'numMin' =>  0 ),
				'end' =>  array( 'numHour' =>  0, 'numMin' =>  0 ),
			),
		),
		array(#2016 only
			'flagType' =>  'term',
			'strTitle' =>  '春分の日',
			'stamp' =>  0,
			'term' =>  array( 'stampStart' => 1458399600000, 'stampEnd' =>  1458485999000,),
			'loop' =>  array(
				'flagType' =>  '',
				'arrayMonth' =>  array(),
				'arrayWeek' =>  array(),
				'arrayDate' =>  array(),
				'arrayDay' =>  array(),
				'start' =>  array( 'numHour' =>  0, 'numMin' =>  0 ),
				'end' =>  array( 'numHour' =>  0, 'numMin' =>  0 ),
			),
		),
		array(#2017 only
			'flagType' =>  'term',
			'strTitle' =>  '春分の日',
			'stamp' =>  0,
			'term' =>  array( 'stampStart' => 1489935600000, 'stampEnd' =>  1490021999000,),
			'loop' =>  array(
				'flagType' =>  '',
				'arrayMonth' =>  array(),
				'arrayWeek' =>  array(),
				'arrayDate' =>  array(),
				'arrayDay' =>  array(),
				'start' =>  array( 'numHour' =>  0, 'numMin' =>  0 ),
				'end' =>  array( 'numHour' =>  0, 'numMin' =>  0 ),
			),
		),
		array(#2018 only
			'flagType' =>  'term',
			'strTitle' =>  '春分の日',
			'stamp' =>  0,
			'term' =>  array( 'stampStart' => 1521558000000, 'stampEnd' =>  1521644399000,),
			'loop' =>  array(
				'flagType' =>  '',
				'arrayMonth' =>  array(),
				'arrayWeek' =>  array(),
				'arrayDate' =>  array(),
				'arrayDay' =>  array(),
				'start' =>  array( 'numHour' =>  0, 'numMin' =>  0 ),
				'end' =>  array( 'numHour' =>  0, 'numMin' =>  0 ),
			),
		),
		array(#2019 only
			'flagType' =>  'term',
			'strTitle' =>  '春分の日',
			'stamp' =>  0,
			'term' =>  array( 'stampStart' => 1553094000000, 'stampEnd' =>  1553180399000,),
			'loop' =>  array(
				'flagType' =>  '',
				'arrayMonth' =>  array(),
				'arrayWeek' =>  array(),
				'arrayDate' =>  array(),
				'arrayDay' =>  array(),
				'start' =>  array( 'numHour' =>  0, 'numMin' =>  0 ),
				'end' =>  array( 'numHour' =>  0, 'numMin' =>  0 ),
			),
		),

		array(
			'flagType' =>  'loop',
			'strTitle' =>  '昭和の日',
			'stamp' =>  0,'term' =>  array( 'stampStart' =>  0,'stampEnd' =>  0,),
			'loop' =>  array(
				'flagType' =>  'year',
				'arrayMonth' =>  array(3),
				'arrayWeek' =>  array(),
				'arrayDate' =>  array(29),
				'arrayDay' =>  array(),
				'start' =>  array( 'numHour' =>  0, 'numMin' =>  0 ),
				'end' =>  array( 'numHour' =>  0, 'numMin' =>  0 ),
			),
		),

		array(#2019 only 20190530
			'flagType' =>  'term',
			'strTitle' =>  '祝日',
			'stamp' =>  0,
		    'term' =>  array( 'stampStart' => 1556550000000, 'stampEnd' =>  1556636399000,),
			'loop' =>  array(
				'flagType' =>  '',
				'arrayMonth' =>  array(),
				'arrayWeek' =>  array(),
				'arrayDate' =>  array(),
				'arrayDay' =>  array(),
				'start' =>  array( 'numHour' =>  0, 'numMin' =>  0 ),
				'end' =>  array( 'numHour' =>  0, 'numMin' =>  0 ),
			),
		),
		array(#2019 only 20190601
			'flagType' =>  'term',
			'strTitle' =>  '天皇の即位の日',
			'stamp' =>  0,
		    'term' =>  array( 'stampStart' => 1556636400000, 'stampEnd' =>  1556722799000,),
			'loop' =>  array(
				'flagType' =>  '',
				'arrayMonth' =>  array(),
				'arrayWeek' =>  array(),
				'arrayDate' =>  array(),
				'arrayDay' =>  array(),
				'start' =>  array( 'numHour' =>  0, 'numMin' =>  0 ),
				'end' =>  array( 'numHour' =>  0, 'numMin' =>  0 ),
			),
		),
		array(#2019 only 20190602
			'flagType' =>  'term',
			'strTitle' =>  '祝日',
			'stamp' =>  0,
		    'term' =>  array( 'stampStart' => 1556722800000, 'stampEnd' =>  1556809199000,),
			'loop' =>  array(
				'flagType' =>  '',
				'arrayMonth' =>  array(),
				'arrayWeek' =>  array(),
				'arrayDate' =>  array(),
				'arrayDay' =>  array(),
				'start' =>  array( 'numHour' =>  0, 'numMin' =>  0 ),
				'end' =>  array( 'numHour' =>  0, 'numMin' =>  0 ),
			),
		),
		array(
			'flagType' =>  'loop',
			'strTitle' =>  '憲法記念日',
			'stamp' =>  0,'term' =>  array( 'stampStart' =>  0,'stampEnd' =>  0,),
			'loop' =>  array(
				'flagType' =>  'year',
				'arrayMonth' =>  array(4),
				'arrayWeek' =>  array(),
				'arrayDate' =>  array(3),
				'arrayDay' =>  array(),
				'start' =>  array( 'numHour' =>  0, 'numMin' =>  0 ),
				'end' =>  array( 'numHour' =>  0, 'numMin' =>  0 ),
			),
		),
		array(
			'flagType' =>  'loop',
			'strTitle' =>  'みどりの日',
			'stamp' =>  0,'term' =>  array( 'stampStart' =>  0,'stampEnd' =>  0,),
			'loop' =>  array(
				'flagType' =>  'year',
				'arrayMonth' =>  array(4),
				'arrayWeek' =>  array(),
				'arrayDate' =>  array(4),
				'arrayDay' =>  array(),
				'start' =>  array( 'numHour' =>  0, 'numMin' =>  0 ),
				'end' =>  array( 'numHour' =>  0, 'numMin' =>  0 ),
			),
		),
		array(
			'flagType' =>  'loop',
			'strTitle' =>  'こどもの日',
			'stamp' =>  0,'term' =>  array( 'stampStart' =>  0,'stampEnd' =>  0,),
			'loop' =>  array(
				'flagType' =>  'year',
				'arrayMonth' =>  array(4),
				'arrayWeek' =>  array(),
				'arrayDate' =>  array(5),
				'arrayDay' =>  array(),
				'start' =>  array( 'numHour' =>  0, 'numMin' =>  0 ),
				'end' =>  array( 'numHour' =>  0, 'numMin' =>  0 ),
			),
		),
		array(
			'flagType' =>  'loop',
			'strTitle' =>  '海の日',
			'stamp' =>  0,'term' =>  array( 'stampStart' =>  0,'stampEnd' =>  0,),
			'loop' =>  array(
				'flagType' =>  'year',
				'arrayMonth' =>  array(6),
				'arrayWeek' =>  array(array( 'flagNum' =>  3, 'numDay' =>  1 )),
				'arrayDate' =>  array(),
				'arrayDay' =>  array(),
				'start' =>  array( 'numHour' =>  0, 'numMin' =>  0 ),
				'end' =>  array( 'numHour' =>  0, 'numMin' =>  0 ),
			),
		),
		array(
			'flagType' =>  'loop',
			'strTitle' =>  '山の日',
			'stamp' =>  0,'term' =>  array( 'stampStart' =>  0,'stampEnd' =>  0,),
			'loop' =>  array(
				'flagType' =>  'year',
				'arrayMonth' =>  array(7),
				'arrayWeek' =>  array(),
				'arrayDate' =>  array(11),
				'arrayDay' =>  array(),
				'start' =>  array( 'numHour' =>  0, 'numMin' =>  0 ),
				'end' =>  array( 'numHour' =>  0, 'numMin' =>  0 ),
			),
		),
		array(
			'flagType' =>  'loop',
			'strTitle' =>  '敬老の日',
			'stamp' =>  0,'term' =>  array( 'stampStart' =>  0,'stampEnd' =>  0,),
			'loop' =>  array(
				'flagType' =>  'year',
				'arrayMonth' =>  array(8),
				'arrayWeek' =>  array(array( 'flagNum' =>  3, 'numDay' =>  1 )),
				'arrayDate' =>  array(),
				'arrayDay' =>  array(),
				'start' =>  array( 'numHour' =>  0, 'numMin' =>  0 ),
				'end' =>  array( 'numHour' =>  0, 'numMin' =>  0 ),
			),
		),
		array(#2011 only
			'flagType' =>  'term',
			'strTitle' =>  '秋分の日',
			'stamp' =>  0,
			'term' =>  array( 'stampStart' =>  1316703600000, 'stampEnd' =>  1316789999000,),
			'loop' =>  array(
				'flagType' =>  '',
				'arrayMonth' =>  array(),
				'arrayWeek' =>  array(),
				'arrayDate' =>  array(),
				'arrayDay' =>  array(),
				'start' =>  array( 'numHour' =>  0, 'numMin' =>  0 ),
				'end' =>  array( 'numHour' =>  0, 'numMin' =>  0 ),
			),
		),
		array(#2012 only
			'flagType' =>  'term',
			'strTitle' =>  '秋分の日',
			'stamp' =>  0,
			'term' =>  array( 'stampStart' =>  1348239600000, 'stampEnd' =>  1348325999000,),
			'loop' =>  array(
				'flagType' =>  '',
				'arrayMonth' =>  array(),
				'arrayWeek' =>  array(),
				'arrayDate' =>  array(),
				'arrayDay' =>  array(),
				'start' =>  array( 'numHour' =>  0, 'numMin' =>  0 ),
				'end' =>  array( 'numHour' =>  0, 'numMin' =>  0 ),
			),
		),
		array(#2013 only
			'flagType' =>  'term',
			'strTitle' =>  '秋分の日',
			'stamp' =>  0,
			'term' =>  array( 'stampStart' =>  1379862000000, 'stampEnd' =>  1379948399000,),
			'loop' =>  array(
				'flagType' =>  '',
				'arrayMonth' =>  array(),
				'arrayWeek' =>  array(),
				'arrayDate' =>  array(),
				'arrayDay' =>  array(),
				'start' =>  array( 'numHour' =>  0, 'numMin' =>  0 ),
				'end' =>  array( 'numHour' =>  0, 'numMin' =>  0 ),
			),
		),
		array(#2014 only
			'flagType' =>  'term',
			'strTitle' =>  '秋分の日',
			'stamp' =>  0,
			'term' =>  array( 'stampStart' =>  1411398000000, 'stampEnd' => 1411484399000,),
			'loop' =>  array(
				'flagType' =>  '',
				'arrayMonth' =>  array(),
				'arrayWeek' =>  array(),
				'arrayDate' =>  array(),
				'arrayDay' =>  array(),
				'start' =>  array( 'numHour' =>  0, 'numMin' =>  0 ),
				'end' =>  array( 'numHour' =>  0, 'numMin' =>  0 ),
			),
		),
		array(#2015 only
			'flagType' =>  'term',
			'strTitle' =>  '国民の休日',
			'stamp' =>  0,
			'term' =>  array( 'stampStart' =>  1442847600000, 'stampEnd' => 1442933999000,),
			'loop' =>  array(
				'flagType' =>  '',
				'arrayMonth' =>  array(),
				'arrayWeek' =>  array(),
				'arrayDate' =>  array(),
				'arrayDay' =>  array(),
				'start' =>  array( 'numHour' =>  0, 'numMin' =>  0 ),
				'end' =>  array( 'numHour' =>  0, 'numMin' =>  0 ),
			),
		),
		array(#2015 only
			'flagType' =>  'term',
			'strTitle' =>  '秋分の日',
			'stamp' =>  0,
			'term' =>  array( 'stampStart' =>  1442934000000, 'stampEnd' => 1443020399000,),
			'loop' =>  array(
				'flagType' =>  '',
				'arrayMonth' =>  array(),
				'arrayWeek' =>  array(),
				'arrayDate' =>  array(),
				'arrayDay' =>  array(),
				'start' =>  array( 'numHour' =>  0, 'numMin' =>  0 ),
				'end' =>  array( 'numHour' =>  0, 'numMin' =>  0 ),
			),
		),
		array(#2016 only
			'flagType' =>  'term',
			'strTitle' =>  '秋分の日',
			'stamp' =>  0,
			'term' =>  array( 'stampStart' =>  1474470000000, 'stampEnd' => 1474556399000,),
			'loop' =>  array(
				'flagType' =>  '',
				'arrayMonth' =>  array(),
				'arrayWeek' =>  array(),
				'arrayDate' =>  array(),
				'arrayDay' =>  array(),
				'start' =>  array( 'numHour' =>  0, 'numMin' =>  0 ),
				'end' =>  array( 'numHour' =>  0, 'numMin' =>  0 ),
			),
		),
		array(#2017 only
			'flagType' =>  'term',
			'strTitle' =>  '秋分の日',
			'stamp' =>  0,
			'term' =>  array( 'stampStart' =>  1506092400000, 'stampEnd' => 1506178799000,),
			'loop' =>  array(
				'flagType' =>  '',
				'arrayMonth' =>  array(),
				'arrayWeek' =>  array(),
				'arrayDate' =>  array(),
				'arrayDay' =>  array(),
				'start' =>  array( 'numHour' =>  0, 'numMin' =>  0 ),
				'end' =>  array( 'numHour' =>  0, 'numMin' =>  0 ),
			),
		),
		array(#2018 only
			'flagType' =>  'term',
			'strTitle' =>  '秋分の日',
			'stamp' =>  0,
			'term' =>  array( 'stampStart' =>  1537628400000, 'stampEnd' => 1537714799000,),
			'loop' =>  array(
				'flagType' =>  '',
				'arrayMonth' =>  array(),
				'arrayWeek' =>  array(),
				'arrayDate' =>  array(),
				'arrayDay' =>  array(),
				'start' =>  array( 'numHour' =>  0, 'numMin' =>  0 ),
				'end' =>  array( 'numHour' =>  0, 'numMin' =>  0 ),
			),
		),
		array(#2019 only
			'flagType' =>  'term',
			'strTitle' =>  '秋分の日',
			'stamp' =>  0,
			'term' =>  array( 'stampStart' =>  1569164400000, 'stampEnd' => 1569250799000,),
			'loop' =>  array(
				'flagType' =>  '',
				'arrayMonth' =>  array(),
				'arrayWeek' =>  array(),
				'arrayDate' =>  array(),
				'arrayDay' =>  array(),
				'start' =>  array( 'numHour' =>  0, 'numMin' =>  0 ),
				'end' =>  array( 'numHour' =>  0, 'numMin' =>  0 ),
			),
		),

		array(
			'flagType' =>  'loop',
			'strTitle' =>  '体育の日',
			'stamp' =>  0,'term' =>  array( 'stampStart' =>  0,'stampEnd' =>  0,),
			'loop' =>  array(
				'flagType' =>  'year',
				'arrayMonth' =>  array(9),
				'arrayWeek' =>  array(array( 'flagNum' =>  2, 'numDay' =>  1 )),
				'arrayDate' =>  array(),
				'arrayDay' =>  array(),
				'start' =>  array( 'numHour' =>  0, 'numMin' =>  0 ),
				'end' =>  array( 'numHour' =>  0, 'numMin' =>  0 ),
			),
		),
		array(#2019 only
			'flagType' =>  'term',
			'strTitle' =>  '即位礼正殿の儀の行われる日',
			'stamp' =>  0,
			'term' =>  array( 'stampStart' =>  1571670000000, 'stampEnd' => 1571756399000,),
			'loop' =>  array(
				'flagType' =>  '',
				'arrayMonth' =>  array(),
				'arrayWeek' =>  array(),
				'arrayDate' =>  array(),
				'arrayDay' =>  array(),
				'start' =>  array( 'numHour' =>  0, 'numMin' =>  0 ),
				'end' =>  array( 'numHour' =>  0, 'numMin' =>  0 ),
			),
		),
		array(
			'flagType' =>  'loop',
			'strTitle' =>  '文化の日',
			'stamp' =>  0,'term' =>  array( 'stampStart' =>  0,'stampEnd' =>  0,),
			'loop' =>  array(
				'flagType' =>  'year',
				'arrayMonth' =>  array(10),
				'arrayWeek' =>  array(),
				'arrayDate' =>  array(3),
				'arrayDay' =>  array(),
				'start' =>  array( 'numHour' =>  0, 'numMin' =>  0 ),
				'end' =>  array( 'numHour' =>  0, 'numMin' =>  0 ),
			),
		),
		array(
			'flagType' =>  'loop',
			'strTitle' =>  '勤労感謝の日',
			'stamp' =>  0,'term' =>  array( 'stampStart' =>  0,'stampEnd' =>  0,),
			'loop' =>  array(
				'flagType' =>  'year',
				'arrayMonth' =>  array(10),
				'arrayWeek' =>  array(),
				'arrayDate' =>  array(23),
				'arrayDay' =>  array(),
				'start' =>  array( 'numHour' =>  0, 'numMin' =>  0 ),
				'end' =>  array( 'numHour' =>  0, 'numMin' =>  0 ),
			),
		),
/*  2019~
		array(
			'flagType' =>  'loop',
			'strTitle' =>  '天皇誕生日',
			'stamp' =>  0,'term' =>  array( 'stampStart' =>  0,'stampEnd' =>  0,),
			'loop' =>  array(
				'flagType' =>  'year',
				'arrayMonth' =>  array(11),
				'arrayWeek' =>  array(),
				'arrayDate' =>  array(23),
				'arrayDay' =>  array(),
				'start' =>  array( 'numHour' =>  0, 'numMin' =>  0 ),
				'end' =>  array( 'numHour' =>  0, 'numMin' =>  0 ),
			),
		),
*/
	),
);


